rudderlabs/rudder-server

processor/processor.go, processor/processor_test.go, router/failed-events-manager.go
=> Processor failed events

router/batchrouter/batchrouter.go, router/router.go, router/utils/utils.go
=> abort job reason in proc errors

processor/processor.go
=> transformationEnabled bool fix

genload/genload.go
=> loadForHostedConfig

jobsdb/jobsdb.go
Introduce cache expiration. 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ :( ] I have added unit tests for the code
- [x ] I have made corresponding changes to the documentation
=> Jobsdb cache expiration

warehouse/schema.go
=> Redshift: Do not cast between string<->text types

config/backend-config/backend-config.go, config/backend-config/multitenant-workspace-config.go, distributed/computeConfigController.go
=> Multitenant

router/batchrouter/batchrouter.go, router/router.go, router/utils/utils.go
=> drainReasonMetricTag

services/streammanager/personalize/personalizemanager.go
Returning 429 to retry, when throttlingException is returned.
=> Personalize throttling event support

utils/misc/misc.go, warehouse/archiver.go, warehouse/identity/identity.go, warehouse/redshift/redshift.go, warehouse/slave.go
=> Cleanup Empty Folder structures while removing files.

warehouse/schema.go
=> Compare Schemas In Local and WareHouse.

warehouse/upload.go
=> Surface Previous Job Errors.

event-schema/event_schema.go, warehouse/schema.go
=> Async setup for Event Schemas.

warehouse/postgres/postgres.go
=> WH: Option to skip computing latest user traits for postgres warehouse

warehouse/api.go
=> Handle response for trigger warehouse upload

router/batchrouter/batchrouter.go
=> Adding an additional check for nil object in file objects

router/batchrouter/batchrouter.go, services/filemanager/azureBlobStoragemanager.go
=> FileObjects-nil-reference-error-fix

warehouse/clickhouse/clickhouse.go
=> ClickHouse Error Handling

event-schema/event_schema.go, event-schema/sampler.go
Move not so useful Info logs to Debug level.
=> move some logs to info to debug

README.md
=> Added section on RudderStack architecture

router/batchrouter/batchrouter.go, router/rterror/error.go, services/filemanager/filemanager.go
https://www.notion.so/rudderstacks/Don-t-panic-on-dest-miss-config-caa5ae4b225343f5ba6ccc8c47e050f9
=> handling wrong batch destination config case for batch router

warehouse/stats.go
=> Add sourceCategory in stats

warehouse/warehouse.go
=> Query optimization for warehouse when resetInProgressJobs

build/Dockerfile-aws-dev
=> added tag for base image

gateway/webhook/webhook.go
**Fixes** # (*[issue](https://github.com/rudderlabs/rudder-server/issues/1463)*)
=> Fix `application/x-www-form-urlencoded` content-type header check

jobsdb/jobsdb.go
Casting errors are handled properly.
=> cast err handling

gateway/gateway.go
=> Sources enchance fix (#1484)

gateway/gateway.go
=> Sources enchance fix

gateway/gateway.go
=> Sources enchance fix (#1487)

regulation-worker/cmd/main.go, regulation-worker/internal/delete/api/api.go, regulation-worker/internal/delete/api/api_test.go, regulation-worker/internal/service/service.go
Changed /delete-users API call type to POST from DELETE
Initialised nil objects wherever necessary
=> nil reference and request type fix

warehouse/schema.go
=> Fix in fetching local schema

.gitignore, Makefile, build/Dockerfile-aws, build/Dockerfile-aws-dev
Include regulation-worker binary in the rudder-server image.
https://www.notion.so/rudderstacks/Build-deletion-worker-f7ac80ddbfa6476d9047c35af630cf76
=> Build deletion worker

regulation-worker/README.md
=> empty commit

gateway/gateway.go
=> added logs for http writer and webReqHandler

services/pgnotifier/pgnotifier.go, warehouse/upload.go
=> Sending status when pg_notifier marks jobs as Aborted

processor/processor.go
Adds `eventName` and `eventType` for gateway events in reports table.
=> reporting_gatewayNameType

warehouse/archiver.go
=> stop backing up wh load file records while archiving

warehouse/archiver.go
=> fix long running transaction

warehouse/warehouse.go
=> Take max of end_staging_file_id for getting the pending staging count

warehouse/slave.go, warehouse/upload.go
=> Reverted empty load files changes.

build/buildspec.docker.master.yml
=> use kafka 7.0.0 instead of latest in master buildspec

utils/misc/misc.go
=> Review GoTest

router/batchrouter/batchrouter.go
https://www.notion.so/rudderstacks/aab9175babbb48918aa17fb3f91b9988?v=1652064037f04ef7ac0497fb83f36c37&p=c60d48b2b2304ce6b96ca6ca44b845a5
=> Fix for Non Positive Responses for Failed Jobs

build/buildspec.docker.dev.yml, build/buildspec.docker.master.yml
=> Added warehouse images in pre build for docker

gateway/gateway.go, gateway/response/response.go
**Fixes**
Ratelimits metrics issue.
=> metrics correction and clean up

config/config.go, config/config.yaml, gateway/webhook/configuration.go, gateway/webhook/webhook.go
**Description* # 
- added support for putting list of string values in config.yaml
- added logic for parsing query_params in webhook only for configured sources
=> Adding query params in payload

build/buildspec.docker.dev-ent.yml, build/buildspec.docker.dev.yml
Separate responsibilities for Open Source and Enterprise Builds
=> Optimise build specs

build/buildspec.docker.dev-ent.yml, build/buildspec.docker.dev.yml, build/buildspec.docker.master.yml
=> Add missing docker pull

warehouse/stats.go, warehouse/warehouse.go
=> use sourceID when creating warehouseID tag for stats

services/filemanager/s3manager.go
=> s3manager-trucated-nil-fix

router/batchrouter/asyncdestinationmanager/asyncdestinationmanager.go, router/batchrouter/batchrouter.go
=> Marketo Bulk Upload Improvements

app/apphandlers/setup.go, processor/integrations/integrations.go, processor/processor.go, router/batchrouter/batchrouter.go, router/router.go, utils/misc/misc.go, warehouse/bigquery/bigquery.go, warehouse/slave.go, warehouse/stats.go, warehouse/upload.go, warehouse/utils/utils.go, warehouse/warehouse.go
Get rid of misc.Contains at multiple places.
=> Get Rid of misc.Contains()

warehouse/warehouse.go
=> Handling warehouse connection flags on Config changes

warehouse/api.go
=> wh: getWhUploads: use separate queries for hosted and non hosted workspaces

event-schema/event_schema.go, processor/processor.go
=> Enable event schemas to hot reloadable

warehouse/client/client.go
=> Bug: converts uint8 array to string in case of byte stream

warehouse/api.go
=> Using subquery to obtain result for warehouse uploads

warehouse/stats.go, warehouse/table_upload.go, warehouse/upload.go
=> Handle negative rudder discards for negative count.

warehouse/stats.go, warehouse/utils/utils.go, warehouse/warehouse.go
=> Chore adds alerts on ssl file generation failure

processor/processor.go
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=3e9c3b1dc5ad48ffa15b4a8322eefa00
=> Stop saving jobs which fail at event filter

router/batchrouter/batchrouter.go
https://rudderlabs.slack.com/archives/C01HTT66UMB/p1644907137267929
=> Add Timeout PostToWarehouse

services/filemanager/azureBlobStoragemanager.go
=> Hot fix blob stoarage

services/streammanager/kafka/kafkamanager.go
https://www.notion.so/rudderstacks/Kafka-Config-Improvements-e6bf6890614549989a3be174027428c1
=> Support for multiple hosts

services/streammanager/kafka/kafkamanager.go
=> Fix Kafka Batching Crash

jobsdb/unionQuery.go, router/router.go
=> isJobTerminated_Fix

services/streammanager/kafka/kafkamanager.go
=> Kafka feat latch

services/streammanager/kafka/kafkamanager.go
=> Kafka feat latch (#1708)

.github/pull_request_template.md
Add security section to PR template.
=> add security section to pr template

processor/processor.go
=> Pass recordID in metadata in dest transformation

config/backend-config/multi-workspace-config.go, processor/processor.go, processor/processor_test.go, router/batchrouter/batchrouter.go, services/debugger/uploader.go, utils/misc/misc.go
Event Filter wasn't working as expected as golang was not able to typecast interface to string array. Also closing the body in eventUploader and Warehouse Post
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=f87e015571ac40c8b2e0411191440150
=> Event Filter TypeCast Fix

router/router.go
Concurrent Read Write Map during Multi-Tenant Refactor
> Notion Link
=> Router Read Write Fix

warehouse/upload.go, warehouse/warehouse.go
=> Added column count support per warehouse destination.

warehouse/scheduling.go
> Description here
> [Notion Link](https://www.notion.so/rudderstacks/Hostedsted-crashloop-back-due-to-concurrent-read-write-error-b741fe26a49943e990d6771406a62555)
=> concurrent map read and map write in scheduling

router/transformer/transformer.go
Logs in router transformer.
> Notion Link
=> Hosted patch3

processor/processor.go, router/utils/utils.go
Support to retire jobs of a particular destination through config
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=aa64b05b1986448ba4f97bb9417849d0
=> retention support per destination id

router/router.go
Handle incorrect format of transformer response instead of panicking.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=212368cf19d844baa75552685b8f4ca8
=> handling transformer response unmarshal error

build/Dockerfile, build/Dockerfile-aws, build/Dockerfile-aws-dev
This PR fixes the issue raised here - https://github.com/rudderlabs/rudder-server/issues/1755
https://www.notion.so/rudderstacks/Rudder-server-vulnerability-56397b9cfd49463caeebc04459b7f29c
=> Fix vulnerabilities

router/batchrouter/batchrouter.go
> Added support to alter `upload interval` in Marketo Bulk upload destinations.
> https://www.notion.so/rudderstacks/MarketoBlukUpload-Enhancement-086e6c89c0e04e56b97e1f2c83af00f0
=> marketoUploadInterval

warehouse/configuration_testing/validate.go
Cleanup not happening because we are closing the connections and then call drop queries.
=> Cleanup not happening during configuration testing

gateway/gateway.go, gateway/webhook/webhook.go
Changing log level of webhook errors from debug to info for better debuggability.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=ed969b02b11e40e48a16c17847606360
=> log webhook errors

services/metric/registry.go
The metric registry's index values are maps which might be updated concurrently. This fix introduces a `RWMutex` for each map in order to assure safe concurrent rw access.
https://www.notion.so/rudderstacks/Safe-concurrent-access-of-metric-registry-s-index-values-ea9fc31a7c864a1a81316090c02c569c
=> Fix: safe concurrent access of metric registry's index values

app/apphandlers/processorAppHandler.go
Missing file changes from https://github.com/rudderlabs/rudder-server/pull/1803
> [Notion Link](https://www.notion.so/rudderstacks/Use-legacy-pickup-algorithm-on-non-multi-tenant-environments-7474d1ff5dac489a902ec64e7d8ad75b)
=> Use legacy pickup on processor app

router/batchrouter/batchrouter.go
We don't have upload time metric in batch router. This pr adds an upload timing metric.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=b9c05a6aabce4738875ba91b4fdfadc0
=> added upload time stat in batchrouter

utils/misc/misc.go
This PR is just for the cleanup of panics in misc.go
=> removed panics from AddFileToZip and UnZipSingleFile

admin/admin.go, config/backend-config/admin.go, config/config.go, event-schema/event_schema.go, gateway/admin.go, jobsdb/jobsdb_utils.go, processor/stash/admin.go, router/admin.go, router/destinationReponseHandler.go, services/debugger/transformation/transformationStatusUploader.go, services/metric/counter_test.go, warehouse/warehouse.go
Fixing panics on recover
[> Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=2c36ad782c444537b8ae2880ed5c986c)
=> Fix.recover panic

app/apphandlers/embeddedAppHandler.go, app/apphandlers/processorAppHandler.go, app/cluster/integration_test.go, go.mod, go.sum, jobsdb/jobsdb.go, processor/manager.go, processor/manager_test.go, router/router.go, services/multitenant/tenantstats.go, services/streammanager/kafka/kafkamanager.go
> Bumping Sarama Library version and Fixing the bug where there were no reports being sent by processor module
> https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=dfad9c47b33b4851823528b6d0478531
=> fix.ReportingNotInitialised: Initialised Reporting while creating new Processor Lifecycle Manager

processor/processor.go, processor/processorBenchmark_test.go, utils/misc/misc.go
> Removing `json.Marshal` from `makeCommonMetadataFromSingularEvent`.
> Left the function for now to facilitate a benchmark test.
with Marshal:
```Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -bench ^Benchmark_makeCommonMetadataFromSingularEvent_jsonMarshalling$ github.com/rudderlabs/rudder-server/processor
DB_DSN: postgres://rudder:password@localhost:55021/jobsdb?sslmode=disable
goos: darwin
goarch: arm64
pkg: github.com/rudderlabs/rudder-server/processor
Benchmark_makeCommonMetadataFromSingularEvent_jsonMarshalling-8   	  105403	     10408 ns/op	    4960 B/op	      70 allocs/op
PASS
ok  	github.com/rudderlabs/rudder-server/processor	9.073s
```
without:
```
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -bench …
```
=> refactor(Processor): remove unnecessary json.Marshalling while making common metadata from singular event

.github/workflows/tests.yaml, .github/workflows/verify.yml, .gitignore, Makefile, build/Dockerfile, build/buildspec.docker.dev-ent.yml, build/buildspec.docker.dev.yml, build/buildspec.docker.master.yml, build/buildspec.docker.saas.yml, build/buildspec.pr.yml, build/buildspec.release.yml, build/buildspec.saas.yml, go.mod
We update the golang version fo the repo to 1.17.8.
We also updated buildspecs to use the newer 1.17.8 image to build.
Testing:
1. Tests are passing locally and in our CI pipelines
2. Deployed `rudderlabs/develop-rudder-server:bump-golang-version` into dev cluster and sent a couple of events to the `desttest` deployment.
https://www.notion.so/rudderstacks/Golang-version-bump-to-1-17-8-b008537c9916494a9a54360da25ae150
=> Config[golang]: bump golang version to 1.17.8

processor/manager.go, processor/processor.go, processor/processor_test.go, processor/trackingplan.go
* moving stats into own attribute (see `processor.HandleT`) to better understand processor dependencies
* typos and linting
* fix: honouring context during sleep
> Notion Link
=> Processor stats into separate struct

main.go
> Changing the defaults to use the new app handler mechanism
> [Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=d4bc9c2a6b024e15901433d13f655278)
=> chore.ChangeDefaultValue: Change Default Legacy App Handler to false

admin/admin.go
> Data race fix (see notion link)
> [Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=d3806f442555412fb7c5c86a51ab2c11&p=2365bb50c54443b1ad6737c46d3f6d24)
=> fix: admin status handlers data race

README.md
Fixing broken developer machine setup link
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a34d50ef6e3641a09d72b2296e24100c
=> fix(readme): update developer machine setup link

mocks/services/debugger/uploader.go, services/debugger/cache.go, services/debugger/cache_test.go, services/debugger/destination/eventDeliveryStatusUploader.go, services/debugger/destination/eventDeliveryStatusUploader_test.go, services/debugger/source/eventUploader_test.go, services/debugger/uploader.go, services/debugger/uploader_test.go
* Fixes overall testing time. Average execution time for the affected tests is now 6x faster (down to 2 from 12 seconds).
* All `• [SLOW TEST:5.000 seconds]` tags are now removed from this part.
=> chore(tests): Remove sleep(), use wait logic

warehouse/deltalake/deltalake.go
Added support for deltalake multi-line support.
https://www.notion.so/rudderstacks/devsistersfsg-warehouse-upload-aborted-1be974e9698a468f8b9571eae109ff75
=> fix(warehouse): add support for multiline in deltalake.

processor/transformer/transformer.go
=> fix: added http client timeout in processor transformer (#1887)

router/router.go
=> fix.invalid-json-fix

router/router.go
Insert into postgres - invalid json input fix.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=64878060eec34f7db037cdc0c302fb5d
=> fix: invalid-json-fix (#1905)

services/pgnotifier/pgnotifier.go
=> chore: saas -> master

processor/trackingplan.go
Remove error logs from tracking plan as it will be going to create a lot of fuss in the logs.
https://www.notion.so/rudderstacks/Remove-error-logs-from-tracking-plan-as-it-will-be-going-to-create-a-lot-of-fuss-in-the-logs-7161ca7e0032492da906be0af17e0531
=> chore(warehouse): remove tracking plan error logs.

warehouse/redshift/redshift.go
many logs in `redshift.go` file were printing the sql statements and other big logs as info type which were polluting the logs and making them hard to read. Changed those to debug type logs.
Example of old logs: 
```
2022-04-20T15:05:36.089Z	INFO	redshift/redshift.go:376	RS: Complete load for table:mp_buy_click_web
2022-04-20T15:05:36.089Z	INFO	redshift/redshift.go:251	WH: dropping table rudder_staging_61006242e9fc44f3ade77a446206e232_mp_buy_click_web
2022-04-20T15:05:39.031Z	INFO	redshift/redshift.go:376	RS: Complete load for table:order_details_clicked
2022-04-20T15:05:39.031Z	INFO	redshift/redshift.go:251	WH: dropping table rudder_staging_758f348bd7e64730bf30345ee3158098_order_details_clicked
2022-04-20T15:05:39.293Z	INFO	warehouse/upload.go:788	[WH]: Starting schema update for table …
```
=> chore(warehouse): change SQL statement logs to debug type

services/streammanager/kafka/kafkamanager.go, services/streammanager/kafka/kafkamanager_test.go
I'm just adding some metrics to monitor skipped messages on Kafka destinations.
=> feat: stats for skipped messages on kafka destinations

app/apphandlers/gatewayAppHandler.go, app/apphandlers/processorAppHandler.go, app/cluster/dynamic.go, config/backend-config/backend-config.go, main.go
Introduced dynamic cluster manager in Gateway App also which was needed to start the backend config. 
[Notion](https://www.notion.so/rudderstacks/Include-Cluster-Manager-in-Gateway-App-Handler-e3d4dfd8dd6d4a29a278237bfa1d6b98)
=> feat(multi-tenant): cluster manager gateway int

app/cluster/state/etcd.go, app/cluster/state/etcd_test.go, config/backend-config/multitenant_workspaces.go, config/backend-config/single_workspace.go, config/config.go
Made the ETCD keys upper case. 
[<Notion Link >](https://www.notion.so/rudderstacks/Change-workspace-ID-change-ETCD-Key-74b92e2a62664132816a4f4475563c60)
=> fix(multi-tenant): etcd Key case fix

build/buildspec.docker.dev-ent.yml, build/buildspec.docker.dev.yml, build/buildspec.docker.master.yml, build/buildspec.docker.saas.yml, build/buildspec.pr.yml
Forcing GO111MODULE=on to stop failing code builds
[Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=20d45effb5da4c93a4a35f9a06ec9e55)
=> chore: force gomodule to on for codebuild

Makefile, build/buildspec.docker.master.yml, build/buildspec.pr.yml
Changing to go install
(https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=20d45effb5da4c93a4a35f9a06ec9e55)
=> chore: go install on for codebuild

app/apphandlers/embeddedAppHandler.go, app/cluster/dynamic.go
Enabling support to use Embedded App in the multi tenant deployment. In this case the ETCD based cluster manager will be used. 
[Notion Link](https://www.notion.so/rudderstacks/Support-for-Embedded-in-Multi-Tenant-environment-b1ff065508534fdfa30b6bab4b795948)
=> feat(multi-tenant): multitenant support for embedded app

warehouse/upload.go, warehouse/utils/utils.go, warehouse/utils/utils_test.go
configurable timewindow layout for gcs datalake
https://www.notion.so/rudderstacks/Configurable-timewindow-format-for-destination-gcs_datalake-1307064d55724ebb9b7aee29b4735463
=> feat(warehouse): configurable timewindow layout for gcs datalake

main.go
Warehouse Slave doesn't need to have access to backendConfig. Skipping the check which validates the backend config
[Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a9053e612c424e4fb45a43f4b98971ec)
=> fix(warehouse): skip backendConfig check for slave

jobsdb/jobsdb.go
Assisting query planning in case a large number of jobs or job statuses are copied (i.e. batchrouter)
[Execute ANALYZE after a bulk store/update threshold has been reached](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a05d41a4f89044939aac8ff2016c7147)
=> chore: execute ANALYZE after copying a large number of jobs or job statuses

router/batchrouter/batchrouter.go, router/router.go
While events are being processed in router and batch router, the actual outcome of each event cannot be guaranteed, since it might fail, succeed, be aborted, drained etc.
At the same time, we need a metric that indicates whether the system's modules (router & batch router) are processing events, regardless of what their actual outcome is.
Such a metric is especially useful for detecting stuck processing pipelines in the system, i.e. scenarios where we do have outstanding events in our queues, but the relevant system modules don't appear to be processing anything.
Unfortunately, the current alerts that detect such stuck processing pipelines rely on partial measurements, leading to false positives, more specifically:
- **router** - we are currently using `router_response_counts` which …
=> chore: introduce pipeline_processed_events metric in router and batch router

.github/workflows/tests.yaml, Makefile, docker_test.go
As per title.
Due to this discussion: https://github.com/rudderlabs/rudder-server/pull/2059#discussion_r899803486
=> chore: enable slow tests by default

processor/processor.go, processor/stash/stash.go, processor/transformer/transformer.go, router/batchrouter/batchrouter.go, router/router.go, router/transformer/transformer.go
This PR adds some of the missing tags and cleans up unused stats.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=f37c0af35ac7480c9c511a68f0f2444b
=> chore: remove stale stats

services/rsources/stats_collector.go
rSources handlers from different modules can cause deadlock when attempting unordered inserts between two competing transactions. statsCollector now sorts the inserts beforehand to avoid deadlock.
``` Process 32628 waits for ShareLock on transaction 811911309; blocked by process 12444.
Process 12444 waits for ShareLock on transaction 811911471; blocked by process 32628.
Process 32628: insert into "rsources_stats" (
job_run_id,
task_run_id,
source_id,
destination_id,
in_count,
out_count,
failed_count
) values ($1, $2, $3, $4, $5, $6, $7)
on conflict(db_name, job_run_id, task_run_id, source_id, destination_id)
do update set
in_count = "rsources_stats".in_count + excluded.in_count,
out_count = "rsources_stats".out_count + excluded.out_count,
failed_count = "rsources_stats".failed_count + …
```
=> fix(core): order inserts(updates) to avoid deadlocks

router/router.go
Unlocking RLock before posting job to `responseQ` in `router.workerProcess`.
Also counting router_status_events before setting `responseList` to `nil` in `StatusInsertLoop`
[configSubscriber lock, router_status_events count](https://www.notion.so/rudderstacks/configSubscriber-lock-router_status_events-count-a8fb896529284b508414c62add0fe45d)
=> fix(core): configSubscriber lock, router_status_events count

jobsdb/jobsdb.go
The internal migration fails for tables with negative indices with error 
```
panic: pq: syntax error at or near "-" [recovered]
panic: pq: syntax error at or near "-"
```
This PR attempts to fix this issue
[Notion Link ](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a585a3f3e72b4e1b806b0f44153abda5)
=> fix(jobsdb): fix ANALYSE for Negative Indices during internal migration

processor/processor.go, processor/transformer/transformer.go, router/router.go, router/utils/utils.go, utils/misc/misc.go
1. Clean up stale variables
2. Use proper duration for alerting
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=d83fc81b3a284659a0c40875810c10f8
=> chore: remove unused variables

services/rsources/handler_test.go
- Make tests Ordered
- Increase Timeouts
- Use non-colliding hostnames
=> chore: fix flaky handler_test

router/batchrouter/batchrouter.go, router/router.go
Several pause/resume channels are no longer being used in the code. Cleaning the code using those pause/resume channels. 
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=162061950cc44a4caba9fe6c2935d2c2&pm=s
=> chore(router): clean up the various pairs of pause/resume channels

app/apphandlers/setup.go, app/cluster/dynamic.go, config/backend-config/backend-config.go, enterprise/migrator/export.go, enterprise/migrator/failedKeysMigrator.go, enterprise/migrator/import.go, gateway/webhook/setup.go, jobsdb/jobsdb.go, middleware/middleware.go, mocks/services/stats/mock_stats.go, processor/stash/stash.go, processor/transformer/transformer.go, router/batchrouter/batchrouter.go, router/customdestinationmanager/customdestinationmanager.go, router/transformer/transformer.go, services/debugger/transformation/transformationStatusUploader.go, services/stats/stats.go, warehouse/deltalake/deltalake.go, warehouse/warehouse.go
Removing the deprecated code and refactoring the code to use the new functions.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a1e5d5d78a774aa3b62f4132772ba56a&pm=s
=> chore: clean up deprecated code

utils/misc/retry_test.go
Increasing the operation's timeout to a sensibly larger value than the competing timeout
=> chore: fixing flaky test

warehouse/db.go, warehouse/warehouse.go
We need to refactor our interactions with the database. At this moment, the domain logic is directly interacting with the database queries. This needs to be refactored for better separation of concerns and ability to test / refactor in a better way.
The purpose of this change is to kickoff the refactoring by creating a separate db module and drive interactions through the function.
https://www.notion.so/rudderstacks/Refactor-warehouse-database-interactions-through-a-separate-module-e2bdb18ec7d149769839c34f1baf8086
=> chore(warehouse): refactor db interactions

services/streammanager/bqstream/bqstreammanager_test.go
Two pull requests were merged back-to-back causing a compilation error
=> chore: fix compilation error after #2152 merge

services/filemanager/digitalOceanSpacesManager.go, services/filemanager/s3manager.go
Propagating s3 getSession errors to the caller avoiding panic.
=> chore: propogate s3manager error up

jobsdb/jobsdb.go
Replacing "%s" with %q to keep deepsource happy.
=> chore: jobsdb query formatting (using %q)

config/backend-config/namespace_config.go, config/backend-config/namespace_config_test.go, multi_tenant_test.go
The Control plane made some minor changes to the namespace config endpoint:
* Use the existing hosted service secret for auth
* `data-plane` was renamed to `dataPlane`
https://www.notion.so/rudderstacks/Fetch-backend-config-with-namespace-9e837c1b2f354df7be15d6224558bb42
=> feat: update namespace endpoint according to the latest changes

services/rsources/handler_test.go
Remove test expectations relying on uncontrolled async operations having completed already
=> chore: fix flaky test in rsources

config/backend-config/backend-config.go, config/backend-config/multitenant_workspaces.go, config/backend-config/multitenant_workspaces_test.go, config/backend-config/namespace_config.go, config/backend-config/namespace_config_test.go, router/router.go
When we cleaned up hosted workspace config, We missed a few things very specific to hosted deployment [here](https://github.com/rudderlabs/rudder-server/pull/2240/files#diff-4f799306a3605b051353f0aa7463da845b95309e09520a954272f41541097a69L131) . Adding the missing pieces
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=3a0652cc416042a081dc308ba8b28972&pm=s
=> chore: fix issues during cleanup

Dockerfile
Adding tzdata to the docker image
[Slack thread about clickhouse timezone support](https://rudderlabs.slack.com/archives/C02AALVFHJN/p1660212575248279)
=> chore: update Dockerfile - add tzdata

admin/admin.go, event-schema/event_schema.go, jobsdb/jobsdb.go, jobsdb/jobsdb_utils.go, processor/processor.go, services/debugger/cache.go, services/filemanager/azureBlobStoragemanager.go, services/filemanager/digitalOceanSpacesManager.go, services/filemanager/gcsmanager.go, services/filemanager/miniomanager.go, services/metric/registry.go, services/transientsource/transientsource.go, utils/googleutils/googleutils.go, utils/misc/default_string.go, utils/misc/misc.go, utils/tests/async-helper.go, warehouse/clickhouse/clickhouse.go, warehouse/configuration_testing/configuration_testing.go, warehouse/warehouse.go
The formatting of the committed code was not consistent with the changes of `make fmt`
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a43ec161cfe54a1e8b46799d6ab2a246&pm=s
=> chore: make fmt

main.go
Added initialization for datalake in main package for runAllInit
https://www.notion.so/rudderstacks/Added-initialization-for-Datalake-4d1799de0b794c4f9af9072d40f3e241
=> fix(warehouse): added initialization for datalake

enterprise/reporting/reporting.go, warehouse/azure-synapse/azure-synapse.go, warehouse/identity/identity.go, warehouse/mssql/mssql.go, warehouse/testhelper/setup.go, warehouse/upload.go, warehouse/warehouse.go
Fix spell mistakes which were found go report: https://goreportcard.com/report/github.com/rudderlabs/rudder-server
https://www.notion.so/rudderstacks/Fix-issues-reported-in-go-card-6359da43e4054db6b1bf3a3617ca2af0
=> chore: fix misspell

eventorder_test.go
=> chore: remove build tag from test

eventorder_test.go
=> chore: fix lint errors in test

gateway/webhook/webhook.go
`webhook.requestQ` is a map that can be read when [handling a new request](https://github.com/rudderlabs/rudder-server/blob/master/gateway/webhook/webhook.go#L184) on `RequestHandler` and can be written during backendConfig update, if a new source [is registered](https://github.com/rudderlabs/rudder-server/blob/master/gateway/webhook/webhook.go#L342).
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a43f2cdad72848a287aeadaad4d6768b&pm=s)
=> fix: safe webhook concurrent map access

warehouse/snowflake/snowflake_test.go
Disable warehouse integration tests for snowflake.
https://www.notion.so/rudderstacks/Disable-warehouse-snowflake-integration-tests-637e0c907d014fd19bed78552c71ca9e
=> chore(warehouse): skip warehouse snowflake test

testhelper/freeport.go
Fixing a regression introduced by #2410
=> chore: skip double mutex unlock

jobsdb/jobsdb.go
Fix minor bug to use cache for no parameter filters scenarios
[Notion Link ](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=54e42282047f463fa8496961ae889531&pm=s)
=> chore: fix cache bug

regulation-worker/internal/client/client.go
> Currently in case of Data Regulation Service, if no job is found, regulation-manager returns 404 statusCode with `ErrNoRunnableJob` body. But, Control-Plane get alerts if it returns 404 for any request. So, we are modifying the status code returned from `404` to `204` in regulation-manager & modifying here (in regulation-worker) to handle the same. (regulation-manager PR: https://github.com/rudderlabs/data-regulation-service/pull/50)
https://www.notion.so/rudderstacks/For-regulation-worker-regulation-manager-modify-statusCode-for-no-jobs-found-from-404-to-204-95b3e80b87a64d3599e95c1588d4269e
=> chore: modified regulation-worker response code handling from 404 to 204, when no job is available

README.md
Temporary announcement header
Adding header for v1.0 announcement. It is a temporary change.
=> doc: v1.0 announcement and event link

CHANGELOG.md, services/destination-connection-tester/destination_connection_tester.go
Applying 1.1.x hotfixes to main branch
=> chore: applying 1.1.1 hotfixes to main branch

router/batchrouter/batchrouter.go, router/router.go
Adding information for status code in pipeline_processed_events metric
=> chore: include status code in pipeline_processed_events metric

gateway/gateway.go, gateway/gateway_test.go
Expose warehouse's pending-events endpoint in gateway.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=6f7ba01a249d4e82a708f4964a9e78a6&pm=s)
=> chore: reverse proxy warehouse pending-events endpoint

CHANGELOG.md, warehouse/snowflake/snowflake.go
Applying 1.1.2 hotfixes to main branch
=> chore: applying 1.1.2 hotfixes to main branch 

jobsdb/jobsdb.go
Added metrics for `pre_drop_table` count.
https://www.notion.so/rudderstacks/add-metrics-alert-for-pre_drop-table-count-dddf58fd73c940f39b113a54bc6f06f6
=> chore: added pre_drop_table count metrics

services/stats/stats.go
Fixes panic: runtime error: invalid memory address or nil pointer dereference
=> chore: fix race defect after stats refactoring

README.md
Fix the missing bold tag in README html
=> doc: remove unnecessary bold style in README

services/pgnotifier/pgnotifier.go, warehouse/admin.go, warehouse/api.go, warehouse/archiver.go, warehouse/db.go, warehouse/identities.go, warehouse/identity/identity.go, warehouse/query_builder.go, warehouse/scheduling.go, warehouse/schema.go, warehouse/slave.go, warehouse/staging_file.go, warehouse/table_upload.go, warehouse/upload.go, warehouse/utils/utils.go, warehouse/warehouse.go
For SQL statements for better understanding.
https://www.notion.so/rudderstacks/Formal-SQL-Queries-Parameterized-it-cb44268e604c446c9f31858bba98635f
=> chore(warehouse): format warehouse queries

info/features.go
Added warehouse-supported features for control plane compatibility.
https://www.notion.so/rudderstacks/Warehouse-features-92c03ef2b3294c79a0d68e4f15168d8d
=> feat(warehouse): added warehouse features

processor/transformer/transformer.go
Fixing a minor defect introduced by #2225
=> chore: fix error log defect in processor's transformer

config/backend-config/backend-config.go, config/backend-config/backend_config_test.go, config/backend-config/internal/cache/cache.go
https://app.squadcast.com/incident/634022812e29e30e4da5b511
=> chore: fix defect and use noCache if database setup fails during cache.Start

jobsdb/jobsdb.go
Currently,  when `isBackupEnabled` is set, whereas `isBackupConfigured` is not set, `DS` are dropped without being backedup.
https://www.notion.so/rudderstacks/fix-silent-drop-of-pre_drop-DS-8327c03b942a433098fb98defc00342c
=> fix: silent backup ds drop

warehouse/bigquery/bigquery.go
Use proper parameter exported names for the Big Query handler and background context.
https://www.notion.so/rudderstacks/Bigquery-handler-restrucutring-947795693b8c4a0faa6d5c7a9cb55332
=> chore(warehouse): bigquery handler restructuring

warehouse/api.go, warehouse/errors.go, warehouse/warehousegrpc.go, warehouse/warehousegrpc_test.go
minor error refactoring
https://www.notion.so/rudderstacks/Refactoring-error-message-for-object-storage-validation-9fc7d4329da54a608ebd42bce6432332
=> chore: minor error message change

app/apphandlers/embeddedAppHandler.go, app/apphandlers/gatewayAppHandler.go, app/apphandlers/setup.go, jobsdb/jobsdb_utils.go, jobsdb/readonly_jobsdb.go, jobsdb/setup.go, processor/processor.go, router/router.go
Cleaning up unused code left over from deleting Migrator code
[Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=0a191ae269f24a34b459f0ec6f15fd00&pm=s)
=> chore: cleanup unused code

go.mod, multi_tenant_test.go
Sometimes the multi tenant test fails waiting for an ack. I'm adding a log entry to check the ETCD connectivity at that time.
=> chore: adding log entry to multi tenant test

CHANGELOG.md, gateway/gateway.go, jobsdb/integration_test.go, jobsdb/jobsdb.go, jobsdb/jobsdb_backup_test.go, jobsdb/jobsdb_test.go, mocks/jobsdb/mock_jobsdb.go, processor/processor.go, processor/processor_test.go, router/batchrouter/batchrouter.go, router/router.go
Applying 1.2.1 hotfix to main branch
=> chore: applying 1.2.1 hotfix to main branch

CHANGELOG.md, jobsdb/jobsdb.go
Applying 1.2.2 hotfixes to main branch
=> chore: applying 1.2.2 hotfixes to main branch

warehouse/identities.go
removing lock
https://www.notion.so/rudderstacks/Warehouse-service-down-for-Pro-customers-a374bf525d314e3fbbd72576356f06dd
=> fix(warehouse): Remove bad unlock

warehouse/identities.go
applying 1.2.2 hotfixes to main branch
https://www.notion.so/rudderstacks/Release-process-094ecf877f3d47e9ad94ab28622da225
=> fix(warehouse): read unlock in historic identities

CHANGELOG.md, services/pgnotifier/pgnotifier.go
applying 1.2.4 hotfixes to main branch
=> chore: applying 1.2.4 hotfixes to main branch

warehouse/jobs/runner.go
We are logging the process to list the async jobs as info. This is causing unnecessary information getting logged on every iteration. The purpose of this PR is to move the level to debug for now.
=> chore(warehouse): fix log level of async jobs

.github/workflows/tests.yaml, .github/workflows/verify.yml, .golangci.yml, Dockerfile, build/Dockerfile-warehouse-integration, go.mod, proto/common/dpauth.pb.go
Upgrading to latest go version
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=ea0df32b3f1345f097aec7db7dcf3e69&pm=s)
=> chore: upgrade GO version to 1.19

processor/processor_test.go
This PR handles the lint issues introduced [here](https://github.com/rudderlabs/rudder-server/actions/runs/3375866788/jobs/5602936742)
=> fix: golangci-lint issues

processor/integrations/integrations.go
> adding different env pointing to user transformer service
https://www.notion.so/rudderstacks/separate-out-user-transformer-dest-transformer-deployments-6c7b62acdc08462cb45f696f3f6cd52e
=> chore(warehouse): add user transformer url env

enterprise/replay/dumpsloader.go, enterprise/replay/setup.go, enterprise/replay/sourceWorker.go, services/filemanager/filemanager.go, utils/misc/misc.go
Fixing replay bugs that occurred while replaying for recroom
[Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=0ec68abc11e046b0ad4988490dfd3805&pm=s)
=> chore: fix replay bugs

.github/workflows/prerelease.yaml
To support a prerelease (release candidate) workflow
=> chore: add github action for prerelease workflow

router/batchrouter/batchrouter.go, router/router.go
add source to event delivery metric
https://www.notion.so/rudderstacks/Add-source-to-the-event_delivery-metrics-542e52cb88fc442c95c20ceff534ce6e
=> chore: add source to event_delivery metric

processor/processor.go, router/router.go
To get notified about any panic happening in router and processor
=> chore: use bugsnag in router and processor goroutines

.github/workflows/release-please.yaml, CHANGELOG.md
Merging 1.3.0 release to main branch
=> chore: release 1.3.0 (#2665)

CHANGELOG.md, processor/stash/stash.go
Applying 1.3.1 hotfixes to main branch
=> chore: applying 1.3.1 hotfixes to main branch

CHANGELOG.md, gateway/gateway.go, gateway/webhook/setup.go, gateway/webhook/webhook.go, mocks/gateway/webhook/mock_webhook.go, router/batchrouter/batchrouter.go
Applying 1.3.2 hotfixes to main branch
=> chore: applying 1.3.2 hotfixes to main branch

jobsdb/setup.go
When a writer jobsdb performed schema migration on its dataset tables, it did it only for the last two.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=80e7b276f920456887b48f98b5fce644&pm=s)
=> fix: jobsdb schema migration not performed against all datasets

enterprise/replay/dumpsloader.go, enterprise/replay/sourceWorker.go, utils/misc/misc.go
Fix Replay Issues
https://www.notion.so/rudderstacks/Fix-Replay-issues-14c2163e94bf4736b0f8308cf38b90b7
=> fix: no timezone while parsing

warehouse/warehouse.go
Regression introduced by #2734
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=bdf94aeaedb84e5c985a3b6648bf45fb&pm=s)
=> chore: regression while starting a standalone warehouse slave

processor/transformer/transformer.go
Enhance transformer error log with more metadata
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=4ee7a7d05ffb4463ad1f8bc24efa46ed&pm=s
=> chore: enhance transformer error with more metadata

jobsdb/jobsdb.go, jobsdb/jobsdb_test.go
Acquire a distributed shared lock during `add_ds` & `migrate_ds`. Preparing for deployment of 1.4.0 which introduces jobsdb schema changes.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=accc62687a574edbb6b4bcff120107b5&pm=s)
=> chore: acquire schema_migrate distributed shared lock

.github/workflows/prerelease.yaml, .github/workflows/release-please.yaml, CHANGELOG.md, info/features.go, integration_test/multi_tentant_test/testdata/expected_features.json, jobsdb/jobsdb.go, jobsdb/migration.go, runner/runner.go, warehouse/warehouse.go
=> chore: 1 4 merge

CHANGELOG.md, jobsdb/migration.go, warehouse/internal/api/http.go, warehouse/internal/api/http_test.go, warehouse/internal/model/staging.go, warehouse/internal/model/staging_test.go, warehouse/internal/repo/staging.go, warehouse/internal/repo/staging_test.go, warehouse/types.go
Applying 1.4.3 and 1.4.4 hotfixes to main branch
=> chore: applying 1.4.3 and 1.4.4 hotfixes to main branch

CHANGELOG.md, processor/processor.go, processor/processor_test.go, router/router.go, router/transformer/transformer.go
Applying 1.4.6 hotfixes to main branch
fix(destination): add proper stats for rt/batch transformation & proxy (#2855)
fix: shallow copy config in processor (#2856)
=> chore: applying 1.4.6 hotfixes to main branch

router/router.go, router/router_test.go
remove external backoff package
[router backoff](https://www.notion.so/rudderstacks/router-backoff-be6e80e68f35478eab4922bb2e5618ac)
=> refactor: using an exponential backoff

regulation-worker/internal/client/client.go, regulation-worker/internal/delete/api/api.go, regulation-worker/internal/delete/batch/batch.go, regulation-worker/internal/delete/kvstore/kvstore.go, regulation-worker/internal/service/service.go
Added prefix `regulation_worker` to all the regulation-worker stats.
=> chore: added prefix to regulation worker stats

processor/stash/stash.go
Using a mutex to control multiple goroutines' access to the slice collecting error jobs
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=656ae72b562f45598c7832d536cf6b1a&pm=s)
=> fix: stash reporting back less error jobs after store

gateway/gateway.go, gateway/gateway_test.go, gateway/internal/stats/stats.go, gateway/internal/stats/stats_test.go
add `sourceType`, `sdkVersion` tags to gateway stats.
[new gateway stat-tags](https://www.notion.so/rudderstacks/new-gateway-stat-tags-87db19e3380449018a7da14f847190f3)
=> chore: add tags(sourceType, sdkVersion) to gateway stats

internal/throttling/throttling_test.go
To achieve consistent results from GCRA rate limiting algorithms, `burst` should be set equal to `rate` and a **warmup** cycle should  be performed before the actual test, in order to fill up the `burst`. After that point the algorithm should "leak" at the expected rate.
=> chore: warmup gcra algorithms in throttling test

CHANGELOG.md, config/config.yaml, router/router.go
Applying 1.5.1 hotfixes to main branch
fix: adding throttling stats in router (#2923)
=> chore: applying 1.5.1 hotfixes to main branch

warehouse/integrations/deltalake/deltalake.go
Added support for UseRudderStorage to use RudderStack managed object storage for deltalake.
https://www.notion.so/rudderstacks/Databricks-useRudderStorage-option-6e1f4e0972d34a2ebc0a853989ebe5aa
=> feat(warehouse): added use rudder storage option to deltalake

CHANGELOG.md, warehouse/scheduling.go, warehouse/tracker.go, warehouse/tracker_test.go, warehouse/warehouse.go
Applying 1.5.4 & 1.5.5 hotfixes to main branch
[x] The code changed/added as part of this pull request won't create any security issues with how the software is being used.
chore: introduce stat for skip upload syncs (#2938)
fix: upload missing metric (#2947)
=> chore: applying 1.5.4 & 1.5.5 hotfixes to main branch

router/throttler/throttler.go
Gorate is unstabled and removed in main branch
=> fix: setting default throttling algorithm to gcra

processor/processor.go, processor/processor_test.go
Filtering events based on consent management rules
[Filter destinations based on consent management preferences](https://www.notion.so/rudderstacks/Filter-destinations-based-on-consent-management-preferences-2c1ddf1ff37b44f2913830459c825032?pvs=4)
=> feat: filter events based on destination consent management rules

warehouse/integrations/postgres/postgres.go
Additional error mappings.
https://www.notion.so/rudderstacks/Additional-error-mappings-f456488d3a9141bfb929c23f4f156158?pvs=4
=> chore(warehouse): additional error mappings

sql/migrations/jobsdb/000011_add_workspace_id_index.up.tmpl, sql/migrations/jobsdb_always/000011_add_workspace_id_index.up.tmpl
Fixing issue with migration script
=> fix: create index concurrently cannot run inside a transaction block

services/debugger/cache/internal/badger/badger.go
Have an aggressive GC for Live Events Badger DB usage and add few more options to reduce disk consumption
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=c29bc50da3d042dca7d109cc66447a42&pm=s
=> chore: make GC discard ratio configurable

services/debugger/cache/internal/badger/badger.go
Use configurable badgerDB parameters
=> chore: tunable badgerDB config params

CHANGELOG.md, services/debugger/cache/internal/badger/badger.go, services/debugger/cache/internal/badger/badger_test.go
Applying 1.6.1 hotfixes to main branch
chore: debugger's badgerdb cache optimisations (#3042)
=> chore: applying 1.6.1 hotfixes to main branch

testhelper/destination/kafka.go, testhelper/etcd/etcd.go
Bitnami images now support arm64 architecture.
=> chore: use official bitnami images for arm64

warehouse/upload.go
Increase default max parallel load for warehouses
[Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=32576ecb344c467ca55a94581fd0a58f&pm=s)
=> chore: increase parallel loads

README.md
Add link to Transformations Month challenge - https://www.rudderstack.com/blog/join-the-transformations-challenge-for-a-chance-to-win/
=> chore: add transformations challenge announcement

processor/stash/stash.go, utils/misc/misc.go, warehouse/scheduling.go, warehouse/utils/utils.go, warehouse/utils/utils_test.go
Support sync frequency at connection level
[ Notion Link ](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=239d9894330e40e1bdf1bc9492ee019d&pm=s)
=> chore: enable pipeline level sync frequency

services/streammanager/kafka/client/testutil/util.go
To fix [these builds](https://github.com/rudderlabs/rudder-server/actions/runs/4424009493/jobs/7757326891).
Some integration tests running with more than one Kafka broker would occasionally fail. That is because the creation of topics and other administration operations have to be done directly on the broker that is the "controller" of such topic.
< [Notion Link](https://www.notion.so/rudderstacks/Fix-Kafka-integration-tests-59ec627e3be6481fa424509d3a164852) >
=> fix: kafka create topic

config/config.yaml, config/sample.env
Restoring config.yaml and sample.env which were previously deleted by #3104
=> chore: restore sample configuration files

CHANGELOG.md, warehouse/internal/repo/table_upload.go, warehouse/internal/repo/table_upload_test.go, warehouse/upload.go
Applying hotfix 1.7.1 to the main branch
https://www.notion.so/rudderstacks/Table-uploads-not-updates-errors-41e6eee090fc4957a528221ecc1c07f9?pvs=4
fix(warehouse): table uploads were not getting updated
=> chore: applying hotfix for 1.7.1 to main branch

enterprise/replay/dumpsloader.go, enterprise/replay/replay_test.go
=> chore: use tmpdir

README.md
Transformations challenge is now over. Replace the transformations challenge link with slack link
=> chore: replace readme header link with slack link

warehouse/integrations/datalake/datalake.go, warehouse/testdata/errors/S3_DATALAKE
Update error mappings for s3 datalake for access denied
https://www.notion.so/rudderstacks/s3-datalake-error-mappings-for-access-denied-9361f9c412a74620a5c9cc82114ac8c9?pvs=4
=> chore: access denied for s3 datalake

.github/workflows/release-please.yaml
=> chore: use the common PAT for release-please

.snyk, go.mod, go.sum
Ignoring and/or replacing indirect dependencies
=> chore: addressing snyk vulnerabilities

go.mod, go.sum
bump github.com/rudderlabs/sql-tunnels from 0.1.2 to 0.1.3
=> chore: bump github.com/rudderlabs/sql-tunnels from 0.1.2 to 0.1.3

regulation-worker/cmd/main_test.go, regulation-worker/internal/delete/delete.go, regulation-worker/internal/delete/kvstore/kvstore.go, testhelper/destination/minio.go, warehouse/integrations/testhelper/setup.go, warehouse/internal/service/loadfiles/downloader/downloader_test.go
One first step towards combating a flaky test
=> chore: refactor regulation worker integration test

testhelper/destination/kafka/kafka.go
Addressing issues with latest images from bitnami
=> chore: lock bitnami test image versions

services/streammanager/kafka/kafkamanager.go, services/streammanager/kafka/kafkamanager_test.go
Enable setting of `embedAvroSchemaID` from config in addition to setting it via env.
=> chore: enable setting of `embedAvroSchemaID` from config

warehouse/integrations/deltalake-native/deltalake.go
- Add `databricks` retries policy to the `databricks` client. This is basically used as a cold start time in order to connect to the `databricks` cluster.
https://www.notion.so/rudderstacks/Databricks-intermittent-failures-d5e939f3749543888b8f070a4c14c7e2?pvs=4
=> fix: databricks retries

.github/workflows/tests.yaml
=> chore: add coverage

.github/workflows/tests.yaml, Makefile
Coverage for warehouse tests.
https://www.notion.so/rudderstacks/Warehouse-Integration-Tests-d37a84f8e4b14aecaa544727eae0dd33?pvs=4
=> chore: coverage for warehouse integration tests

gateway/gateway.go
For debugging failure to read request body
[Link](https://rudderlabs.slack.com/archives/C02B0A38QQG/p1684335797662189)
=> chore: include error message in error log

go.mod, go.sum, integration_test/kafka_batching/kafka_batching_test.go
=> chore: rudder-go-kit v0.13.4

regulation-worker/cmd/main_test.go
Directly comparing gzip files, one stored locally as golden file and other downloaded from s3 might not be a good idea. Since, both might have different compression level. Hence, compressed output might be different for same file from these source.
https://www.notion.so/rudderstacks/regulation-worker-flaky-test-fix-785bba7ea60f4c508acdee6c0be3b8d1?pvs=4
=> fix: regulation-worker flaky test

warehouse/internal/service/loadfiles/downloader/downloader_test.go, warehouse/validations/validate_test.go
Validations flaky test
https://www.notion.so/rudderstacks/Validations-flaky-test-4c173cf3d74942dda2657e8e5ccaaf18?pvs=4
=> fix: warehouse flaky test

go.mod, go.sum
Updating kit to fix duplicated labels issue.
< [Notion Link](https://www.notion.so/rudderstacks/Fix-stats-duplicated-attributes-b6dce1a41523401097267172058e2ce7) >
=> fix: stats duplicated labels

warehouse/warehouse.go
Not closing the rows after executing the query is leaving the connection dangling. This PR now uses exec to avoid rows 
[Notion Link](https://www.notion.so/rudderstacks/Fix-Close-Rows-Warehouse-Crash-Recovery-a2ee799b5ba74226926e946c54e93c63?pvs=4)
=> chore: fix idle query

router/batchrouter/asyncdestinationmanager/asyncdestinationmanager.go, router/batchrouter/asyncdestinationmanager/bing-ads/bingads.go
=> update message structure of bingads_audience

router/batchrouter/asyncdestinationmanager/asyncdestinationmanager.go, router/batchrouter/asyncdestinationmanager/bing-ads/bingads.go, router/batchrouter/asyncdestinationmanager/bing-ads/bingads_sdk/base.go, router/batchrouter/asyncdestinationmanager/bing-ads/bingads_sdk/bulk.go, router/batchrouter/asyncdestinationmanager/bing-ads/bingads_sdk/client.go, router/batchrouter/batchrouter_test.go
=> chore.bing ads

warehouse/upload.go
Added flag to skip altering columns for warehouse
https://www.notion.so/rudderstacks/Warehouse-altering-columns-flag-3e99c9a29656474596eddfc7375e1bdb?pvs=4
=> fix: flag for warehouse altering

enterprise/reporting/error_reporting.go, enterprise/reporting/reporting.go, warehouse/integrations/clickhouse/clickhouse.go, warehouse/integrations/deltalake-native/deltalake.go, warehouse/integrations/postgres-legacy/postgres.go, warehouse/integrations/postgres/load.go, warehouse/integrations/redshift/redshift.go, warehouse/integrations/snowflake/snowflake.go
Namespace tag is automatically added by our stats library
=> chore: remove namespace tag from measurements

gateway/gateway.go, gateway/gateway_test.go
Using dedicated public endpoints for the warehouse instead of passing everything with the matching `/warehouse` pattern. Currently, the warehouse supports these endpoints:
```
GET     /health                         INTERNAL
POST    /v1/process                     INTERNAL
POST    /v1/warehouse/pending-events    PUBLIC
POST    /v1/warehouse/trigger-upload    PUBLIC
GET     /databricksVersion              INTERNAL
POST    /v1/warehouse/jobs              PUBLIC
GET     /v1/warehouse/jobs/status       PUBLIC
POST    /v1/warehouse/fetch-tables      PUBLIC
```
https://www.notion.so/rudderstacks/Gateway-endpoints-are-not-working-for-warehouse-b6e7acafe48f49a587f7f7ef7e401291?pvs=4
=> fix: warehouse proxy endpoints

sql/migrations/warehouse/000022_alter_wh_uploads_drop_mergedschema.up.sql
Reverts rudderlabs/rudder-server#3493
=> chore: revert drop merged schema column

gateway/gateway.go, gateway/gateway_test.go
Corrects the method `/fetch-tables`
https://www.notion.so/rudderstacks/Fix-for-warehouse-endpoint-for-fetching-endpoints-0b86acfaa10c494587259a45ab17c6c9?pvs=4
=> fix(gateway): method for /fetch-tables

processor/processor.go, utils/misc/misc.go, utils/types/types.go
I was examining the code while investigating duplicate issues and noticed some minor issues:
* The unmarshalling error is getting ignored.
* We unmarshal 4 times, one for the events, and three times for top-level fields. 
* Checking for the ok, adding unnecessary code depth and can be miss-directing.
https://www.notion.so/rudderstacks/minor-processor-refactor-6827228c426e4e1595c68387fd631551?pvs=4
=> refactor: minor processor refactor for error handling and readability 

warehouse/stats.go, warehouse/upload.go
Exclude attempt from stats because of high cardinality.
https://www.notion.so/rudderstacks/Exclude-attempt-from-stats-ba1e88fddead4f74861ce6915e2b07ca?pvs=4
=> chore: exclude attempt from metrics

enterprise/replay/setup.go
This PR enables the replay code to use IAM Role for S3 destination
[ Notion Link ](https://www.notion.so/rudderstacks/replay-for-expressVPN-7afcf7102ba148fda9ca8f8d3a61ee38?pvs=4)
=> chore: support replay with iam role

router/batchrouter/asyncdestinationmanager/asyncdestinationmanager.go, router/batchrouter/handle.go, router/batchrouter/handle_lifecycle.go
With this pr, we are adding the feature of updating destination config for async destinations.
=> feat: bingads destination config refresh

router/handle.go
Adding some more conditions for stopping router's pickup iteration if:
- parent context is cancelled
- event ordering is disabled and there is no worker slot available
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=bcb501de94b746bcad74086900dd0db5&pm=s)
=> chore(router): stop pickup iteration conditions

router/batchrouter/asyncdestinationmanager/bing-ads/bingads_test.go, router/batchrouter/asyncdestinationmanager/bing-ads/bulk_uploader.go, router/batchrouter/asyncdestinationmanager/bing-ads/util.go, router/batchrouter/asyncdestinationmanager/common/common.go, router/batchrouter/asyncdestinationmanager/common/manager.go, router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/marketobulkupload.go, router/batchrouter/handle.go, router/batchrouter/handle_async.go, router/batchrouter/handle_lifecycle.go
=> refactor: batch router handle async

enterprise/reporting/error_reporting.go, enterprise/reporting/reporting.go
- Add max open connections configuration for both normal and error detail reporting
- Close deleted rows for error-detail reporting
=> fix(destination): fix: add max-open connections & close deleted rows for reporting modules

go.mod, go.sum
Pulling new kit with the minio manager data race bugfix.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-54/minio-manager-data-race) >
=> fix: minio manager race

CHANGELOG.md, runner/buckets.go
Applying 1.11.3 hotfixes to main branch
chore: add custom buckets to gateway.user_suppression_age (#3679)
=> chore: applying 1.11.3 hotfixes to main branch

router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/marketobulkupload.go
=> fix: marketo bulk upload poll function

app/apphandlers/embeddedAppHandler.go
Write gateway needs to start before read gateway so that database migrations run properly and before runAlways migrations.
[Link](https://linear.app/rudderstack/issue/PIPE-116/when-running-in-embedded-mode-migration-fails-with-column-workspace-id)
=> fix(jobsdb): when running in embedded mode migration fails with column workspace_id does not exist

router/batchrouter/asyncdestinationmanager/bing-ads/util.go, router/batchrouter/asyncdestinationmanager/common/common.go, router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/marketobulkupload.go, router/batchrouter/handle.go, router/batchrouter/handle_async.go, router/batchrouter/handle_lifecycle.go, router/manager/manager.go, utils/misc/misc.go
=> fix: batch router attemptnos, reports, rsources stats

warehouse/archive/archiver.go, warehouse/archive/archiver_test.go, warehouse/jobs/runner.go, warehouse/warehouse.go
Prepared statements for archiver + more DRY and cleanup.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-121/warehouse-archiver-cleanup) >
=> chore: archiver cleanup

CHANGELOG.md, warehouse/integrations/azure-synapse/azure-synapse.go, warehouse/integrations/clickhouse/clickhouse.go, warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/deltalake/deltalake_test.go, warehouse/integrations/manager/manager.go, warehouse/integrations/mssql/mssql.go
Applying 1.12.2 hotfixes to main branch
chore: deltalake error message length (#3766)
fix: extend sql middleware for mssql, azure_synapse and clickhouse (#3771)
=> chore: applying 1.12.2 hotfixes to main branch

warehouse/archive/archiver.go
- Do not delete staging files during archival if opted for rudder storage, since there is already a retention policy set for the bucket.
- Also, by doing so, we will have an option to re-sync the data. We have seen a couple of cases, where customers opted for the rudder storage option and backups were not enabled.
- https://linear.app/rudderstack/issue/PIPE-197/stop-deleting-staging-files-during-archival-for-use-rudder-storage
=> fix: do not delete staging files when opted for rudderstorge during archival

LICENSE, README.md
Made some formatting updates to license.
Investigating why tests are failing (no answer to that for now)
=> chore: License update

CHANGELOG.md
Merge release 1.13.0 in main branch
**_CAUTION:_ needs to be merged using a Merge Commit!**
=> chore: merge release 1.13.0 in main branch

archiver/archiver.go, archiver/worker.go
Adding stats for monitoring archiver
[PIPE-229](https://linear.app/rudderstack/issue/PIPE-229/add-stats-for-archiver)
=> chore: add stats for archiver

go.mod, go.sum, services/kvstoremanager/redis.go
Upgrade to latest Redis package `github.com/redis/go-redis/v9` to overcome certificate issue.
=> fix: redis cluster mode

go.mod, go.sum
- Upgrading compose test
- https://linear.app/rudderstack/issue/PIPE-234/compose-test-error-logging-and-unmarshalling
=> chore: upgrade compose test

jobsdb/backup.go, jobsdb/jobsdb.go, jobsdb/jobsdb_test.go, jobsdb/migration.go, jobsdb/migration_test.go
Use new reloadable config in jobsdb.
[new reloadable config in jobsdb](https://linear.app/rudderstack/issue/PIPE-270/new-reloadable-config-in-jobsdb)
=> chore: new reloadable config in jobsdb

router/batchrouter/asyncdestinationmanager/eloqua/eloqua_test.go, router/batchrouter/asyncdestinationmanager/eloqua/testdata/uploadDataIdentify.txt, router/batchrouter/asyncdestinationmanager/eloqua/utils.go, router/batchrouter/handle_async.go
We only showed error messages without any details of which fields failed. We are not delivering the error message on the dashboard. So with this task, we are fixing those issues.
> Resolves INT-654
=> fix: update error processing of eloqua

processor/eventfilter/eventfilter.go
This branch was used to debug the e2e failures that we've been having since last week.
=> chore: better log message

processor/processor.go
using the memoized `payloadFunc` for deduplication.
=> chore: use memoized payloadFunc for dedup

CHANGELOG.md, processor/transformer/transformer.go, router/transformer/transformer.go
Applying 1.14.1 hotfixes to main branch
fix: router transformer client fails with error connect: cannot assign requested address (#3898)
=> chore: applying 1.14.1 hotfixes to main branch

archiver/archiver_isolation_test.go, backend-config/backend-config.go, backend-config/replay_types.go, backend-config/types.go, processor/processor.go, processor/processor_test.go, schema-forwarder/internal/testdata/configdata.go
=> chore: added flags for event audit

warehouse/utils/querytype.go, warehouse/utils/querytype_test.go
More query types fixes.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-390/fix-wh-query-type-for-update-query) >
=> fix: wh query types

cmd/devtool/commands/event.go, cmd/rudder-cli/db/queries.go, cmd/rudder-cli/gateway/gateway.go, cmd/rudder-cli/main.go, cmd/rudder-cli/router/router.go, cmd/rudder-cli/stash/stash.go, cmd/rudder-cli/status/status.go, cmd/rudder-cli/warehouse/warehouse.go, go.mod, go.sum, router/isolation/isolation_test.go
fixes PIPE-381 : upgrade urfave/cli v2 for rudder-cli
https://linear.app/rudderstack/issue/PIPE-381/upgrade-urfavecli-v2-for-rudder-cli
=> chore: upgrade urfave/cli v2 for rudder-cli

controlplane/controlplane.go, controlplane/manager.go, go.mod, warehouse/api/grpc.go, warehouse/api/grpc_test.go, warehouse/app.go
- Introducing response stats for GRPC.
- Resolves PIPE-456
=> feat: grpc middleware for stats

backend-config/namespace_config.go, backend-config/namespace_config_test.go
incremental update failure causes a panic. Removing that panic.
Resolves PIPE-515
[slack thread for context](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1699502654415459)
=> chore: remove panic and trigger full update on incremental update failure

CHANGELOG.md, backend-config/namespace_config.go, backend-config/namespace_config_test.go
Applying 1.16.3 hotfixes to main branch
chore: remove panic and trigger full update on incremental update failure (#4109)
=> chore: applying 1.16.3 hotfixes to main branch

warehouse/router/tracker.go
- Graceful termination for router cron tracker.
- Resolves PIPE-528
=> fix: graceful termination for cron tracker

warehouse/integrations/clickhouse/clickhouse_test.go
Uncommenting the commented out lines
Fixes : PIPE-482
=> chore: uncomment clickhouse integration test

router/handle.go
In case router iterator is interrupted prematurely, limits should not be considered to be reached, i.e. router shouldn't immediately run the next loop without sleeping first.
Additionally, in case router iterator is interrupted prematurely and iterator's discarded ratio is above the predefined limit, router's loop should pay the failing job penalty and sleep for additional time.
resolves PIPE-566
=> chore(router): interruption of iterator should cause router to sleep

warehouse/integrations/snowflake/snowflake.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/integrations/testhelper/verify.go, warehouse/slave/worker.go, warehouse/source/source.go, warehouse/source/types.go, warehouse/source/types_test.go, warehouse/utils/utils.go
Enhanced the DeleteBy method to use parameterized queries for improved security and maintainability.
Introduced a CustomTime type to standardize time-related operations across the system to support unmarshalling from a `"01-02-2006 15:04:05"` format.
Updated various structures to use time.Time and CustomTime instead of string representations for time fields, ensuring better type safety and consistency.
[slack thread link](https://rudderlabs.slack.com/archives/C017H2XKZ9R/p1700664781766739)
=> fix: snowflake delete

router/worker.go
Added error log to debug unmarshal errors
Resolves INT-1108
https://linear.app/rudderstack/issue/INT-1108/unmarshal-error-klaviyo
=> chore: error logs for unmarshal error debugging

.github/workflows/housekeeping.yaml
=> fix: align gha pr comment with workflow config

warehouse/source/source.go
- Avoid GetToProcess in case no pending jobs are present. https://github.com/rudderlabs/rudder-server/issues/4187 
- Resolves RUD-1043
=> fix: source no pending jobs

router/throttler/adaptive.go, router/throttler/adaptivethrottlercounter/algorithm.go, router/throttler/adaptivethrottlercounter/algorithm_test.go, router/throttler/adaptivethrottlercounter/decrease_limit_counter.go, router/throttler/adaptivethrottlercounter/increase_limit_counter.go, router/throttler/algorithm.go, router/throttler/factory.go, router/throttler/factory_test.go, router/throttler/static.go
=> Chore.aris pavan

CHANGELOG.md, app/apphandlers/setup.go, internal/drain-config/drainConfig.go, services/rsources/rsources.go
chore: tune shared db connection pooling (#4213)
=> chore: applying 1.18.1 hotfixes to main branch

services/rsources/handler.go
Before deleting stats for a job status, we are verifying first that the job is completed, so that we won't end up recording corrupted stats after a partial delete.
In case shared db is enabled, we shouldn't be using it for performing this verification, since it is being updated asynchronously through logical replication, so it is possible that it doesn't contain the latest stats. We should always be using the local db for such a verification.
resolves PIPE-636
=> chore: use local db in rsources handler for verifying job completed status

.github/workflows/dispatch-deploy-event-dev.yaml
Add a dedicated github workflow to empower automated releases.
No ticket at the moment
=> chore(ci): automated deployment

.github/workflows/dispatch-deploy-event-dev.yaml
=> fix(ci): fix distpatch event action typo

warehouse/integrations/deltalake/deltalake.go, warehouse/router/errors_test.go
- Additional error mappings for DELTALAKE destination
=> chore: additional error mappings for deltalake

utils/pubsub/pubsub.go
Starting the ping loop eagerly in producer function so that the channel will be closed on `close` even if no event has been published
resolves PIPE-646
=> fix: pubsub channel not closing during close if no value has been published

backend-config/backend_config_test.go, backend-config/namespace_config.go, backend-config/single_workspace.go
Adding the request size as well to understand pricing.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-695/backend-config-calls-metric) >
=> chore: backend config response size metric

processor/stash/stash_test.go
- Currently, we are logging as a byte sequence. [GA link.](https://github.com/rudderlabs/rudder-server/actions/runs/7536725383/job/20514557162?pr=4303)
```
stash_test.go:159: file list:  [0xc0007a10b0 0xc0007a10e0]  err:  <nil> len:  2
stash_test.go:159: file list:  [0xc000bb83f0 0xc000bb8420]  err:  <nil> len:  2
stash_test.go:153: 
Error Trace:	/home/runner/work/rudder-server/rudder-server/processor/stash/stash_test.go:153
Error:      	Condition never satisfied
Test:       	TestStoreErrorsToObjectStorage
Messages:   	no backup files found in backup store: %!(EXTRA <nil>)
--- FAIL: TestStoreErrorsToObjectStorage (26.17s)
```
- Log as string instead of byte sequence for better debuggability.
=> chore: improve error logs during processor stash test

warehouse/integrations/deltalake/deltalake_test.go
- Proper location format for datbricks test.
=> chore: set container and account name for load file does not exist test for databricks

services/streammanager/kafka/kafkamanager_test.go, services/streammanager/kafka/testdata/aiokafka/Dockerfile, services/streammanager/kafka/testdata/aiokafka/consumer.py, services/streammanager/kafka/testdata/aiokafka/requirements.txt
Adding a test for aiokafka consumer, when using batching and zstd compression.
resolves PIPE-752
=> chore: add tests for aiokafka consumer

.github/workflows/tests.yaml
Change GHA to account for breaking changes in codecov version
Fixes PIPE-774
=> chore: fix code cov breaking change

cmd/benchmark/throttling/deployment.yaml
Changes on yaml file as reported by https://app.snyk.io/org/rudder-server/project/45121e96-de97-496f-a4cc-a4e02a915ab3 and also used https://github.com/aquasecurity/trivy for additional verification.
I understand that this deployment yaml is not used in production, it was probably an one off use. I felt is better to fix those minor use rather than ignore them or delete it.  I wanted to remove any noise from our snyk report, with this change rudder-server repo will have zero issue.
resolves [PIPE-792](https://linear.app/rudderstack/issue/PIPE-792/fix-benchmarkthrottlingdeploymentyaml-snyk-security-issues
)
=> chore: fix snyk reported security issues with benchmark k8s deployment

processor/processor.go
Fix empty customVal in router tables
Fixes PIPE-867
=> fix: empty customVal in rt tables

router/worker.go
fixes: dontbatch not persisted properly
INT-1616
=> fix: dontbatch not persisted properly

router/batchrouter/handle_async.go
decrease pending events for async destinations.
[slack thread](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1709989850630779)
=> fix: decrease async destination pending events

schema-forwarder/internal/transformer/transformer.go
Sending blank sample event to event schemas
https://linear.app/rudderstack/issue/DAT-1015/stop-collecting-sample-events-from-rudder-server
=> chore: sending blank event to event schemas

warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/deltalake/deltalake_test.go
For Databricks the way we have been doing merge was running the merge query on the last 2 days data. This PR attempts to run merge on all the old data and not based on the partitioned data
Fixes PIPE-895
=> chore: fix databricks merge query

warehouse/api/grpc.go, warehouse/api/grpc_test.go, warehouse/internal/model/upload.go, warehouse/internal/repo/upload.go
Optimise WH Syncs Page Queries
=> fix: optimise WH Syncs page query

CHANGELOG.md, warehouse/api/grpc.go, warehouse/api/grpc_test.go, warehouse/internal/model/upload.go, warehouse/internal/repo/upload.go
fix: optimise WH Syncs page query (#4507)
=> chore: applying 1.22.1 hotfixes to main branch

router/batchrouter/handle_async.go, router/handle.go, router/handle_lifecycle.go, router/network.go, router/router_test.go, router/types.go, router/types/types.go, router/worker.go
Remove unused router code and config
Fixes PIPE-986
=> chore: remove unused code

CONTRIBUTING.md
Updates contribution guide with the new CLA link
=> doc: update cla link

gateway/handle.go
- Adding destination id in jobs db params for internal batch event
- Resolves PIPE-1026
=> feat: adding destination id in params

CHANGELOG.md
Merge release branch in master
NA - Release process
feat: adding destination id in params (#4618)
feat: monitor warehouse databases (#4619)
feat: onboard Yandex Metrica Offline Events destination (#4534)
=> chore: release 1.24.0 (#4617)

gateway/webhook/webhook.go
=> fix: query params not added with iteration

gateway/webhook/webhook.go, gateway/webhook/webhook_test.go
refactoring the code and adding unit test case for the util function
=> fix: refactor and adding unit test case

warehouse/integrations/datalake/datalake_test.go, warehouse/validations/validate_test.go
- Updated bucket name for both the tests in validations and datalake package.
- Resolves PIPE-1105
=> fix: warehouse tests

CHANGELOG.md
Syncing release v1.26.0 to main branch
=> chore: sync release v1.26.0 to main branch

CHANGELOG.md, warehouse/archive/archiver.go, warehouse/archive/archiver_test.go
Syncing patch release v1.26.1 to main branch
=> chore: sync release v1.26.1 to main branch

CHANGELOG.md, gateway/handle.go, gateway/webhook/webhook.go, gateway/webhook/webhook_test.go
Syncing patch release v1.26.2 to main branch
=> chore: sync release v1.26.2 to main branch

jobsdb/integration_test.go, jobsdb/jobsdb.go
* Do a full marshal/unmarshal to clean the payload properly 
* Improve tests
Resolves PIPE-1172
=> fix: jobsdb handle: unicode low surrogate must follow a high surrogate

gateway/gateway_test.go, gateway/handle.go, processor/manager_test.go, processor/processor.go, runner/buckets.go
Addressing comments from https://github.com/rudderlabs/rudder-server/pull/4756
resolves PIPE-1168
=> chore: event lag metric (follow up)

CHANGELOG.md, jobsdb/integration_test.go, jobsdb/jobsdb.go
Syncing patch release v1.26.3 to main branch
fix: jobsdb handle: unicode low surrogate must follow a high surrogate (#4762)
=> chore: sync release v1.26.3 to main branch

integration_test/transformer_contract/transformer_contract_test.go, testhelper/backendconfigtest/config_builder.go
- Integration test for Processor Transformer.
=> chore: transformer processor contract test

CHANGELOG.md
Syncing release v1.27.0 to main branch
=> chore: sync release v1.27.0 to main branch

CHANGELOG.md
Syncing release v1.28.0 to main branch
=> chore: sync release v1.28.0 to main branch

warehouse/integrations/postgres/postgres_test.go, warehouse/integrations/postgres/testdata/docker-compose.replication.yml, warehouse/integrations/postgres/testdata/initdb/primary/init.sql
- Added test case for logical replication setup.
- Resolves PIPE-1196
=> chore: added test for postgres replication

integration_test/trackedusersreporting/tracked_users_reporting_test.go, testhelper/backendconfigtest/config_builder.go, testhelper/backendconfigtest/source_builder.go
Add integration tests for tracked users reporting
pipe-1202
=> chore: add integration tests for mtu reporting

processor/processor.go, processor/processor_test.go
We have found that all the values containing number in the payload comes as float64 rather than some of it being int
Added the fix to caste into float and then extract int value
< Replace with Linear Link ( [create](https://linear.new?title=Awesome-pr-without-linear-ticket) or [search](https://linear.app/rudderstack/search) linear ticket) or  >
-
=> fix: type conversion from float64 to int

CHANGELOG.md, gateway/webhook/setup.go, gateway/webhook/webhook.go, gateway/webhook/webhook_test.go
Syncing patch release v1.30.2 to main branch
fix: introduce config for get requests in webhook sources (#4927)
=> chore: sync release v1.30.2 to main branch

go.mod, go.sum, warehouse/integrations/snowflake/snowflake.go, warehouse/integrations/snowflake/snowflake_test.go
- Integrate sqlconnect-go for snowflake
- Resolves PIPE-1343
=> chore: integrate sqlconnect-go for snowflake

CHANGELOG.md
Syncing patch release v1.30.4 to main branch
=> chore: sync release v1.30.4 to main branch

router/batchrouter/batchrouter_test.go, warehouse/archive/archiver_test.go
- Use minioResource.Contents from go-kit.
=> chore: cleanup duplicate minio contents

CHANGELOG.md
Syncing release v1.32.0 to main branch
=> chore: sync release v1.32.0 to main branch

gateway/webhook/webhook.go, gateway/webhook/webhook_test.go
now we are passing x-* headers to source transformer
Resolves INT-2193
=> feat: add support for headers to webhooks

.github/workflows/verify.yml, Dockerfile, Makefile, cmd/rudder-cli/status/status.go, go.mod, regulation-worker/internal/client/client_test.go, regulation-worker/internal/delete/api/api.go, regulation-worker/internal/delete/api/api_test.go, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bingads_test.go, router/batchrouter/asyncdestinationmanager/klaviyobulkupload/klaviyobulkupload.go, router/batchrouter/asyncdestinationmanager/yandexmetrica/yandexmetrica.go, router/transformer/transformer.go, services/streammanager/bqstream/bqstreammanager.go, suppression-backup-service/Dockerfile, warehouse/integrations/postgres/postgres.go, warehouse/internal/loadfiles/loadfiles.go, warehouse/utils/utils_test.go, warehouse/validations/validate.go
Upgrade go to 1.23
Fixes PIPE-1485
=> chore: upgrade go to 1.23.0

CHANGELOG.md, gateway/webhook/integration_test.go, gateway/webhook/webhook.go, gateway/webhook/webhook_test.go, go.mod, go.sum
Syncing patch release v1.33.1 to main branch
fix: revert support for webhook headers (#5064)
=> chore: sync release v1.33.1 to main branch

CHANGELOG.md, router/handle_lifecycle.go, services/dedup/scylla/scylla.go, warehouse/integrations/datalake/datalake_test.go
Syncing release v1.34.0 to main branch
=> chore: sync release v1.34.0 to main branch

.github/workflows/tests.yaml, CHANGELOG.md, integration_test/warehouse/testdata/docker-compose.ssh-server.yml, jobsdb/jobsdb.go, warehouse/integrations/azure-synapse/azure_synapse_test.go, warehouse/integrations/azure-synapse/testdata/docker-compose.yml, warehouse/integrations/mssql/mssql_test.go, warehouse/integrations/mssql/testdata/docker-compose.yml, warehouse/integrations/postgres/testdata/docker-compose.ssh-server.yml, warehouse/integrations/testdata/docker-compose.jobsdb.yml, warehouse/integrations/testdata/docker-compose.minio.yml, warehouse/integrations/tunnelling/testdata/docker-compose.yml
Merge 1.34.1 into main branch
chore: sync release v1.34.0 to main branch (#5113)
chore: schema and record assertions in warehouse integration test (#5091)
=> chore: merge release 1.34.1 in main branch

.github/workflows/tests.yaml, CHANGELOG.md, integration_test/warehouse/testdata/docker-compose.ssh-server.yml, jobsdb/jobsdb.go, warehouse/integrations/azure-synapse/azure_synapse_test.go, warehouse/integrations/azure-synapse/testdata/docker-compose.yml, warehouse/integrations/mssql/mssql_test.go, warehouse/integrations/mssql/testdata/docker-compose.yml, warehouse/integrations/postgres/testdata/docker-compose.ssh-server.yml, warehouse/integrations/testdata/docker-compose.jobsdb.yml, warehouse/integrations/testdata/docker-compose.minio.yml, warehouse/integrations/tunnelling/testdata/docker-compose.yml
Syncing patch release v1.34.1 to main branch
chore: set maxIdleConns for jobsdb handles and emit (*sql.DB).Stats (#5123)
=> chore: sync release v1.34.1 to main branch

.github/workflows/tests.yaml, integration_test/warehouse/warehouse_test.go, warehouse/integrations/azure-synapse/azure_synapse_test.go, warehouse/integrations/clickhouse/clickhouse_test.go, warehouse/integrations/datalake/datalake_test.go, warehouse/integrations/deltalake/deltalake_test.go, warehouse/integrations/mssql/mssql_test.go, warehouse/integrations/postgres/postgres_test.go, warehouse/integrations/redshift/redshift_test.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/integrations/testdata/docker-compose.transformer.yml, warehouse/integrations/testhelper/records.go
- Added integration test for the associated transformer changes:
- https://github.com/rudderlabs/rudder-transformer/pull/3752
- https://github.com/rudderlabs/rudder-transformer/pull/3753
- Resolves PIPE-1262.
- Resolves PIPE-1413.
- Resolves PIPE-1352
- Resolves PIPE-1421
=> test: users context traits and populate users fields

config/config.yaml, enterprise/reporting/reporting.go, utils/types/reporting_types.go
Reverts rudderlabs/rudder-server#5138
=> chore: revert "chore: trim eventNames sent to reporting if length exceeds 50 characters"

warehouse/app.go, warehouse/integrations/deltalake/deltalake_test.go, warehouse/internal/mocks/utils/mock_uploader.go, warehouse/internal/model/upload.go, warehouse/internal/model/upload_test.go, warehouse/multitenant/manager.go, warehouse/router/router.go, warehouse/router/scheduling.go, warehouse/router/scheduling_test.go, warehouse/router/tracker.go, warehouse/router/upload.go, warehouse/source/source.go, warehouse/utils/utils.go, warehouse/validations/validate.go
- Minor cleanup around the warehouse module.
=> chore: cleanup warehouse

warehouse/integrations/snowflake/snowflake.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/integrations/testhelper/setup.go
Speed up slow warehouse syncs for a customer by limiting the dedup window.
Introduce flags under `Warehouse.snowflake.mergeWindow.<destinationID>` (tables, duration, column)
Use `additionalJoinClause` to filter target table by date `AND original.%s >= DATEADD(hour, -%d, CURRENT_TIMESTAMP())`
https://linear.app/rudderstack/issue/PRI-49/snowflake-dedup-window-for-phantom
=> feat: introduce merge window for snowflake ingestion

warehouse/router/router.go
Fix stuck warehouse module
Fixes PIPE-1627
=> chore: fix stuck runUploadJobAllocator

router/router_test.go, services/dedup/badger/badger.go, services/dedup/dedup_test.go, services/dedup/mirrorBadger/mirrorBadger.go, services/dedup/mirrorScylla/mirrorScylla.go, services/dedup/scylla/scylla.go, warehouse/archive/archiver.go, warehouse/integrations/postgres/postgres.go
Adding time stats to dedup module
Fixes PIPE-1626
=> chore: add stats to dedup module

CHANGELOG.md, jobsdb/jobsdb_test.go
Syncing release v1.36.0 to main branch
chore: remove old replay code (#5198)
=> chore: sync release v1.36.0 to main branch

go.mod, go.sum, warehouse/transformer/testdata/fuzz/FuzzTransformerJSON/0420b68b7550b8b8, warehouse/transformer/testdata/fuzz/FuzzTransformerJSON/c234464ba1289fcb, warehouse/transformer/testdata/fuzz/FuzzTransformerJSON/cbbad75732661f48, warehouse/transformer/testdata/fuzz/FuzzTransformerJSON/d216d9ba19b7f97c, warehouse/transformer/transformer_test.go
< Replace with Linear Link ( [create](https://linear.new?title=Awesome-pr-without-linear-ticket) or [search](https://linear.app/rudderstack/search) linear ticket) or  >
=> Feat.warehouse transformer fuzz

router/batchrouter/handle_async.go
Add logs for visibility for errors
=> fix: add error logs for handle async for visibility of error

CHANGELOG.md, router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/apiService.go, router/batchrouter/handle_async.go
Syncing patch release v1.37.2 to main branch
fix: add error logs for handle async for visibility of error (#5248)
fix: parse error due incrorrect csv response from marketo-n (#5252)
=> chore: sync release v1.37.2 to main branch

CHANGELOG.md, Dockerfile, go.mod, suppression-backup-service/Dockerfile
Syncing release v1.38.0 to main branch
=> chore: sync release v1.38.0 to main branch

CHANGELOG.md, warehouse/integrations/bigquery/bigquery_test.go, warehouse/integrations/bigquery/partition.go, warehouse/integrations/bigquery/partition_test.go
Syncing patch release v1.38.1 to main branch
fix: bq partitioning for additional columns (#5293)
=> chore: sync release v1.38.1 to main branch

go.mod, go.sum, services/notifier/notifier.go, services/notifier/repo.go
Upgrade pg-lock major version to fix a connection bug
Fixes PIPE-1730
=> chore: upgrade major version pglock

processor/processor.go, regulation-worker/internal/client/client.go, regulation-worker/internal/delete/delete.go, regulation-worker/internal/model/model.go, regulation-worker/internal/service/looper.go, regulation-worker/internal/service/service.go
=> chore: minor fixes

.github/workflows/builds.yml
=> chore: moving docker login before buildx

.github/workflows/builds.yml
=> chore: moving docker login before buildx in release

.github/workflows/builds.yml, CHANGELOG.md, enterprise/reporting/reporting.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/apiadapter.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/channel.go
Syncing release v1.39.0 to main branch
=> chore: sync release v1.39.0 to main branch

CHANGELOG.md, warehouse/router/router.go
Syncing patch release v1.39.1 to main branch
fix: processing pickup race condition (#5374)
=> chore: sync release v1.39.1 to main branch

CHANGELOG.md, enterprise/reporting/error_reporting.go, enterprise/reporting/flusher/flusher.go, enterprise/reporting/reporting.go
sync release 1.38.x with current release
NA
=> chore: sync release v1.38.4 to main branch (#5333)

CHANGELOG.md, go.mod, go.sum, processor/transformer/transformer.go, processor/transformer/transformer_test.go, utils/sysUtils/httpclient.go
Syncing release v1.40.0 to main branch
chore(deps): bump the go-deps group with 2 updates (#5412)
fix: invalid error response handling during oauth refresh flow (#5401)
=> chore: sync release v1.40.0 to main branch

warehouse/encoding/parquetloader.go, warehouse/integrations/azure-synapse/azure-synapse.go, warehouse/integrations/mssql/mssql.go, warehouse/logfield/logfield.go, warehouse/slave/worker.go
- As part of security enhancements, customer payloads from logs are removed.
- Resolves WAR-135
=> chore: remove customer payloads from warehouse logs

CHANGELOG.md, gateway/handle.go
Syncing release v1.41.0 to main branch
=> chore: sync release v1.41.0 to main branch

CHANGELOG.md, warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/deltalake/deltalake_test.go
Syncing patch release v1.42.1 to main branch
=> chore: sync release v1.42.1 to main branch

processor/internal/trackingplan_validation/trackingplan_validation.go, processor/internal/user_transformer/user_transformer.go, processor/processor.go
< Replace with Linear Link ( [create](https://linear.new?title=Awesome-pr-without-linear-ticket) or [search](https://linear.app/rudderstack/search) linear ticket) or  >
=> chore: run tests with v2 enabled

processor/transformer/transformer.go, router/transformer/transformer.go, router/transformer/transformer_test.go
* introduce metrics on router transformer metrics for cost attribution
* Two stages are being capture router and router_proxy 
* fix issue with logs on processor transformer [transformer.go](https://github.com/rudderlabs/rudder-server/pull/5511/files#diff-e5cf9e714ad0653a0fbb461268f1bae1b457735baa48d6658e40ed2840c124f3)
https://linear.app/rudderstack/issue/PRI-167/introduce-transformer-client-metrics-in-rudder-server-for-cost
Resolves PRI-167
=> feat: introduce router transformer metrics for cost attribution

CHANGELOG.md
Syncing release v1.43.0 to main branch
feat: make json library configurable and introduce sonnet as an option (#5513)
=> chore: sync release v1.43.0 to main branch

sql/migrations/pg_notifier_queue/0000005_drop_unused_columns.up.sql, sql/migrations/warehouse/000029_drop_unused_columns.up.sql
- Drop unused columns from warehouse jobsdb.
- Resolves WAR-344
=> chore: drop unused columns

jobsdb/jobsdb.go
Introducing a set of new metrics for capturing jobsdb throughput in terms of number of jobsd/events and bytes being stored/queried/updated.
- `jobsdb_stored_jobs`: counter for measuring job store rates
- `jobsdb_stored_bytes`: counter for measuring job store payload rates
- `jobsdb_queried_jobs`: counter for measuring job query rates
- `jobsdb_queried_bytes`: counter for measuring job query payload rates
- `jobsdb_updated_jobs`: counter for measuring job status update rates
- `jobsdb_updated_bytes`: counter for measuring job status update response payload rates
resolves PIPE-1921
=> chore(jobsdb): add metrics for job and payload throughput

jobsdb/jobsdb.go
Index optimizations mentioned [here](https://www.notion.so/rudderstacks/JobsDB-Benchmarking-Q1-2025-1a7f2b415dd0805f9b84c44758eb565f?pvs=4#1a8f2b415dd08019b105c187f4da7555) are now enabled by default with an option to disable them in case of unexpected issues. The configuration flag shall be removed after the next release, as soon as the change has been rolled out to all customers.
- Removing primary key index which is not being used by any query to avoid the unnecessary write overhead.
- Extending existing `(job_id,id)` index to include `job_state` which helps speed up migration checking query (index-only scan).
- Adding an index for `(id ,job_state) INCLUDE (exec_time)` which speeds up `maxDSRetention` query during migration checking.
resolves PIPE-1928
=> chore(jobsdb): optimize job status table indexes

warehouse/transformer/benchmark/Dockerfile, warehouse/transformer/benchmark/Makefile, warehouse/transformer/benchmark/deployment.yaml, warehouse/transformer/benchmark/main.go
- Benchmarking support for warehouse transformations.
- Resolves WAR-389
=> chore: warehouse transformer benchmarking tool

warehouse/transformer/benchmark/Dockerfile, warehouse/transformer/benchmark/Makefile, warehouse/transformer/benchmark/deployment.yaml, warehouse/transformer/benchmark/main.go, warehouse/transformer/transformer.go, warehouse/transformer/types.go
- Instead of doing sequential processing for each event, introducing concurrency. We are getting 3.6x times more processing. More about it [this](https://www.notion.so/rudderstacks/Warehouse-Transformation-Optimizations-1b2f2b415dd08039a6a5c70695100411?pvs=4#1b3f2b415dd080a9b971d6f8cfd10f78) doc.
- Resolves WAR-279
=> chore: warehouse transformer optimizations for concurrency

services/dedup/badger/badger.go
race condition in dedup service causing panic, since two go routines are trying to commit the same key
resolves PIPE-1970
=> fix: race condition in dedup service causing panic

CHANGELOG.md
Syncing release v1.45.0 to main branch
=> chore: sync release v1.45.0 to main branch

.golangci.yml, CHANGELOG.md, go.mod, go.sum, jsonrs/json.go, jsonrs/json_fuzz_test.go, jsonrs/sonnet.go
Syncing patch release v1.45.1 to main branch
fix: sonnet panic while unmarshalling float64 types (#5616)
=> chore: sync release v1.45.1 to main branch

warehouse/transformer/events_test.go
Fixing compilation issue in test
=> fix: compilation error in events_test.go

sql/migrations/warehouse/000030_add_upload_id_to_wh_load_files.up.sql, warehouse/internal/loadfiles/loadfiles.go, warehouse/internal/model/load.go, warehouse/internal/repo/load.go, warehouse/internal/repo/load_test.go
https://linear.app/rudderstack/issue/WAR-458/link-load-files-with-upload-job-instead-of-staging-file
=> feat: add upload_id column in wh_load_files table

gateway/webhook/integration_test.go
Server - Transformer communication is defaulted to v2 format for webhook sources. Clean up of integration tests to cater to that change.
Quick fix, doesn't require linear ticket
=> chore: clean up tests because transformer defaults to v2

gateway/webhook/integration_test.go
Server - Transformer communication is defaulted to v2 format for webhook sources. Clean up of integration tests to cater to that change.
Quick fix, doesn't require linear ticket
=> chore: fix webhook tests in release branch

warehouse/internal/repo/staging.go
**BUG:** Unmarshalling of existing records in the `wh_staging_files` table was failing due to the `bytes_per_table` column having a default value of NULL.
**FIX:**
Updated the insert and read methods to handle the nil case for BytesPerTable
=> fix: unmarshalling error for staging files without bytes per table

CHANGELOG.md, warehouse/internal/repo/staging.go, warehouse/transformer/benchmark/main.go, warehouse/transformer/events.go, warehouse/transformer/internal/rules/rules.go, warehouse/transformer/set.go, warehouse/transformer/transformer.go, warehouse/transformer/transformer_benchmark_test.go
Syncing release v1.47.0 to main branch
feat: use header augmenter for router transformer client (#5640)
feat: query load files using upload_id instead of staging_file_id (#5700)
=> chore: sync release v1.47.0 to main branch

processor/internal/transformer/destination_transformer/destination_transformer.go, router/transformer/transformer.go
disabling transformer request payload compaction
=> chore: disable transformer compaction by default

CHANGELOG.md, router/batchrouter/handle.go, router/batchrouter/handle_lifecycle.go, router/batchrouter/partition_worker.go
Syncing release v1.48.0 to main branch
feat: update config to add account details with destination in workspaceConfig (#5753)
chore: migrate from denisenkom/go-mssqldb to microsoft/go-mssqldb (#5776)
=> chore: sync release v1.48.0 to main branch

go.mod, go.sum, warehouse/api/grpc.go, warehouse/archive/archiver.go, warehouse/identity/identity.go, warehouse/integrations/datalake/datalake.go, warehouse/integrations/datalake/schema-repository/glue_test.go, warehouse/integrations/datalake/schema-repository/glue_v2.go, warehouse/integrations/datalake/schema-repository/schema_repository.go, warehouse/integrations/redshift/redshift.go, warehouse/integrations/testhelper/staging.go, warehouse/internal/service/loadfiles/downloader/downloader.go, warehouse/router/state_export_data.go, warehouse/router/upload.go, warehouse/slave/worker_job.go, warehouse/utils/utils.go, warehouse/validations/validate.go
< Replace with Linear Link ( [create](https://linear.new?title=Awesome-pr-without-linear-ticket) or [search](https://linear.app/rudderstack/search) linear ticket) or  >
=> feat: glue v2 implementation

CHANGELOG.md, processor/consent.go, processor/consent_test.go, processor/processor_test.go
Syncing patch release v1.49.1 to main branch
chore: revert support new consent resolution strategy values (#5855)
=> chore: sync release v1.49.1 to main branch

go.mod, go.sum, processor/internal/transformer/destination_transformer/embedded/warehouse/events_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/uploader.go
- While encoding using the `jsonrs` package, it uses the ([jsoniter](https://github.com/rudderlabs/rudder-go-kit/blob/main/jsonrs/sonnet.go#L41-L48)) library, there is a difference in the output for floating point values, although the value remains the same.
```GO
func TestJSON(t *testing.T) {
data := map[string]any{"output_tokens_cost": 0.0000006}
tests := []struct {
name            string
lib             string
expectedMarshal string
expectedEncode  string
}{
{
name:            "StdLib",
lib:             jsonrs.StdLib,
expectedMarshal: `{"output_tokens_cost":6e-7}`,
expectedEncode:  `{"output_tokens_cost":6e-7}`,
},
{
name:            "JsoniterLib",
lib:             jsonrs.JsoniterLib,
expectedMarshal: `{"output_tokens_cost":6e-07}`,
expectedEncode:  `{"output_tokens_cost":6e-07}`,
},
} …
```
=> chore: warehouse transformations json diff with encoding

processor/processor.go
- Added store sampler for processor to upload sample events in case storing to Postgres fails.
- Resolves WAR-697
=> chore: proc sample store uploader

.github/workflows/prerelease.yaml, .github/workflows/release-please.yaml
triggers deployment for staging and hosted releases
pipe-2097
=> feat: triggers deployment for staging and hosted releases

enterprise/reporting/client/client.go
With the shared backoff, the retries could be waiting for longer time than required. With this PR, we are creating new backoff for every request
=> chore: create new backoff on every reporting request

processor/internal/transformer/destination_transformer/embedded/warehouse/events_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/idresolution.go, processor/internal/transformer/destination_transformer/embedded/warehouse/internal/utils/utils.go, processor/internal/transformer/destination_transformer/embedded/warehouse/internal/utils/utils_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/testhelper/outputbuilder.go
- Add mergePropTwo for empty values as well.
- Resolves WAR-787.
=> fix: warehouse transformations id resolution

CHANGELOG.md
Syncing release v1.54.0 to main branch.
BEGIN_COMMIT_OVERRIDE 
=> chore: sync release v1.54.0 to main branch

CHANGELOG.md, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bingads_test.go, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bulk_uploader.go
Syncing patch release v1.54.1  to main branch
fix: update validation and conversion of timestamp to bingads offline conversion supported format (#6082)
=> chore: sync release v1.54.1 to main branch

CHANGELOG.md, router/handle_lifecycle.go, router/worker.go
Syncing patch release v1.55.2 to main branch
fix(router): worker's batch timeout is getting resetted after new job arrival (#6167)
fix(router): timeout doesn't reset when there are no jobs (#6171)
=> chore: sync release v1.55.2 to main branch

warehouse/internal/repo/load.go, warehouse/internal/repo/schema.go, warehouse/internal/repo/schema_test.go, warehouse/internal/repo/staging.go, warehouse/internal/repo/staging_test.go, warehouse/internal/repo/upload.go, warehouse/internal/repo/upload_test.go
- Add necessary tests and modifications related to enableJsonbToText and enableLz4Compression configs for Warehouse
- Resolves WAR-854, WAR-849
=> chore: modifications and tests related chagnes for the warehouse lz4 and jsonb to text conversion

services/notifier/notifier_test.go, services/notifier/repo.go, services/notifier/repo_test.go
- Add necessary tests and modifications related to enableJsonbToText and enableLz4Compression configs for PG notifier
- Resolves WAR-854, WAR-849
=> chore: modifications and tests related changes for the notifier lz4 and jsonb to text conversion

processor/integrations/integrations.go, router/delivery_throttler_test.go, router/router_test.go, router/throttler/factory.go, router/throttler/internal/delivery/throttler.go, router/throttler/internal/delivery/throttler_test.go, router/worker.go
Renaming endpointLabel to endpointPath
=> chore(router): rename endpointLabel to endpointPath

go.mod, go.sum, processor/internal/transformer/user_transformer/user_transformer.go
Adding some context information on ut http error logs to be able to debug misconfigured transformations
=> chore: add context information on ut http error logs

CHANGELOG.md, enterprise/reporting/error_reporting.go, enterprise/reporting/error_reporting_db_test.go
Syncing release v1.58.0 to main branch
=> chore: sync release v1.58.0 to main branch

CHANGELOG.md, Makefile, services/notifier/notifier.go, services/notifier/notifier_test.go, warehouse/api/grpc.go, warehouse/api/grpc_test.go, warehouse/api/http.go, warehouse/api/http_test.go, warehouse/app.go, warehouse/app_test.go, warehouse/bcm/backend_config.go, warehouse/internal/repo/repo_test.go, warehouse/internal/repo/schema.go, warehouse/internal/repo/schema_test.go, warehouse/router/router_test.go, warehouse/router/upload.go, warehouse/schema/schema_test.go
Syncing patch release v1.58.1 to main branch
fix: remove unwanted table level schemas (#6296)
fix: avoid running migrations for notifier from slaves (#6303)
=> chore: sync release v1.58.1 to main branch

CHANGELOG.md, router/worker.go, router/worker_test.go, warehouse/integrations/deltalake/deltalake_test.go, warehouse/integrations/redshift/redshift_test.go, warehouse/integrations/snowflake/snowflake.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/utils/utils.go, warehouse/utils/utils_test.go
Syncing patch release v1.59.1 to main branch
fix: add outgoing metrics to proxy flow (#6355)
fix: aws session config region (#6354)
=> chore: sync release v1.59.1 to main branch

router/batchrouter/asyncdestinationmanager/README.md
We are adding a readme to asyncdestinaiton manager to understand and onboard a new async integration.
https://linear.app/rudderstack/issue/INT-4136/create-read-me-for-async-destinations
=> chore: add readme for async destinaiton module
