rudderlabs/rudder-server

runner/runner.go, warehouse/archive/archiver.go, warehouse/archive/archiver_test.go, warehouse/archive/cron.go, warehouse/warehouse.go
- Remove `archive.Init()`
- Expose `archive.New(...)` to initialize.
- Remove Globals.
- https://linear.app/rudderstack/issue/PIPE-117/warehouse-init-cleanup
=> chore: remove Init and exported struct variables from Archiver

router/batchrouter/asyncdestinationmanager/bing-ads/bulk_uploader.go
Safe typecast fix.
https://linear.app/rudderstack/issue/INT-244/bingads-audience-upload-via-batch-router
=> chore: bingads safetypecast

warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/deltalake/deltalake_test.go
- While creating an external table, we are getting an error since there is already some data present specifying some other schema, and in the error messages, it's dumping the entire other schema which is coming to be very huge. It's reaching around 20MB.
- For delta lake, trim error if it exceeds 64KB
- https://linear.app/rudderstack/issue/PIPE-164/deltalake-error-length
=> chore: deltalake error message length

warehouse/integrations/azure-synapse/azure-synapse.go, warehouse/integrations/clickhouse/clickhouse.go, warehouse/integrations/manager/manager.go, warehouse/integrations/mssql/mssql.go
- Extend SQL middleware to MSSQL, AZURE SYNAPSE, CLICKHOUSE
- https://linear.app/rudderstack/issue/PIPE-174/extend-sql-middleware-to-remaining-destinations
=> fix: extend sql middleware for mssql, azure_synapse and clickhouse

router/worker.go
`router_response_counts` stat now tell if an attempt is a retry(true/false).
Checks if `attemptNum > 1`.
[adding retry flag to `router_response_counts`](https://linear.app/rudderstack/issue/PIPE-193/adding-retry=bool-labeltag-to-router-delivery-stats)
=> chore: router_response_counts stat now shows if it's a retry attempt

warehouse/integrations/snowflake/snowflake.go, warehouse/integrations/snowflake/snowflake_test.go
- Cloud extract should always go for MERGE irrespective of what the loadTableStrategy is set.
- https://linear.app/rudderstack/issue/PIPE-195/cloud-sources-always-append
=> chore: cloud extract should always merge

jobsdb/jobsdb.go
corrects jobsdb table count stat that was erroneously removed instead of another redundant stat.
[release-1.13 fixes](https://linear.app/rudderstack/issue/PIPE-203/release-1130-fixes)
=> fix: correct jobsdb table count stat

archiver/archiver.go, archiver/archiver_test.go, archiver/options.go, archiver/worker.go, processor/processor.go
Stop querying archival jobsdb if archival is disabled, and sets parameters in the archival job status.
[release-1.13 fixes](https://linear.app/rudderstack/issue/PIPE-203/release-1130-fixes)
=> fix: don't query db if archival is disabled, set parameters in jobStatus

jobsdb/jobsdb.go, jobsdb/queued_db_request.go, processor/processor_test.go, processor/stash/stash.go, router/batchrouter/batchrouter_test.go, router/batchrouter/handle.go, router/internal/jobiterator/jobiterator.go
Switching back to multiple queries in router, batchrouter & stash loops, while keeping jobsdb refactoring introduced by #3742.
**JobsDB changes:**
- `getJobsDS` optimisations so that efficient joins are used for different `stateFilters`
- `GetToProcess` uses 3 distinct queries, as it did before #3742 changes
=> fix: increased postgres cpu usage after switching to a single get jobs query

router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/marketobulkupload.go, router/batchrouter/handle_async.go
Resolves INT-157
we have added the poll error object to ensure more visibility.
=> fix: adding the poll failure response details to db

warehouse/slave_worker_job.go
- Removing table name from load file since table name comes long it exceeds the limit set for filename. 
- `open /data/rudderstack/rudder-warehouse-json-uploads-tmp/_0/SNOWFLAKE_2GPPTuv601yRk511IYD3iXmJsOV/rudder-warehouse-staging-logs/2GP84ugylpnO6KxBCGsUQfbZVhG/2023-09-06/1693979056.2GP84ugylpnO6KxBCGsUQfbZVhG.f969f653-3700-4e19-9219-6e05f6eb8a99.APP_TRACK_WHEN_USER_CLICKS_ONE_OF_THE_SHARE_METHOD_TO_SHARE_THE_APP_SHOP_PRODUCT_TO_AN_EXTERNAL_SITE_PLATFORM_RS.2GP84ugylpnO6KxBCGsUQfbZVhG.13543b71-4e7e-49bc-9fe2-39acc2184e22.csv.gz: file name too long`
- https://linear.app/rudderstack/issue/PIPE-228/load-file-path-too-long
=> fix: remove table name for load file

jobsdb/jobsdb.go, processor/processor_isolation_test.go, processor/processor_test.go, processor/stash/stash.go, router/batchrouter/batchrouter_test.go, router/batchrouter/handle.go, router/handle.go, router/internal/jobiterator/jobiterator.go
Router iterator, batchrouter & stash can now perform a single SQL query for retrieving jobs instead of multiple.
The above behaviour is toggleable through a feature flag, `JobsDB.useSingleGetJobsQuery`. If the flag is disabled, rudder-server falls back to its previous behaviour.
- For unprocessed jobs we are using a left join with the status table
- For all other job states we are using an inner join with the latest status view
- When the query needs to query both types of states we are using a left join with the latest status view
- The no jobs cache is checked for all requested job states separately. e.g. if you ask for failed and unprocessed and an entry exists in the cache for failed, the final query will only contain predicates for unprocessed jobs.
- The no jobs cache is updated for …
=> chore: use single query for getting jobs

jobsdb/admin.go, jobsdb/jobsdb_test.go
Ignoring `sql. ErrNoRows` while deleting journal entries
[PIPE-238](https://linear.app/rudderstack/issue/PIPE-238/error-while-cleaning-up-old-jobs-sql-no-rows-in-result-set)
=> fix: error while cleaning up old jobs: sql: no rows in result set

enterprise/reporting/error_reporting.go
We used to send `reportedAt` in minutes to reporting service which is causing problems.
With this PR, we would be sending `reportedAt` in milliseconds to reporting service
https://linear.app/rudderstack/issue/INT-608/send-reportedat-in-milliseconds
=> fix: send reportedAt in milliseconds for error reporting

go.mod, go.sum, router/batchrouter/batchrouter_test.go, router/batchrouter/handle.go, router/batchrouter/handle_async.go, router/batchrouter/handle_lifecycle.go, router/batchrouter/worker.go, router/eventorder_test.go, router/handle.go, router/handle_lifecycle.go, router/partition_worker.go, router/router_test.go, router/transformer/transformer.go, router/transformer/transformer_test.go, router/types.go, router/utils/utils.go, router/worker.go, runner/runner.go
- Use new reloadable config api in router and batchrouter
- Drop support for `forceHonorUploadFrequency` since it was never used
- Minor improvements on router tests, when mock calls are missing
=> chore: use new reloadable config api in router and batchrouter

warehouse/grpc.go, warehouse/grpc_test.go
In this PR,
Add a check for list permission. This permission is required for doing a replay.
https://linear.app/rudderstack/issue/PIPE-94/verify-replay-will-work-when-custom-object-storage-is-defined
=> chore: check list permissions for replay

jobsdb/jobsdb.go
- Setting correct config for jobsdb.maxTableSizeInMB with defaultValue: 300 and valueScale: 1000000
- https://linear.app/rudderstack/issue/PIPE-298/ds-loop-max-table-size
=> fix: jobsdb ds max table size

processor/processor.go, processor/processor_test.go
`storeMessage#merge` will be called when processor has picked up a number of jobs (`maxLoopProcessEvents: 10K`) that is greater than the configured sub-job size (`subJobSize: 2K`). Processor will split the picked up batch in more than one sub-jobs, it will process all sub-jobs using pipelining and will finally merge them before storing the output to the database.
Whenever more than one source is connected to a destination, this absence of the appropriate `routerDestIDs` in the merged store message can cause processor to write batches of jobs for the same destination in parallel. This, in turn, can cause router to pickup jobs out-of-order due to `jobID` races.
If processor picks jobs less than the configured sub-job size, then the original `storeMessage` will be used, which will include …
=> fix: detected illegal job sequence during barrier enter/wait

router/customdestinationmanager/customdestinationmanager.go
There is no point in trying to create clients for custom destinations which are disabled. Even if there are jobs for such destinations in the database, router will drain them before reaching to the point of needing to use the client.
[PIPE-295](https://linear.app/rudderstack/issue/PIPE-295/dont-create-custom-destination-clients-for-disabled-destination)
=> chore: don't create custom destination clients for disabled destination

router/batchrouter/batchrouter_test.go, router/batchrouter/handle.go, router/batchrouter/handle_lifecycle.go
- `uploadFreq` dictates how often load files will be created under normal conditions
-  `mainLoopFreq` dictates the max frequency at which load files will be created when there is a large backlog in jobsdb (`limitsReached: true`)
[PIPE-299](https://linear.app/rudderstack/issue/PIPE-299/decouple-upload-frequency-from-main-loop-frequency-in-batchrouter)
=> chore(batchrouter): decouple upload frequency from main loop frequency

warehouse/integrations/clickhouse/clickhouse_test.go, warehouse/integrations/deltalake/deltalake.go, warehouse/utils/utils.go, warehouse/validations/validate.go, warehouse/validations/validations.go
- Error copy for Deltalke connection timeout.
- In case of validations for deltalake, if we were not able to connect to the SQL warehouse/cluster display a user-friendly message to the consumer that makes sure that their warehouse/cluster is up and running.
- Making timeout configurable.
- https://linear.app/rudderstack/issue/PIPE-240/databricks-connect-validator
=> fix: error message for deltalake during test connection

warehouse/integrations/snowflake/snowflake.go, warehouse/integrations/snowflake/snowflake_test.go
- Since duplicates need to be found before a merge query is completed, moving it before deduplication for Snowflake.
- https://linear.app/rudderstack/issue/PIPE-266/investigate-duplicates-for-mattermost
=> fix: sample duplicate messagesids for snowflake

CHANGELOG.md
Merge release 1.14.0 in main branch
chore: upgrade go mod replace versions (#3880)
=> chore: merge release 1.14.0 in main branch

processor/events_response.go, processor/processor.go, processor/processor_test.go, processor/transformer/transformer.go, services/debugger/transformation/transformationStatusUploader.go, services/rsources/stats_collector.go, services/rsources/stats_collector_test.go
- All events failed during the processor's pipeline (failed, filtered) are treated as dropped with respect to rudder-sources stats.
- For dropped events we are not capturing failed records
[Ensure drop events are marked as failed in source [job-status endpoint]](https://linear.app/rudderstack/issue/PIPE-177/ensure-drop-events-are-marked-as-failed-in-source-[job-status)
=> chore: add rsources stats for dropped events at processor

processor/transformer/transformer.go, router/transformer/transformer.go
Problem caused by exhausted sockets on the container, due to having too many connections in `TIME_WAIT` state. 
Related to golang/go#16012
- Using common http transport setting for both processor and router transformer clients
- Change `IdleConnTimeout: 30 * time.Second`
- Change default `MaxIdleConnsPerHost: 10`
[PIPE-330](https://linear.app/rudderstack/issue/PIPE-330/router-transformer-client-fails-with-error-connect-cannot-assign)
=> fix: router transformer client fails with error connect: cannot assign requested address

jobsdb/jobsdb.go, processor/stash/stash.go, router/batchrouter/handle.go, router/handle.go, router/internal/jobiterator/jobiterator.go
`JobsDB.useSingleGetJobsQuery` is no longer needed after successful rollout of the change.
[PIPE-303](https://linear.app/rudderstack/issue/PIPE-303/cleanup-jobsdbusesinglegetjobsquery-config-option)
=> chore: cleanup JobsDB.useSingleGetJobsQuery config option

archiver/archiver_test.go
fixing a test in archiver, where there could be more files uploaded per source than 1.
[slack thread](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1695306099725079)
=> chore: fix archiver test - inconsistent number of files

enterprise/reporting/error_reporting.go, enterprise/reporting/reporting.go
Only Event schemas v1 is now left using the old config api, which shall be removed altogether in the next release
=> chore: use the new reloadable config api in reporting

Makefile, warehouse/integrations/clickhouse/clickhouse.go, warehouse/integrations/clickhouse/clickhouse_test.go, warehouse/internal/mocks/utils/mock_uploader.go, warehouse/jobs/jobs.go, warehouse/router_identities.go, warehouse/schema/schema.go, warehouse/schema/schema_test.go, warehouse/slave_worker.go, warehouse/slave_worker_test.go, warehouse/upload.go, warehouse/upload_test.go, warehouse/utils/utils.go, warehouse/validations/validate.go
Sub issue for the Warehouse integration tests with `-race`.
The plan is to incrementally reintroduce the changes in smaller PRs to better test the changes in isolation. This is the last PR that is going to reintroduce the changes we reverted [here](https://github.com/rudderlabs/rudder-server/pull/3825).
In this Pull Request we are moving the `Schema` into its own package and we're making it safe for concurrent use.
The Warehouse Integration tests are going to be covered by `-race` but **not the unit ones**. For those we are going to tackle the issues we found in other PRs.
In order to enable the `-race` in the unit test we have to change the `test-run` recipe in the `Makefile` as such:
```
test-run: ## Run all unit tests
ifeq ($(filter 1,$(debug) $(RUNNER_DEBUG)),)
$(eval TEST_CMD = …
```
=> chore: warehouse schema race and cleanup

backend-config/replay_types.go, backend-config/replay_types_test.go, backend-config/types.go, gateway/gateway_test.go, gateway/handle.go
- Treating `replay` request types equally to `batch` request types in terms of expected payload
- Fixing a loopvar issue
- Setting `IsProcessorEnabled` always true for replay destinations
[PIPE-351](https://linear.app/rudderstack/issue/PIPE-351/replay-request-fails-with-400-request-neither-has-anonymousid-nor)
=> fix: replay request fails with 400 - request neither has anonymousId nor userId

proto/event-schema/types.helper.go, schema-forwarder/internal/forwarder/jobsforwarder.go
Sampling events at EventSchemaVersion level to populate more samples in the `schema_version` table
[ Linear Link ](https://linear.app/rudderstack/issue/PIPE-343/fix-empty-sample-event-bug-in-schema-version-table)
=> fix: event schema versions without a sample event

services/streammanager/kafka/client/client_test.go
First attempt to address flakyness of the `TestSSH` test as seen [here](https://github.com/rudderlabs/rudder-server/actions/runs/6315301663/job/17147543264).
I'm proposing to use the same approach we're using in another test [here](https://github.com/rudderlabs/rudder-server/blob/v1.14.2/services/streammanager/kafka/client/client_test.go#L97).
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-365/testssh-flakyness) >
=> fix: test ssh

services/streammanager/kafka/kafkamanager.go, services/streammanager/kafka/kafkamanager_test.go
Small change to allow customers to figure out why no messages are getting through without asking for our help.
This happened to Cars, the wrong Avro schema was being used and they were not able to figure out why.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-369/cars-unable-to-process-any-of-the-event-in-the-batch) >
=> chore: sampling errors if no message in the batch succeeds

jobsdb/jobsdb.go
For `JobsDB.backup.pathPrefix` we were using the default value as a configuration key and vice versa.
[linear](https://linear.app/rudderstack/issue/PIPE-371/fix-jobsdb-pathprefix-config)
=> fix: invalid JobsDB.backup.pathPrefix configuration

services/rsources/handler.go, services/rsources/handler_test.go
use unique(`rand.String`) credentials(db name, username, password) for each postgres resources spawned.
[slack thread](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1695804872219039)
=> chore: rsources tests - postgres resources use different creds

warehouse/integrations/deltalake/deltalake.go
- Use dedup on new records for deltalake
- https://linear.app/rudderstack/issue/PIPE-373/investigate-duplicates-for-acorns-prod
=> fix: use dedup on new records for deltalake

app/apphandlers/embeddedAppHandler.go, app/apphandlers/processorAppHandler.go, app/features.go, enterprise/reporting/error_reporting.go, enterprise/reporting/mediator.go, enterprise/reporting/noop.go, enterprise/reporting/reporting.go, enterprise/reporting/reporting_test.go, enterprise/reporting/setup.go, enterprise/reporting/setup_test.go, mocks/utils/types/mock_types.go, processor/processor.go, processor/processor_test.go, router/batchrouter/handle_lifecycle.go, router/factory.go, router/handle_lifecycle.go, services/rsources/handler.go, utils/types/reporting_types.go, utils/types/types.go, warehouse/router.go, warehouse/router_test.go, warehouse/upload.go, warehouse/warehouse.go, warehouse/warehouse_test.go
Preparatory work for being able to collect additional error metadata fields for the purpose of replaying errors.
- Introduce a new struct for including error message details in reported data (`types.FailedMessage`). This is required for capturing error index metadata through reporting interfaces.
- Honouring context in goroutines started by the reporting feature. 
- Support new reporting implementations easily by using a variable-sized list of delegates inside reporting mediator.
- Remove `WaitForSetup`, since reporting tables are now being migrated synchronously when the program starts.
- Introduced `types.ReportingSyncer` to decouple database initialisation from syncer's main loop.
- Simplify warehouse's reporting setup conditions: 
- Only standalone slaves don't setup reporting
- …
=> refactor: reporting feature

jobsdb/jobsdb.go
Hot fix for backup prefix
[linear](https://linear.app/rudderstack/issue/PIPE-371/fix-jobsdb-pathprefix-config)
=> chore: fix backup prefix

utils/types/reporting_types.go
Reporting http api doesn't expect a `failedMessages` field in the payload.
=> chore: omit failedMessages from reporting json object

router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/marketobulkupload.go
We are facing difficulties in uploading file with large volume data, for example 100K and that is why we are increasing the timeout for upload as 10 Minute
=> fix: increasing default marketo bulk upload timeout

regulation-worker/internal/delete/api/api.go
- This pr enables user deletion for iterable destination
- user deletion changes for transformer is already released, adding destination name to  `supportedDestinations` list is pending, which is what this pr addresses
https://linear.app/rudderstack/issue/INT-607/iterable-destination-user-delete-support
=> chore: enable user deletion for supported destinations

gateway/gateway_test.go, gateway/handle.go, gateway/response/response.go
Current behaviour:
If a request contains an empty array as value of the batch property in JSON we respond with Invalid JSON
Desired behaviour
If a request contains an empty array as value of the batch property in JSON we should respond with Empty Batch Payload
I could not find other places where `InvalidJSON` is being misused.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-250/improve-response-message-when-json-payload-is-empty-gateway) >
=> chore: empty batch payload

.github/workflows/prerelease.yaml
`secrets.GH_PAT` is using rudder-server-bot Personal Access Token. We want to remove the `rudder-server-bot` account and instead use `secrets.PAT`, already used in other Github actions
https://linear.app/rudderstack/issue/PIPE-388/remove-rudder-server-bot-account-from-github
=> chore: use common PAT instead of rudder-server-bot

warehouse/schema/schema.go, warehouse/schema/schema_test.go
- When syncing from remote, we need to set the local schema as well.
- https://linear.app/rudderstack/issue/PIPE-392/sync-remote-schema-fix
=> fix: set local schema when syncing from remote

.golangci.yml, warehouse/client/controlplane/client_test.go, warehouse/identity/identity.go, warehouse/integrations/azure-synapse/azure-synapse.go, warehouse/integrations/mssql/mssql.go, warehouse/integrations/redshift/redshift.go, warehouse/integrations/snowflake/snowflake_test.go
- Enable `errcheck` and `unparam` linters for warehouse package. (PIPE-410)
=> chore: enable errcheck and unparam linters for warehouse

jobsdb/jobsdb.go, processor/processor.go, services/debugger/transformation/transformationStatusUploader.go
1. Fixes the issue of sending filtered events in UT to the live events as failed. With this fix, filtered events in ut are sent as dropped.
2. Stores failed events during event filtering in proc errors.
=> chore: send filtered events in ut as dropped

enterprise/reporting/error_reporting.go, enterprise/reporting/reporting.go, integration_test/reporting_dropped_events/reporting_dropped_events_test.go, processor/processor.go, processor/processor_test.go, router/batchrouter/handle.go, router/batchrouter/handle_async.go, router/batchrouter/handle_observability.go, router/batchrouter/types.go, router/batchrouter/types_test.go, router/batchrouter/worker.go, router/handle.go, router/rterror/error.go, router/types.go, router/types_test.go, router/worker.go, runner/runner.go, schema-forwarder/internal/forwarder/abortingforwarder.go, testhelper/backendconfigtest/config_builder.go, testhelper/backendconfigtest/destination_builder.go, testhelper/backendconfigtest/server_builder.go, testhelper/backendconfigtest/source_builder.go, testhelper/backendconfigtest/value_builder.go, testhelper/transformertest/builder.go, testhelper/transformertest/handler_funcs.go
1. Filling FailedMessages in reporting stats for aborted job scenarios (processor/router/batchrouter).
2. Fixing a reporting bug where we were counting less when a batch user transformation failed.
3. Fixing a reporting bug where we were not reporting drained jobs in batch router.
4. Introducing `backendconfigtest` package which provides a fluent builder for workspace config, useful for preparing test scenario fixtures.
5. Introducing `transformertest` package which provides a fluent builder for transformer service to easily simulate different transformer behaviours in tests.
6. Added `reporting_dropped_events_test` integration test to verify reporting behaviour in scenarios where events are being aborted/filtered in the pipeline.
7. The same testing framework shall be used to verify …
=> feat: report failed messages in processor, router and batchrouter

warehouse/integrations/deltalake/deltalake.go
- Since error handling is not so good with the Databricks driver we need to verify the exact string in the error.
- Therefore, creating the schema every time before we fetch it. Also, creating the schema is idempotent.
- https://linear.app/rudderstack/issue/PIPE-413/databricks-fetch-schema-error-handling
=> fix: create schema before even fetching for deltalake

router/handle.go, router/types/types.go
fixes PIPE-420 : Add workspaceID to router discarded stats 
[ Linear Link ](https://linear.app/rudderstack/issue/PIPE-420/add-workspaceid-to-router-discarded-stats)
=> chore: add workspaceID to router discarded stats

CHANGELOG.md, jobsdb/jobsdb.go, processor/processor.go, services/debugger/transformation/transformationStatusUploader.go, warehouse/integrations/deltalake/deltalake.go
Merge release 1.15.1 in main branch
**_WARNING:_** this needs to be merged using a **Merge Commit**!
chore: collect only drained failed keys at router (#3930)
chore: replace varcheck and deadcode with  unused linter (#3968)
chore: enable errcheck and unparam linters for warehouse (#3970)
feat: report failed messages in processor, router and batchrouter (#3914)
feat: error index reporting implementation (#3948)
chore: track long-running transformations in processor (#3976)
chore: add workspaceID to router discarded stats (#3977)
=> chore: merge release 1.15.1 in main branch

warehouse/integrations/azure-synapse/azure_synapse_test.go, warehouse/integrations/bigquery/bigquery.go, warehouse/integrations/bigquery/bigquery_test.go, warehouse/integrations/clickhouse/clickhouse_test.go, warehouse/integrations/deltalake/deltalake_test.go, warehouse/integrations/mssql/mssql_test.go, warehouse/integrations/postgres/postgres_test.go, warehouse/integrations/redshift/redshift.go, warehouse/integrations/redshift/redshift_test.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/internal/mocks/utils/mock_uploader.go, warehouse/internal/service/loadfiles/downloader/downloader.go, warehouse/internal/service/loadfiles/downloader/downloader_test.go, warehouse/jobs/jobs.go, warehouse/router/upload.go, warehouse/utils/utils.go, warehouse/validations/validate.go
Fixes PIPE-421 : Removes panics from warehouse jobs module 
[ Linear Link ](https://linear.app/rudderstack/issue/PIPE-421/warehouse-hosted-panic-fix)
=> chore: fix remove warehouse jobs panic

enterprise/reporting/error_index_reporting_test.go
- Since we can't have 2 jobsDB for reading, using existing `eir.errIndexDB`
=> chore: flaky error index report test

enterprise/reporting/reporting.go
Logging error caused by getting reports.
Resolving OBS-159
https://linear.app/rudderstack/issue/OBS-159/log-errors-in-rudder-server-for-reporting-metrics
=> fix: add error log for reporting metrics

processor/transformer/transformer.go, router/transformer/transformer.go
Adding the gzip support header in transformer.go for backward compatibility between server <> transformer
https://github.com/rudderlabs/rudder-server/pull/3904
=> chore: advertise gzip support to transformer through X-Feature-Gzip-Support header

router/batchrouter/asyncdestinationmanager/common/common.go, router/batchrouter/asyncdestinationmanager/eloqua/bulk_uploader.go, router/batchrouter/asyncdestinationmanager/eloqua/manager.go, router/batchrouter/asyncdestinationmanager/eloqua/types.go, router/batchrouter/asyncdestinationmanager/eloqua/utils.go
We were sending null values as "null". For null values, Eloqua doesn't show any warning but as we were sending "null" they were showing an invalid value warning. With this PR we are fixing that. We are also considering warning with statusCode ELQ-00040 as a success when none of the unique fields are invalid.
>Resolves INT-856
=> fix: update error parsing of eloqua

processor/processor.go
Using a unique job id instead of a zero (0) value for every dropped job so that stats are captured correctly.
By using the same (0) job id, `in_count` was being incremented for all different stat key combinations (job_run_id, task_run_id, source_id & destination_id), but `failed_count` was being erroneously incremented always for the first stat key, due to a corrupted [jobIdsToStatKeyIndex](https://github.com/rudderlabs/rudder-server/blob/49b376fc8b8f4eb1cb20c4fd949f4bfa869845d6/services/rsources/stats_collector.go#L151-L152).
Resolves PIPE-433
=> fix: corrupted rsources stats captured by processor for dropped jobs

processor/stash/stash.go
- Config for stash payload limit is misconfigured.
=> fix: config for stash payload limit

services/streammanager/googlecloudfunction/googlecloudfunction.go, utils/httputil/client.go
Using `httputil.CloseResponse` for safely closing the response's body
Fixes PIPE-439
Fixes PIPE-438
=> fix: invalid memory address or nil pointer dereference in googlecloudfunction

warehouse/api/http.go
- Using chi.middleWare to introduce HTTP API response times for the warehouse. This will help us provide better observability around the HTTP requests.
- https://linear.app/rudderstack/issue/PIPE-444/chi-middleware-for-warehouse
=> feat: introducing chi middleware for warehouse

warehouse/validations/validate_test.go, warehouse/validations/validations_test.go
- Too many times, validation tests fail because we are consuming many docker containers, and the docker pool times out and gives EOF error.
```
https://github.com/rudderlabs/rudder-server/actions/runs/6650806396/job/18071584306?pr=4012
=== Failed
=== FAIL: warehouse/validations TestValidate (63.19s)
validate_test.go:48: minio: localhost:32899
validate_test.go:38: 
Error Trace:	/home/runner/work/rudder-server/rudder-server/warehouse/validations/validate_test.go:38
/home/runner/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75
/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/asm_amd64.s:1650
Error:      	Received unexpected error:
reached retry deadline: unexpected EOF
Test:       	TestValidate
--- PASS: TestValidate/invalid_path (0.00s)
--- PASS: TestValidate/steps (0.00s)
--- …
```
=> fix: flaky validations tests

services/rsources/failed_records_pagination_test.go, services/rsources/handler.go, services/rsources/handler_test.go, services/rsources/http/http.go, services/rsources/http/http_integration_test.go, services/rsources/http/http_test.go, services/rsources/mock_rsources.go, services/rsources/rsources.go
Adding support for pagination in failed-keys endpoint in a backwards compatible manner:
- If the request contains a `pageSize` query parameter then pagination will be enabled, otherwise the full resultset will be returned in the response.
- If pagination is requested, then the next page's token will be included in the `paging` field of the response's payload. To retrieve the next page, the client needs to include this token in the `pageToken `query parameter of it's next http request.
- Pagination stops when no more results are returned in the response. When this happens, the `paging` field is omitted from the response's payload as well.
Added a test and a benchmark to verify the performance characteristics of the new paging API compared to the previous one. The paging API is more memory …
=> feat: introduce pagination in failed-keys endpoint

go.mod, go.sum
- Bump rudder-go-kit version to 1.16.2
=> chore: bump rudder-go-kit to 1.16.2

warehouse/validations/validate_test.go, warehouse/validations/validations_test.go
- Even now, a few times tests are failing with i/o timeout, since we are running all of the tests in parallel. Removing parallel for now so that it can be more stable.
```
https://github.com/rudderlabs/rudder-server/actions/runs/6666283593/job/18117517599?pr=4026
=== FAIL: warehouse/validations TestValidator/Fetch_schema (25.01s)
validate_test.go:368: 
Error Trace:	/home/runner/work/rudder-server/rudder-server/warehouse/validations/validate_test.go:368
Error:      	Received unexpected error:
fetch schema: fetching schema: read tcp [::1]:33190->[::1]:32872: i/o timeout
Test:       	TestValidator/Fetch_schema
--- FAIL: TestValidator/Fetch_schema (25.01s)
```
- Although, if we feel that test times become a burden, we can explore other options in the future. Alteast we will stable tetsts.
``` …
```
=> chore: flaky validations test

.github/workflows/verify.yml, Makefile, scripts/install-golangci-lint.sh
Upgrading golangci lint to the latest version and using a local golangci-lint binary instead of the docker image for lightning-fast lints!
=> chore: upgrade golangci-lint

archiver/archiver_isolation_test.go, archiver/archiver_test.go
Increase shm size for archiver tests
Fixes PIPE-461
=> chore: increase archiver postgres shm size

warehouse/admin/admin.go, warehouse/app.go, warehouse/router/router.go, warehouse/router/router_test.go, warehouse/router/scheduling.go, warehouse/router/scheduling_test.go, warehouse/router/tracker.go
- Avoid using globals (`scheduledTimesCache`, `StartUploadAlways`)
- Resolves PIPE-458
=> refactor: minor scheduler cleanup

warehouse/api/grpc_test.go, warehouse/api/http_test.go, warehouse/app_test.go, warehouse/archive/archiver_test.go, warehouse/bcm/backend_config_test.go, warehouse/encoding/encoding_test.go, warehouse/integrations/azure-synapse/azure_synapse_test.go, warehouse/integrations/bigquery/bigquery_test.go, warehouse/integrations/clickhouse/clickhouse_test.go, warehouse/integrations/deltalake/deltalake_test.go, warehouse/integrations/mssql/mssql_test.go, warehouse/integrations/postgres/postgres_test.go, warehouse/integrations/redshift/redshift_test.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/internal/api/http_test.go, warehouse/jobs/http_test.go, warehouse/multitenant/manager_test.go, warehouse/router/errors_test.go, warehouse/router/router_test.go, warehouse/router/tracker_test.go, warehouse/router/upload_stats_test.go, warehouse/router/upload_test.go, warehouse/slave/slave_test.go, warehouse/slave/worker_job_test.go, warehouse/slave/worker_test.go
- Avoid using global configuration in tests like (`config.Default`, `stats.Default`) to have better isolation.
- More about it in [here](https://github.com/rudderlabs/rudder-server/pull/4030#discussion_r1376313312).
- Resolves PIPE-464
=> chore: avoid using global conf during tests

enterprise/reporting/error_index/types.go, enterprise/reporting/error_index/worker_test.go
- Don't use the logical timestamps to store the `time.TIme` fields. Store it as INT64 itself.
- Resolves PIPE-467
=> fix: error index filtering for timestamp fields use int64

warehouse/router/router.go
- Don't send errors in the stats as it can increase the cardinality.
- Resolves PIPE-465
=> fix: don't send error in stats

warehouse/integrations/testdata/docker-compose.minio.yml
- curl no longer available in container image, can no longer healthcheck. See more in [here](https://github.com/minio/minio/issues/18371).
- Resolves PIPE-476
=> fix: minio heathcheck

archiver/archiver_test.go, processor/processor.go, processor/processor_test.go, processor/trackingplan.go, processor/transformer/transformer.go, processor/transformer/transformer_test.go, router/types/types_test.go
Cleaned up some processor code.
Specifically the usage of 2 flags(`trackingPlanEnabled` and `userTransformationEnabled`) to decide the `PU` and `inPU` at various stages during the computation of metrics.
Also using stage literals from one package(`utils/types`) instead of two earlier(`processor/transformer` and `utils/types`).
=> chore: minor processor cleanup

gateway/gateway_test.go, gateway/handle.go, gateway/throttler/throttler.go, gateway/throttler/throttler_test.go, mocks/gateway/throttler.go
Tweaking the existing GW Rate Limiter to throttle based on the incoming events rather than requests
Fixes PIPE-475
=> chore: set gw rate limits at event level

Dockerfile
Less commands, faster build, and smaller image!
=> refactor: apk usage in Dockerfile

integration_test/reporting_dropped_events/reporting_dropped_events_test.go, integration_test/reporting_error_index/reporting_error_index_test.go, processor/manager.go, processor/processor.go, processor/processor_test.go, router/batchrouter/batchrouterBenchmark_test.go, router/batchrouter/batchrouter_test.go, router/batchrouter/factory.go, router/batchrouter/handle.go, router/batchrouter/handle_async.go, router/batchrouter/handle_lifecycle.go, router/batchrouter/types.go, router/batchrouter/types_test.go, router/batchrouter/worker.go, router/handle.go, router/handle_lifecycle.go, router/router_test.go, router/types.go, router/types_test.go, router/utils/utils.go, router/worker.go, utils/types/types.go
The topic of draining events from a sync gave birth to this.
This is a way to pass generic rules by which (batch)router and processor(only `jobRunID` now) can drain events. How this is set to config is another story.
Routers, BatchRouters now have a `drainer` which provides the method:
`Drain(job *jobsdb.JobT) (bool, string)` to check if their jobs can be drained. Support for draining via configurable destinationIDs(`"Router.toAbortDestinationIDs"`) and jobRunID(`"RSources.toAbortJobRunIDs"`) present now. Adding more drain configurations should be straightforward -> just need to add logic in `type drainer` and `(d *drainer) Drain(...)`.
Processor has a simpler approach, a new config field is added to accommodate configurations to drain by, `jobRunId` for now. Also injecting …
=> chore: support generic rules to have routers drain events

enterprise/reporting/error_index/worker.go
- Use sorting key for storing data in parquet. 
- Resolves PIPE-493
=> fix: sorting key for error indexing during parquet

warehouse/api/grpc.go, warehouse/client/client.go, warehouse/client/warehouse_test.go, warehouse/integrations/azure-synapse/azure_synapse_test.go, warehouse/integrations/datalake/schema-repository/glue.go, warehouse/integrations/mssql/mssql_test.go, warehouse/internal/loadfiles/mock_loadfile_repo_test.go, warehouse/internal/loadfiles/mock_stagefile_repo_test.go, warehouse/internal/repo/upload.go, warehouse/router/upload.go, warehouse/utils/utils.go
- Receiver names are different
- Unused constant
- Unused parameter
- Unused exported function
- Redundant type conversion
- Unhandled error
- Type assertion on errors fails on wrapped errors
- Resolves PIPE-494
=> chore: minor formatting changes

schema-forwarder/internal/forwarder/jobsforwarder.go
Using an empty payload for ErrorResponse when recording a successful jobs status for `esch` jobs.
=> fix: invalid input syntax for type json for table esch_job_status

warehouse/integrations/bigquery/bigquery.go, warehouse/integrations/bigquery/bigquery_test.go, warehouse/integrations/bigquery/testdata/template.json, warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/deltalake/deltalake_test.go, warehouse/integrations/deltalake/testdata/template.json, warehouse/integrations/postgres/load.go, warehouse/integrations/postgres/postgres_test.go, warehouse/integrations/redshift/redshift.go, warehouse/integrations/redshift/redshift_test.go, warehouse/integrations/snowflake/snowflake.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/integrations/snowflake/testdata/template.json, warehouse/integrations/testdata/docker-compose.minio.yml, warehouse/internal/model/warehouse.go
Follow up to [this PR](https://github.com/rudderlabs/rudder-server/pull/3965) where we changed the default behaviour for Warehouse destinations so that users would have to opt-in if they want to merge (aka remove duplicates).
Given that the UI changes for enabling the merge are not live we're setting `enableMerge` by default to `true` if it's not set. This maintains backwards compatibility and allows us to decouple the data plane deployment from the control plane one.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-497/default-enablemerge-to-true-if-neither-true-of-false-are-present) >
=> fix: preferAppend defaults to false if not defined

router/eventorder_test.go, router/handle.go, router/handle_lifecycle.go, router/internal/eventorder/eventorder.go, router/internal/eventorder/eventorder_simulation_test.go, router/internal/eventorder/eventorder_test.go, router/partition_worker.go, router/router_test.go, router/worker.go
Replacing concurrency limiter introduced in #3243 with a different strategy which can be summarised as below:
- Whenever the concurrency limit is reached, event ordering (i.e. the barrier) will be disabled for this specific ordering key and router will start distributing events for that key evenly across its workers.
- A disabled barrier will transition to the half-enabled state after a configurable period (default: 20m).
- While in the half-enabled state, event ordering will be re-enabled, however the barrier will not panic if an illegal job sequence is detected. Why? Because multiple workers will be processing events for some time in parallel, so out-of-order delivery will be possible. 
- The barrier will finally transition to the enabled state after a configurable period (default: 10m) …
=> feat(router): disable event order for users with event volume above threshold

gateway/gateway.go, gateway/gateway_test.go, gateway/handle.go, gateway/handle_http_replay.go, gateway/handle_http_retl.go, gateway/handle_lifecycle.go
New event type "record". (To be used to sync rETL records.)
https://linear.app/rudderstack/issue/INT-650/handling-new-event-type-processing-in-pipeline
=> feat: new event type - record

warehouse/integrations/datalake/testdata/docker-compose.spark.yml, warehouse/integrations/datalake/testdata/docker-compose.trino.yml, warehouse/integrations/datalake/testdata/etc/catalog/minio.properties, warehouse/integrations/datalake/testdata/etc/jvm.config, warehouse/integrations/postgres/testdata/docker-compose.postgres.yml, warehouse/integrations/postgres/testdata/docker-compose.ssh-server.yml, warehouse/integrations/testdata/docker-compose.jobsdb.yml, warehouse/integrations/tunnelling/testdata/docker-compose.yml
- Upgrade docker dependencies to the latest version for tests. This will help us detect breaking changes early. We need not worry about rate limits since we are pulling images from our internally deployed Rudder Hub Proxy. More about it is [here](https://rudderlabs.slack.com/archives/C02B31USATA/p1696859664448059).
- Feedback in [here](https://github.com/rudderlabs/rudder-server/pull/4058#discussion_r1384659395).
- **The only concern here is the backward compatibility since we will be using older version [server(PostgreSQL 11.21, PostgreSQL 12.9) and warehouse (PostgreSQL 12.9, PostgreSQL 11.6)] in Production, as compared to [Postgres latest (PostgreSQL 16)] in tests. We were already using 15 now, so I guess we should be OK**
- Resolves PIPE-506
=> chore: use latest dependencies for tests

enterprise/reporting/error_index/worker_test.go
Since `encodeToParquet`, sorts the payloads before writing to the parquet file, we need to make sure that the we use a copy of the original slice for encoding.
=> fix: error index sortKey filter based test

warehouse/integrations/datalake/testdata/docker-compose.trino.yml
- Configuring health check for Trino (Datalake tests). It got failed couple of times, container was not healthy. 
```
https://github.com/rudderlabs/rudder-server/actions/runs/6802468397/job/18511513258
https://github.com/rudderlabs/rudder-server/actions/runs/6808051074/job/18511879650
container test_cpzetxvyawuwqvhyqfgm-trino-1 is unhealthy
err: exit status 1
--- FAIL: TestIntegration (107.12s)
```
=> chore: increasing retries for health check for trino

gateway/handle_lifecycle.go, services/rsources/handler.go, services/rsources/handlerv2_test.go, services/rsources/http/http.go, services/rsources/http/http_integration_test.go, services/rsources/http/http_test.go, services/rsources/http/httpv2_test.go, services/rsources/mock_rsources.go, services/rsources/rsources.go
v2 endpoints for sources use. Basic premise is to separate the delete endpoint which used to delete all the available info for passed query filters.
Now there's two different endpoints to delete job stats and failed keys separately.
`/v2/failed-keys` - lets the user fetch or delete failed keys
`/v2/job-status` - lets the user fetch or delete job status(stats)
The existing endpoint has been left for now to be deprecated soon.
`/v1/job-status` - lets the user fetch job stats, failed keys, and delete all relevant information for a particular `jobRunId`.
[delete endpoints](https://linear.app/rudderstack/issue/PIPE-401/deletefailedkeys-deletestats)
=> feat: new sources endpoints

app/apphandlers/embeddedAppHandler.go, app/apphandlers/gatewayAppHandler.go, app/apphandlers/processorAppHandler.go, app/cluster/integration_test.go, gateway/gateway_test.go, gateway/handle_http_auth.go, gateway/handle_lifecycle.go, gateway/internal/types/types.go, gateway/response/response.go, gateway/webhook/setup.go, gateway/webhook/webhook.go, gateway/webhook/webhookTransformer.go, gateway/webhook/webhookTransformer_test.go, gateway/webhook/webhook_test.go, processor/manager.go, processor/manager_test.go, processor/processor.go, processor/processor_test.go, services/transformer/features.go, services/transformer/features_impl.go, services/transformer/features_impl_test.go, services/transformer/features_suite_test.go
Resolves INT-543 and INT-768
**What do we want to achieve?**
We want to send fetch the `sourceConfig` and send it to transformer for sources as well as we do for destinations.
**How we are planning to do that ?**
We are introducing new endpoint `{transformUrl}/v1/sourceType` which would accept the data in the format 
`{event: ingested event, source: sourceObject}`.
**How We are Maintaining Backward Compatibility ?**
If some how transformer is old and **does not** support v1 endpoint then it could break. To control this we are 
globalising the `/feature` endpoint from we already use in `processor.go` to check for router destinations.
In feature json response we are checking for a boolean value to check if transformer support `v1` endpoint.
Also for this `/feature` endpoint we made a new …
=> feat: new transformer service to fetch and serve transformer features

gateway/gateway_integration_test.go, gateway/webhook/webhookTransformer.go, gateway/webhook/webhookTransformer_test.go, testhelper/backendconfigtest/source_builder.go
Source type should be set to lowercase while constructing the webhook url. Introduced by #4007 
Adding an integration test to guard against a future regression.
Fixes PIPE-522
=> fix: webhook source transformation failed with error: cannot find module

testhelper/etcd/etcd.go
Adding a timeout so that the client creation doesn't block forever in case of a problem
=> chore: add a dial timeout of 10 seconds in etcd client during tests

integration_test/warehouse/integration_test.go
- Entries for staging files and load files are archived during the test. Verifying their count may introduce a race condition due to the archiving process.
- We can skip verification for staging files and load files as we are already validating the successful upload count.
- Resolves PIPE-535
=> fix: warehouse archiver integration tests

.github/dependabot.yml
Configure dependabot to check for updates github-actions and dockerfiles
https://linear.app/rudderstack/issue/PIPE-539/extend-dependabot-responsibilites
=> chore: include github-actions and docker updates (PIPE-539)

integration_test/kafka_batching/kafka_batching_test.go
Fixing test flakyness.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-527/kafka-batching-integration-test) >
=> chore: kafka batch integration test

go.mod, go.sum
Revert data bricks sql client to 1.4.0
Reverts [this](https://github.com/rudderlabs/rudder-server/pull/4084) PR
Fixes PIPE-547
=> chore: revert data bricks sql client to 1.4.0

router/batchrouter/handle_observability.go, router/handle_observability.go
Including all router/batchrouter aborted jobs in failed records instead of just drained ones
Partially resolves PIPE-485 see also #4116
=> chore: include all aborted jobs in failed records

gateway/handle.go
Sanitizing user id fields while reading them from the message before storing user_id in database 
fixes PIPE-549
=> fix: gateway responds with http status 500 and body pq: invalid byte sequence for encoding UTF8: 0x00

processor/processor.go, processor/trackingplan.go
separates filtered and error stats in processor.
[slack thread](https://rudderlabs.slack.com/archives/C03CX31FNAG/p1699905141075659)
=> chore: filtered and error stats separated in processor

router/worker.go
Avoiding storing huge error responses in job status tables causing infinite full vaccums
resolves PIPE-562
=> chore: trim down error responses stored in job status to a maximum of 10KB

processor/processor.go, processor/worker.go, processor/worker_handle.go, processor/worker_test.go
Adding the partition tag in processor stats for better observability during incidents
resolves PIPE-567
=> chore(processor): include partition tag in stats

utils/misc/misc.go
Ensuring Fatal log during panic capture contains equivalent information to panic. This will allow us to start using alerts based on logs instead of bugsnag for getting notified.
resolves PIPE-549 https://linear.app/rudderstack/issue/PIPE-594/improve-log-during-panic-capture
=> chore: improve fatal log during panic capture

.github/workflows/prerelease.yaml, .github/workflows/release-please.yaml
Reverts rudderlabs/rudder-server#4184
I tried to adapt to the breaking changes, but I wasn't successful https://github.com/rudderlabs/rudder-server/pull/4204/files
The usage of manifest files breaks our prerelease strategy completely.  requesting revert until we find a better solution.
=> chore(deps): revert google-github-actions/release-please-action from 4 to 3

CHANGELOG.md
[ syncing with the main branch 
](https://www.notion.so/rudderstacks/Release-process-094ecf877f3d47e9ad94ab28622da225?pvs=4#1a026c7afbde425fa849f2ed0d804387)
feat: warehouse append vs merge (#4139)
feat: support for adaptive rate limiting [PIPE-481] (#4160)
chore(deps): bump github.com/snowflakedb/gosnowflake from 1.6.25 to 1.7.0 (#4190)
chore: remove events schemas v1 (#3923)
=> chore: merge release 1.18.0 in main branch

app/apphandlers/setup.go, internal/drain-config/drainConfig.go, services/rsources/rsources.go
Trying to minimise each rudder-server's footprint on the overall number of shared postgres's connections
=> chore: tune shared db connection pooling

processor/processor.go, services/rsources/stats_collector.go
1. Calling `rsourcesStats.CollectStats` only once so that no duplicates can be captured.
2. Avoiding to reset state in `rsourcesStats.Publish` so that the method can be repeated for another transaction (we are not reusing stat collectors anyway).
3. Performing `rsourcesStats.Publish` as the last step of the transaction.
4. Honouring context while storing dropped jobs' stats.
fixes PIPE-616
=> fix(processor): duplicate rsources out stats can be recorded in case of a retry due to an operation timeout

enterprise/reporting/error_index/error_index_reporting.go, enterprise/reporting/error_index/error_index_reporting_test.go, enterprise/reporting/error_reporting.go, enterprise/reporting/event_stats.go, enterprise/reporting/mediator.go, enterprise/reporting/noop.go, enterprise/reporting/reporting.go, mocks/utils/types/mock_types.go, processor/processor.go, router/batchrouter/handle.go, router/batchrouter/handle_async.go, router/batchrouter/worker.go, router/factory.go, router/handle.go, utils/types/types.go, warehouse/router/upload.go
Processor, router & batchrouter cannot gracefully shutdown while their loops are working, since any error during the loop will lead to a panic. Thus all reporters' `Report` method need to honour a different context, that of the caller, and not the app's lifecycle context.
- Not using the error index reporter's context in the error index reporter's `Report` method
- Adding context in Report method, which can be different than the lifecycle context
- Honouring this new context in all reporters
=> fix: server panics during shutdown with reporting metrics: failed to store jobs: context canceled

services/rsources/http/http.go, services/rsources/rsources.go, services/rsources/rsources_test.go
Whenever corrupted job-status stats are encountered (in < out), gateway fixes them before responding and logs a warning.
resolves PIPE-617
=> chore: autofix corrupted job-status stats

gateway/handle_http_auth.go, gateway/handle_http_auth_test.go
Seeing empty `workspaceID` in gateway stats when source is disabled. This fixes that. Added a couple tests to verify that.
[slack thread](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1701714466251759)
=> fix: gateway stat tags when source is disabled

warehouse/integrations/redshift/redshift.go
- Added connection timeout for middleware for Redshift.
- Stuck stacktrace.
```
goroutine 299619831 [IO wait, 3151 minutes]:
internal/poll.runtime_pollWait(0x7fce0052e5a0, 0x72)
/usr/local/go/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc03779b200?, 0xc03b95a000?, 0x0)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc03779b200, {0xc03b95a000, 0x2000, 0x2000})
/usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc03779b200, {0xc03b95a000?, 0x6c8dd488321103b6?, 0x653e59eb27991262?})
/usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc087082ce0, {0xc03b95a000?, 0x523fe6d9683bf05f?, 0xc0e11a3fe70c5767?}) …
```
=> fix: adapt connection timeout for sql for redshift

router/throttler/adaptive.go
chore: change the max limit to take `multiplier` of the existing limits rather than the same in case the `maxLimit` env is missing. Default: 150% of the current limit
https://linear.app/rudderstack/issue/PIPE-645/change-maxlimit-to-use-130percent-of-existing-limits
=> chore: change the max limit to take multiplier of the existing limits

warehouse/integrations/bigquery/bigquery.go
- While getting job statistics for BigQuery, it's getting rate limited for gelato (PRO). 
```
load table: append job statistics: getting job: googleapi: Error 429: Quota exceeded for quota metric 'Requests' and limit 'Requests per day' of service 'bigquery.googleapis.com'
```
- We can ignore the errors as these statistics are just for tracking alerts and we don't want to retry the syncs due to the following error.
- Resolves PIPE-653
=> fix: bigquery job statistics for rate limit

runner/buckets.go
Adding custom buckets for GW request size for better cost analysis (HA ingestion project).
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-659/histogram-buckets-for-gw-request-size) >
=> chore: custom buckets for gw request size

app/apphandlers/embeddedAppHandler.go, app/apphandlers/processorAppHandler.go, app/apphandlers/setup.go, backend-config/internal/cache/cache.go, internal/drain-config/drainConfig.go, jobsdb/jobsdb.go, services/notifier/notifier.go, services/validators/envValidator.go, utils/misc/dbutils.go, utils/misc/dbutils_test.go, warehouse/app.go
We want to manage and identify PostgreSQL connections based on the components that establish them. PostgreSQL provides the application_name parameter, which we can use to tag connections with the name of the component. This can be helpful for monitoring and managing connections.
Usecase:
1. To see how many connections are used by a specific component, we can query the `pg_stat_activity`
2. To identify slow queries by a specific component, we can use the `pg_stat_statements` extension along with `application_name`
3. kill all connections from a specific component
4. To monitor resource usage (e.g., CPU, memory) by a specific component, we can use the `pg_stat_activity` along with other system views.
pipe-605
=> chore: include the component in application_name of postgres connection

services/rsources/handler_test.go, services/rsources/handler_v1_test.go
- Currently, we are logging as a byte sequence. [GA link.](https://github.com/rudderlabs/rudder-server/actions/runs/7338777343/job/19981825989)
```
Failed Records from both services should be the same%!(EXTRA []uint8=[123 34 105 100 34 58 34 34 44 34 116 97 115 107 115 34 58 110 117 108 108 125], []uint8=[123 34 105 100 34 58 34 34 44 34 116 97 115 107 115 34 58 110 117 108 108 125], []uint8=[123 34 105 100 34 58 34 56 101 51 53 98 55 56 53 98 55 48 56 52 56 49 99 56 100 100 53 97 101 50 101 99 53 52 98 54 101 53 99 34 44 34 116 97 115 107 115 34 58 91 123 34 105 100 34 58 34 116 97 115 107 95 114 117 110 95 105 100 34 44 34 115 111 117 114 99 101 115 34 58 91 123 34 105 100 34 58 34 115 111 117 114 99 101 95 105 100 34 44 34 114 101 99 111 114 100 115 34 58 110 117 108 108 44 34 100 101 …
```
=> chore: improve error logging

integration_test/docker_test/docker_test.go
- Tables can be empty or they might not be created as well, since warehouse syncing might be in progress. [GA link](https://github.com/rudderlabs/rudder-server/actions/runs/7421240913/job/20194180962).
```
docker_test.go:180: 
Error Trace:	/home/runner/work/rudder-server/rudder-server/integration_test/docker_test/docker_test.go:180
/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/asm_amd64.s:1650
Error:      	Received unexpected error:
sql: no rows in result set
Test:       	TestMainFlow/postgres
```
- Moving it to require.Eventually
```
require.Eventually(t, func() bool {
eventSql := "select anonymous_id, user_id from dev_integration_test_1.screens limit 1;"
_ = db.QueryRow(eventSql).Scan(&myEvent.anonymousID, &myEvent.userID)
return myEvent.anonymousID == "anonymousId_1"
}, time.Minute, …
```
=> chore: flaky docker test

app/apphandlers/embeddedAppHandler.go, app/apphandlers/gatewayAppHandler.go, app/apphandlers/processorAppHandler.go, app/apphandlers/setup.go, internal/drain-config/drainConfig.go, internal/drain-config/http.go, services/rsources/failed_records_pagination_test.go, services/rsources/handler.go, services/rsources/handler_test.go, services/rsources/handler_v1_test.go, services/rsources/http/http_integration_test.go, services/rsources/rsources.go
Gateway was not able to start web server, If sharedDB is down for some reason. Following steps in startup are blocking web server to start.
1. RSources service was not able to start as it was not able to connect with sharedDB and setup db tables and replication.
2. DrainConfigManager was not able start and run migrations for the drain config db tables present in shared DB.
Solution: 
When a new gateway instance is coming up, 
1. while setting up RSources service we will not setup sharedDB tables and replication.
2. while setting up DrainConfigManager we will not halt gateway setup on failure of migration for drain config tables.
We will raise an alert for the failure logs. AI for the alert will be to restart gateway instance.
https://linear.app/rudderstack/issue/PIPE-484/gateway-should-acc …
=> chore: enabling gateway to ingest events even when sharedDB is down

gateway/handle.go, gateway/handle_http_auth.go, gateway/handle_http_auth_test.go, gateway/handle_http_retl.go, gateway/internal/context/context.go, gateway/internal/types/types.go, gateway/response/response.go
Adding Destination ID to rETL endpoint to provide a way for rETL to send an event from a source to a destination. If there are multiple sources rETL will call `/retl` endpoint multiple times to deliver to multiple destinations. 
- Destination ID will be stored in parameters column along with source ID
Pipe-619
=> feat: add destinationID to rETL endpoint

enterprise/reporting/error_index/worker.go, enterprise/reporting/error_index/worker_test.go
- Since the loop SleepDuration is set to 30 seconds, exhaust all the jobs present in the err index, when work is called.
- Resolves PIPE-680
=> fix: exhaust error index jobs when work is called

go.mod, go.sum
Upgrade SQL tunnel to v0.1.6
- Resolves PIPE-680
=> chore: upgrade sql tunnels to v0.1.6

enterprise/reporting/error_index/worker.go, enterprise/reporting/error_index/worker_test.go
- Identified and addressed an issue with over 10k records (around 2M) for a specific **sourceID** and **failedAt** during PWCC debugging.
- Introduced a **uuid** to the error-index file path, maintaining backward compatibility with the existing format.
- Successfully executed e2e tests [here](https://github.com/rudderlabs/e2e/actions/runs/7475473131/job/20343689226).
- Resolves PIPE-682
=> chore: error index file path collision

gateway/handle_lifecycle.go, router/batchrouter/batchrouter_isolation_test.go, router/eventorder_debugger_test.go, router/eventorder_test.go, router/router_isolation_test.go, router/router_throttling_test.go, services/rsources/stats_collector.go
Ignore destinationID in gateway's rsources stats collector.
[slack thread](https://rudderlabs.slack.com/archives/C02B0A38QQG/p1704894410348019)
=> fix: ignore destinationID in gateway rsources.statCollector

enterprise/reporting/error_reporting.go
Removed namespace tag from error_detail_reporting_failures as it is not supported
https://rudderlabs.slack.com/archives/C01HTT66UMB/p1704960958577379
=> chore: remove namespace tag from error_detail_reporting_failures metric

backend-config/backend_config_test.go, backend-config/namespace_config.go, backend-config/single_workspace.go, backend-config/single_workspace_test.go, go.mod, go.sum
Adding metric to record the number of calls to the BackendConfig HTTP API.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-695/backend-config-calls-metric) >
=> chore: backend config calls metric

jobsdb/jobsdb_backup_test.go
- Log files instead of a pointer which will help debug the failed test.
```
jobsdb_backup_test.go:320: file list:  [0xc0008caea0 0xc0008caed0 0xc0008caf00 0xc0008caf30 0xc0008caf60 0xc0008caf90]  err:  <nil> len:  6
jobsdb_backup_test.go:320: file list:  [0xc0008cb1a0 0xc0008cb1d0 0xc0008cb230 0xc0008cb260 0xc0008cb290 0xc0008cb2c0]  err:  <nil> len:  6
```
- Refer to the [GitHub Actions run](https://github.com/rudderlabs/rudder-server/actions/runs/7490156481/job/20388357432) for details on the unsuccessful validation.
=> chore: improve error logs during jobsdb backup table test

warehouse/internal/repo/schema_test.go
- Recognized potential variations in the ordering of the tables field in GetTablesForConnection.
- Comparing individual fields now.
- Refer to the [GitHub Actions run](https://github.com/rudderlabs/rudder-server/actions/runs/7498425504/job/20413517963) for details on the unsuccessful validation.
```
=== Failed
=== FAIL: warehouse/internal/repo TestWHSchemasRepo/GetTablesForConnection (0.00s)
schema_test.go:120: existing
schema_test.go:124: 
Error Trace:	/home/runner/work/rudder-server/rudder-server/warehouse/internal/repo/schema_test.go:124
Error:      	elements differ
extra elements in list A:
([]interface {}) (len=1) {
(warehouseutils.FetchTableInfo) {
SourceID: (string) (len=9) "source_id",
DestinationID: (string) (len=14) "destination_id",
Namespace: (string) (len=9) "namespace", …
```
=> chore: fix flaky test for tables for connections from wh schemas as ordering for tables can be different

integration_test/docker_test/docker_test.go, processor/processor.go, processor/processor_test.go, utils/types/types.go
For events received through rETL endpoints, destination ID for an event will be stored in params field in JobsDB. For all the events having destination ID in params should be delivered to only those destinations irrespective of how many other destinations are connected to the source. All the other destinations will be filtered at processor.
Base PR: https://github.com/rudderlabs/rudder-server/pull/4234
pipe-620
=> feat: filter destinations for events from rETL in processor

processor/processor.go, processor/worker.go, processor/worker_test.go
Ignore gw jobs' destination id at processor sources stat collector as well.
[slack conversation](https://rudderlabs.slack.com/archives/C02B0A38QQG/p1705416465275999)
=> fix: ignore gwJobs' destinationID in processor rsources.statCollector

CHANGELOG.md
chore(deps): bump github.com/DATA-DOG/go-sqlmock from 1.5.0 to 1.5.2 (#4301)
chore(deps): bump github.com/go-chi/chi/v5 from 5.0.10 to 5.0.11 (#4303)
chore: improve error logs during processor stash test (#4317)
=> chore: merge release 1.19.0 in main branch(#4316)

CHANGELOG.md, processor/processor.go, processor/worker.go, processor/worker_test.go
fix: ignore gwJobs' destinationID in processor rsources.statCollector (#4321)
=> chore: applying 1.19.1 hotfixes to main branch

warehouse/integrations/bigquery/bigquery.go
- In case of rate limit errors, we are sending empty statistics and then trying to access a Load field which will be nil.
- Resolves PIPE-704
=> fix: nil load statistics for bigquery

cmd/rudder-cli/util/s3.go, gateway/webhook/webhookTransformer.go, jobsdb/jobsdb_backup_test.go, router/batchrouter/handle_async.go, suppression-backup-service/cmd/main_test.go, utils/misc/dbutils.go, warehouse/integrations/azure-synapse/azure-synapse.go, warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/mssql/mssql.go
Decreasing pending events for successful and aborted jobs in async batch router destinations.
[slack](https://rudderlabs.slack.com/archives/C02A3UAU9UN/p1706009016160949?thread_ts=1706007698.186699&cid=C02A3UAU9UN)
=> fix: batchrouter async dest pending event counts aren't being decreased

router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/marketobulkupload.go
fix: marketo bulk upload's upload url preparation fix
https://linear.app/rudderstack/issue/INT-1449/%5Bfix%5D-fix-marketo-bulk-uploads-upload-url
=> fix: marketo bulk upload's upload url preparation fix

warehouse/router/upload_stats.go
1. Classifying table names other than `"tracks", "identifies", "pages", "screens", "aliases", "groups"` as others. this will reduce the number of distinct tableName tags going into metrics.
https://linear.app/rudderstack/issue/PIPE-340/remove-tablename-from-event-delivery-time-metric
=> chore: reduce cardinality of warehouse metrics

router/handle.go, router/router_test.go, router/worker.go
Drain router jobs faster. Done by sending the job to worker in case of backoff or throttling whereas it was discarded earlier.
[slack thread](https://rudderlabs.slack.com/archives/C02026YSHQ9/p1705411872414129?thread_ts=1705297122.598099&cid=C02026YSHQ9)
[Resolves PIPE-713](https://linear.app/rudderstack/issue/PIPE-713/drain-to-avoid-rate-limiting)
=> fix: jobs not draining as fast as we'd like because of rate-limiting etc.

router/eventorder_debugger_test.go, router/handle.go, router/handle_lifecycle.go, router/handle_observability.go, router/internal/eventorder/eventorder.go, router/internal/eventorder/eventorder_simulation_test.go, router/internal/eventorder/eventorder_test.go, router/misc.go, router/router_test.go, router/worker.go
Provides config to toggle event ordering at a workspace/destination level.(`"Router.orderingDisabledWorkspaceIDs"`, `"Router.orderingDisabledDestinationIDs"`)
On setting required workspace/destinationID, the barrier for that `BarrierKey` is disabled. Turns back to processing events in  order once the config has been reset and after passing of `eventOrderDisabledStateDuration` and `eventOrderHalfEnabledStateDuration` duration.
Introduces `BarrierKey` which is just a composite:
```
type BarrierKey struct {
DestinationID, UserID, WorkspaceID string
}
```
so the barrier methods now take this instead of the string(`<destID>:<userID>`) earlier
[linear](https://linear.app/rudderstack/issue/PIPE-28/disable-event-ordering-at-a-workspace-level-destination-id-level)
=> feat: toggle event ordering for workspace/destination

gateway/handle.go, gateway/handle_lifecycle.go, runner/runner.go
=> chore: ununsed code

gateway/gateway.go, gateway/gateway_test.go, gateway/handle.go, gateway/handle_http.go, gateway/handle_lifecycle.go, gateway/handle_observability.go, gateway/integration_test.go, gateway/openapi.yaml, gateway/openapi/index.html
internal batch endpoint: no buffering, not a lot of validations -> just write to jobsdb.
[resolves PIPE-765](https://linear.app/rudderstack/issue/PIPE-765/[rudder-server]-create-a-gw-internal-endpoint-to-bypass-validations)
=> feat: internal batch endpoint

processor/processor.go, processor/worker.go, processor/worker_test.go
corrects wrong out of order stats at processor.
[slack thread](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1709027650780319)
=> fix: wrong processor out of order stats

processor/transformer/transformer.go
use parent context in transformer to create new request.
[link to relevant line](https://github.com/rudderlabs/rudder-server/blob/3f879308aa17f56a77c0e3d116ee0d371e00c716/processor/transformer/transformer.go#L466)
=> chore: processor transformer uses parent ctx to create new request

warehouse/archive/archiver.go
- Enable archiver for staging file entries irrespective of the use rudder storage option. 
- This we got to know when we wanted to retry for one of our customers who opted for rudder storage and we didn't see any entries in object storage.
- Resolves PIPE-859
=> fix: enable archiver for use rudder storage for dtaging file entries

processor/processor.go, processor/processor_test.go, processor/trackingplan.go, processor/transformer/transformer.go
send source name as part of metadata to transformer.
[ref](https://rudderlabs.slack.com/archives/C018SGKA998/p1709213709105579)
=> chore: send source name in metadata to transformer

processor/processor.go, processor/processor_test.go
adding some non-exhaustive drop count stats in processor.
[motivation is to help find out where events are dropped(if they are) in cases like this(in a not so tiring manner)](https://rudderlabs.slack.com/archives/C02AALVFHJN/p1709405639968449)
=> chore: some non-exhaustive processor drop count stats

enterprise/reporting/reporting.go
vacuum reports table when size estimate goes over 5GB(configurable).
[slack thread](https://rudderlabs.slack.com/archives/C02GW9B6K08/p1709952064963919)
=> chore: vacuum reports table when size > 5GB

router/batchrouter/asyncdestinationmanager/eloqua/manager.go
We are updating the destType name in the stats of Eloqua destination to send only the destination definition name, not the destination name set by the customer.
Resolves INT-1671
=> fix: destType issue in eloqua stats

enterprise/reporting/error_reporting.go, enterprise/reporting/error_reporting_test.go
- In this pr we are filtering successful events before sending it to errors table in reporting DB
- [ ✅] The code changed/added as part of this pull request won't create any security issues with how the software is being used.
=> fix: filter success events before sending it to error reporting table

warehouse/integrations/redshift/redshift.go, warehouse/integrations/redshift/redshift_test.go
Recently we had three incidents where redshift crash recovery kept on failing. We select tables matching a prefix and then attempt to delete them. Due to race, the table has already been deleted by another process. Although we have concurrency controls to prevent multiple recoveries from taking place for the same destination, but another destination configured in the same namespace could likely cause this. 
Thus, introducing `IF EXIST` to ensure that deletes failures won't cause sync to fail.
https://linear.app/rudderstack/issue/PIPE-926/robust-dangling-tables-deletion
=> fix: robust dangling table deletion during recovery

.github/workflows/builds.yml
Adding support to build arm64 image in GA. 
We will create both arm64 as well as amd64 docker image for rudder-server. A manifest will be created that will add both the builds to a common tag so that based on the arch of host machine correct build will be picked-up
Successful Build: https://github.com/rudderlabs/rudder-server/actions/runs/8537621984/job/23388772427
https://linear.app/rudderstack/issue/PIPE-889/arm-build-for-rudder-server
=> feat: add support to build arm64 image

integration_test/warehouse/testdata/docker-compose.ssh-server.yml, warehouse/integrations/postgres/testdata/docker-compose.ssh-server.yml, warehouse/integrations/tunnelling/testdata/docker-compose.yml
- There seem to be some changes made in the latest docker image which was published 4 days back. I tried with an older image [9.3_p2-r1-ls145](https://hub.docker.com/layers/linuxserver/openssh-server/9.3_p2-r1-ls145/images/sha256-518b05c43d45a515f5e78b3f822f25884afd2ddfa396ff430e6fb1ed7dd8ad02?context=explore) and it's working there.
- Resolves PIPE-966
=> fix: health check for ssh server

gateway/handle.go
-  Remove rudder id from internal batch endpoint, as it is being set by the ingestion svc.
- Corresponding ingestion svc changes: https://github.com/rudderlabs/rudder-ingestion-svc/pull/41
- Resolves PIPE-920
=> chore: remove rudder id from internal batch endpoint

CHANGELOG.md
merge 1.23.0 into master
[release process](https://www.notion.so/rudderstacks/Release-process-094ecf877f3d47e9ad94ab28622da225?pvs=4#1a026c7afbde425fa849f2ed0d804387)
=> chore: merge release 1.23.0 in main branch

router/batchrouter/handle_observability.go, router/worker.go, runner/buckets.go, runner/runner.go
- As part of the [delays project](https://www.notion.so/rudderstacks/End-to-End-Delays-in-Pipeline-362b6fe1e3b148c68aa538670d2a60da), we are planning to show end-to-end delay in pipeline to customers on webapp. As part of this PR we are making 2 changes
- Tweak the histogram buckets on `event_delivery_time` metric
- Add `sourceId` label on `event_delivery_time` metric
- On destination page, we are planning to show end-to-end delay for a selected connection or delay across all sources connected to a destination
- https://linear.app/rudderstack/issue/OBS-428/tweak-buckets-on-histogram-metric-event-delivery-time-bucket
completes OBS-428
=> chore: configure histogram buckets and add sourceId label on event_delivery_time metric

.github/dependabot.yml
Group minor, patch updates in go package, docker and github actions.
Any major upgrade can be dealt with separately.
[context](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1712768198567829)
=> chore: group minor, patch dependabot updates

.github/workflows/builds.yml, .github/workflows/tests.yaml, .github/workflows/verify.yml
Our earlier change was cancelling actions in progress.
[That change](https://github.com/rudderlabs/rudder-server/pull/4573) was unwittingly cancelling runs on push to master as well. 
IMO, it's nice to have this suite run for every commit to master without cancelling.
On push to master `github.head_ref` would be empty, so one way to group the workflows would be by falling back on commit hash - `github.sha`.
Alternatively, we could separate workflow files for `push`, `pull-request` for simplicity and not have concurrency groups in `push` workflow.
=> fix: actions cancelling on push to master

warehouse/integrations/redshift/redshift.go, warehouse/integrations/redshift/redshift_test.go, warehouse/integrations/snowflake/snowflake.go
- Introducing append-only table for redshift at the table level same as we have for [Snowflake](https://github.com/rudderlabs/rudder-server/blob/c7398deb820ad4a1f0f51d3d150f36cd5426b80c/warehouse/integrations/snowflake/snowflake.go#L192) but at a granularity for `destinationID`.
- For setting this, we would need something like:
```
serverConfigOverride:
Warehouse:
redshift:
appendOnlyTables:
destinationID:
- tracks
- identifies
```
- Resolves PIPE-1021, PIPE-1020
=> feat: append only tables for redshift

services/rsources/handler.go, services/rsources/handler_test.go
The issue triggered by this change https://github.com/rudderlabs/rudder-server/pull/4598, when deployed to free users.
The underlaying cause was that we didn't properly escaping the connection info string passed to the query. The new connection query contained `'`, causing the parsing to break and the following error to happen:
```
{"level":"ERROR","ts":"2024-04-23T12:27:22.674Z","logger":"runner","caller":"runner/runner.go:274","msg":"Terminal error: rudder core: logical replication in \"hostedmtedmt-v0-rs-postgresql-3.hostedmtedmt-v0-rs-postgresql-headless\": failed to create subscription on shared database: pq: syntax error at or near \"-\""}
```
Using [pq.QuoteLiteral](https://pkg.go.dev/github.com/lib/pq#QuoteLiteral) to properly escape the connection string. 
Updated the test to …
=> fix: correctly quote connection on subscription creation

router/transformer/transformer_test.go, services/oauth/v2/http/transport.go
We want to add logs for errors in oauthv2 implementation. These errors are platform and not user actionable.
Resolves INT-2041
=> chore: add error logs for oauthv2 errors

app/app.go
This PR introduced a breaking change for the health endpoint https://github.com/rudderlabs/rudder-server/pull/4584/files#diff-0f1d2976054440336a576d47a44a37b80cdf6701dd9113012bce0e3c425819b7R168
Thus hard-coding the routingEvents to always true, since we remove recovery on rudder-server.
https://linear.app/rudderstack/issue/PIPE-1033/health-endpoint-backwards-compatibility
=> chore: ensure health endpoint backwards compatibility

go.mod, go.sum, services/notifier/notifier.go, warehouse/app.go
- Integrating with `sqlutil.MonitorDatabase` for warehouse and notifier package.
- Resolves PIPE-894
=> feat: monitor warehouse databases

jobsdb/jobsdb.go
Minor cleanup in jobsdb's `checkIfFullDSInTx` method.
1. Using a better query imo to get min `created_at`
2. Use the transaction to fetch required info(because why use another conn)
3. return early if `sql.ErrNoRows`
4. query only once for row count and table size
```
Limit  (cost=0.29..0.56 rows=1 width=16) (actual time=0.013..0.013 rows=1 loops=1)
->  Index Scan using gw_jobs_132478_pkey on gw_jobs_132478  (cost=0.29..26637.24 rows=100258 width=16) (actual time=0.012..0.012 rows=1 loops=1)
Planning Time: 0.048 ms
Execution Time: 0.022 ms
```
```
Aggregate  (cost=25277.23..25277.24 rows=1 width=8) (actual time=56.690..56.691 rows=1 loops=1)
->  Seq Scan on gw_jobs_132478  (cost=0.00..25026.58 rows=100258 width=8) (actual time=0.022..48.656 rows=100265 loops=1)
Planning Time: 0.062 ms …
```
=> chore: cleanup *jobsdb.Handle.checkIfFullDSInTx(...)

archiver/worker.go
Adding a uuid suffix for archival files to avoid conflicts while uploading same files
https://linear.app/rudderstack/issue/PIPE-1059/use-uuid-for-archival-files-to-avoid-conflicts
=> chore: use uuid for archival files to avoid conflicts

warehouse/integrations/clickhouse/clickhouse.go, warehouse/router/state_export_data.go, warehouse/router/upload_stats.go, warehouse/router/upload_test.go, warehouse/utils/stats.go, warehouse/utils/stats_test.go
- Restricting tableName in warehouse stats to be from one of these []string{"tracks", "identifies", "pages", "screens", "aliases", "groups", "users"}, otherwise use others.
- Resolves PIPE-1067
=> chore: reducing metrics cardinality

CHANGELOG.md
chore: use uuid for archival files to avoid conflicts (https://github.com/rudderlabs/rudder-server/pull/4631)
chore: reducing metrics cardinality (https://github.com/rudderlabs/rudder-server/pull/4662)
chore(deps): bump golangci/golangci-lint-action from 5 to 6 (https://github.com/rudderlabs/rudder-server/pull/4663)
=> chore: merge release 1.25.0 in main branch

enterprise/reporting/reporting.go
Disabling event name tracking for all RETL connections, because many customer uses UUIDs for event names, creates a high level of cardinality.
https://linear.app/rudderstack/issue/OBS-470/disable-event-name-tracking-for-retl-connections
=> chore: disable event name tracking for retl connections

processor/processor.go, processor/transformer/transformer.go
Add destination name to the transformation metadata fields
Fixes PIPE-1102
=> chore: add destName to metadata

warehouse/slave/slave_test.go, warehouse/slave/worker.go, warehouse/slave/worker_test.go
warehouse-slave is spending a lot of cpu time in marshalling JSON, but we don't use jsoniter to marshall or unmarshall.
https://linear.app/rudderstack/issue/PIPE-1104/warehouse-slave-is-spending-a-lot-of-cpu-time-in-marshaling-json-but
=> chore: use jsoniter in warehouse slave

.github/workflows/sync-release.yaml
Automatically creating a **_sync to main branch_** pull request after a new release and assigning it to the person who merged the release-please PR.
**Examples:**
- Minor release [here](https://github.com/rudderlabs/wht/pull/1407)
- Patch release [here](https://github.com/rudderlabs/wht/pull/1434)
=> chore: action for automatically creating sync to main pr after a release

warehouse/slave/worker.go
replacing jsoniter.ConfigFast with jsoniter.ConfigCompatibleWithStandardLibrary as we are loosing precision in case of json.ConfigFast
ref: https://jsoniter.com/migrate-from-go-std.html#:~:text=6%20digits%20precision%20(lossy)
pipe-1104
=> chore: use jsoniter.ConfigCompatibleWithStandardLibrary

backend-config/internal/cache/cache.go
use json-iterator in backend config cache as its consuming 3.2% cpu time for multitenent customers
https://linear.app/rudderstack/issue/PIPE-1119/use-json-iterator-in-backend-config-cache
=> chore: use json-iterator in backend config cache

warehouse/bcm/backend_config.go, warehouse/internal/api/http.go, warehouse/router/tracker.go, warehouse/router/tracker_test.go
- **Avoid sending warehouseID in stats** since we already have sourceID and destinationID we don't need warehouseID which is essentially a combination of `(sourceName, destinationName, sourceID, destiantionID)`.
- For new tags following the standards we have in [observability-kit](https://github.com/rudderlabs/rudder-observability-kit/blob/main/go/labels/common.go#L11).
- **Current Plan Overview**:
- **Ensuring Availability of Stable Identifiers**: In all statistics where `warehouseID` is utilized, `sourceID` and `destID` are ensured to be available. For any instances where these identifiers are absent, they are added.
- **Transitioning from `warehouseID`**: Once the new tags (`sourceID` and `destID`) are consistently populated, the next step involves removing `warehouseID` from the …
=> chore: avoid sending warehouseID in stats

processor/processor.go, processor/processorBenchmark_test.go
Instead of `config.Get...`ing the same thing(kube namespace, instanceID) for every event, we may fetch it once and use that information for all.
[Resolves PIPE-1072](https://linear.app/rudderstack/issue/PIPE-1072/misc)
=> chore: get processor namespace, instanceID during setup

jobsdb/jobsdb.go
Adding error to handle invalid byte UTF-8 sequences for jobsdb.
< Linear Link >
=> fix: invalid byte sequence UTF-8

warehouse/archive/archiver.go, warehouse/archive/archiver_test.go
- Since the current archival runs every 6 Hrs and archives 10K (limit) uploads which are older then 5 days.
- This is causing an issue if we are generating more than 10K uploads in 6Hrs which will create a Backlog and it will keep accumulating.
- We face an issue with our MT system where we have accumulated 1.1M uploads. More about it in [here](https://rudderlabs.slack.com/archives/C01JF5MGUAG/p1717045801751619?thread_ts=1717040388.986919&cid=C01JF5MGUAG).
- Resolves [PIPE-1140](https://linear.app/rudderstack/issue/PIPE-1140/warehouse-archiver-fix)
=> fix: archival to archive everything whenever it is running

gateway/handle.go
Events coming for HA ingestion did not appear in live-events viewer, due to `writeKey` missing from the payload.
Note: this PR doesn't contain test, as it would require significant changes in our tests suite. I wanted to keep scope small since it is hotfix. I have create a [task](https://linear.app/rudderstack/issue/PIPE-1148/improve-gateway-tests-for-internalv1batch) for them.
https://linear.app/rudderstack/issue/PIPE-1147/fix-ha-ingestion-live-events
=> fix: populate singular batch with writeKey in internal handler

gateway/webhook/webhook.go, gateway/webhook/webhook_test.go
The sources names need to be lower cased in order to stay consistent with sourceListForParsingParams, which is getting lower cased in https://github.com/rudderlabs/rudder-server/blob/2ac517df928248bda5465396b9963b1642d9dab4/gateway/webhook/setup.go#L57
https://linear.app/rudderstack/issue/RUD-1741/hey-team-a-customer-reached-out-regarding-potential-lack-of-events
=> fix: webhook sources name needs to be lower cased

warehouse/integrations/datalake/testdata/etc/jvm.config
- Using previous version (trinodb/trino:448) for trino test. 
- Else it requires some [additional JVM config changes](https://github.com/rudderlabs/rudder-server/actions/runs/9347809213/job/25725576454?pr=4747) as per the recent release for `trinodb/trino:449`.
=> fix: trino test

warehouse/router/tracker.go, warehouse/router/tracker_test.go
Introduce `warehouse_cron_tracker_tick` metric, always incrementing. If cronTrack loop stop running, the metric will remain stable.
We can setup an alert on `increase(warehouse_cron_tracker_tick[5m]) = 0`
https://linear.app/rudderstack/issue/PIPE-1183/detect-stuck-cron-tracker
=> chore: detect tracker not running

warehouse/integrations/clickhouse/testdata/docker-compose.clickhouse-cluster.yml, warehouse/integrations/clickhouse/testdata/docker-compose.clickhouse.yml, warehouse/integrations/datalake/testdata/docker-compose.yml
Clickhouse and datalake tests were failing, as the container was unheathy. The issue was with docker versions 26.1.x. Event though we had disabled ipv6 on the host machine localhost requests were resolved to `[::]:8123` in container which is ipv6 address. When I switched from `localhost` to `0.0.0.0` everything worked.
```
runner@fv-az532-110:~/work/rudder-server/rudder-server$ docker exec -it test_qzldqgzazleffkelfbjz-clickhouse04-1 wget --no-verbose --tries=1 --spider http://localhost:8123/ping                                                                     
Connecting to localhost:8123 ([::1]:8123)
wget: can't connect to remote host: Connection refused
runner@fv-az532-110:~/work/rudder-server/rudder-server$ docker exec -it test_qzldqgzazleffkelfbjz-clickhouse04-1 wget --no-verbose …
```
=> chore: fix warehouse integration tests

sql/migrations/tracked_users/000001_init_schema.up.sql
create migration for tracked_user_reports table for POC on monthly tracked users.
Column Name | Data Type | Description
-- | -- | --
id | BIGSERIAL PRIMARY KEY | unique identifier
workspace_id | VARCHAR(64) NOT NULL | workspace identifier
instance_id | VARCHAR(64) NOT NULL | rudder server node identifier
source_id | VARCHAR(64) NOT NULL | source identifier
reported_at | TIMESTAMP WITH TIMEZONE NOT NULL |  
userid_hll | TEXT NOT NULL | serialized HLL for user IDs
anonymousid_hll | TEXT NOT NULL | serialized HLL for anonymous IDs
identified_anonymousid_hll | TEXT NOT NULL | serialized HLL for anonymous IDs where userIDs are known
https://linear.app/rudderstack/issue/PIPE-1189/create-migrations-for-db-table-on-rudder-server-for-poc
=> chore: create migration for tracked_user_reports table

gateway/gateway_test.go, gateway/handle.go
rename `requestIP` to `request_ip` in payload
https://linear.app/rudderstack/issue/PIPE-1192/rename-requestip-to-request-ip
=> chore: rename requestIP to request_ip in payload

warehouse/integrations/clickhouse/clickhouse.go
- We are not closing the context causing the memory leak to happen for `clickhouse` during `ExecContext`.
- Resolves PIPE-1211
=> fix: memory leak for clickhouse during loading

CHANGELOG.md, warehouse/integrations/clickhouse/clickhouse.go
Syncing patch release v1.28.1 to main branch
fix: memory leak for clickhouse during loading (#4829)
=> chore: sync release v1.28.1 to main branch

warehouse/integrations/postgres/load.go, warehouse/safeguard/stop.go, warehouse/safeguard/stop_test.go
It has been observe in production that during shutdown postgres can get stuck on rollback, ignoring ctx cancelation:
```
github.com/lib/pq.(*conn).Rollback(0x4025540908)
/go/pkg/mod/github.com/lib/pq@v1.10.9/conn.go:646 +0xc8
database/sql.(*Tx).rollback.func1()
/usr/local/go/src/database/sql/sql.go:2335 +0x34
database/sql.withLock({0x3c84c08, 0x408783a090}, 0x40a6da58b0)
/usr/local/go/src/database/sql/sql.go:3530 +0x7c
database/sql.(*Tx).rollback(0x4045941380, 0x0)
/usr/local/go/src/database/sql/sql.go:2334 +0xf0
database/sql.(*Tx).Rollback(...)
/usr/local/go/src/database/sql/sql.go:2349
github.com/rudderlabs/rudder-server/warehouse/integrations/middleware/sqlquerywrapper.(*Tx).Rollback(0x4053255050)
/rudder-server/warehouse/integrations/middleware/sqlquerywrapper/sql.go:347 +0x64 …
```
=> fix: use safeguard to panic if not stop on time

processor/processor.go, processor/processor_test.go
Fix the `timestamp` field to be equal to `recievedAt` in case the timestamp is missing in payload
Fixes PIPE-1230
=> chore: fix timestamp fields

jobsdb/jobsdb.go, jobsdb/jobsdb_test.go, jobsdb/migration.go
Separate out index creation for jobsdb datasets. Motivation stemmed from wanting to create indices after jobs are copied during migration([src](https://www.postgresql.org/docs/current/populate.html#POPULATE-RM-INDEXES)). Includes foreign key constraint.
Removed `addDS` journal entry during migration. Which imo is fine considering the `migrateDS` entry contains info about the created dataset.
[Resolves PIPE-1072](https://linear.app/rudderstack/issue/PIPE-1072/misc)
=> chore: separate dataset index creation

processor/processor.go, processor/processor_test.go
fix trackedUsers reports merging for subjobs in processor, adding tests for the entire flow might need some refactoring of worker tests, I will raise a separate PR for that
-
=> fix: trackedUsers reports merging in processor

enterprise/trackedusers/factory.go, enterprise/trackedusers/users_reporter.go, enterprise/trackedusers/users_reporter_test.go, processor/processor.go, runner/buckets.go
Add following metrics in rudder server
- Latency of generating HLLs
- Size in each HLL inserted in the outbox table
https://linear.app/rudderstack/issue/PIPE-1245/add-metrics-for-rudder-server
=> chore: add metrics for unique users reporter

warehouse/integrations/postgres/load.go
- Adding index on union of users and identifies table for postgres integration
- Resolves PIPE-1275
=> chore: postgres index on union users table

CHANGELOG.md
Syncing release v1.29.0 to main branch
chore(deps): bump github.com/aws/aws-sdk-go from 1.54.14 to 1.54.15 in the frequent group (#4878)
=> chore: sync release v1.29.0 to main branch

enterprise/trackedusers/users_reporter.go, enterprise/trackedusers/users_reporter_test.go
- Update default value for MTU precision to 16
- Set timezone for reported_at in UTC as flusher is expecting time in UTC timezone. currently we are storing timezone in the DB so it should not an issue.
=> chore: update default mtu config

sql/migrations/warehouse/000025_drop_trigger_schema_versions.sql.up.sql
Stop populating `wh_schema_version` table.
https://linear.app/rudderstack/issue/PIPE-1318/stop-populating-schema-versions
Resolves PIPE-1318
=> feat: drop trigger for populating warehouse schema versions

.github/workflows/tests.yaml, integration_test/trackedusersreporting/tracked_users_reporting_test.go
Add mock reporting server in MTU integration tests where currently we are reading from DB and validating. We need to add a mock reporting server to record the requests and aggregate HLLs and see if correct data is showing up.
https://linear.app/rudderstack/issue/PIPE-1300/add-mock-reporting-server-in-mtu-integration-tests
=> chore: add mock reporting server in mtu integration tests

Dockerfile, go.mod, suppression-backup-service/Dockerfile
Addressing:
```
Vulnerability #1: GO-2024-2963
Denial of service due to improper 100-continue handling in net/http
More info: https://pkg.go.dev/vuln/GO-2024-2963
Standard library
Found in: net/http@go1.22.4
Fixed in: net/http@go1.22.5
Example traces found:
#1: services/streammanager/googlecloudfunction/googlecloudfunction.go:169:42: googlecloudfunction.GoogleCloudFunctionProducer.Close calls http.Client.CloseIdleConnections
#2: utils/misc/misc.go:346:24: misc.MakeHTTPRequestWithTimeout calls http.Client.Do
#3: integration_test/retl_test/sut.go:348:28: retl_test.SUT.JobStatus calls http.Client.Get
#4: services/alert/pagerduty.go:35:26: alert.PagerDuty.Alert calls http.Client.Post
#5: services/streammanager/googlecloudfunction/googlecloudfunction.go:86:17: …
```
=> chore: upgrade go v1.22.5

CHANGELOG.md
Syncing release v1.30.0 to main branch
chore(deps): bump docker/login-action from 3.1.0 to 3.3.0 (#4914)
chore(deps): bump the go-deps group across 1 directory with 4 updates (#4912)
chore(deps): bump github.com/aws/aws-sdk-go from 1.54.19 to 1.54.20 in the frequent group (#4907)
=> chore: sync release v1.30.0 to main branch

.github/workflows/prerelease.yaml
automate server release on hosted whenever we push to a pre-release branch
https://linear.app/rudderstack/issue/PIPE-1327/trigger-release-workflow-from-pre-release
=> chore: automate server release on hosted with prerelease

warehouse/api/grpc.go, warehouse/api/grpc_test.go, warehouse/internal/repo/table_upload.go, warehouse/internal/repo/table_upload_test.go, warehouse/internal/repo/upload.go, warehouse/internal/repo/upload_test.go
- Fixes in syncs dashboard
- souceID filter is not working as expected.
- In case of `lastExecAt` is set as NULL, it behaving in an unexpected way.
- Resolves PIPE-1232
- Resolves PIPE-1344
=> fix: syncs dashboard

.github/workflows/prerelease.yaml, .github/workflows/release-please.yaml
Trigger release workflow after release
https://linear.app/rudderstack/issue/PIPE-1346/trigger-release-workflow-from-release
=> chore: trigger release workflow after release

.github/workflows/sync-release.yaml
- remove check for github user before running sync-release action
- don't start the jobs if base branch is not release branch. current action logs are cluttered with runs where job didn't really execute ref: https://github.com/rudderlabs/rudder-server/actions/workflows/sync-release.yaml
-
=> chore: update sync-release action to run on all release prs

gateway/webhook/setup.go, gateway/webhook/webhook.go, gateway/webhook/webhook_test.go
- Max limit enforcement on the incoming webhook request. 
- Currently, we are enforcing the source transformation responses we get from the transformer if there is some Output present. 
- We might overwhelm the transformers if we don't enforce the incoming webhook request.
- Resolves PIPE-1382
=> chore: enforce max limit for webhook

go.mod
replace gocql/gocql with scylladb/gocql in go.mod to fix lint and import issue for intelij users
-
=> fix: replace gocql/gocql with scylladb/gocql in go.mod

services/fileuploader/fileuploader.go, services/fileuploader/fileuploader_test.go
Draft PR used for demo only.
With this approach we can preserve the current behaviour that we have on `master` of blocking until initialized.
Just a demo.
=> chore: channels instead of atomic

CHANGELOG.md
Syncing release v1.31.0 to main branch
chore: update sync-release action to run on all release prs (#4967)
chore(deps): bump the go-deps group across 1 directory with 9 updates (#4970)
fix: vaccum handling in error detail reports table (#4945)
=> chore: merge release 1.31.0 in main branch

enterprise/reporting/flusher/flusher.go
vacuum tracked_users_reports table
https://linear.app/rudderstack/issue/PIPE-1360/vacuum-handling-for-mtu-tables
=> chore: vacuum tracked_users_reports table

router/batchrouter/handle_observability.go
We use different destination label keys for `event_delivery_time` metric for different modules, for router and warehouse we are using `destID` and for batch_router we are using `destinationId`. 
Changing destination id label for batch_router module to be consistent with other modules.
Resolves OBS-586
https://linear.app/rudderstack/issue/OBS-586/update-labels-in-event-delivery-time-metric
=> chore: update destination id label to be consistent with other modules

enterprise/trackedusers/users_reporter.go, enterprise/trackedusers/users_reporter_test.go, integration_test/trackedusersreporting/tracked_users_reporting_test.go
store anonymous ids in userID hll to optimise storage and memory
https://linear.app/rudderstack/issue/PIPE-1384/add-anonymous-ids-in-userid-column
=> chore: store anonymous ids in userID hll to optimise storage

processor/transformer/transformer.go, processor/transformer/transformer_test.go
limit max retry interval for transformer
ref: https://rudderlabs.slack.com/archives/C01HTT66UMB/p1723483841421519
=> chore: limit max retry interval for transformer

warehouse/router/upload_stats.go
Adding sourceCategory label in event_delivery_time metric.
https://linear.app/rudderstack/issue/OBS-600/add-sourcecategory-label-for-warehouse-latency-metric
=> chore: add sourceCategory label in event_delivery_time metric

runner/buckets.go, warehouse/router/upload.go, warehouse/schema/schema.go, warehouse/schema/schema_test.go
- Stats for schema size. This will help us understand how often we are making calls to the warehouse JobsDB and the size distribution.
- This will help us understand the Postgres OOM issues with `expressvpn`. [Thread](https://rudderlabs.slack.com/archives/C02HCFVJVAR/p1719536279602979).
- Resolves PIPE-1456
=> feat: stats for schema size

processor/processor.go, processor/processor_test.go
take tacking plan id from dgsourceTPconfig instead of context.ruddertyper config
[DAT-1551](https://linear.app/rudderstack/issue/DAT-1551/typer-rudder-server-take-tacking-plan-id-from-dgsourcetpconfig-instead)
=> fix: take tacking plan id from dgsourceTPconfig

go.mod, go.sum
Update rudder-transformer module to get latest test-cases.
https://linear.app/rudderstack/issue/PIPE-1484/update-webhook-test-cases-in-rudder-server
Resolves PIPE-1484
=> chore: update webhook test cases

processor/transformer/transformer.go, processor/transformer/transformer_test.go
* Include transformationId on tags
* Use proper names for existing tags, keeping previous name for compatibility
https://linear.app/rudderstack/issue/PIPE-1486/include-transformationid-in-transformer-cli-observability
Resolves PIPE-1486
=> chore: include transformationId in transformer client metrics

gateway/webhook/integration_test.go, gateway/webhook/webhook.go, gateway/webhook/webhook_test.go, go.mod, go.sum
The webhook headers feature was added in release 1.33 but it is causing issues for SendGrid webhooks as they are sending the request body as a JSON array so we are reverting the change and we will revisit the logic later
https://linear.app/rudderstack/issue/INT-2504/webhook-source-deckers-has-requested-the-ability-to-forward-the-x-dash
=> fix: revert support for webhook headers

warehouse/integrations/datalake/testdata/docker-compose.spark.yml
- Getting some flakiness around the Spark tests where the `hive-metastore` server is not up. I added a dependency for the spark-master to have the `hive-metastore` server up first.
- https://github.com/rudderlabs/rudder-server/actions/runs/10775819984/job/29883355740
```
datalake_test.go:717: compose library exec: docker exec: output: Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/09/09 15:42:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/09/09 15:42:23 WARN metastore: Failed to connect to the MetaStore Server...
24/09/09 15:42:24 WARN metastore: Failed to connect to the MetaStore Server...
24/09/09 15:42:25 WARN …
```
=> fix: datalake spark flaky test

services/dedup/badger/badger.go, services/dedup/badger/badger_test.go
When transitioning a newly created rudder-server instance that has received no traffic from normal to degraded mode, the process hangs. Causing migration to stuck as well, until instance is restarted, upon restart no transition is required, as rudder-server starts on degrade mode.
Taking a goroutine dump:
```
goroutine 786 [chan receive, 3 minutes]:
github.com/rudderlabs/rudder-server/services/dedup/badger.(*BadgerDB).Close(...)
/rudder-server/services/dedup/badger/badger.go:118
github.com/rudderlabs/rudder-server/services/dedup/badger.(*Dedup).Close(0x0?)
/rudder-server/services/dedup/badger/badger.go:230 +0x38
github.com/rudderlabs/rudder-server/processor.(*Handle).Shutdown(0x4001b08008)
/rudder-server/processor/processor.go:766 +0x50 …
```
=> fix: prevent badgerdb hang when closing without prior operations

router/batchrouter/asyncdestinationmanager/bing-ads/audience/bingads_test.go, router/batchrouter/asyncdestinationmanager/bing-ads/audience/bulk_uploader.go, router/batchrouter/asyncdestinationmanager/bing-ads/audience/manager.go, router/batchrouter/asyncdestinationmanager/bing-ads/audience/types.go, router/batchrouter/asyncdestinationmanager/bing-ads/audience/util.go, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bingads_test.go, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bulk_uploader.go, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/manager.go, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/types.go, router/batchrouter/asyncdestinationmanager/eloqua/bulk_uploader.go, router/batchrouter/asyncdestinationmanager/eloqua/eloqua_test.go, router/batchrouter/asyncdestinationmanager/eloqua/manager.go, router/batchrouter/asyncdestinationmanager/eloqua/types.go, router/batchrouter/asyncdestinationmanager/klaviyobulkupload/klaviyobulkupload.go, router/batchrouter/asyncdestinationmanager/klaviyobulkupload/klaviyobulkupload_test.go, router/batchrouter/asyncdestinationmanager/klaviyobulkupload/types.go, router/batchrouter/asyncdestinationmanager/lytics_bulk_upload/lyticsBulkUpload.go, router/batchrouter/asyncdestinationmanager/lytics_bulk_upload/lytics_test.go, router/batchrouter/asyncdestinationmanager/lytics_bulk_upload/manager.go, router/batchrouter/asyncdestinationmanager/lytics_bulk_upload/types.go, router/batchrouter/asyncdestinationmanager/lytics_bulk_upload/utils.go, router/batchrouter/asyncdestinationmanager/manager.go, router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/marketobulkupload.go, router/batchrouter/asyncdestinationmanager/sftp/manager.go, router/batchrouter/asyncdestinationmanager/sftp/sftp_test.go, router/batchrouter/asyncdestinationmanager/sftp/types.go, router/batchrouter/asyncdestinationmanager/yandexmetrica/yandexmetrica.go, router/batchrouter/asyncdestinationmanager/yandexmetrica/yandexmetrica_test.go, router/batchrouter/handle_lifecycle.go
- Passing dependency for config, logger and stats instead of global default for `asyncdestinationmanager` package.
- It's a preliminary PR for the changes I am making around `snowpipe streaming` in `asyncdestinationmanager`.
- Resolves PIPE-1511
=> chore: passing dependency for asyncdestinationmanager

warehouse/router/tracker.go, warehouse/router/tracker_test.go
counter resetting on restarts was causing [false alerts](https://www.notion.so/rudderstacks/warehouse-cron-tracker-stuck-cfb91cfa9f45431ca9ed8f22415129d9). As the operation being tracked (cron tracker execution) doesn't happen often, using epoch gauge metric will help. 
part of PIPE-1514
=> fix: replace counter with gauge cron tracker alert

services/dedup/scylla/scylla.go
Add support to pass `Scylla.Hosts` as a slice
Fixes PIPE-1536
=> chore: make scylla hosts as slice

router/handle_lifecycle.go, warehouse/integrations/datalake/datalake_test.go
Each router handle stored the connections for all destinations, even those of which were not of the same destType!
It's now filtered so router handles only store connection details of destinations of the same destType.
[Resolves PIPE-1540](https://linear.app/rudderstack/issue/PIPE-1540/shared-backend-config-across-router-instances)
=> fix: each router handle stores the entire connections map

.github/workflows/tests.yaml, integration_test/warehouse/testdata/docker-compose.ssh-server.yml, jobsdb/jobsdb.go, warehouse/integrations/azure-synapse/azure_synapse_test.go, warehouse/integrations/azure-synapse/testdata/docker-compose.yml, warehouse/integrations/mssql/mssql_test.go, warehouse/integrations/mssql/testdata/docker-compose.yml, warehouse/integrations/postgres/testdata/docker-compose.ssh-server.yml, warehouse/integrations/testdata/docker-compose.jobsdb.yml, warehouse/integrations/testdata/docker-compose.minio.yml, warehouse/integrations/tunnelling/testdata/docker-compose.yml
1. Set maxIdleConns for all the jobsdb handles.
The current default is only 2 max idle conns per pool which causes a lot of turnaround and consistent new connections. Setting it to the same as max open connections.
2. Emit periodic (*sql.DB).Stats(). that gauge the total closed(due to maxIdleConns) every 15 seconds(configurable).
3. Add tablePrefix to the jobsdb connection pool's application_name.
=> chore: set maxIdleConns for jobsdb handles and emit (*sql.DB).Stats

config/config.yaml, enterprise/reporting/reporting.go, utils/types/reporting_types.go
Trimming eventName being sent to reporting if length exceeds 50 characters
Completes OBS-670
=> chore: trim eventNames sent to reporting if length exceeds 50 characters

app/apphandlers/embeddedAppHandler.go, enterprise/reporting/error_reporting.go, enterprise/reporting/flusher/flusher.go, enterprise/reporting/reporting.go
1. Using `vacuum` instead of `vacuum full` for various reports tables. This only takes lenient locking and doesn't disrupt other reads/writes to the tables. And while it doesn't free up disk space, it makes the space available for newer tuples added to the table.
2. Full vacuum on startup
3. vacuum threshold based on number of deleted rows.
Having done all this, the table size might still grow, but not at the rate when there was no vacuum at all. Each server startup would help free up disk space.
[Resolves PIPE-1517](https://linear.app/rudderstack/issue/PIPE-1549/remove-full-vacuum)
=> chore: no full vacuum for various reports tables

services/validators/envValidator.go
No component name for env validator so that `kill-dangling-queries` query filters correctly.
Earlier query was for `kill where APPLICATION_NAME LIKE '%env-validator-<rudder-server-host-name>`.
Now it becomes `kill where APPLICATION_NAME LIKE '%-<rudder-server-host-name>`. This kills all connections/transactions from previous host.
=> fix: wrong filtering while killing dangling connections

services/notifier/repo.go, warehouse/internal/loadfiles/loadfiles.go
PrizePicks CFD
- Reduce the number of config backend API calls being made for a single revisionId
- `VACUUM FULL` notifier table if the size exceeds 5GB
Fixes PIPE-1583
=> chore: optimise config backend revisionId calls

enterprise/reporting/error_index/error_index_reporting.go, enterprise/reporting/error_reporting.go, enterprise/reporting/flusher/factory.go, enterprise/trackedusers/users_reporter.go
remove panic on NewDatabaseSQLStats Register from various reports
=> chore: remove panic on NewDatabaseSQLStats Register from various reports

router/worker.go
Replace the check for validating an rETL event from comparing sourceJobRunId(which can also appear in a replay) to sourceCategory
Fixes PIPE-1606
=> fix: change retl check to source category

warehouse/integrations/bigquery/bigquery.go, warehouse/integrations/bigquery/bigquery_test.go
- BQ validations for partition column and type.
- Resolves PIPE-1608
=> fix: bigquery validations for partition column and type

CHANGELOG.md, router/worker.go, warehouse/integrations/bigquery/bigquery.go, warehouse/integrations/bigquery/bigquery_test.go
Syncing patch release v1.35.2 to main branch
fix: change retl check to source category (#5167)
fix: bigquery validations for partition column and type (#5168)
=> chore: sync release v1.35.2 to main branch

processor/transformer/transformer.go
sourceID and originalSourceID not flipped before transformation.
=> fix: sourceID and originalSourceID not flipped before transformation

warehouse/integrations/clickhouse/clickhouse.go
- Since we are already calling `misc.RemoveFilePaths` around `LoadFileDownloader.Download`, we don't need to call it again.
=> fix: clickhouse temporary files deletion happening twice

jobsdb/admin.go, jobsdb/jobsdb.go, jobsdb/jobsdb_test.go
Remove the cleanup loop from jobsdb, because it's not "air-tight"(Doesn't enforce a proper abort for a job).
Also it isn't triggered in many production instances because it triggers once every 24 hours
and more often than not - servers restart within that duration anyway.
So considering these two facts, it's prudent to perform cleanup once at startup and not worry about it later on.
We should also take a look at consumers and have them perform some operation in the off chance that a server were to live for longer durations(days) and jobs are no longer of interest to them.
[Resolves PIPE-1619](https://linear.app/rudderstack/issue/PIPE-1619/clean-up-invalid-jobs)
=> chore: cleanup old jobs(beyond maxAge) at startup

services/debugger/destination/eventDeliveryStatusUploader.go, services/debugger/destination/eventDeliveryStatusUploader_test.go, services/debugger/source/eventUploader.go, services/debugger/source/eventUploader_test.go, services/debugger/transformation/transformationStatusUploader.go, services/debugger/transformation/transformationStatusUploader_test.go, services/debugger/uploader.go, services/debugger/uploader_test.go
Set hosted secret as auth instead of workspace token. We can also validate with hosted secret. More info [here](https://github.com/rudderlabs/rudder-config-backend/blob/f83d9f7e7651ee536d7117f373fa6f8b3b956aa5/src/controllers/dataPlane.controller.ts#L40-L53)
Fixes PIPE-1571
=> fix: set hosted secret as auth instead of workspace token

jobsdb/jobsdb.go, jobsdb/jobsdb_test.go
Missed teardown in one of the tests. That was causing jobsdb test suite to fail. This fixes that.
[Resolves PIPE-1619](https://linear.app/rudderstack/issue/PIPE-1619/clean-up-invalid-jobs)
=> chore: jobsdb flaky test

services/dedup/badger/badger.go
According to badger documentation:
`func (db *badger.DB) NewTransaction(update bool) *badger.Txn`
```
NewTransaction creates a new transaction.
Badger supports concurrent execution of transactions,
providing serializable snapshot isolation, avoiding write skews.
Badger achieves this by tracking the keys read and at Commit time,
ensuring that these read keys weren't concurrently modified by another transaction.
For read-only transactions, set update to false.
In this mode, we don't track the rows read for any changes.
Thus, any long running iterations done in this mode wouldn't pay this overhead.
Running transactions concurrently is OK.
However, a transaction itself isn't thread safe, and should only be run serially.
It doesn't matter if a transaction is created by one goroutine and passed …
```
=> fix: discard badger transactions

utils/misc/dbutils.go, utils/misc/dbutils_test.go
Due to early ticker stop, the common db pool config couldn't hot-reload.
=> fix: common db pool config wasn't reloadable

CHANGELOG.md
Syncing release v1.37.0 to main branch
chore(deps): bump the go-deps group across 1 directory with 2 updates (#5240)
=> chore: sync release v1.37.0 to main branch

router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/utils_test.go
This PR address the flaky marketo utils unit tests, where headers are compared which are written in csv and output from the function.
=> fix: address flaky marketo test

router/batchrouter/asyncdestinationmanager/marketo-bulk-upload/apiService.go
The issue is due to incorrect csv response from marketo, hence rather than reading all rows at once we are reading each row separately. 
For the erroneous rows we cannot identify which particular job as we cant generate hash to get corresponding job id hence these specific ones will be marked as success (we need to figure out a long term solution for this though)
=> fix: parse error due incrorrect csv response from marketo-n

enterprise/reporting/reporting.go
We are currently ignoring 4XX errors from reporting service (for example due to payload too large or invalid sourceDefinitionId value). This result in reports being silently dropped without generating any alert. 
By treating 4XX as failure, we ensure that reports are retired, allowing us to detect and receive alerts for high 4XX rates or report backlogs.
https://linear.app/rudderstack/issue/OBS-711/fix-silent-ignore-of-400-errors-in-reporting-service
=> fix: silent ignore of 4xx errors from reporting

mocks/services/dedup/mock_dedup.go, processor/processor.go, processor/processor_test.go, services/dedup/badger/badger.go, services/dedup/badger/badger_test.go, services/dedup/dedup.go, services/dedup/dedup_test.go, services/dedup/mirrorBadger/mirrorBadger.go, services/dedup/mirrorBadger/mirrorBadger_test.go, services/dedup/mirrorScylla/mirrorScylla.go, services/dedup/mirrorScylla/mirrorScylla_test.go, services/dedup/scylla/scylla.go, services/dedup/scylla/scylla_test.go, services/dedup/types/types.go
This PR aims to 
- Get rid of the fields timestamp and size field in scylla table
- Change the contract to remove the size field from dedup interface
- Minor fixes in processor
Fixes PIPE-1700
=> chore: remove unused columns from scylla

Dockerfile, go.mod, suppression-backup-service/Dockerfile
Upgrade to Go1.23.3, to address fatal crash observe in production.
https://github.com/golang/go/issues/69882
https://linear.app/rudderstack/issue/PIPE-1723/fix-fatal-error-too-many-concurrent-timer-firings
resolves PIPE-1723
=> fix: too many concurrent timer firings

warehouse/integrations/bigquery/bigquery_test.go, warehouse/integrations/bigquery/partition.go, warehouse/integrations/bigquery/partition_test.go
- BQ partitioning is used for additional columns like `sent_at`, `timestamp`, and `original_timestamp`.
- Resolves PIPE-1731
=> fix: bq partitioning for additional columns

utils/timeutil/timeutil.go, warehouse/router/scheduling_test.go
Fix exclude window handling for single-digit minute values
=> fix: exclude window feature for single-digit minute values (#5266)

router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bingads_test.go, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bulk_uploader.go
With this pr, we are trying to remove the discrepancy between server and integrations-info.
INT-2916
https://linear.app/rudderstack/issue/INT-2916/bing-ads-conversion-seems-like-the-bing-api-expects
=> fix: bing ads audience

router/batchrouter/asyncdestinationmanager/klaviyobulkupload/apiService.go, router/batchrouter/asyncdestinationmanager/klaviyobulkupload/klaviyobulkupload.go, router/batchrouter/handle_lifecycle.go
Allow only enabled destinations to be iterated in backendSubscriber.
Update Klaviyo bulk upload error handling
Resolves INT-2820
=> fix: allow only enabled dest in backendSubscriber, fix klaviyo bulk

enterprise/reporting/error_reporting.go, enterprise/reporting/reporting.go
- Added flag for conditionally running vacuuming for reporting and error reporting at startup.
Ref PIPE-1748
=> fix: disable vacuum at startup for reporting

enterprise/reporting/error_extractor.go, enterprise/reporting/error_reporting.go, enterprise/reporting/reporting.go, enterprise/reporting/reporting_test.go, processor/processor.go, processor/processor_test.go, processor/trackingplan.go, processor/transformer/transformer.go, router/batchrouter/handle.go, router/batchrouter/handle_async.go, router/handle.go, router/transformer/transformer.go, router/types.go, router/types/types.go, router/worker.go, utils/types/reporting_types.go
Propagate statTags from transformer response to reporting.
Address sonar issues of too many function params and reduced code complexity
https://linear.app/rudderstack/issue/INT-2973/[chore]-propagate-error-category-from-stattags-of-transformer
Resolves INT-2973
=> refactor: error reporting to drive category from stats

enterprise/reporting/flusher/flusher.go
Removes full vacuum at flusher startup.
=> chore: remove full vacuum at flusher startup

warehouse/internal/repo/staging.go, warehouse/internal/repo/staging_test.go, warehouse/router/router.go, warehouse/router/state_generate_load_files.go, warehouse/router/testdata/sql/upload_test.sql, warehouse/router/upload.go, warehouse/router/upload_stats.go, warehouse/router/upload_stats_test.go
Since `wh_staging_files` has a `upload_id,` we can use that to find associated staging files. We don't need additional filters for `source_id` and `destination_id`.
- Resolves WAR-103
=> chore: cleanup staging repo to use upload_id for queries

router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming_test.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/types.go
- Caching polling response so that if we go to an in-progress state and the poll is later called again, we don't need to make the API calls again for the ones that have reached the terminal offset.
- Resolves PIPE-1780
=> chore: poll caching for snowpipe streaming

sql/migrations/warehouse/000026_drop_wh_upload_id_column.up.sql, warehouse/api/http_test.go, warehouse/bcm/testdata/sql/namespace_test.sql, warehouse/internal/model/schema.go, warehouse/internal/repo/schema.go, warehouse/internal/repo/schema_test.go, warehouse/router/state_export_data.go, warehouse/router/upload.go, warehouse/schema/schema.go, warehouse/schema/schema_test.go
Removes unused wh_upload_id from wh_schema table
Fixes WAR-102
=> chore: drop upload id from wh_schema

router/batchrouter/asyncdestinationmanager/snowpipestreaming/apiadapter.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/channel.go
- Since we are now handling errors during Polling (earlier we used to mark it as aborted instead of marking it as failed), We can call `AddColumns` with all the necessary columns. 
- In case some columns already exist (maybe another instead added them), we will get an error and will mark these jobs as a failure. They will be picked up again.
- Resolves WAR-115
=> fix: bulk add columns

enterprise/reporting/reporting.go
For warehouse module sample event will always be empty, we need to update the FILTER on ARRAY_AGG in reporting reports aggregation query to select samples response even if sample event is empty. 
Resolves OBS-732
[OBS-732: Fix reports aggregation query on rudder-server to handle empty sample event](https://linear.app/rudderstack/issue/OBS-732/fix-reports-aggregation-query-on-rudder-server-to-handle-empty-sample)
=> fix: reports aggregation query to select sample_event and sample_response correctly

warehouse/router/router.go
- There is a race condition happening, when the upload job is getting picked up, at the same time while trying to create new jobs, we are checking if there are some waiting jobs present. If present, we are deleting those.
- Resolves WAR-123
=> fix: processing pickup race condition

.github/workflows/verify.yml, Dockerfile, gateway/handle.go, go.mod, go.sum, suppression-backup-service/Dockerfile
add error msg in the logs when gw req fails
https://linear.app/rudderstack/issue/PIPE-1797/better-error-logging-for-ingestion-requests
=> chore: add error msg in the logs when gw req fails

processor/trackingplan.go
This PR is to fix the issue in the replay flow for connections with tracking plan . We were generating the commonMetaData from the input struct and were also altering the metadata before the transformer call while the commonMetaData was generated post the transformer call resulting in incorrect metadata propogated downstream. This PR fixes this by generating the commonMetaData before the transformer call 
Fixes PIPE-1813
=> fix: replay tracking plan bug

services/oauth/v2/common/constants.go, services/oauth/v2/oauth.go, services/oauth/v2/oauth_test.go
There is a new error being thrown from config-backend's `/token` endpoint, when the response from downstream service is not valid(i.e, refresh has not happened). We are trying to understand the response and respond correctly.
When config-backend returns `INVALID_REFRESH_RESPONSE` error, we would `retry` the event with appropriate error message
Resolves INT-2963
=> fix: invalid error response handling during oauth refresh flow

router/batchrouter/asyncdestinationmanager/snowpipestreaming/channel.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming_test.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/testdata/successful_user_records.txt, router/batchrouter/asyncdestinationmanager/snowpipestreaming/types.go, warehouse/integrations/manager/manager.go
This PR introduces a backoff mechanism when creating channels in the Snowpipe streaming destination. If an authorization error is encountered at the schema, table, or column level, the backoff ensures that we avoid repeatedly attempting to connect to Snowflake unnecessarily.
- Added a new struct `backoff` in manager to store backoff related state
- Refactoring: Added `managerCreator` as a field in the manager for making the code testable.
- Until now, any error encountered while creating the channel for the discards table resulted in the job being marked as aborted. In this PR, the behavior has been updated to mark the job as failed, allowing it to be retried.
- Backoff is applied whenever an authorization error is encountered.
- Backoff is being cleared whenver channels for all the …
=> feat: implement backoff for snowpipe streaming authorization errors

warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/deltalake/deltalake_test.go
- There seems to be a bug that got introduced in [this](https://github.com/rudderlabs/rudder-server/pull/5001) PR. 
```GO
func (d *Deltalake) tableLocationQuery(tableName string) string {
enableExternalLocation := warehouseutils.GetConfigValueBoolString(configKeyEnableExternalLocation, d.Warehouse)
externalLocation := warehouseutils.GetConfigValue(configKeyExternalLocation, d.Warehouse)
if enableExternalLocation != "true" || externalLocation == "" {
return ""
}
return fmt.Sprintf("LOCATION '%s/%s/%s'", externalLocation, d.Namespace, tableName)
}
```
Got converted to 
```GO
func (d *Deltalake) tableLocationQuery(tableName string) string {
enableExternalLocation := d.Warehouse.GetBoolDestinationConfig(model.EnableExternalLocationSetting)
externalLocation := …
```
=> fix: databricks external location

router/batchrouter/asyncdestinationmanager/klaviyobulkupload/klaviyobulkupload.go, router/batchrouter/asyncdestinationmanager/klaviyobulkupload/klaviyobulkupload_test.go, router/batchrouter/handle_async.go, router/batchrouter/handle_async_test.go
Polling errors were not being set with a proper status code in Klaviyo Bulk Upload. This is rectified here
Resolves INT-3076
=> fix: add missing statuscode for poll call, update error string

processor/transformer/transformer.go, processor/transformer/transformer_test.go
This pull request aims to enhance the efficiency of the User Transformation (UT) payload by eliminating unnecessary fields, thereby improving performance by reducing payload size.
Changes Introduced:
Field Removal: Unused or redundant fields have been identified and removed from the UT payload structure.
In the image shown above the blue line represent the latency for a User Transformation with master and the yellow line represent the latency with the changes made in this PR. This change leads to 10-15% reduction in latency
Fixes PIPE-1845
=> feat: remove unnecessary fields from UT payload

warehouse/router/upload.go, warehouse/router/upload_test.go, warehouse/schema/schema.go, warehouse/schema/schema_test.go
Refactoring
- Replaced the Schema struct with the SchemaHandler interface, ensuring that clients depend on the interface rather than the concrete implementation. This change will enable switching to a different schema implementation via a feature flag.
- `Schema` -> `schema`
resolves WAR-150
=> refactor: replace schema struct with interface to enable flexible implementation

processor/transformer/transformer.go, router/transformer/transformer.go
This commit aims to allow logging of 404 errors in the processor while communicating with transformer to trigger log based alerts (loki)
Transformer can respond with 404 errors if the destination is not available in the transformer image but the config-backend has the destination.
This can only happend when some outdated transformer image is used in the deployment. In order to catch such errors and immediately alert (throw loki-log based triggers) the team to make a fix, we aim to log 404 errors and add alerts for those errors.
The below ticket is attached with corresponding alert PR in devops as well.
Resolves INT-3031
https://linear.app/rudderstack/issue/INT-3031/revisit-transformer-and-rudder-server-api-contracts-and-throw-alerts
=> chore: transformer 404 error logs

jobsdb/migration.go
Wrong count calculated as part of migration check that happens every 30 seconds.
We fetch counts of terminal statuses in the status table, but since at startup we "cleanup" old jobs just by appending another aborted status irrespective of it's state, that above query can count more than one terminal status per job.
Understandably while actually migrating the jobs, we see that more jobs than we expect have been moved because we were expecting a lesser number.
This issue happened now because archival tables have a default retention of 24 hours. so on successive restarts, more and more statuses were being appended for the same job. And we expect the following expression number of jobs to be migrated: 
```
numExpectedNumberOfMigratedJobs(e) = number of jobs(a) - number of terminal statuses in …
```
=> fix: wrong terminal counts calculated during migration check

warehouse/integrations/bigquery/bigquery.go, warehouse/integrations/bigquery/bigquery_test.go, warehouse/utils/utils.go, warehouse/utils/utils_test.go
- BQ load using folder pattern instead of providing all file locations.
- Added loadByFolderPath configuration, by default it's false.
- Resolves WAR-179, WAR-216
=> feat: bq load using folder

runner/buckets.go
add custom bucket for throttling metric
-
=> chore: add custom bucket for throttling metric

enterprise/reporting/error_reporting.go, enterprise/reporting/reporting.go, enterprise/reporting/util_test.go, enterprise/reporting/utils.go
In Reporting Report function, we are modifying the metric object by removing sample event and sample response when  event sampling is enabled. This same metrics is used by error reporting since metric is being passed as pointer. 
Because of this, error reporting will not get all samples. So, we should transform the metric in any reporter.
Completes OBS-763
=> fix: report modification in reporting during event sampling

warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/deltalake/deltalake_test.go
**Issue**
Deltalake syncs were failing when processing events containing a field of type `DECIMAL(38,0)`, which was not handled by the warehouse code.
- For unhandled data types, the column is skipped in the local table schema. So when a mismatch was detected between the local table schema and event schema, warehouse attempted to add the missing columns in the table. The column addition failed because the column already existed.
- This is a regression introduced from changes in #5322 
- This issue doesn't affect other warehouses since their `AddColumns` method handles already existing columns.
**Fix**
To resolve this, we now retrieve all existing columns of the table before adding new ones. Columns that are already present are skipped, preventing the failure.
=> fix: deltalake syncs failing for columns with unhandled data type

sql/migrations/warehouse/000027_drop_wh_schema_versions_table.up.sql
This PR adds a migration to get rid of `wh_schema_versions` table which is not being used anymore
=> chore: migration to drop unused wh_schema_versions table

warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/deltalake/deltalake_test.go
(cherry picked from commit 6e69bd93eae05c6dddb6ca65d33e7a6510807fdd)
#5467
=> fix: deltalake syncs failing for columns with unhandled data type (#5467)

CHANGELOG.md
Syncing release v1.42.0 to main branch
fix: deltalake syncs failing for columns with unhandled data type (#5467)
chore: migration to drop unused wh_schema_versions table (#5469)
=> chore: sync release v1.42.0 to main branch

router/batchrouter/asyncdestinationmanager/snowpipestreaming/channel.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming_test.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/types.go
- Snowpipe streaming error enrichment for failed events. Earlier we were just logging the errors, now we are sending some sample error.
- Resolves WAR-244
- [] The code changed/added as part of this pull request won't create any security issues with how the software is being used.
=> fix: snowpipe streaming error enrichment for failed events

internal/transformer-client/client.go, processor/transformer/transformer.go, router/transformer/transformer.go
Configurable http Client(`Doer`) in processor, rt transformers. Doesn't include `oauth` clients in rt transform at this point.
On top of #5451
=> chore: configurable transformer http client in processor, router

gateway/gateway_test.go, gateway/handle.go, gateway/internal/stats/stats.go
We iterate on the jobs and for each job we increase the events by 1 like this:
```
for _, jws := range jobsWithStats {
jws.stat.RequestEventsSucceeded(1)
```
The problem is that, whenever you call RequestEventsSucceeded it is also increasing the requests:
```
func (ss *SourceStat) RequestEventsSucceeded(num int) {
ss.events.succeeded += num
ss.events.total += num
ss.requests.total++
ss.requests.succeeded++
}
```
So we should increment events and requests separately. there are some tags like sourceID which are required for events but do not makes sense for internalBatch request. So introducing new methods `EventsSuccess` `EventsFailed` to increment events and requests separately.
-
=> chore: fix gateway metrics

warehouse/integrations/deltalake/deltalake.go, warehouse/integrations/deltalake/deltalake_test.go
- Databricks columns to add become empty after filtering.
- Resolves WAR-268
=> fix: databricks columns to add becomes empty after filtering

router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming_test.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/types.go, warehouse/internal/model/validation.go, warehouse/validations/steps.go, warehouse/validations/steps_test.go, warehouse/validations/validate.go
[Context](https://linear.app/rudderstack/issue/WAR-240/short-term-solution-for-validation-errors-in-sync-errors-for-snowpipe#comment-150d9d94)
Implementation
- Made changes in `StepsToValidate` method to return relevant steps for Snowpipe destination
- Moved `DestinationValidationResponse` struct from `internal/model` package to `validations` package so that it can be accessed in `snowpipestreaming` package
- Added a `validator` field in snowpipe's `Manager` struct which is responsible for validating the destination config
- Made changes in `Upload` function to call the validator whenever there is an authorization error. And if the response is not successful, the error is being returned.
=> feat: implement snowpipe destination config validation

processor/transformer/transformer.go, processor/transformer/transformer_test.go
Added the following metrics:
```
transformer_client_request_total_bytes
transformer_client_response_total_bytes
transformer_client_request_total_events
transformer_client_response_total_events
transformer_client_total_durations_seconds
```
Adding `workspaceId` and `endpoint` as labels, to all metrics collected in transformer, we already track dest/source id so they won't increase cardinality.
Created `transformerMetricLabels` to pass around all the labels
Note: This PR covers processor, will create a similar PR for gateway/ingestion-svc and router
https://linear.app/rudderstack/issue/PRI-163/introduce-transformer-client-metrics-in-rudder-server-for-cost
resolves PRI-163
=> feat: introduce transformer metrics for cost attribution

router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bingads_test.go, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bulk_uploader.go
Updated validation check for `microsoftClickId`. Currently `microsoftClickId` is considered as required field. But when `email` or `phone` is present, it should be considered as optional.
Resolves INT-3288
https://linear.app/rudderstack/issue/INT-3288/error-importing-conversions-for-bing-without-click-id
=> feat: updated validation check for microsoftClickId in bingads_offline_conversions async destination

router/batchrouter/asyncdestinationmanager/snowpipestreaming/channel.go
If a Snowpipe destination is created with an invalid private key, the Snowpipe client returns an `ERR_VALIDATION_ERROR` code. Previously, this was handled in the default case, preventing it from being classified as an `Authz` error. As a result, neither backoff nor config validation occurred in the Upload function.
This PR fixes the issue by correctly identifying and returning this error as `Authz`.
- Added `ErrAuthenticationFailed` for invalid user name and `ErrRoleDoesNotExistOrNotAuthorized` for invalid role
=> fix: snowpipe backoff missing for validation error

jsonrs/json.go, jsonrs/switcher.go, jsonrs/switcher_test.go
The `Json.Library.Unmarshaller` configuration option was not respected and the unmarshaller was actually using `Json.Library.Marshaller` configuration option instead. This regression was introduced after refactoring, post benchmarking.
Added a scenario to verify correct behaviour
=> fix: unmarshaller json configuration not respected

warehouse/slave/worker.go, warehouse/slave/worker_test.go
- Problem with the existing code is [**Unsafe Quoting for Strings**](https://github.com/rudderlabs/rudder-server/security/code-scanning/171).  If value is a string that already contains quotes, special characters, or escape sequences, using `fmt.Sprintf` does not properly escape them.
- Using `strconv.Quote` for properly escaping it.
- Resolves WAR-315
=> fix: handle schema change for unsafe quotes

warehouse/integrations/datalake/datalake_test.go, warehouse/router/upload.go, warehouse/schema/schema.go, warehouse/schema/schema_v2.go, warehouse/schema/schema_v2_test.go
**BUG**: In the `getSchema` method of `schemaV2` if the schema is found to be expired, it calls the `FetchSchema` method of the corresponding warehouse. In case of datalake, it calls `GetLocalSchema` of the uploader which calls the `GetLocalSchema` of schema. This created an inifinte loop as `GetLocalSchema` again calls `getSchema`
**FIX**: Moved the logic of fetching schema from DB from `schema` to `uploader` and removed it from the `Handle` interface
=> fix: refreshing of datalake expired schemas causing inifinite loop

warehouse/router/state_export_data.go, warehouse/router/upload.go, warehouse/router/upload_test.go
- Skipping previously failed tables when retrying for failed syncs, we can set the failed syncs priority as lower so that it will not affect the real-time syncs. Failed syncs will get processed at a lower priority.
- Using this config, we will not skip the tables which failed for previous syncs. If we don't do it then the current sync will fail till the retry policy and will eventually get marked as aborted.
- In most retry cases, we usually go with the default priority as 100, which means the failed syncs will be processed first and then the real-time ones. But if the number of re-triggered syncs are too many it will take time and affect the real-time syncs.
- Resolves WAR-329.
=> chore: skip previously failed tables

router/batchrouter/asyncdestinationmanager/common/manager.go, router/batchrouter/handle_async.go, router/batchrouter/handle_async_test.go, router/batchrouter/handle_lifecycle.go
Async destinations are not providing clear errors when destination initialization is failing so customers are getting confused.
https://linear.app/rudderstack/issue/INT-3323/investigate-object-storage-configuration-errors-in-snowflake-to-eloqua
Resolves INT-3323/
=> fix: error handling for async destinations

docker-compose.yml, rudder-docker.yml
[Self-hosted Docker version](https://www.rudderstack.com/docs/get-started/rudderstack-open-source/data-plane-setup/docker/) of RudderStack sometimes may crash with the following stack trace:
```
rudderstack-backend-1  | 2025-02-03T10:17:00.400Z	ERROR	processor	processor/processor.go:3518	Failed to get unprocessed jobs from DB. Error: pq: could not resize shared memory segment "/PostgreSQL.1265551680" to 8388608 bytes: No space left on device
rudderstack-backend-1  | 2025-02-03T10:17:00.400Z	ERROR	runner.panic	crash/logger.go:33	Panic detected. Application will crash.	{"stack": "goroutine 1119 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/rudderlabs/rudder-server/utils/crash.(*panicLogger).Notify.func1.1()\n\t/rudder-server/utils/crash/lo …
```
=> feat: increase shm size for postgres in docker compose

integration_test/warehouse/warehouse_test.go, router/batchrouter/batchrouter_test.go, router/batchrouter/handle_lifecycle.go, warehouse/client/warehouse.go, warehouse/client/warehouse_test.go, warehouse/integrations/testhelper/staging.go
- Stats for warehouse process API. Once the stat is added, need to add an alert for non 2xx's response code.
- Resolves WAR-343
=> chore: add stats for warehouse process API

warehouse/integrations/azure-synapse/azure-synapse.go, warehouse/integrations/azure-synapse/azure_synapse_test.go, warehouse/integrations/azure-synapse/testdata/docker-compose.yml, warehouse/integrations/mssql/mssql.go, warehouse/integrations/mssql/mssql_test.go, warehouse/integrations/mssql/testdata/docker-compose.yml
- Enable integration tests for **MSSQL** and **Azure Synapse**. This was [disabled](https://github.com/rudderlabs/rudder-server/pull/5123/commits/5a310c62f714ceb07211bbcf814da4851e153ca9) a couple of months back because we had an issue with the existing [microsoft/azure-sql-edge](https://hub.docker.com/r/microsoft/azure-sql-edge) image. Also, Microsoft is planning to [retire](https://learn.microsoft.com/en-us/lifecycle/products/azure-sql-edge) this image around Sep 30, 2025.
- Using [mcr.microsoft.com/mssql/server:2022-latest](https://hub.docker.com/r/microsoft/mssql-server) instead.
- A small clean up around making fields unexported for `AzureSynapse` and `MSSQL` struct.
- Resolves WAR-365
=> chore: mssql and azure synapse cleanup and enable integration tests

app/apphandlers/embeddedAppHandler.go, jobsdb/bench/bench.go, jobsdb/bench/bench_test.go, jobsdb/bench/scenario/rate_limiter.go, jobsdb/bench/scenario/simple.go, jobsdb/bench/scenario/two_stage.go
Preparing two benchmarking scenarios for jobsdb which can be triggered when server is running in embedded mode.
These scenarios are supporting our benchmarking efforts documented [here](https://www.notion.so/rudderstacks/JobsDB-Benchmarking-Q1-2025-1a7f2b415dd0805f9b84c44758eb565f).
resolves PIPE-1920
=> chore(jobsdb): benchmarking scenarios

jobsdb/jobsdb.go, jobsdb/jobsdb_utils.go
We need finer granularity of jobsdb metrics when querying jobs, which can help us troubleshoot issues easier and gain some more insight about the system's behaviour:
- Adding parameter filters and moreToken as tags in existing metrics so that we can know what gets queried by each and every pipeline
- Adding a new metric for counting the times we query for jobs but get nothing back so that we can tell with confidence whether the pipeline is active or not
resolves PIPE-1953
=> chore(jobsdb): finer granularity metrics when querying jobs

jobsdb/internal/cache/cache.go, jobsdb/internal/cache/cache_internal_test.go, jobsdb/internal/cache/cache_test.go, jobsdb/jobsdb.go, processor/processor_isolation_test.go, router/router_isolation_test.go
- Inside jobsdb, `noResultsCache` uses its own concept of transactions for properly handling concurrent reads/writes and avoiding caching stale results.
- A `noResultsCache` transaction begins before a query against a dataset happens and this transaction gets committed if the query doesn't return any results. 
- Each transaction has an id and when the transaction begins, it marks all cache entries that it plans to mark as having no jobs by adding its id in the entries' list of **pending ids**.
- During commit, the entry will be updated as having no jobs, as long as the entry's list of pending ids still contains the transaction id, i.e. no write operation happened in the meantime which invalidated the entry.
- Each entry has a **bounded limit of 10** for the number of pending transaction …
=> fix(jobsdb): cache not getting updating after 10 consecutive uncommitted transactions

jobsdb/internal/cache/cache.go
We shouldn't be logging a warning when leaf nodes get invalidated
=> chore(jobsdb): leaf invalidations should be logged at debug level

jobsdb/jobsdb_utils.go
Avoiding unnecessary evaluation of `fmt.Sprintf` which is slow
```go
func BenchmarkCheckValidJobState(b *testing.B) {
jobStates := lo.Map(jobStates, func(s jobStateT, _ int) string { return s.State })
var a dummyAssert
b.Run("v1", func(b *testing.B) {
for i := 0; i < b.N; i++ {
checkValidJobStatev1(a, jobStates)
}
})
b.Run("v2", func(b *testing.B) {
for i := 0; i < b.N; i++ {
checkValidJobStatev2(a, jobStates)
}
})
}
```
```sh
goos: darwin
goarch: arm64
pkg: github.com/rudderlabs/rudder-server/jobsdb
cpu: Apple M1 Pro
BenchmarkCheckValidJobState2
BenchmarkCheckValidJobState2/v1
BenchmarkCheckValidJobState2/v1-10 	   90434	     13019 ns/op	    6613 B/op	     190 allocs/op
BenchmarkCheckValidJobState2/v2
BenchmarkCheckValidJobState2/v2-10 	 3285302	       371.2 ns/op	     336 B/op	       2 …
```
=> chore(jobsdb): improve checkValidJobState performance

enterprise/suppress-user/internal/badgerdb/badgerdb.go, jobsdb/jobsdb.go, processor/processor.go, router/batchrouter/handle.go, router/batchrouter/handle_async.go, router/config.go, router/handle.go, router/handle_lifecycle.go, router/internal/eventorder/eventorder.go, router/network.go, router/utils/utils.go, router/worker.go, services/rsources/rsources.go, warehouse/utils/utils.go
- using plain string concatenation instead of formatted strings for critical paths
- caching and using reloadable configuration variables instead of asking for the same variable again and again in critical paths
```sh
goos: darwin
goarch: arm64
pkg: github.com/rudderlabs/rudder-server/processor
cpu: Apple M1 Pro
BenchmarkSprintfvsConcat
BenchmarkSprintfvsConcat/Sprintf
BenchmarkSprintfvsConcat/Sprintf-10         	 2810226	       430.2 ns/op	     288 B/op	      10 allocs/op
BenchmarkSprintfvsConcat/Concat
BenchmarkSprintfvsConcat/Concat-10          	 9418416	       124.6 ns/op	     147 B/op	       2 allocs/op
```
```go
func BenchmarkSprintfvsConcat(b *testing.B) {
SourceID := "source_id"
DestinationID := "destination_id"
SourceJobRunID := "source_job_run_id"
TransformationID := …
```
=> chore: cpu performance improvements

router/handle.go, router/handle_lifecycle.go, router/router_test.go, router/types/types.go
`findWorkerSlot` cpu breakdown:
- 14% unmarshalling parameters for getting destination id
- 12% resolving `Router.orderingDisabledWorkspaceIDs` configuration option
- 12% resolving `Router.orderingDisabledDestinationIDs` configuration option
- 53% calling `drainOrRetryLimitReached` (addressing this in #5591 )
- 9% other
We are eliminating the time for the first 3 bullets by:
1. reading destination id only once and skipping unmarshalling
2. using cached reloadable configuration variables
resolves PIPE-1966
=> chore(router): finding worker slots efficiently

CHANGELOG.md
Syncing release v1.44.0 to main branch
chore: add pattern based matching for version deprecation errors (#5558)
chore(jobsdb): add metrics for job and payload throughput (#5568)
fix(jobsdb): clearDB option fails with error (#5570)
chore(jobsdb): benchmarking scenarios (#5571)
refactor: add columns in snowflake using IF NOT EXISTS (#5581)
chore(jobsdb): finer granularity metrics when querying jobs (#5582)
chore(jobsdb): optimize job status table indexes (#5584)
chore(jobsdb): leaf invalidations should be logged at debug level (#5589)
chore(jobsdb): improve checkValidJobState performance (#5590)
chore: warehouse …
=> chore: sync release v1.44.0 to main branch

warehouse/transformer/internal/utils/utils.go, warehouse/transformer/internal/utils/utils_test.go, warehouse/transformer/transformer_test.go
- Handle warehouse transformations for empty array and map. These should not be included in the response.
- This is what we see in the debug logs files.
```
types.TransformerResponse{
Output: map[string]any{
"data": map[string]any{
- 			"companies_data":        []any{},
- 			"notes_data":                               []any{},
- 			"opted_out_subscription_types_data":        []any{},
- 			"social_profiles_data": []any{},
- 			"tags_data":            []any{},
},
"metadata": map[string]any{
"columns": map[string]any{
- 				"companies_data":        string("string"),
- 				"notes_data":                               string("string"),
- 				"opted_out_subscription_types_data":        string("string"),
- 				"social_profiles_data": string("string"),
- 				"tags_data": …
```
=> fix: warehouse transformations for empty array and map

.golangci.yml, go.mod, go.sum, jsonrs/json.go, jsonrs/json_fuzz_test.go, jsonrs/sonnet.go
Issue raised against upstream repository: https://github.com/sugawarayuuta/sonnet/issues/14 
Until issues in upstream are resolved, we'll be using our own fork
Summary of issues:
- fast path for unmarshalling floats was unreliable, i.e. it could either panic or parse wrong float ([fix](https://github.com/rudderlabs/sonnet/commit/7713358c8f1700f017c9e68882df2ec380c303fa))
- issue in marshalling float32 numbers at the boundaries ([fix](https://github.com/rudderlabs/sonnet/commit/c6531aaf3eb5b9fab5e71909ef12720471f7093a))
Adding fuzzing scenarios for all json types, covering both libraries that we are using (`sonnet` & `jsoniter`) and verifying them against the reference `std` json library.
resolves PIPE-1972
=> fix: sonnet panic while unmarshalling float64 types

enterprise/reporting/error_extractor.go, enterprise/reporting/error_reporting_test.go
Version deprecation extraction uses regex and it consumes a lot of CPU so avoid it
https://linear.app/rudderstack/issue/INT-3339/linkedin-ads-version-deprecation
=> refactor: version deprecation detection avoid regex

warehouse/integrations/bigquery/bigquery.go, warehouse/integrations/bigquery/bigquery_test.go, warehouse/internal/model/settings.go
- Based on the new configuration (`skipViews`) added in [here](https://github.com/rudderlabs/rudder-integrations-config/pull/1948),  provide a way to skip the creation of views if the customer has opted for it.
- Decouple the user's table loading from the [logical view](https://cloud.google.com/bigquery/docs/views-intro), and use the actual query for merging the traits.
```GO
SELECT * EXCEPT (__row_number)
FROM (
SELECT *, ROW_NUMBER() OVER (
PARTITION BY id ORDER BY loaded_at DESC
) AS __row_number
FROM `big-query-integration-poc.achetty_dataset.product_trac`
WHERE _PARTITIONTIME BETWEEN TIMESTAMP_TRUNC(TIMESTAMP_MICROS(UNIX_MICROS(CURRENT_TIMESTAMP()) - 60 * 60 * 60 * 24 * 1000000), DAY, 'UTC')
AND TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY, 'UTC')
)
WHERE __row_number = 1;
```
- For …
=> feat: option for disabling view creation for bigquery

enterprise/reporting/error_extractor.go, enterprise/reporting/error_reporting_test.go
We are evaluating the combination of "API" and "invalid." This pairing generates excessive noise due to frequent errors such as "invalid API key." To reduce unnecessary alerts, we are removing this combination.
https://linear.app/rudderstack/issue/INT-3339/linkedin-ads-version-deprecation
=> refactor: version deprecation detection logic

go.mod, go.sum, utils/payload/limiter_setup.go
rss memory excludes active page cache memory, which can be reclaimable in our case, since badger db makes heavy use of mmap.
resolves PIPE-1989
=> chore: use rss for calculating used memory in adaptive payload limiter

.github/workflows/tests.yaml, jsonrs/json.go
Tests will only run once with the default json library, sonnet
=> chore: use sonnet as the default json library

app/apphandlers/embeddedAppHandler.go, app/apphandlers/gatewayAppHandler.go, app/apphandlers/processorAppHandler.go, archiver/archiver.go, archiver/archiver_test.go, archiver/worker.go, jobsdb/jobsdb.go
Archival jobsdb cache was keep getting invalidated, due to usage of incomplete job status (missing `workspaceID` & `jobParameters`) and query conditions (missing `customVal` filter). As such, a low dsLimit was causing the archiver worker to keep querying the same tables again and again, leading to table pileup.
Additional items:
- Using separate configuration options for each jobsdb's dsLimit
- Giving precedence to more sensible configuration option names, `JobsDB.<tableprefix>.dsLimit`
- Logging a warning whenever a full branch of arc jobsdb's cache is being invalidated
**Note:** for archival we should use a `dsLimit` closer to the value we are using for `batch_rt` (12), since we are picking 100K jobs on every loop.
resolves PIPE-1988
=> fix: increased archival table count alert firing after starting using dslimit

warehouse/transformer/events.go, warehouse/transformer/events_test.go, warehouse/transformer/logger.go, warehouse/transformer/options.go, warehouse/transformer/options_test.go, warehouse/transformer/transformer.go, warehouse/transformer/types.go
- Ordering for **JSON Paths** for `DATA_WAREHOUSE` should be first w.r.t the corresponding integration.
- https://github.com/rudderlabs/rudder-transformer/blob/3c20393a0e4e3ec98d316820d187310bfec1faea/src/warehouse/util.js#L155
- Resolves WAR-446
=> fix: warehouse transformations for data_warehouse json paths

warehouse/transformer/events_test.go, warehouse/transformer/transformer.go, warehouse/transformer/types.go
Some mandatory fields like `messageId` and `receivedAt` are sometimes missing or empty, where events are added during the user transformation stage. Since the rudder-server only guarantees these fields at the gateway level, they may be absent when events reach destination transformation.
This update ensures that:
-  `messageId` is assigned a unique value if missing.
-  `receivedAt` is validated and set appropriately, falling back to **event.Metadata.ReceivedAt** or the **current timestamp** if needed.
This follows the same approach as in [rudder-transformer](https://github.com/rudderlabs/rudder-transformer/blob/develop/src/warehouse/index.js#L675-L688).
- Resolves WAR-442
=> fix: warehouse transformations for mandatory fields

enterprise/reporting/event_sampler/badger_event_sampler.go, enterprise/reporting/event_sampler/event_sampler_test.go, services/dedup/badger/badger.go, services/dedup/badger/badger_test.go
- All badger db configuration options are now externally configurable
- Event Sampler
- Using `nil` values
- Using lower memory (5x1MB+10MB vs 5x64MB+16MB)
- Using smaller memory mapped base tables (200KB instead of 2MB)
- Using smaller level size (1MB vs 10MB)
- Using smaller memory mapped valuefiles since we are not using them (1MB vs 1GB)
- Dedup
- Using `nil` values
- Using lower memory (5x20MB+16MB vs 5x64MB+16MB)
- Using smaller memory mapped base tables (1MB instead of 2MB)
- Using smaller level size (5MB vs 10MB)
- Using smaller memory mapped valuefiles since we are not using them (1MB vs 1GB)
For both databases, if during startup we fail to open the database using the previous data, we are logging a warning, clearing the directory and starting badgerdb again.
resolves OBS-805
=> chore: badger configuration tuning

warehouse/transformer/datatype.go, warehouse/transformer/events_test.go, warehouse/transformer/internal/utils/utils.go, warehouse/transformer/internal/utils/utils_test.go, warehouse/transformer/set.go, warehouse/transformer/transformer.go
The [Tracking Plan properties](https://github.com/rudderlabs/rudder-server/blob/master/processor/trackingplan.go#L28-L51) in the Go code differ in type from the response received from `rudder-transformer`, causing a type mismatch:
- **`context_tracking_plan_version`**:  
- Unmarshalling response from `rudder-transformer` treats all numbers as `json.Number` (essentially `float64`).  
- Go code sets it as `int`.
- **`context_violation_errors`**:  
- Unmarshalling response from `rudder-transformer` returns it as `[]any`.  
- Go code sets it as `[]types.ValidationError`.
- This results in a type mismatch, though the actual data remains correct.
```GO
- 			"context_tracking_plan_version": int(8),
+ 			"context_tracking_plan_version": float64(8),
- 			"context_violation_errors": …
```
=> fix: warehouse transformations for tracking plans

.github/workflows/verify.yml, Makefile, enterprise/reporting/event_sampler/badger_event_sampler.go, services/dedup/badger/badger.go
Treating panic as error and deleting badgerdb folder for recovering
=> chore: recover from badgerdb panic

warehouse/transformer/datatype.go, warehouse/transformer/datatype_test.go, warehouse/transformer/internal/utils/utils_test.go, warehouse/transformer/transformer_benchmark_test.go, warehouse/transformer/transformer_test.go
- Avoid using refections instead use type inferring for warehouse transformations.
- Resolves WAR-454
=> chore: avoid using reflections for warehouse transformations

warehouse/integrations/snowflake/snowflake_test.go
- Use keypair instead of Password for Snowflake Integration Tests since Password based authentication Is getting deprecated.
- Removed `SNOWFLAKE_KEYPAIR_ENCRYPTED_INTEGRATION_TEST_CREDENTIALS` based test, as it is redundant now. We are by default using encrypted key pair credentials.
- Resolves WAR-471
=> chore: snowflake integrations tests to use keypair instead of password

processor/processor.go, router/handle.go, router/internal/jobiterator/jobiterator.go, router/internal/jobiterator/jobiterator_test.go
Router picks up 10K jobs during each loop. Whenever any job gets discarded due to throttling, even if it is the first one, router stops the iteration immediately and the next loop kicks in after <1sec, which will pick up again 10K jobs.
With all destinations being throttled at 1K/sec by default, router ends up querying 10K+ jobs/sec while it can only produce max 1K/sec. This excessive number of jobs that are being retrieved from the database, cause high read iops and affects all other database operations.
To alleviate this issue, whenever a job is discarded due to throttling in a router's pipeline, this pipeline will mark all pending jobs as discarded, effectively making the loop eligible for sleeping for `failingJobsPenaltySleep` seconds , relieving some of the read pressure from the …
=> fix(router): applying excessive read pressure to the database when jobs are being throttled

services/streammanager/kafka/kafkamanager.go
Kafka stream manager is used for `Azure Event Hub` and `Confluent Cloud` destinations. The problem is message batching directive(configured for Kafka) is applied across all three as well which can be a problem if batched messages cannot be accepted further down the pipeline. The same compression directive still applies to all three.
Resolves PIPE-1982
[Remove kafka batching on transformer and use client batching with a new config flag](https://linear.app/rudderstack/issue/PIPE-1982/remove-kafka-batching-on-transformer-and-use-client-batching-with-a)
=> fix: kafka message batching applies to Confluent Cloud and Azure Event Hub

warehouse/integrations/bigquery/bigquery_test.go, warehouse/router/identities.go, warehouse/router/state_create_schema.go, warehouse/router/state_export_data.go, warehouse/router/state_generate_load_files.go, warehouse/router/state_generate_upload_schema.go, warehouse/router/upload.go, warehouse/router/upload_test.go, warehouse/schema/schema.go, warehouse/schema/schema_test.go
**Updated the Handler interface in schema:**
- Removed `SyncRemoteSchema` and `FetchSchemaFromWarehouse` since schema sync is now driven by TTL instead of the caller.
- Removed the no-op `UpdateLocalSchemaWithWarehouse` method.
- Renamed methods to eliminate "local" and "warehouse" from their names.
**Other updates:**
- Updated `updateSchema` and `loadTable` to remove the first argument, as it is no longer used.
=> refactor: remove explicit schema synchronization in upload job

.github/workflows/tests.yaml, processor/processor.go, processor/processor_test.go
During processor's **store** stage, the following operations are happening in sequence:
1. store jobs in batch router jobsdb
2. store jobs in router jobsdb
3. store jobs in proc errors jobsdb
4. update job statuses in gateway and report stats
Providing a new configuration option so that (1) (2) (3) & (4) can happen concurrently. Transaction of (4) will only commit as long as (1) (2) and (3) have completed successfully to guarantee our current at-least-once delivery semantics.
resolves PIPE-2020
=> feat(processor): concurrent store steps

.github/workflows/tests.yaml, integration_test/snowpipestreaming/testdata/docker-compose.rudder-transformer.yml, mocks/services/transformer/mock_features.go, processor/internal/transformer/destination_transformer/destination_transformer.go, processor/internal/transformer/destination_transformer/destination_transformer_test.go, processor/internal/transformer/user_transformer/user_transformer.go, processor/internal/transformer/user_transformer/user_transformer_test.go, processor/manager.go, processor/processor_isolation_test.go, processor/transformer/clients.go, processor/types/types.go, router/handle_lifecycle.go, router/router_isolation_test.go, router/testdata/rtIsolationTestTemplate.json.tpl, router/transformer/transformer.go, router/transformer/transformer_test.go, router/types/types.go, router/types/types_test.go, services/transformer/features.go, services/transformer/features_impl.go, testhelper/transformertest/builder.go, testhelper/transformertest/handler_funcs.go
Related to https://github.com/rudderlabs/rudder-transformer/pull/4220
From now on, as long as transformer service supports it and the relevant feature flag is enabled, rudder-server is going to send compacted transformation request payloads by making use of lookup tables instead of repeating the same destination and connection information in every event.
The feature can be enabled through the following configuration options
```yaml
Transformer:
compactionEnabled: true # enables compaction in both processor and router as long as the remote transformer service supports it
forceCompactionEnabled: true # enables compaction in both processor and router regardless if the remote transformer service supports it or not
Router:
DestinationTransformer:
compactionEnabled: true # enables compaction in …
```
=> feat: support compacted destination transformation payloads

warehouse/transformer/internal/utils/utils.go, warehouse/transformer/internal/utils/utils_test.go, warehouse/transformer/logger.go
- Added additional format ("2006-01-02T15:04:05") for timestamp detection.
```
  types.TransformerResponse{
  	Output: map[string]any{
  		"data": map[string]any{
  			... // 45 identical entries
- 			"published_date": string("2025-04-02T01:09:03"),
+ 			"published_date": string("2025-04-02T01:09:03.000Z"),
  			"received_at":    string("2025-04-08T09:12:48.456Z"),
  			... // 7 identical entries
  		},
  		"metadata": map[string]any{
  			"columns": map[string]any{
  				... // 45 identical entries
- 				"published_date": string("string"),
+ 				"published_date": string("datetime"),
  				... // 8 identical entries
  			},
  		},
  		"userId": string(""),
  	},
  	StatusCode: 200,
  	... // 3 identical fields
  }
```
- Resolves WAR-494
=> fix: warehouse transformations valid timestamp formats and log file path

warehouse/transformer/events_test.go, warehouse/transformer/set.go, warehouse/transformer/transformer.go, warehouse/transformer/types.go
- Events are stored as map[string]any in-memory while processing. Upon sending the request to the rudder-transformer, we do JSON marshalling, which [keeps the keys sorted](https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L151-L152). While doing [Object.keys(columnMapping)](https://github.com/rudderlabs/rudder-transformer/blob/develop/src/warehouse/index.js#L146C3-L146C29) during processing in rudder-transformer it follows that same sorted order.
- Now in GO, we do range over a map [does not guarantee ordering](https://go.dev/blog/maps#iteration-order). So sorting the keys while processing the properties in GO code as well.
```
    types.TransformerResponse{
  	  Output: map[string]any{
  		  "data": map[string]any{
  			  ... // 40 identical entries
-  …
```
=> fix: warehouse transformations ordering while processing properties

processor/consent.go, processor/consent_test.go, processor/processor.go, processor/processor_test.go
Fixed the consent management based event filtering logic for GCM to prepare in-memory maps based on both source and destination ID. This is because the GCM configuration can be specified per source type unlike the legacy OneTrust and Ketch configuration.
I've also updated the test suites to cover these advanced scenarios.
Ideally, we should store the data per source type and destination ID but making it more specific to the connection level shouldn't hurt. Moreover, when these kind of configurations move to the connection settings in the future, it'll be beneficial.
Without these changes, a destination that's connected to more than one source type and has distinct GCM config for each source types will result in incorrect consent based filtering as the last source type overrides all the …
=> fix: handle consent management filtering per connection

app/apphandlers/embeddedAppHandler.go, app/apphandlers/processorAppHandler.go, enterprise/reporting/error_index/error_index_reporting.go, jobsdb/admin.go, jobsdb/jobsdb.go, jobsdb/migration.go
Introducing `JobsDB.jobMinRowsLeftMigrateThres` configuration property, for handling compaction of jobsdb datasets containing multiple destinations, where one destination is slower than the others. In such a case, jobsdb datasets end up containing some pending jobs (e.g. 40%), but the dataset doesn't get migrated because it is neither small (we count total number of jobs for calculating small tables) nor does it have an adequate percentage of completed jobs (70%).
With this new option, tables with less than 40K pending jobs will become migration candidates and will be migrated (i.e. compacted) alongside some other dataset candidate for migration, as long as one exists.
- Making jobsdb configuration properties tableprefix-aware, i.e. making it possible to have different settings for `gw`, …
=> feat(jobsdb): introduce jobMinRowsLeftMigrateThres

warehouse/transformer/benchmark/main.go, warehouse/transformer/events.go, warehouse/transformer/internal/rules/rules.go, warehouse/transformer/set.go, warehouse/transformer/transformer.go, warehouse/transformer/transformer_benchmark_test.go
- In processor, [multiplexing happens](https://github.com/rudderlabs/rudder-server/blob/69f1baff51e05c561f0b3122a020e315c62c37bc/processor/processor.go#L2159) when source is connected to multiple destinations. These shallow events point to the same singular event, a map. Modifying and reading this singular event gives `fatal error: concurrent map read and map write` error.
- Also, avoid making modifications to singular events.
- Resolves WAR-488.
=> fix: warehouse transformations concurrent writes

warehouse/api/grpc.go, warehouse/api/grpc_test.go, warehouse/api/http_test.go, warehouse/archive/archiver.go, warehouse/archive/testdata/dump.sql, warehouse/internal/loadfiles/loadfiles.go, warehouse/internal/loadfiles/loadfiles_test.go, warehouse/internal/loadfiles/mock_loadfile_repo_test.go, warehouse/internal/repo/load.go, warehouse/internal/repo/load_test.go, warehouse/internal/repo/table_upload.go, warehouse/internal/repo/table_upload_test.go, warehouse/internal/repo/upload_test.go, warehouse/router/router.go, warehouse/router/state_generate_load_files.go, warehouse/router/upload.go, warehouse/source/http_test.go, warehouse/source/source.go
https://linear.app/rudderstack/issue/WAR-464/modify-load-files-lookup-query-to-start-using-upload-id
=> feat: query load files using upload_id instead of staging_file_id

jobsdb/jobsdb.go, jobsdb/jobsdb_test.go, schema-forwarder/internal/transformer/transformer_test.go
Job queries aggregated over `pg_column_size(event_payload)` to limit the result when a size limit is passed. This could lead to loading more jobs into memory than can be handled safely because it's the compressed size of the column(when compressed). Using the `octet_length(event_payload)` instead to find the actual byte size of the event payload column.
[Resolves PIPE-2009](https://linear.app/rudderstack/issue/PIPE-2009/fix-payload-limiting-by-adding-actual-column-size-in-jobsdb)
=> fix: jobsdb payload limit used compressed column sizes instead of actual payload length

regulation-worker/internal/delete/api/api.go
It is difficult to triage the issue from timeout-alerts without clearly knowing the type of destination the regulation worker is facing issues with. This PR is to add that.
Resolves INT-3436
https://linear.app/rudderstack/issue/INT-3436/research-regulation-worker-alerts
=> chore: add destination type in metrics

router/throttler/adaptivethrottlercounter/algorithm.go, router/throttler/adaptivethrottlercounter/algorithm_test.go, router/throttler/algorithm.go, router/throttler/factory.go
- Support granular configuration in adaptive rate limiter, different for each destination.
- Decouple `throttleTolerancePercentage` from `increasePercentage` and `decreasePercentage`
=> chore: granular configuration for adaptive rate limiting

Dockerfile, archiver/archiver.go, archiver/options.go, enterprise/reporting/error_index/error_index_reporting.go, go.mod, go.sum, processor/processor.go, regulation-worker/internal/delete/batch/batch_test.go, router/batchrouter/batchrouterBenchmark_test.go, router/batchrouter/handle_lifecycle.go, router/batchrouter/util.go, router/config.go, router/handle_lifecycle.go, router/network.go, suppression-backup-service/Dockerfile
- Using reloadable limiters so that we can adjust limits at runtime
- Tuning some router configuration
- process limiter increased from 200 to 1024
- http client's max idle connections following the number of workers by default
=> chore: use reloadable limiters

jobsdb/bench/bench_test.go, jobsdb/integration_test.go, jobsdb/jobsdb.go
Change jobsdb column type default to text. This change ensures - when not configured new datasets created have a `text` event_payload column. Left the config and related handling for now so that it can phased out at a later point so it leaves some time for jobsdb to compact and cleanup older jsonb column containing datasets.
[Resolves PIPE-2043](https://linear.app/rudderstack/issue/PIPE-2043/jobsdb-update-default-payload-column-type-to-text)
=> chore: change jobsdb payload column type default to text

.github/workflows/tests.yaml, processor/internal/transformer/destination_transformer/destination_transformer.go, router/transformer/transformer.go, router/transformer/transformer_test.go
transformer compaction will now be enabled by default, as long as transformer service supports it
=> chore: use transformer compaction by default

config/config.yaml, processor/internal/transformer/destination_transformer/destination_transformer.go, processor/internal/transformer/destination_transformer/destination_transformer_test.go, processor/internal/transformer/trackingplan_validation/trackingplan_validation.go, processor/internal/transformer/trackingplan_validation/trackingplan_validation_test.go, processor/internal/transformer/user_transformer/user_transformer.go, processor/internal/transformer/user_transformer/user_transformer_test.go, processor/types/types.go
`TrackingPlanValidationEvent` should only include `message` and `metadata`
- Remove `Processor.maxConcurrency` since concurrency can be controlled through `Transformer.Client.maxHTTPConnections`
resolves PIPE-2011
=> chore: trim down tracking plan validation payload

warehouse/integrations/redshift/redshift.go, warehouse/integrations/redshift/redshift_test.go
- `tx.Commit` for redshift getting stuck in some cases when loading data into table. In case of append mode, we can directly load file instead of doing it in transaction
- Since we are now skipping creating staging table if append mode is preferred. In case of `loadUserTables`, it relies on indentifies staging table because `users` table will be deduped/merged even when append mode is preferred.  So, creating a staging table for `identifies` is now handled by `loadUserTables`
Part of WAR-517, WAR-515
=> fix: use copy to load table in case append mode

services/notifier/notifier.go, warehouse/internal/loadfiles/loadfiles.go, warehouse/internal/loadfiles/loadfiles_test.go, warehouse/internal/loadfiles/mock_notifier_test.go, warehouse/router/state_generate_load_files.go, warehouse/slave/worker_job.go
This PR introduces support for creation of upload_v2 notifier jobs required for batching of staging files
**Key Changes:**
- Files are grouped into v1 and v2 based on the presence of BytesPerTable and a feature flag.
- Extracted common logic for v1 and v2 paths into separate methods
- For now, v2 notifier jobs include only one staging file per job, similar to v1. This is temporary — batching logic will be implemented in the next PR.
- We will no longer track the processing status (success/failure) of staging files in v2.
- v2 jobs will always force creation of load files (see state_generate_load_files.go).
https://linear.app/rudderstack/issue/WAR-461/enable-creation-of-upload-v2-notifier-jobs
=> feat: support for creating upload v2 notifier jobs

jobsdb/integration_test.go, jobsdb/jobsdb.go, jobsdb/migration.go, jobsdb/migration_test.go
- `jobMinRowsLeftMigrateThreshold` is now the only configuration option that controls whether a table is small or not, i.e. the migration logic will expect two small tables to exists for an actual migration to happen (a.k.a ds compaction).
- Including equality check during `jobDoneMigrateThres` comparison, so that it is easier to disable this option by setting it to 1. It is now recommended to turn off `jobDoneMigrateThres`, so that datasets only get migrated whenever a ds compaction is possible. Migrating an incomplete dataset requires time and acquires a lock (stops-the-world), thus if this is to lead to the same number of datasets, it doesn't provide much benefit.
=> chore(jobsdb): remove jobMinRowsMigrateThres configuration option

go.mod, go.sum, internal/transformer-client/client.go, processor/internal/transformer/destination_transformer/destination_transformer.go, processor/internal/transformer/trackingplan_validation/trackingplan_validation.go, processor/internal/transformer/user_transformer/user_transformer.go, processor/internal/transformer/utils.go, router/transformer/transformer.go, utils/sysUtils/httpclient.go
- respecting `MaxConnsPerHost` & `MaxIdleConnsPerHost` in `httplb` transport
- removed `recycled` client as it can be emulated using `httplb`
- `httplb` client should only use `WithRoundTripperMaxLifetime` in case `{DEST,USER}_TRANSFORM_URL_IS_HEADLESS=false` or `Transformer.Client.recycle: true`. If none is present, `WithRoundTripperMaxLifetime` will not be used
=> fix: httplb client doesn't respect connection limits

router/batchrouter/handle.go, router/batchrouter/handle_lifecycle.go, router/batchrouter/partition_worker.go
- remove `brt_process` limiter which is no longer used after latest changes
- increase `brt_upload` limiter to 200, since we'll be using multiple goroutines per worker now
- rename `batchrouter_partition_worker` limiter to `brt_work` to adhere to existing naming conventions
- use same options in `brt_work` limiter that we are using in other limiters
- rename `batchrouter_partition_worker_add_job_delay` to `brt_partition_worker_add_job_delay` and include `destType` in stats tags
=> chore(batchrouter): limiter cleanup adjust stats and use harmonized config

warehouse/internal/loadfiles/loadfiles.go, warehouse/internal/loadfiles/loadfiles_benchmark_test.go, warehouse/internal/loadfiles/loadfiles_test.go
- Renamed `prepareBaseJobRequest` to `generateBaseRequest` and added computing `StagingDestinationConfig` and `LoadFilePrefix` instead of doing it in `publishJobs`
- Renamed `publishJobs` to `publishToNotifier` which now accepts `messages` as argument instead of computing it using `chunk`
- In `createUploadV2Jobs`, added `GroupStagingFiles` to group files based on size and other characteristics
=> feat: batch staging files for creating upload_v2 notifier jobs

internal/transformer-client/client.go, processor/internal/transformer/destination_transformer/destination_transformer.go, processor/internal/transformer/trackingplan_validation/trackingplan_validation.go, processor/internal/transformer/user_transformer/user_transformer.go, processor/internal/transformer/utils.go, router/transformer/transformer.go
- Transformer client recycle ttl is now bound to a separate configuration option `Transformer.Client.recycleTTL`
- Removing support for {DEST,USER}_TRANSFORM_URL_IS_HEADLESS config options
- Revisiting defaults
- MaxIdleConnsPerHost: 1
- IdleConnTimeout: 5s
- RecycleTTL: 60s
=> fix: transformer client recycle ttl bound to connection idle timeout

go.mod, go.sum, services/streammanager/kafka/kafkamanager.go, services/streammanager/kafka/kafkamanager_test.go
Instead of enabling kafka client batching only whenever transformer-based batching is enabled, we are turning it on by default and using worker-based batching instead (multiple workers in same router using the same client which sends events in batches). This can achieve significantly higher throughput than transformer-based batching.
- We are using by default a batch size equal to the number of workers along with a batching timeout of `100ms`.
- We are using destination type-specific configuration for overriding kafka client parameters, different for `KAFKA`, `CONFLUENT_CLOUD` & `AZURE_EVENT_HUB`.
- Wherever transformer-based batching is enabled, we are falling back to the previous default configuration parameters (batch size: 100 & batch timeout: 1s)
- We are increasing default read & …
=> feat: enable worker-based kafka client batching

services/oauth/v2/oauth.go, services/oauth/v2/oauth_test.go
We are adding validation for a nil secret being stored in the cache, for OAuthV2. 
https://linear.app/rudderstack/issue/INT-3599/fix-add-validation-for-nil-secret-being-stored-in-cache-for-oauthv2
=> fix: add check for nil secret on oauthv2

warehouse/internal/repo/schema.go, warehouse/internal/repo/schema_test.go
Issue - In case of updates to a connection (source_1,destination_1, namespace_1), schema belonging to (source_2, destinaton_1, n1) is not valid. 
Fix -  In case of schema change, for one connection identified by three identifiers (sourceId, destinationId, namespace), we want to update the schema belonging to other connections involving same (destinationId, namespace) pair. 
Part of WAR-606
=> fix: warehouse cached schema mismatch

warehouse/transformer/datatype.go, warehouse/transformer/datatype_test.go, warehouse/transformer/events.go, warehouse/transformer/events_test.go, warehouse/transformer/idresolution.go, warehouse/transformer/internal/response/response.go, warehouse/transformer/internal/rules/rules.go, warehouse/transformer/internal/rules/rules_test.go, warehouse/transformer/internal/types/types.go, warehouse/transformer/internal/utils/utils.go, warehouse/transformer/internal/utils/utils_test.go, warehouse/transformer/logger.go, warehouse/transformer/set.go, warehouse/transformer/testhelper/outputbuilder.go, warehouse/transformer/transformer_fuzz_test.go, warehouse/transformer/transformer_test.go
- For string length calculation, always use `utf8.RuneCount` instead of `len` function to be compatible with JavaScript.
- Extract event name is coming as empty because rules calculation was being done later to the event name calculation.
- Using receivedAt from metadata if empty in the event.
- Extract recordID to be empty in case of slices.
- For getting event type use event instead of metadata.
- While doing JSON marshalling, handle HTML Unicode characters. By default, during marshalling, SetEscapeHTML is true. During Unmarshalling, the library is already taking care of the unescape. So if we do both Marshalling and UnMarshalling, there would be no effect,t which is why it's working for the Transformer response. But here in the warehouse, the transformer would need to handle it …
=> fix: warehouse transformations mismatches

go.mod, go.sum
- Upgrading rudder-go-kit to v0.49.2
=> chore: update rudder-go-kit to 0.49.2

router/transformer/transformer_test.go, services/oauth/v2/http/transport.go, services/oauth/v2/http/transport_test.go
this pr addresses the issue described in [INT-2962](https://linear.app/rudderstack/issue/INT-2962/investigate-on-why-bad-request-is-being-sent-in-routertransform) where "bad request" errors in the routertransform component are causing system panics.
1. modified the oauth interceptor's `postroundtrip` method to handle "bad request" errors by converting them to 500 status codes (which are retryable) instead of propagating errors that could cause panics.
2. changed the return type of `postroundtrip` from `(*http.response, error)` to just `*http.response` since we're no longer returning errors from this function.
3. added tests to verify that "bad request" errors are properly handled and don't cause panics.
4. updated existing tests to reflect the new behavior (returning 500 errors instead of …
=> fix: convert bad request errors to 500 errors in oauth interceptor to prevent panics

services/notifier/notifier.go, services/notifier/repo.go, services/notifier/repo_test.go, warehouse/slave/slave.go, warehouse/slave/slave_test.go, warehouse/slave/worker.go, warehouse/slave/worker_test.go
**Notifier**
- Add a new method to the slaveNotifier interface: `RefreshClaim(ctx context.Context, jobId int64) error`
- This method updates the `last_exec_time` column to NOW() for the specified job ID.
**Slave**
- Extend the worker struct to include a new field: `activeJobId int64`
- When a worker picks up a notifier job, it sets `activeJobId` to the corresponding job ID. This value is cleared once the job processing completes.
- A background goroutine is being launched within each worker that periodically invokes `RefreshClaim` for the current activeJobId, if set. This acts as a heartbeat to signal that the job is still actively being processed.
=> feat: support claim renewal in notifier jobs

processor/consent.go, processor/consent_test.go, processor/processor_test.go
Besides, "and" and "or" consent resolution strategies, we're now supporting the new "all" and "any" values. The UI changes will be rolled out very soon.
Also, the logic now prefers to use "allowed consent IDs" and falls back to "denied consent IDs" to align with the client side implementation. It's a bit tricky with allowed consent IDs as some older SDK versions send it as an object for OneTrust CMP.
So, we're handling both an object and array of strings.
Additionally, I've sanitized the consent IDs from the config and event before resolving them for filtering events to destinations.
https://linear.app/rudderstack/view/scrum-board-75b83c60706a5
=> feat: support new consent resolution strategy values

backend-config/account_association.go, backend-config/account_association_test.go, backend-config/types.go
This PR optimizes the `Account` data structure by removing the redundant `Id` field from the `Account` struct. Since we're now using a map structure where the account ID is already the key (`map[string]Account`), storing the same ID inside the struct is redundant and inefficient.
- Removed the `Id` field from the `Account` struct in `types.go`
- Updated the `setDestinationAccounts` method to use the map key (account ID) directly when creating `AccountWithDefinition` instances
- Removed redundant `Id` field references from all test cases in `account_association_test.go`
- Eliminates data duplication by not storing the same ID twice (as map key and inside the struct)
- Reduces memory usage by removing redundant fields
- Improves code clarity by making it explicit that the map key is the …
=> fix: update account type to remove id which we are getting as map key

processor/internal/transformer/destination_transformer/embedded/warehouse/uploader.go
- For sample diff, avoid checking for `auto-` if the `messageId` is not present, because rudder-transformer will add some random UUID that will not match.
- Resolves WAR-645
=> chore: warehouse transformer sample diff

router/config.go, router/handle_lifecycle.go
We should be able to override router's configuration for a specific destination type without affecting others.
=> chore(router): support destination-specific configuration overrides for all options

enterprise/reporting/client/client.go, enterprise/reporting/client/client_test.go, enterprise/reporting/error_reporting.go, enterprise/reporting/flusher/factory.go, enterprise/reporting/reporting.go
url.JoinPath has a side effect of encoding query parameter. Causing `/metrics?version=v1` to be used as path, rather than `/metrics` with query `?version=v1`.
Added a test to cover this.
Resolves PIPE-2062
https://linear.app/rudderstack/issue/PIPE-2062/fix-reporting-client-path-with-query
=> fix: reporting common client path with query

processor/internal/transformer/destination_transformer/destination_transformer.go, processor/internal/transformer/destination_transformer/embedded/warehouse/transformer_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/uploader.go, processor/internal/transformer/destination_transformer/embedded/warehouse/uploader_test.go, processor/internal/transformer/destination_transformer/logger.go
- Use a go-routine when you only need to compare and upload. In case of early return, no need for a go-routine. In most cases, when the limit is reached, we will be unnecessarily spinning a go-routine which is not required.
- Use warehouse transformations for snowpipe streaming as well.
- Resolves WAR-654
=> fix: embedded transformations upload

router/factory.go, router/handle_lifecycle.go, router/router_test.go, router/transformer/transformer.go, router/worker.go, router/worker_test.go, services/oauth/v2/destination_info.go, services/oauth/v2/destination_info_test.go
=> chore: revert use account to decide oauth type of a destination

warehouse/internal/repo/upload.go, warehouse/internal/repo/upload_test.go, warehouse/router/state_export_data.go, warehouse/router/upload.go, warehouse/router/upload_test.go
- While picking up jobs we are relying on picking jobs via [COALESCE(metadata->>'priority', '100')::int ASC, COALESCE(first_event_at, NOW()) ASC, id ASC) AS row_number](https://github.com/rudderlabs/rudder-server/blob/6232755882293157539ad003f11eb7bbc67c2a78/warehouse/internal/repo/upload.go#L300-L319).
- Same thing this needs to be done while getting PendingTableUploads, so as to avoid dependency for skipping table uploads.
- Modified query still using the existing indexes.
```
Sort  (cost=16.95..16.96 rows=1 width=522)
--
Sort Key: ((COALESCE((ut.metadata ->> 'priority'::text), '100'::text))::integer), (COALESCE((ut.first_event_at)::timestamp with time zone, now())), ut.id
->  Nested Loop  (cost=0.43..16.94 rows=1 width=522)
->  Nested Loop  (cost=0.29..16.36 rows=1 width=550)
->  Index …
```
=> fix: warehouse pending tables to skip

jobsdb/integration_test.go, jobsdb/jobsdb.go, jobsdb/migration.go
This configuration option is already disabled in production (by setting it to 1). Removing it, since the cost of migrating pending jobs without reducing the number of datasets is not worth taking.
**Coming next:** Avoid migrating a small and incomplete dataset (needing a pair) if all other datasets to be migrated are complete (without pending jobs). E.g. if dataset1 is complete and dataset2 needs a pair, only dataset1 will be migrated/deleted. Dataset2 will only be migrated if there is another dataset3 that needs a pair too.
=> chore(jobsdb): remove support for jobDoneMigrateThres

processor/internal/transformer/destination_transformer/embedded/warehouse/datatype.go, processor/internal/transformer/destination_transformer/embedded/warehouse/datatype_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/events.go, processor/internal/transformer/destination_transformer/embedded/warehouse/events_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/internal/utils/utils.go, processor/internal/transformer/destination_transformer/embedded/warehouse/internal/utils/utils_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/set.go, processor/internal/transformer/destination_transformer/embedded/warehouse/transformer.go, processor/internal/transformer/destination_transformer/embedded/warehouse/uploader.go
- In rudder-transformer, we are using `Number.isInteger` to determine for int datatype, in comparison with Golang, which has a lower range `9223372036854775807`. `654645465456456400000` is being calculated as a float in Golang and an int in JS. Using a `big` package to determine now.
- `utf16` Rune count for being in conjunction with JavaScript.
- GeoLocation enrichment struct getting embedded directly to a singular event. These need to be handled separately, like we are doing for the Tracking Plan.
- Exclude the extract event in case the event name is empty.
- Exclude the identity event in case the userID is empty. 
- Resolves WAR-672.
=> fix: warehouse transformations

jobsdb/integration_test.go, jobsdb/jobsdb.go, jobsdb/migration.go
Avoid migrating a small and incomplete dataset (needing a pair) if all other datasets to be migrated are complete (without pending jobs). 
E.g. if dataset1 is complete and dataset2 needs a pair, only dataset1 will be migrated/deleted. Dataset2 will only be migrated if there is another dataset3 that needs to be migrated and has some incomplete jobs too.
Migrating incomplete datasets takes time and while the migration is happening all other operations (reads, store, update) are being blocked, thus we avoid migrating a single incomplete dataset, even though the resulting dataset would have less jobs to query.
Continuation of #5873
=> chore(jobsdb): migrate incomplete datasets in pairs excluding completed ones

jobsdb/integration_test.go, jobsdb/jobsdb.go, jobsdb/jobsdb_test.go, utils/misc/misc.go
- Removing null bytes while sanitizing. Previously we were only removing a unicode encoded null byte.
- Removing null bytes from UserID while sanitizing
=> fix: server panicking with invalid byte sequence for encoding utf8 0x00

.github/workflows/housekeeping.yaml
Get the housekeeping github action back to running state
Follow the security guidelines and replace version with commit sha
=> chore: move house keeping action to commit sha

integration_test/warehouse/warehouse_test.go, warehouse/internal/loadfiles/loadfiles.go, warehouse/internal/repo/load.go, warehouse/internal/repo/load_test.go, warehouse/internal/repo/table_upload.go, warehouse/internal/repo/table_upload_test.go, warehouse/router/upload.go, warehouse/router/upload_test.go
**BUG** - Using partition by on (upload_id, table_name) was picking only one file per table even though there exists multiple files per table
**FIX** - Now we are picking all the files for the given upload_id. Any load files generated in a previous attempt gets deleted so we need not worry about that
=> fix: under reporting of load files when using upload id

backend-config/dynamicconfig/utils_test.go
Adds a test case for dynamic config patterns that use numeric default values.
- Added test case for pattern `{{ message.traits.key || 1233 }}`
- Ensures `ContainsPattern` function correctly identifies patterns with numeric defaults
- Improves test coverage for dynamic config pattern detection
The new test case verifies that dynamic config patterns with numeric default values are properly detected by the `ContainsPattern` function.
Resolves INT-3633
---
Pull Request opened by [Augment Code](https://www.augmentcode.com/) with guidance from the PR author
=> test: add test case for dynamic config pattern with numeric default value

router/batchrouter/asyncdestinationmanager/bing-ads/common/token.go, services/oauth/v2/http/transport.go, services/oauth/v2/oauth.go, services/oauth/v2/oauth_test.go, services/oauth/v2/types.go
This PR refactors the OAuth v2 system by simplifying the RefreshTokenParams struct and removing the dependency on the full DestinationInfo object. Instead of passing the entire destination object, it now only passes the specific DestinationID string that's actually needed.
**Removed**: Destination *DestinationInfo field
**Added**: DestinationID string field
**Improved**: Field alignment and formatting for better readability
- Eliminated the creation of a DestinationInfo object in GenerateTokenV2()
- Now directly passes DestinationID instead of creating and passing the entire destination object
- **Reduced code complexity**: Removed 5 lines of unnecessary object construction
- Updated OAuth transport to pass rts.destination.ID directly instead of the full destination object
- Maintains the …
=> chore: clean up destinationInfo from refreshTokenParams

warehouse/router/router.go
- Remove unused wh schemas repo in warehouse router
Part of WAR-644
=> chore: remove unused schemas repo in warehouse router

regulation-worker/internal/service/service.go
Added this metric for setting up alerts when regulations are failing
https://linear.app/rudderstack/issue/INT-3757/add-observability-on-data-regulation-failures
Resolves INT-3757
=> chore: add new metric regulation_worker_attempted_user_deletions_count

warehouse/integrations/clickhouse/clickhouse.go, warehouse/integrations/clickhouse/clickhouse_test.go
- Add config to disable load stats for clickhouse. 
Part of WAR-250
=> chore: add config to disable load table stats for clickhouse

processor/internal/transformer/destination_transformer/embedded/warehouse/transformer.go, processor/internal/transformer/destination_transformer/embedded/warehouse/uploader.go
- Avoid making modifications, such as ordering a legacy response, as it will be consumed later.
- Avoid concurrent transformations like what's happening in the rudder-transformer JS code. Once we completely migrated to warehouse transformations, we can then later have concurrency set.
- Resolves WAR-742, WAR-697
=> fix: warehouse transformations responses ordering

router/network.go, router/network_test.go
Remove excess headers in `network.go` introduced by #5888
=> fix: router request failing with unsupported media type error

processor/internal/transformer/destination_transformer/destination_transformer.go, processor/internal/transformer/destination_transformer/destination_transformer_test.go
- Using deepcopy for client events and legacy response, so as to be careful of any modifications within the embedded warehouse transformations module.
- Added test within the processor to cover the warehouse transformations component.
- Resolves WAR-762
=> fix: warehouse transformations deep copying arguments

warehouse/integrations/snowflake/datatype_mapper.go, warehouse/integrations/snowflake/snowflake.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/integrations/snowflake/table_manager.go, warehouse/integrations/snowflake/table_manager_test.go, warehouse/internal/model/settings.go
This PR enhances the Snowflake implementation of the Manager interface by adding support for Iceberg tables.
Implementation Details:
- Introduced two new destination settings for Iceberg: `enableIceberg` and `externalVolume`.
- Created a `tableManager` interface to encapsulate table-specific behavior. This interface has two implementations: standard (existing) and Iceberg.
- Moved `dataTypesMap` and the corresponding Iceberg type handling behind this interface.
- `tableManager` is being initialized in the Setup method.
- Refactored `getSortedColumnsFromTableSchema` into a standalone function, making it reusable for `tableManager` instead of being a Snowflake-specific method.
- Removed unused `ColumnsWithDataTypes` method
=> feat: add support for Snowflake Iceberg tables

go.mod
add golang.org/x/net/html vulnerability
pipe-2132
=> fix: add golang.org/x/net/html vulnerability

processor/internal/transformer/destination_transformer/embedded/warehouse/benchmark/deployment.yaml
`provisioner-name` is deprecated and we should now use `nodepool`.
https://linear.app/rudderstack/issue/INF-1077/update-clusters-to-v0377
=> chore: update nodeSelector for warehouse benchmark deploy

.github/workflows/builds.yml
- For every enterprise image/tag that is built and pushed, also build and push a new image with the environment variable RACE_ENABLED=TRUE.
- The new image should have the same tag as the original, but with -race appended (e.g., if the tag is 1.2.3, the new tag should be 1.2.3-race).
=> chore: create enterprise images with an additional race enabled build

processor/partition_worker.go, processor/partition_worker_handle.go, processor/partition_worker_test.go, processor/pipeline_worker.go, processor/processor.go, utils/signal/signal.go
Include the pipeline index when we’re creating the key for `storePlocker`. Since the same userID will always be processed by the same processor pipeline index, we should be fine with this change and wouldn't any cause out-of-order panics in router.
resolves PIPE-2143
=> chore(processor): use pipeline-specific destination locks during store

router/batchrouter/asyncdestinationmanager/snowpipestreaming/apiadapter.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/discards.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/internal/api/api.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/internal/api/api_integration_test.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/internal/api/api_test.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming_test.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/types.go
**BUG**
A fix was made for preventing duplicates in Snowpipe in PR #5957 . But it missed returning the id of the newly created channel in the `Upload` method. As a result, `Poll` method was still receiving the stale channel id. So the GetStatus API call was failing with 404, causing the event to be marked as failed. This failed event would be retried causing duplicates
**FIX**
- The actual fix was simple to propagate the new channel id from the Insert API method back to the caller. But there was another miss, that post channel recreation the cache was not being updated. So instead this PR, moves the recreation logic from the API layer to the manager layer. This meant reverting the changes done in `api.go` and `apiadapter.go` and the corresponding test files
- In case of 404 status code, …
=> fix: incorrect snowpipe channel id being returned if insert recreates the channel

processor/internal/transformer/destination_transformer/embedded/warehouse/internal/utils/utils.go, processor/internal/transformer/destination_transformer/embedded/warehouse/internal/utils/utils_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/transformer.go, processor/internal/transformer/destination_transformer/embedded/warehouse/transformer_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/uploader.go
- Keeping the constant to be 1600 for `WH_MAX_COLUMNS_IN_EVENT`, as is present for transformers. https://github.com/rudderlabs/rudder-devops/blob/158a05bd7a6c35b06795e3c46a109ce632bd2330/helm-charts/shared-services/per-az/environment/production/production.yaml#L34
- Ignore Unicode diffs caused by Go vs JavaScript serialisation differences, regex `\\u[0-9a-fA-F]{4}`.
- While parsing datetime, in case of "day out of range" error, fall back to normalising the date. This is being handle in JavaScript automatically `console.log(new Date('1988-04-31').toISOString()); // 1988-05-01T00:00:00.000Z`.
- Resolves WAR-785
=> chore: warehouse transformations parsing timestamp and serialisation

regulation-worker/internal/delete/api/api_test.go, services/oauth/v2/http/transport.go, services/oauth/v2/http/transport_test.go
- Combine destination existence and nil checks into single condition
- Improve log message clarity with [RoundTrip] prefix
- Add comprehensive test coverage for missing and nil destination info scenarios
- Enhance error handling consistency in OAuth transport layer
test(oauth): add coverage for transport round trip error logging
- Add comprehensive test for transport round trip error path
- Ensure error logging with destination details is covered
- Test error propagation in OAuth transport layer
Resolves https://linear.app/rudderstack/issue/INT-3637/runbook-and-troubleshooting-guide-to-triage-oauth-failures
=> chore: oauth platform error logs

backend-config/types.go
This PR adds informational logging when the HasDynamicConfig flag is enabled for destinations in the backend config. The logging includes destination ID and workspace ID to help with debugging and tracking which destinations have dynamic configuration patterns.
- Added logging in the `UpdateHasDynamicConfig` method in `backend-config/types.go`
- The log is emitted only when `HasDynamicConfig` is true to avoid noise
- Includes relevant context (destination ID and workspace ID) for better debugging
Resolves https://linear.app/rudderstack/issue/INT-3613/propagate-hasdynamicconfig-in-destination-in-rudder-server
=> chore: add logging for HasDynamicConfig flag in destination config

backend-config/types.go, backend-config/types_test.go, processor/testdata/goldenUtMirrorClientEvents.json
This PR ensures that the  field is always present in the JSON representation of  struct, even when its value is .
1. **Updated JSON tag**: Removed  from  field in  struct
- Before: `json:"hasDynamicConfig,omitempty"`
- After: `json:"hasDynamicConfig"`
**Added comprehensive test**: Created `TestDestinationT_MarshalJSON_HasDynamicConfigAlwaysPresent` to verify:
- Field is present when `HasDynamicConfig` is `false`
- Field is present when `HasDynamicConfig` is `true`
- Field is present for zero-value `DestinationT` structs
Previously, when  was  (the zero value for booleans), the  tag would cause the field to be omitted from the JSON output. This change ensures consistent JSON structure regardless of the boolean value.
- All existing tests continue to pass
- New test specifically validates …
=> fix: ensure hasDynamicConfig field always present in DestinationT JSON

gateway/webhook/setup.go, gateway/webhook/webhook.go
inject stats in source transformer to avoid using global stats.
-
=> chore: inject stats in source transformer

warehouse/integrations/bigquery/bigquery.go
- Passing more information while bigquery load error as the current one does not have sufficient information (J`SON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.`)
- Resolves WAR-824
=> fix: bigquery load errors population

processor/internal/transformer/destination_transformer/embedded/warehouse/datatype.go, processor/internal/transformer/destination_transformer/embedded/warehouse/datatype_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/events_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/internal/response/response.go, processor/internal/transformer/destination_transformer/embedded/warehouse/internal/types/types.go, processor/internal/transformer/destination_transformer/embedded/warehouse/internal/utils/utils.go, processor/internal/transformer/destination_transformer/embedded/warehouse/internal/utils/utils_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/set.go, processor/internal/transformer/destination_transformer/embedded/warehouse/testhelper/validate.go, processor/internal/transformer/destination_transformer/embedded/warehouse/transformer.go, processor/internal/transformer/destination_transformer/embedded/warehouse/transformer_fuzz_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/transformer_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/uploader_test.go
- We rely on being `SingularEvent` only to contain `map[string]any`, but some context properties are being directly added to the SingularEvent as the struct type like these:
- [Bot Details](https://github.com/rudderlabs/rudder-server/blob/master/internal/enricher/bot.go#L49-L54).
- [Geo enrichment](https://github.com/rudderlabs/rudder-server/blob/master/internal/enricher/geolocation.go#L134-L135)
- [Tracking plan.](https://github.com/rudderlabs/rudder-server/blob/master/processor/trackingplan.go#L32-L50)
- In case of Bot Details, we don't have access to the struct, so we can't infer the type and handle it. Adding support for any custom struct which checks for `reflect.Struct`, `reflect.Ptr`, `reflect.Slice`, `reflect.Array` using reflection.
- Resolves WAR-821
=> fix: custom type in payload during enrichment

gateway/gateway_test.go, gateway/handle.go, gateway/handle_lifecycle.go
- Add leaky uploader functionality to handle invalid JSON payloads
- Upload invalid payloads to s3 for debugging and analysis
- Ensure valid payloads are processed normally without being uploaded
- Configure leaky uploader with S3 storage options
- Implement backoff and buffer mechanisms for failed uploads
pipe-2188
=> feat: implement leaky uploader for invalid payloads

gateway/handle.go, gateway/handle_test.go, internal/enricher/bot.go, internal/enricher/bot_test.go, processor/processor.go, processor/processor_bot_enricher_test.go, utils/types/reporting_types.go, utils/types/types.go
This PR moves bot event dropping from the ingestion service to the processor to capture accurate reporting metrics before deduplication occurs.
Previously, bot events were dropped at the ingestion service level. The main issue was that there is currently no way to emit reporting metrics from ingestion, so we were using Prometheus metrics to power the UI which are not accurate. Now we are using reporting metrics in the processor to capture accurate bot event statistics.
- Drop bot events in the processor when botAction is set to "drop" in message parameters
- Block live events recording in gateway for bot events that will be dropped in the processor 
- Capture accurate bot event metrics before the deduplication stage
- Move event blocking logic to occur before dedup processing.
- Cleanup …
=> chore: drop bot events in processor after capturing metrics

router/customdestinationmanager/customdestinationmanager.go
This pull request makes a small but important change to the logging level in the `refreshClient` method of the `CustomManagerT` struct. The change updates the log level from `Debug` to `Info` to ensure that refresh operations are logged with higher visibility.
* [`router/customdestinationmanager/customdestinationmanager.go`](diffhunk://#diff-1e9610e1dd9e153448cfb4ad28adbe60b0b5d9cd300e998e0cc1bfda227aeedeL226-R226): Changed the logging level from `Debugn` to `Infon` in the `refreshClient` method to increase the visibility of refresh operations.
https://linear.app/rudderstack/issue/INT-3715/investigate-zoopla-error-with-google-sheets-destination-delivery
=> chore: change refresh time log to info

cmd/rudder-cli/warehouse/warehouse.go, processor/internal/transformer/destination_transformer/destination_transformer.go, processor/internal/transformer/destination_transformer/embedded/warehouse/events_test.go, processor/internal/transformer/destination_transformer/embedded/warehouse/transformer_fuzz_test.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/channel.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming.go, warehouse/bcm/backend_config.go, warehouse/encoding/encoding_test.go, warehouse/integrations/snowflake/snowflake.go, warehouse/utils/utils.go
Changes made to add support for Snowpipe streaming destination
1. Workspace config contained config only for warehouse destinations. Updated this code to included config for Snowpipe destination as well
2. For snowpipe streaming, the only mode of authentication supported is key pair auth. So that is why there is no explicit field `useKeyPairAuth` in its destination config. So added this logic in the connect function of snowflake. Post this change, also removed it from other places (validations and manager creation), since now it is unnecessary there.
Refactoring: Added Snowpipe in `WarehouseDestinationMap` to avoid having separate check for it at multiple places. Also renamed it to `PseudoWarehouseDestinationMap`.
=> feat: add support for snowpipe destination in rudder-cli

router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bingads_test.go, router/batchrouter/asyncdestinationmanager/bing-ads/offline-conversions/bulk_uploader.go
This PR improves the handling of the `conversionTime` field for Bing Ads offline conversions and ensures robust test coverage for the new logic. The changes address issues with overly strict timestamp validation and align the system with Bing Ads' accepted formats, while also ensuring that the new logic is well-tested.
---
- **Flexible Timestamp Parsing:**  
The `conversionTime` field is now parsed using two formats:  
1. **ISO 8601/RFC3339** (e.g., `2025-07-02T18:50:54Z`)  
2. **Bing Ads UI format** (`mm/dd/yyyy hh:mm:ss AM/PM`, e.g., `7/2/2025 6:50:54 PM`)
- **Consistent Output:**  
Regardless of the input format, the timestamp is always converted and output in Bing Ads' required format:  
`mm/dd/yyyy hh:mm:ss AM/PM` (Go layout: `"2/1/2006 3:04:05 PM"`).
- **Clear Error Messaging:** …
=> fix: update validation and conversion of timestamp to bingads offline conversion supported format

router/transformer/transformer_proxy_adapter.go, router/transformer/transformer_proxy_adapter_test.go
- The `getTransformerProxyURL` function now prioritizes the `TRANSFORMER_PROXY_URL` environment variable. If this variable is not set, it falls back to `DEST_TRANSFORM_URL`.
- Added unit tests to cover all environment variable scenarios.
- Reference: [INT-3943 - Add support for dedicated deployment for transformer proxy/delivery](https://linear.app/rudderstack/issue/INT-3943/add-support-for-dedicated-deployment-for-transformer-proxydelivery)
=> feat(router): support TRANSFORMER_PROXY_URL for dedicated transformer proxy

warehouse/internal/model/staging_snapshot.go, warehouse/internal/repo/staging_snapshot.go, warehouse/internal/repo/staging_snapshot_test.go, warehouse/internal/snapshots/staging_schema.go, warehouse/internal/snapshots/staging_schema_test.go, warehouse/internal/snapshots/staging_strategy.go, warehouse/utils/utils.go
- Introduces a new table: `wh_staging_file_schema_snapshots`
- Stores JSON-encoded schema snapshots for staging files.
- Keys: source_id, destination_id, workspace_id, and created_at.
- Adds columns to wh_staging_files:
- `schema_snapshot_id` (UUID, references the new snapshot table)
- `schema_patch` (TEXT, stores a JSON Patch diff from the snapshot to the actual schema)
- Adds supporting indexes for efficient lookup and retrieval.
[WAR-867: Snapshot cached repository with different strategies](https://linear.app/rudderstack/issue/WAR-867/snapshot-cached-repository-with-different-strategies)
=> feat: staging files schema snapshot cached repository with different strategies

warehouse/integrations/azure-synapse/azure_synapse_test.go, warehouse/integrations/bigquery/bigquery_test.go, warehouse/integrations/clickhouse/clickhouse_test.go, warehouse/integrations/datalake/datalake_test.go, warehouse/integrations/deltalake/deltalake_test.go, warehouse/integrations/mssql/mssql_test.go, warehouse/integrations/postgres/postgres_test.go, warehouse/integrations/redshift/redshift_test.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/router/upload.go, warehouse/router/upload_test.go, warehouse/utils/utils.go
- Avoid cleaning up load files for Datalake destination
- Resolves RUD-2448
=> fix: avoid cleanup object storage for datalakes

warehouse/utils/utils.go, warehouse/utils/utils_test.go
With `useRudderStorage`  we end up not getting any bucket in the destination configuration and resulting in a forbidden call to get region. If we have use rudder storage we know the region of the bucket which can be used directly skipping the get region call.
=> fix: empty bucket with use rudder storage

archiver/archiver.go, enterprise/reporting/error_index/error_index_reporting.go, enterprise/reporting/error_reporting.go, enterprise/reporting/flusher/cron_runner.go, enterprise/reporting/mediator.go, enterprise/reporting/reporting.go, gateway/handle_lifecycle.go, gateway/webhook/setup.go, jobsdb/jobsdb.go, jobsdb/jobsdb_test.go, processor/processor.go, router/batchrouter/handle.go, router/batchrouter/handle_lifecycle.go, router/handle.go, router/handle_lifecycle.go, router/manager/manager.go, router/partition_worker.go, schema-forwarder/internal/forwarder/abortingforwarder.go, schema-forwarder/internal/forwarder/baseforwarder.go, schema-forwarder/internal/forwarder/jobsforwarder.go, schema-forwarder/internal/transformer/transformer.go, schema-forwarder/internal/transformer/types.go, services/notifier/notifier.go, warehouse/router/router.go, warehouse/router/router_test.go
since sync 0.16.0 errgroup panic propagation has been reverted thus it is now safe to use again.
=> chore: use errgroup.Group instead of kitsync.ErrGroup

jobsdb/jobsdb.go, jobsdb/jobsdb_test.go, jobsdb/migration.go
Introducing a context with timeout during addNewDSLoop so that: 
- the loop can stop early during shutdown
- the dsList lock is not being held indefinitely in case of blocking long running queries
resolves PIPE-2254
=> chore(jobsdb): introduce context with timeout during add new ds loop

warehouse/internal/loadfiles/mock_stagefile_repo_test.go
This PR fixes a data race detected during test execution in the warehouse/internal/loadfiles package. The mockStageFilesRepo used in tests is now protected with a sync.Mutex to ensure safe concurrent access to the internal store map. This resolves the race condition observed in TestV2CreateLoadFiles/mixed_staging_files.
[WAR-960: race detection during test code execution](https://linear.app/rudderstack/issue/WAR-960/race-detection-during-test-code-execution)
=> fix(warehouse): add mutex to mockStageFilesRepo to prevent data race in tests (WAR-960

router/transformer/transformer_proxy_adapter_test.go, services/validators/envValidator.go
Using `sql.NullString` instead of a pointer to a `string`, so that value is being printed properly
```
dangling connection #37: {pid:2850595 queryStart:0x40005e8040 waitEventType:Client waitEvent:ClientRead state:active query:COPY "gw_job_status_47132" ("job_id", "job_state", "attempt", "exec_time", "retry_time", "error_code", "error_response", "parameters") FROM STDIN terminated:true}
```
resolves PIPE-2221
=> fix: dangling connection start time not being logged properly

jobsdb/jobsdb.go, jobsdb/migration_test.go
The foreign key constraint introduced in #4710 has a performance impact:
- The jobs table cannot be locked if job status table has incomplete transactions, i.e. status updates and hang transactions can hinder creation of new datasets
- There is an overhead during bulk job status inserts due to row-by-row validation of the foreign key constraint
- cleanup `indexOptimizations` configuration option (always enabled)
resolves PIPE-2221
=> chore(jobsdb): remove foreign key constraint

router/handle_lifecycle.go, router/worker.go
Regression introduced by #6114
After a new job arrives in the worker's queue, the worker's batch timeout is getting reset. This causes the following behaviour:
- For pipelines with high traffic: no significant effect
- For pipelines with low traffic: 
- No significant effect, as long as events arrive infrequently, i.e. less than 1 event to each worker every 5sec
- Processing stalls until the full batch gets filled, as long as events arrive more frequent than 5sec. Increased delivery times are observed by customers in such a case.
We are now resetting the timer only after we actually process a batch
resolves PIPE-2260
=> fix(router): worker's batch timeout is getting resetted after new job arrival

regulation-worker/cmd/main.go, regulation-worker/internal/delete/api/api.go, regulation-worker/internal/delete/api/api_test.go, regulation-worker/internal/service/component_test.go
This PR implements a comprehensive refactor of the regulation-worker's OAuth integration to:
1. **Remove legacy OAuth v1 implementation** - Eliminates dead code and simplifies the codebase
2. **Fix OAuth v2 framework compliance** - Ensures destination context is always attached for ALL destinations (OAuth + non-OAuth)
3. **Clean up unused dependencies** - Removes OAuth v1 imports and initialization code
4. **Update test coverage** - Removes OAuth v1 test scenarios and simplifies test structure
[INT-3897: Fix OAuthv2 integrations and clean up OAuth v1 module from regulation](https://linear.app/rudderstack/issue/INT-3897/fix-oauthv2-integrations-and-clean-up-oauth-v1-module-from-regulation)
**Critical Bug Fix**: Previously, destination context was only attached to HTTP requests when …
=> fix: oauthv2 integrations and remove oauthv1 implementation from regulation worker

router/partition_worker.go, router/router_test.go, router/worker.go, router/worker_batch_loop.go, router/worker_batch_loop_test.go, router/worker_test.go
Refactoring the worker processing logic in the `router` package to improve code clarity, modularity, and testability. 
- Introducing `workerBatchLoop` struct in a new file, `router/worker_batch_loop.go`, to encapsulate batch processing logic. This includes handling job batching, timeouts, and job transformations.
- Adding tests for the new batch processing logic in `router/worker_batch_loop_test.go` to ensure correctness.
- Original worker's `workLoop` logic is now refactored to use the new `workerBatchLoop` and we introduced `acceptWorkerJob` method for managing job filtering and processing, which was previously coupled with batching logic.
resolves PIPE-2262
=> refactor(router): separate worker loop batching logic from processing logic

services/notifier/notifier.go, services/notifier/repo.go, services/notifier/repo_test.go
- This PR adds comprehensive stats emission to all notifier repository operations, providing better observability and monitoring capabilities for database performance across the notifier module
- Resolves WAR-922
=> feat: stats for notifier repo module

router/worker.go
Currently, when a job is aborted, the payloadStage is incorrectly set to "delivery" in error response. This PR overwrites the payloadStage in such cases to reflect the correct stage i.e `router_input`.
[Resolves OBS-879](https://linear.app/rudderstack/issue/OBS-879/overwrite-payloadstage-in-sample-response-when-a-job-is-aborted)
=> fix: overwrite payloadStage in error response for aborted jobs

integration_test/warehouse/warehouse_test.go, warehouse/integrations/datalake/datalake_test.go, warehouse/internal/loadfiles/loadfiles.go, warehouse/internal/loadfiles/loadfiles_test.go, warehouse/internal/loadfiles/mock_loadfile_repo_test.go, warehouse/internal/repo/load.go, warehouse/internal/repo/load_test.go, warehouse/internal/repo/table_upload.go, warehouse/internal/repo/table_upload_test.go, warehouse/router/mocks/upload.go, warehouse/router/state_generate_load_files.go, warehouse/router/state_update_table_uploads.go, warehouse/router/testdata/sql/upload_test.sql, warehouse/router/upload.go, warehouse/router/upload_stats_test.go, warehouse/router/upload_test.go
This PR is one of the cleanup PRs for the load file size optimization feature. It gets rid of `queryWithUploadId` flag. Going forward the value will always be true.
=> chore: remove queryWithUploadId flag support for load files

CHANGELOG.md, router/worker.go
Syncing release v1.56.0 to main branch
chore: bump  the go-dependencies group with 12 updates (#6189)
chore: remove queryWithUploadId flag support for load files (#6192)
=> chore: sync release v1.56.0 to main branch

go.mod, go.sum
Bumping rudder-go-kit version to [v0.59.4](https://github.com/rudderlabs/rudder-go-kit/releases/tag/v0.59.4) to fix gcra's throttler caching issue where the cache key was not including the throttling rate.
resolves PIPE-2284
=> fix: adaptive throttling not applying dynamic throttling limits consistently

router/throttler/internal/adaptive/adaptive_all_event_types.go, router/throttler/internal/adaptive/adaptive_all_event_types_test.go, router/throttler/internal/adaptive/adaptive_per_event_type.go, router/throttler/internal/adaptive/adaptive_per_event_type_test.go, router/throttler/internal/adaptive/throttler.go, router/throttler/internal/static/static_all_event_types.go, router/throttler/internal/static/static_all_event_types_test.go, router/throttler/internal/static/static_per_event_type.go, router/throttler/internal/static/static_per_event_type_test.go, router/throttler/internal/static/throttler.go
Our only means of disabling throttling for a destination type or destination id is by setting the limit or window to zero. Thus it makes no sense to emit a warning log in case some throttler is disabled. Renamed `validConfiguration` to `enabled` to avoid any confusion in the future.
Regression introduced by #6181
=> chore: throttler should emit no warning if not enabled

enterprise/reporting/error_extractor.go, enterprise/reporting/error_reporting_test.go
This PR enhances the error extractor in the enterprise reporting module to properly handle nested JSON responses. The fix addresses cases where error messages are embedded within nested JSON structures, particularly when the outer JSON contains a 'response' field with a JSON string that includes error information.
- **Enhanced Error Extractor Logic**: Added a fallback mechanism in the  function to handle direct message keys in parsed JSON
- **Improved Nested JSON Parsing**: Better handling of nested JSON response structures for more accurate error message extraction
- **Comprehensive Test Coverage**: Added extensive test cases covering various nested JSON scenarios, edge cases, and real-world examples
- **Backward Compatibility**: Maintained all existing functionality while adding new …
=> fix: error extractor to handle nested JSON responses

app/apphandlers/embeddedAppHandler.go, app/apphandlers/gatewayAppHandler.go, app/apphandlers/processorAppHandler.go, app/cluster/integration_test.go, gateway/gateway_test.go, gateway/handle.go, gateway/handle_lifecycle.go, gateway/handle_test.go, gateway/handle_webhook.go, gateway/webhook/integration_test.go, processor/manager.go, processor/manager_test.go, processor/processor.go, processor/processor_test.go, processor/stash/stash.go, router/batchrouter/batchrouter_test.go, router/batchrouter/handle.go, router/batchrouter/handle_lifecycle.go, router/batchrouter/worker.go, router/handle.go, router/handle_lifecycle.go, router/manager/manager_test.go, router/router_test.go
We are no longer be collecting errors in `proc_error` jobsdb as we are planning to remove error collection for debugging purposes in the near future. 
What was happening until now:
- rudder-server was collecting failed jobs from webhook, processor steps, router, and batchrouter, and was storing these failed jobs in the `proc_error` JobsDB.
- periodically, the `stash` processor component was creating backup files from the `proc_error` JobsDB and uploading them to `rudder-proc-err-logs` in object storage.
In the past, we relied on `proc_error` jobs for replays, but that’s no longer the case. At this point, it feels like we’re spending unnecessary resources collecting and storing all this information which no-one actually needs, using as an excuse that it is useful for debugging purposes…
As …
=> chore: stop collecting errors in proc_error jobsdb

warehouse/internal/loadfiles/loadfiles.go, warehouse/internal/loadfiles/loadfiles_test.go, warehouse/internal/loadfiles/mock_loadfile_repo_test.go, warehouse/internal/loadfiles/mock_stagefile_repo_test.go, warehouse/internal/model/load.go, warehouse/internal/repo/load.go, warehouse/internal/repo/load_test.go, warehouse/internal/repo/repo_test.go, warehouse/internal/repo/staging.go, warehouse/internal/repo/staging_test.go, warehouse/internal/repo/table_upload_test.go, warehouse/router/testdata/sql/stats_test.sql, warehouse/router/upload_stats_test.go, warehouse/router/upload_test.go
Since we ran migration for all the deployments, a valid load file doesn't have null upload-id anymore. So this PR updated the code to reflect the same.
=> chore: remove null handling of upload id in load files

warehouse/api/http.go, warehouse/internal/api/http.go, warehouse/internal/api/http_test.go, warehouse/internal/repo/staging.go, warehouse/internal/repo/staging_test.go
- Remove the `enableStagingFileSchemaSnapshot` flag-based changes.
- Stop populating the schema while inserting the staging file.
- Remove unmarshalling and deep equals.
- Resolves WAR-906
=> chore: cleanup for schema snapshoting

Makefile, warehouse/api/grpc.go, warehouse/api/grpc_test.go, warehouse/api/http.go, warehouse/api/http_test.go, warehouse/bcm/backend_config.go, warehouse/internal/repo/repo_test.go, warehouse/internal/repo/schema.go, warehouse/internal/repo/schema_test.go, warehouse/router/upload.go, warehouse/schema/schema_test.go
- When we fetch the schema from the warehouse, additional tables are also fetched, for which table-level schemas are also generated.
- Now, when these tables get deleted in the customer's warehouse, upon fetching the schema, we will not receive those. But since the table-level schemas got generated, they will be present.
- So, deleting those table-level schemas which are not part of the warehouse schema.
- Adding some logs to the `wh_schemas` repo.
- Resolves WAR-1078.
=> fix: remove unwanted table level schemas

go.mod, go.sum, services/dedup/dedup_test.go, services/dedup/keydb/keydb.go, services/dedup/keydb/keydb_test.go
Updating keydb client with the latest version.
We're introducing infinite retries with an exponential backoff.
If we were to return an error it would cause the processor to panic and I'd prefer to avoid that.
The idea is to get an alert on the number of retries and act on those.
For that purpose we're exposing [these metrics](https://github.com/rudderlabs/keydb/blob/v0.4.2-alpha/client/client.go#L160):
```go
c.metrics.getReqCount = c.stats.NewTaggedStat("keydb_client_req_total", stats.CountType, stats.Tags{
"method": "get",
})
c.metrics.getReqLatency = c.stats.NewTaggedStat("keydb_client_req_latency_seconds", stats.TimerType, stats.Tags{
"method": "get",
})
c.metrics.getReqFailures = c.stats.NewTaggedStat("keydb_client_req_failures_total", stats.CountType, stats.Tags{
"method": "get",
}) …
```
=> chore: updating keydb client

.github/workflows/builds.yml
Bumping rudderlabs/build-scan-push-action to 1.7.0
=> chore: update rudderlabs/build-scan-push-action to 1.7.0

enterprise/trackedusers/users_reporter.go, enterprise/trackedusers/users_reporter_test.go
Starting this month, we are using the new MTU logic. This PR cleans up the legacy MTU logic.
Resolves [OBS-883](https://linear.app/rudderstack/issue/OBS-883/clean-up-old-mtu-logic)
=> chore: clean up legacy MTU logic

services/dedup/db.go, services/dedup/dedup_test.go
* Renaming mirroring modes to avoid confusion.
* Adding gauge to show current dedup modes in Grafana dashboards.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-2373/keydb-follow-ups) >
=> chore: renaming mirroring modes

services/oauth/README.md
This PR adds comprehensive documentation for the OAuth module located at `services/oauth/` in the form of a README.md file. The documentation covers:
- Module overview and purpose
- Architecture and component breakdown
- Request lifecycle for both OAuth and non-OAuth destinations
- Control Plane contracts and API endpoints
- Configuration options and environment variables
- Public APIs and extension points
- Usage examples and code snippets
- Observability and metrics information
- Troubleshooting guidelines
- Maintenance notes
https://linear.app/rudderstack/issue/INT-4124/create-readme-for-oauth-module-in-rudder-server
=> chore: add readme for OAuth module

CHANGELOG.md
Syncing release v1.59.0 to main branch
fix: ut mirroring tests (#6341)
chore: upgrade build-scan-push-action to v1.8.0 (#6350)
=> chore: sync release v1.59.0 to main branch

warehouse/integrations/deltalake/deltalake_test.go, warehouse/integrations/redshift/redshift_test.go, warehouse/integrations/snowflake/snowflake.go, warehouse/integrations/snowflake/snowflake_test.go, warehouse/utils/utils.go, warehouse/utils/utils_test.go
- Pass the region in the AWS config session in case of using Rudder storage.
- Add tests for the use of the rudder storage use case.
- Resolves WAR-1142
=> fix: aws session config region

router/throttler/factory.go, router/throttler/factory_test.go
Redis throttler configuration collides with throttling configuration for REDIS destination, since viper treats yaml configuration keys in a case-insensitive manner
resolves PIPE-2412
=> fix: naming collision in redis throttling configuration

go.mod, go.sum, services/dedup/dedup_test.go, services/dedup/keydb/keydb.go
Updating keydb to use new client with consistent hashing.
Fixes [PIPE-2437](https://linear.app/rudderstack/issue/PIPE-2437/keydb-fix-flaky-test)
=> fix: keydb consistent hashing

gateway/webhook/webhook.go, gateway/webhook/webhook_test.go
1. When webhook requests are processed, they go through a batch transformation process
2. If any failures occur during transformation (either batch-level or individual request level), the system creates `FailedWebhookPayload` objects
3. These failed payloads are then passed to `SaveWebhookFailures` method
4. This method can be implemented by different services (like ingestion-svc) to handle these failures appropriately
5. In the context of ingestion-svc, these failures are published to proc errors for further processing
pipe-2448
=> fix: save webhook failures

router/batchrouter/asyncdestinationmanager/snowpipestreaming/discards.go, router/batchrouter/asyncdestinationmanager/snowpipestreaming/snowpipestreaming.go, warehouse/slave/worker.go, warehouse/slave/worker_test.go
Enhanced the warehouse schema change handling to properly support integer to float datatype coercion across all warehouse destinations.
For all warehouses, if inferred datatype was int, we used to convert value to int explicitly. [Code Ref](https://github.com/rudderlabs/rudder-server/blob/master/warehouse/slave/worker.go#L404)
In case, inferred Data type from event payload was int and existingDatatype in WH was float, old logic in handleSchema used to explicitly check int type, else it used to consider it as error scenario. This used to work for all warehouses, as we used to convert value to int explicitly. [Code Ref](https://github.com/rudderlabs/rudder-server/blob/master/warehouse/slave/worker.go#L404)
For Snowpipe streaming, such mismatch meant int values will go to rudder_discards.
As …
=> fix(warehouse): int to float datatype handling

enterprise/reporting/reporting.go, enterprise/reporting/reporting_test.go
Fixing the panic caused due to `maxLen != prefixLength + suffixLength` for event name
https://rudderlabs.slack.com/archives/C02HCFVJVAR/p1759820729096899?thread_ts=1759820535.227109&cid=C02HCFVJVAR
.
=> fix: reporting event name trimming configuration

enterprise/reporting/error_extractor.go, enterprise/reporting/error_extractor_test.go, enterprise/reporting/error_reporting.go
This PR enhances the HTML detection logic in error message handling and adjusts message truncation configuration for more flexible error reporting.
- **Enhanced HTML Detection**: Improved isHTMLString function to detect additional HTML patterns:
- DOCTYPE html with html tags
- html with title tags
- html with head tags
- Existing body tag detection
- **Configuration Adjustment**: Changed maxMessageLength scaling factor 10 to 1 and increased length to 200 so effectively (`100*10 -> 200*1`)
- **Test Updates**: Updated test expectations to reflect the new truncation behavior and added comprehensive test coverage for the improved HTML detection
Resolves https://linear.app/rudderstack/issue/INT-4198/on-call-oct-01-07-dilip-progress-on-following-tasks
=> fix: improve HTML error extractration and truncation limits
