- config/config.go
- main.go
This change removes the default Bugsnag key and requires the developer to obtain their own.
To support this, `config.GetRequiredEnv()` is added, to retrieve a environment variable but fail if not present.
> Remove default Bugsnag key

- gateway/gateway.go
Instead of failing silently if the ListenAndServe() call fails, display an error and exit.
> Wrap ListenAndServe() in gateway with error check.

- config/backend-config/backend-config.go
- config/backend-config/multi-workspace-config.go
- config/backend-config/workspace-config.go
- config/config.go
- config/config.toml
- gateway/gateway.go
Gets workspace config from a local json. Make rudder-server work without config.toml file.
> Get backend config from file

- README.md
- utils/misc/misc.go
There's an issue related to `RUDDER_TMPDIR` when I run rudder-server in Centos 7 with suppervisord. This causes the server crash and falling back to `degraded` mode.
Solution for `*unix` system: fallback to `/tmp` if this folder exists
> Fallback for RUDDER_TMPDIR

- LICENSE
Hello from the hacker news thread... https://news.ycombinator.com/item?id=22637302
This might seem a picky... 
In the HN thread there was reference to the migration from SSPL to AGPLv3 License. That's cool & the repo was just updated to remove the SSPL reference a few minutes ago.
However, I think if you're going to want broader adoption (again which I know this could come across as picky)... there should be a license file that enterprise scanning tooling can read. (I used the Github Template so that it also displays the license badge here...)
Bonus points for more information about the decision to change the license to be linked in a comment below. 
Don't mean to bust your chops @soumyadebm - in my past enterprise experience, this clarity could be the difference in a developer being able …
> AGPL License File

- main.go
- processor/processor.go
- replay/replayconfig.go
Replay Processor is move to its own package, separated from processor implementation.
Replay has now its own main loop, and backend config subscriber.
Current implementation is using the Processor's configuration controlling main loop's time.
It also does not include any stats.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/239)
> Separate replay implementation from processor

- processor/integrations/integrations.go
- processor/processor.go
This is to decide if we should group events based on userId in custom transformer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/262)
> Send process sessions as a query parameter to transformer

- gateway/gateway.go
Dedupe can remove the wrong messages from a batch due to a logic error.
Steps to reproduce:
```go
body := []byte(`{"batch":["a","b","c","c"]}`)
messageIDs := []string{"a", "b", "c", "c"}
allMessageIDsSet := map[string]struct{}{"a": struct{}{}}
writeKey := "writeKey"
writeKeyDupStats := map[string]int{}
c := &HandleT{}
c.dedup(&body, messageIDs, allMessageIDsSet, writeKey, writeKeyDupStats)
```
Expected result:
```
{"batch":["b","c"]}
```
Actual result:
```
{"batch":["a","b"]}
```
The fix is pretty simple.  
The logic functions correctly when `toRemoveMessageIndexes` is sorted.
Normally I would write a failing test, but this method has no tests and is not easily testable because the badger client is referenced directly within the function rather than through an interface so it can't be …
> Fixes bug in dedupe logic

- processor/transformer/transformer.go
Receiving an apiVersion as a response header for destination transformations to check against a supported version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/380)
> Api Version for backend compatibility <-> transformer

- admin/admin.go
- build/Dockerfile-aws
- build/Dockerfile-aws-dev
- config/backend-config/admin.go
- config/backend-config/backend-config.go
- config/config.go
- gateway/admin.go
- gateway/gateway.go
- jobsdb/jobsdb.go
- main.go
- mocks/jobsdb/mock_jobsdb.go
- router/admin.go
- router/batchrouter/admin.go
- router/batchrouter/batchrouter.go
- router/router.go
- utils/misc/misc.go
- warehouse/admin.go
- warehouse/scheduling.go
* Removed debugStack and writeKeys endpoints in gateway and moved to this admin interface
* Added support for getting pprof heap profile for a running server
* Refer https://github.com/rudderlabs/rudder-cli/pull/2/files for rudder-cli changes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/389)
> Adds admin interface using rpc over a unix socket

- warehouse/bigquery/bigquery.go
Fixes #357 
When setting the location in the connection credentials, I expected the Dataset to be created in this location, but it was created in the US.
This commit fix this behaviour by using the "location" configuration (and defaulting it to `US`).
---
To test this, create a BigQuery destination with a location different than US (such as EU). The dataset when created will be in the given location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/358)
> BigQuery Warehouse - Fix DataSet Location

- warehouse/warehouse.go
this is a bug that fetches first 10 records and sends it to the destination debugger. but the actual use case is to fetch last 10 records order by updated_at asc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/455)
> warehouse destination debugger bug

- gateway/gateway.go
TotalEventsInReq is zero except for batch calls. this is leading to wrong metrics which depend on this variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/616)
> fix toltalEventsInReq for track, identity, ... calls

- gateway/gateway.go
I'm not sure exactly which time complexity the original code falls under (e.g. O(n^2) ), but the problem only becomes apparent with larger batch sizes. Batches larger than ~ 400 events were causing severe performance issues.
[K6](https://k6.io/) results locally with batch size of 400
```
before 
scenarios: (100.00%) 1 scenario, 200 max VUs, 1m30s max duration (incl. graceful stop):
* constant_request_rate: 2.83 iterations/s for 1m0s (maxVUs: 100-200, gracefulStop: 30s)
iteration_duration.........: avg=616.1ms  min=575.44ms med=607.48ms max=907.34ms p(90)=643.99ms p(95)=663.54ms
after
scenarios: (100.00%) 1 scenario, 200 max VUs, 1m30s max duration (incl. graceful stop):
* constant_request_rate: 2.83 iterations/s for 1m0s (maxVUs: 100-200, gracefulStop: 30s) …
```
> Improve performance of batch request worker

- services/stats/stats.go
Stats tags format was only made configurable on the taggedClient when it should have been applied to both clients
Original work missed configuring this client:
https://github.com/rudderlabs/rudder-server/pull/832
> Use getTagsFormat for normal stats

- .github/workflows/verify.yml
- Makefile
- mocks/app/mock_app.go
- mocks/app/mock_features.go
- mocks/config/backend-config/mock_backendconfig.go
- mocks/jobsdb/mock_jobsdb.go
- mocks/rate-limiter/mock_ratelimiter.go
- mocks/router/mock_network.go
- mocks/router/transformer/mock_transformer.go
- mocks/services/debugger/uploader.go
- mocks/services/dedup/mock_dedup.go
- mocks/services/filemanager/mock_filemanager.go
- mocks/utils/logger/mock_logger.go
- mocks/utils/mock_pubsub.go
- mocks/utils/sysUtils/mock_archive.go
- mocks/utils/sysUtils/mock_compress.go
- mocks/utils/sysUtils/mock_http.go
- mocks/utils/sysUtils/mock_httpclient.go
- mocks/utils/sysUtils/mock_io.go
- mocks/utils/sysUtils/mock_os.go
- mocks/utils/types/mock_types.go
This PR addresses two issues:
1. People forgetting running `go generate` after making changes to a particular interface, or more commonly people forgetting to commit those files.
2. People with different tools version `gomock` in our case, generating mock files with small differences everytime they prepare a PR. For instance, the following changes are only related to gomock version differences.
```diff
diff --git a/mocks/app/mock_app.go b/mocks/app/mock_app.go
index 58bc44b..aaf1a94 100644
--- a/mocks/app/mock_app.go
+++ b/mocks/app/mock_app.go
@@ -5,35 +5,36 @@
package mock_app
import (
+	reflect "reflect"
+
gomock "github.com/golang/mock/gomock"
app "github.com/rudderlabs/rudder-server/app"
-	reflect "reflect"
)
-// MockInterface is a mock of Interface interface
+// MockInterface is a …
```
> Verify `go generate`d files are committed and gomock@1.6 is used

- docker_test.go
- gateway/gateway.go
- gateway/gateway_test.go
- gateway/webhook/webhook.go
- gateway/webhook/webhookTransformer.go
- processor/processor.go
- processor/transformer/transformer.go
- router/network.go
- router/network_test.go
- router/transformer/transformer.go
- services/alert/pagerduty.go
- services/alert/victorops.go
- services/db/recovery.go
- services/debugger/uploader_test.go
- services/filemanager/filemanager.go
- services/sql-migrator/migrator.go
- tests/helpers/helpers.go
- tests/load/correctness.go
- tests/load/genload.go
- utils/logger/logger.go
- utils/misc/misc.go
- utils/sysUtils/io.go
- utils/tests/GA/GAcheck.go
- warehouse/redshift/redshift.go
- warehouse/warehouse.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
No breaking changes.
A small refactoring.
> refactor: move from io/ioutil to io and os package

- router/transformer/transformer.go
Fix for payload value being set to nil upon retry of response transform, as the length of the reader (*strings.reader) type was not set to 0 during retry. Hence used Seek from `i.o.Seeker` interface to set the offset of the payload on retry
> Response transform, fix for empty payload on response transform retry

- config/config.yaml
- main.go
- processor/processor.go
**Fixes** # [(*issue*)](https://www.notion.so/rudderstacks/Event-Delivery-disruption-d0ac4fa62da54e91838eaa96fd10ac5d)
Patch to remove unsafe db_read cursor technique, this is a patch, not a proper cleanup. The cleanup of code related to this feature will happen in another PR.
Also set:
```
JobsDB:
gw:
enableWriterQueue: false
```
as is the default every customer is using but not used for dev cluster or local testing.
Also added metrics and logs for detecting job_id gaps and out of order.
> Disable cursor  reading, event_count flag, checks for out of order/sequence

- build/Dockerfile
```
> [8/8] RUN go install:
#12 43.97 # github.com/DataDog/zstd
#12 43.97 cgo: exec gcc: exec: "gcc": executable file not found in $PATH
```
> Add build-base to fix missing gcc

- router/batchrouter/batchrouter.go
- router/router.go
**Fixes** # 
We were saving (in proc errors) the reason why router jobs are aborted, but not for batch router jobs. This PR addresses it.
> save abort reason in proc errors for brt

- gateway/gateway.go
Pending events endpoint is always returning 500. This fixes the condition.
> Sources enchance fix

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/processorAppHandler.go
**Fixes** # 
When workspace token is changed, rudder-server renames the existing jobsdb and starts with a fresh one. In such scenario, node migrations are not getting applied on the new jobsdb. This pr fixes the order in which new db is created & migrations are applied.
> correct the order of node migrations

- config/config.yaml
…to 1 worker for event consistency
We are seeing events getting updated instead of getting appended we are pushing from parallel workers, from the google side we are not seeing a consistency guarantee, also there exist aggressive rate limits with sheets API. Hence to resolve the issue we are limiting Sheets to 1 worker per Router
> Limiting each google-sheets destinations to 1 worker for event consistency

- gateway/gateway.go
**Fixes** # 
Times are reported incorrectly because the execution of the parameters passed to the function happens immediately. This pr fixes it.
> gw-time-stats-fix

- services/filemanager/s3manager.go
Temporary fix to address panic when `resp.IsTruncated` is nil
> Check ptr not nil before dereference 

- event-schema/event_schema.go
- jobsdb/jobsdb.go
- processor/processor.go
- processor/transformer/transformer.go
- utils/misc/misc.go
- warehouse/slave.go
Certain logs are frequently repeated and are no longer useful. Metrics and pprof endpoint, can be used for debugging this situations.
Those logs create noise when debugging an issue locally, prod, even tests!  
Also they increase the cost of storage and the time to query the logs in general.
[notion
](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=b53cf35b1d724079aff2790c3255e721)
> Remove spammy logs

- gateway/gateway.go
- gateway/gateway_test.go
`misc.Contains` is a computationally expensive function since it is using reflect.
1m CPU sample of hosted:
`misc.Contains` is replaced with a simple map lookup.
What misc.Contains was doing:
```go
func Contains(in interface{}, elem interface{}) bool {
inValue := reflect.ValueOf(in)
elemValue := reflect.ValueOf(elem)
inType := inValue.Type()
switch inType.Kind() {
case reflect.Map:
for _, key := range inValue.MapKeys() {
if equal(key.Interface(), elem) {
```
First, it reflect both on in and elem values.
If ti was a map, it was iterating all the map keys and comparing their interfaces - this comparison was doing:
```go
func equal(expected, actual interface{}) bool {
if expected == nil || actual == nil {
return expected == actual
}
return reflect.DeepEqual(expected, …
```
> Remove costly reflection compare

- router/router.go
- router/router_test.go
Attempts to fix the BlockJobID crash in cases where router batching is enabled.
Does so by marking the failed job with least jobID as failed and others as waiting, and adding that jobID to the failedMap.
> Router jobid crashfix tests

- sql/migrations/jobsdb/000006_alter_dataset_table.up.tmpl
`AFTER` is not supported in Postgres, was added by mistake.
> Fix migration file

- app/apphandlers/setup.go
- router/batchrouter/batchrouter.go
- router/batchrouter/batchrouter_test.go
- router/router.go
- router/router_test.go
Cleaning up router tables during startup per router takes huge time when there are too may router tables. Pulled cleanup out of router and doing it once for all the routers.
> moved deleteexecuting out from router. Doing it once for all routers.

- jobsdb/jobsdb.go
Because the variables inside cacheEntry struct start with lowercase, they aren't json marshalled properly. The response we see when investigating jobsdb cachemap using rudder-cli is incorrect. This fixes it.
> correct-marshalling-cacheEntry

- services/dedup/dedup.go
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=6b928ca0c96642019a931d889f6d1039
This is a quick fix for a critical dedup issue. A PR with other improvements and testing is being prepared as well.
We were configuring `dedupWindow` in seconds https://github.com/rudderlabs/rudder-server/blob/39c312d6a18cd8e8a8e1e6807309c500078a71a3/services/dedup/dedup.go#L41
And then [multiply with time.Seconds](https://github.com/rudderlabs/rudder-server/pull/1657/files#diff-0fec60879512f77a2e223aa0353389b5efb1f9cdfdf9b723b59681a41c581346L113) again, going from `1h0m0s` to `801362h40m26.63743488s` - essentially for ever.
Entries never expired and thus disk usage kept growing.
Stop multiplying with `time.Seconds`. Unfortunately, we can not pick a …
> Fix expiration value for entries TTL

- .github/workflows/tests.yaml
integration test was running twice in the default integration test, no need for that:
```yaml
- run: go test -v ./docker_test.go -integration -count 1
- run: ENABLE_MULTITENANCY=false go test -v ./docker_test.go -integration -count 1
```
fixed since it was taking more time
> Run docker test only once

- router/router.go
Lets the router worker mark  a job as waiting only if they follow a `non-terminal` job for a user.
Previous behaviour was to mark any job following a `non-succeeding` job of a user as waiting.
> isSuccessStatus->isJobTerminated

- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/setup.go
We wanted to be able to Start and Stop jobsdb, in order to get to degraded mode without process restart. 
Moreover, we would like to maintain the database connection, so start/stop should have the minimum amount of performance impact while remaining safe.
Our goal with this change is to maintain backward compatibility and minimise the number of changes.
For this, we came up with a new interface, while keeping the existing one intact.
The new methods (& function) are:
* New()
* .Start()
* .Stop()
* .Close()
They meant to be symmetric:
```go
gw := New()
defer gw.Close()
gw.Start()
defer gw.Stop()
// jobsdb can be used now
// and will safely close
``` 
```go
gatewayDB.Setup(jobsdb.ReadWrite, options.ClearDB, "gw", gwDBRetention, migrationMode, true, jobsdb.QueryFiltersT{})
defer …
```
> New jobsdb Lifecycle control

- gateway/gateway.go
- jobsdb/readonly_jobsdb.go
- router/transformer/transformer.go
Pending events optimization: Break after non zero jobs found in a table.
Change count functions return types from int to bool to make more readable.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=82b289382ef044338ad3a8567ae5d0d9
> Hosted Pending Events Fix

- build/Dockerfile-aws
- build/Dockerfile-aws-dev
- build/docker-entrypoint.sh
Add and use bash to run our entrypoint.sh script. Latest alpine versions have introduce a `sh` shell that didn't support our syntax.
[Notion Link](https://www.notion.so/rudderstacks/Fix-entrypoint-sh-script-issue-f185b8c0e23a4339baba2d8f783cb3e5)
> Use bash to run entrypoint script

- services/pgnotifier/pgnotifier.go
> Remove batch id from stats as it has high cardinality
> [Notion Link](https://www.notion.so/rudderstacks/Remove-batchId-from-stats-high-cardinality-0f25e8dfcddd4c76a8fe1194dd5d9cbf)
> Remove batch id from stats as it has high cardinality

- config/config.yaml
- processor/processor.go
The processor can get stuck under some conditions. We know that in this case writes to batchrouter (or router) at wait for a very long time or forever.
We still have found the root cause of this issue, but given the urgency and impact of this problem, we would like to provide quick mitigation.
**Note**: we could have also used metrics, to automatically restart the server and avoid this hack. However, automatic actions based on metrics are only available for Prometheus alerts, not Kapacitor.
When the store method is called, we create a context with a timeout. We check in a goroutine if the context is Done due to Deadline, if yes then we panic.
It might seem crude way but is better to panic than block forever. Unfortunately, there wasn't any easy way to exit gracefully.
I've set the timeout …
> Mitigation for stuck processor: Panic on processor store timeout

- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
computeInsertVals function goes into infinite loop, when before and after are given as follows:
before: 10_1
after: 10_2.
This pr fixes the bug and adds some safe checks.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=98a1ca1d4c5f429b9116fa0eb1652714
> compute index fixes

- jobsdb/jobsdb.go
When we evaluate the datasets eligible for internal migration, we don't have to check the right most dataset. This pr makes sure that we dont call checkIfMigrateDS on the right most dataset by breaking out of the loop.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=cbaf61884eef45fbbb49da47a6d0b60f
> fix order of checkifmigrate function

- warehouse/bigquery/bigquery.go
> Dedup big query tables on flag isDedupEnabled
> [Notion Link](https://www.notion.so/rudderstacks/Dedup-on-bigquery-5384cb414b544e2ab6e1f2d37e57e274)
> Dedup bigquery tables

- jobsdb/jobsdb.go
- jobsdb/jobsdb_import.go
If server crashes (panics)  while the `migrateDSLoop` is running and has managed to create a new `dataSet` but has not managed to mark the start of copy operation in the journal yet, then the dataSet's tables are not cleaned up during recovery.
This fix reverses the order of actions so that the copy operation is recorded in the journal before any new dataSet gets created. To achieve this, `HandleT#addNewDS` method had to be refactored to accept the `dataSetT` to be created as a parameter instead of calculating it within the method's body  based on the previous method parameters. Due to this change, all invocations of this method had to be adapted as well.
_**Hint:**_
The jobDB's journal table appears to be a poor man's method for performing transaction demarcation. To understand this a …
> Fix: Jobsdb migration bug

- build/buildspec.docker.dev.yml
- processor/processor.go
- processor/processor_test.go
> Properly drop unsupported events, so that there's no ambiguity from a metrics standpoint.
> https://www.notion.so/rudderstacks/Filtered-events-should-not-shown-in-live-events-should-not-be-reported-as-failed-events-c9033e7484f04412af3028e5e22a5a8c
> dropUnsupportedEvents

- .github/workflows/handle-stale-pr.yaml
We need to reduce the overal repo noise. One of the action items we came up with is to automatically annotate PR to be `Stale` after 20 days of inactivity.
Every `Stale` annotated PR is going to be closed and the related branch to be deleted after 7 days of inactivity. 
https://www.notion.so/rudderstacks/GHA-Mark-and-close-stale-PRs-fa4dd98cef2846b3bf82f18e2f3ec909
> Feat[github]: stale PR handling

- app/apphandlers/embeddedAppHandler.go
- services/multitenant/legacy.go
`multitenantStats` are responsible for two things:
1. Collect input/output jobs from processor/router
2. Determine the number of pickup jobs based on collected stats
Until [pending-event metrics PR](https://github.com/rudderlabs/rudder-server/pull/1736), there was a flag to enable/disable `multitenantStats` via `EnableMultitenancy`.
After pending-event metrics, the `multitenantStats` are always enabled.
This PR enables/disables only the `pickup jobs` functionality depending on the `EnableMultitenancy` flag.
> [Notion Link
](https://www.notion.so/rudderstacks/Use-legacy-pickup-algorithm-on-non-multi-tenant-environments-7474d1ff5dac489a902ec64e7d8ad75b)
> Use legacy pickup algorithm on non multi-tenant environments. 

- router/batchrouter/batchrouter.go
Whenever the server crashes , on restart it performs a crashRecover on all the components to ensure that all the dangling/incomplete operations are cleaned up. The crashRecover in `batch_router` component performs a function called `dedupRawDataDestJobsOnCrash` where the idea essentially is to ensure we do not upload duplicate files/events to the destination(i.e crash between uploading to the destination and storing the job status).We have all such entries in journalTable  and such entries are deleted post successful updation of `job_status` table.
The current `batch_rt_journal` table has very old unsuccessful entries because we fail to download those files from the objectStorage but do not remove them from journal table causing the `crashRecover` to retry these jobs every time a restart …
> Remove entries from journal with download error

- app/cluster/integration_test.go
- testhelper/destination/kafka.go
Our current tests on`master` are commonly failing for two reasons:
1. TestDynamicClusterManager is failing
2. Clickhouse network is unable to create a network with the desired subnet. This appears to be side-effect of not deleting each kafka network that we create during docker testing.
Note: The subnet used by the kafka network is now printed to facilitate troubleshooting in potential conflicts in the future.
[Notion Link](https://www.notion.so/rudderstacks/Fix-failing-CI-due-to-TestDynamicClusterManager-and-docker-network-leftovers-20efc40b287b4dbeb2cbc99de5c53390)
> Cleanup docker kafka network and skip failing TestDynamicClusterManager

- .github/workflows/handle-stale-pr.yaml
Since we use the repo GITHUB_TOKEN we can increase the operations limit to 200 so as all PRs are included on every execution round.
> Notion Link
> Config[gha]: increase the limit for stale pr managment

- services/multitenant/tenantstats.go
> There was a bug in mutitenanat stat, when creating NewStat we were not storing the routerDBs which was creating issues for lifecycle Manager.
> [Notion Link](https://www.notion.so/rudderstacks/Integration-of-Cluster-Manager-451b5da33c2944919996532b8d8d1a0e)
> tenantStat empty map bg fixed

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/processorAppHandler.go
- app/apphandlers/setup.go
- operation-manager/clear-queue-manager.go
- processor/processor-manager.go
* removed unnecessary types and abstraction in the processor manager
* made some types unexported for better encapsulation
* removed `Processor` as a prefix to types given that the package name already has the word `processor` it is not needed (it is also an issue highlighted by linters)
* using private `processorManager` interface to decouple `operation-manager` package from `processor`
* removed `enableProcessor` and `enableRouter` from `StartProcessor` and `StartRouter` functions due to `Control-coupled functions detected: RVV-A0005`
* replaced errgroup with WaitGroup because usage of contexts and ignoring error made it unnecessary
[> Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=d3806f442555412fb7c5c86a51ab2c11&p=c7e5e52686f04fd58b2b0ca96fa72845)
> Processor manager cleanup

- jobsdb/jobsdb.go
- jobsdb/jobsdb_import.go
During a migration or import, new tables get created and populated in bulk with a large amount of rows.
It is possible that the AUTOVACUUM process does not manage to analyze those tables before we start querying them
which will result in the database's query planner making wrong decisions that may lead to never-ending queries.
This fix makes sure that whenever data is inserted in bulk in JobsDB, affected tables are explicitly ANALYZEd
before we release them into the wild
**Refactoring Notes**
1. `updateJobStatusDS` was renamed to `copyJobStatusDS`.
2. Both `storeJobsDS` and `storeJobsDSInTxn` methods where using a `bool` method parameter as a control flag. This control parameter was removed from both methods and methods were split to (1) `storeJobsDS` & `copyJobsDS` and (2) …
> fix(jobsdb): execute ANALYZE after completing batch jobsdb operations

- router/router.go
In router, we have a statement which asserts that events from different sources connected to the same destination can't be batched. This is incorrect. Removed the assert.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a484a53a9b4448dabc5714d4f8e6c67e
> Notion Link
> remove incorrect assert which says events from different sources can't be grouped

- router/customdestinationmanager/customdestinationmanager.go
- router/router.go
- router/transformer/transformer.go
I was able to replicate the `panic` mentioned in the Notion ticket and noticed that the comparison with the source ID in each destination was done considering only the first `sourceID` encountered (i.e. `sourceID := destinationJob.JobMetadataArray[0].SourceID`) which made the following code fail.
Then I also realized that the `sourceID` is not really used by `SendData` so there shouldn't be a bug there. To make it more clear I dropped `sourceID` altogether.
> [Notion Link](https://www.notion.so/rudderstacks/Fix-panic-different-sources-are-grouped-together-in-router-a484a53a9b4448dabc5714d4f8e6c67e)
> fix(router): panic sources grouped together

- jobsdb/jobsdb.go
> Currently, when `BackupEnabled` is `true`, we try backing-up `pre_drop` tables to the configured bucket. And, drop the table only after the upload is successful. But, there is no upper limit on how many times (or for how long) we are going to retry in case of failure. Because of this, we end up retrying infinitely & never really drop the table if config is incorrect or if access key is has expired.
>We have introduced an `exponentialBackoff` retry mechanism with maximum retry time of 10 minute, i.e. if upload didn't succeed in 10 min, retry will be stopped & `pre_drop` tables will be dropped.
>Currently, we retry uploading a table for sometime & if it fails. We only drop that table & not all `pre_drop` tables. So, in situation when new table creation rate is more than drop. We will …
> fix: `pre_drop` table pileup issue

- warehouse/bigquery/bigquery.go
> Disable bq dedup by default with branch naming convention
> [Notion Link](https://www.notion.so/rudderstacks/Number-of-records-in-custoemr-BigQuery-does-not-match-the-records-ingested-shown-in-syncs-dashboar-91b17ea63a064a1ca9c141e27d1d7a71)
> fix: disable bq dedup by default

- .github/workflows/tests.yaml
- .gitignore
- Makefile
- build/buildspec.docker.dev-ent.yml
- build/buildspec.docker.dev.yml
* CI tests taking a lot of time 
* Slow to get a docker image for testing, since all tests had to run before
* Hard to debug failed tests in code build (require AWS access /w two-factor auth)
* Need to run tests under multiple configurations (matrix strategy & scalable GitHub action resources are perfect for that) 
* Ability to re-run tests
1. Run enterprise tests in GitHub actions, for this required a bot to be created for a PAT to be used.
2. Include `-bigqueryintegration` flag in integration tests and adding `BIGQUERY_INTEGRATION_TEST_USER_CRED` as a secret.
3. Improve code coverage [consolidation script](https://github.com/rudderlabs/rudder-server/pull/1852/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R20) 
4. Add codecov report  as GitHub action
5. …
> chore(ci): run all tests only in github actions

- .github/workflows/semantic-pr.yaml
Adding a new github action in order to automate PR title linting
https://www.notion.so/rudderstacks/Add-github-action-for-validating-semantic-PR-titles-342d159c51144467967ad12e20a12a68
> chore(ci): add github action for validating semantic PR titles

- .github/pull_request_template.md
The existing template had a few issues and was missing a reference to Pull Request description document.
I wanted to simplify the template and use other conventions and automation instead of the checklists.
**Problem with the checklists**:
Most of our PRs look like this:
That not a problem per se, but we can use the checklist to indicate work to be done in order to merge rather than optional checks.
**Type of change** -> checklist doesn't make sense, a radio button would, but we have the pattern of the PR name to convey the type. Automated labels can be used instead. Also, most people forget to check this button.
**Checklist** -> Most people tend to ignore this, let's use Github actions for:
* I have added unit tests for the code -> add a label if `_test.go` is detected in the changes.
* …
> chore(ci): simplify pr template

- warehouse/bigquery/bigquery.go
* Disable bq dedup by default
https://www.notion.so/rudderstacks/Number-of-records-in-custoemr-BigQuery-does-not-match-the-records-ingested-shown-in-syncs-dashboar-91b17ea63a064a1ca9c141e27d1d7a71
> fix: disable bq dedup by default (#1855)

- jobsdb/jobsdb.go
> `JobsDB.backup.enabled` config was not hot-reloadable till now, which means if we want to stop the tables backup while server is already running, that was not possible. Now this is hot-reloadable. Now if we switch this feature in config then the effect will take effect at-max in time which is defined by`JobsDB.backupCheckSleepDuration` config. 
> [Notion Link](https://www.notion.so/rudderstacks/Make-backup-config-masterBackupEnabled-hot-reloadable-4bf69e32c37a40f194749cb7e4633f1a)
> feat(jobsdb): made backup related config hot-reloadable

- build/Dockerfile
- build/Dockerfile-aws
- build/Dockerfile-aws-dev
- scripts/generate-event
- Also lint fixes on script and dockerfiles
An example of the usage for now would be to open a terminal inside the running container and execute the script in the `scripts` directory.
Currently when open source users are asked to generate an event to test their deployed rudderstack data plane, they need to clone the whole repository and then run the script, or download it locally. Adding the script to the image allows for quicker and simpler interaction with the deployed rudder-server. 
[Notion Link](https://www.notion.so/rudderstacks/Include-scripts-generate-event-in-OSS-docker-image-39079734c70d497bb0c4e98b0d9ea187)
> chore(ci): add generate event script to image

- router/batchrouter/batchrouter.go
- router/router.go
- services/metric/measurement.go
- services/multitenant/tenantstats.go
- services/multitenant/tenantstats_test.go
Aggregating metrics for all workspaces in InfluxDB through Grafana using a subquery is suboptimal and essentially prohibitive, performance-wise.
Setting up separate alerts per workspace is also not possible due to the high cardinality of workspaces in the hosted environment.
For all the above reasons, we need to calculate aggregated metrics along with the high-granularity ones.
https://www.notion.so/rudderstacks/Calculate-aggregated-pending_events-metrics-for-all-workspaces-57bb54cf65e94ebda818b62c1c6cbba9
> feat: calculate aggregated pending_events_count metrics for all workspaces

- processor/transformer/transformer.go
There were no timeout configured for transformer http client. This results in hanging client sometimes. Added client timeout to cancel the request after some duration.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=f430b15138a240f483df677993553d72
> fix: added http client timeout in processor transformer

- services/metric/measurement.go
Fix, using the correct measurement name and tags for aggregate metrics.
Previously the following measurement was recorded:
`jobsdb_ALL_pending_events_count workspace=ALL,destType=<type>`
Now:
`jobsdb_rt_pending_events_count workspace=ALL,destType=ALL`
`jobsdb_batch_rt_pending_events_count workspace=ALL,destType=ALL`
https://www.notion.so/rudderstacks/Use-the-correct-measurement-name-and-tags-for-aggregated-pending-events-metrics-dbfc88275e9e4652ad4067f58c24c214
> fix: use the correct measurement name and tags for aggregated pending events metrics

- config/config.go
- config/config_test.go
This pr adds support to hot-reload multiple config variables registered for the same key.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=33e351a631834eac9303d378d771a86e
> fix: support multiple configvars registration

- warehouse/configuration_testing/steps.go
- warehouse/configuration_testing/types.go
- warehouse/configuration_testing/validate.go
- warehouse/identities.go
- warehouse/stats.go
- warehouse/upload.go
- warehouse/upload_test.go
- warehouse/warehouse.go
Added ability to test the destination credentials once we have an aborted upload. We do this to better classify the alerts that systems fires off on aborted uploads.
[Ticket](https://www.notion.so/rudderstacks/Classify-upload_aborted-alert-as-user-vs-platform-caused-95a2a4ad15894c63809566210071362f)
> fix(warehouse): added ability to test destination credentials once the upload gets aborted

- warehouse/bigquery/bigquery.go
- Views not required in bqDedup method
- If switched to partition method from dedup
- required users_view will be created while loading users table
- views for new track events will be created
- skipped views will be left alone. customer can create view himself or make a request to us
https://www.notion.so/rudderstacks/skip-views-generation-when-dedup-is-enabled-in-BQ-2cbec577f93a4bc3abaea7b89c076c3e
> fix: disable creation of views when dedup is enabled in BQ

- services/pgnotifier/pgnotifier.go
> fix: Force set lower version during pg notifier sql migration

- router/router.go
- router/router_test.go
A few router destinations have introduced support for batching.
The way to configure the number of jobs a worker will receive is via `noOfJobsToBatchInAWorker` , which currently applies to all destinations.
However, this is not optimal for destinations that support batching, since they would work more optimally with a higher number of jobs.
With this change, we are able to set this number specifically per destination type. So destinations that support batching can be configured with higher numbers.
Note: The specific configuration for such destinations is not in the scope of this PR, it will be applied in a different PR/repository
<https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a6724a95111b45308beb9403c3ef556f>
> feat(router): enable batching config at destType level.

- .github/workflows/tests.yaml
Disable big query integration test for now.
https://www.notion.so/rudderstacks/Disable-big-query-integration-tests-for-now-a2c888eff448459ab46e0ec8886ca53a
> fix(warehouse): skipping bigquery integration test for now

- warehouse/configuration_testing/validate.go
Closing load file when creating load file during warehouse configuration test.
https://www.notion.so/rudderstacks/Fix-warehouse-configuration-test-for-closing-load-file-eb17eb411e774c2489d5af68b5e4620e
> fix(warehouse): closing file while creating load file for warehouse configuration test

- processor/processor.go
- utils/misc/misc.go
>In PR: https://github.com/rudderlabs/rudder-server/pull/1892,
in func  `newUserTransformationStat`, we modified 
`proc_num_ut_input_events` -> `proc_transform_stage_in_count`
`proc_num_ut_output_success_events` -> `proc_transform_stage_out_count`
`proc_num_ut_output_failed_events` -> `proc_transform_stage_error_count` 
but forgot to make modification at other similar places. So, those are fixed in this PR.
https://www.notion.so/rudderstacks/minor-metrics-name-fix-for-chore-enrichTransformationsMetrics-branch-PR-43f98884ee704f0ab42a1a57f41c9653
> chore: fix for `chore.enrichTransformationsMetrics` branch PR

- main.go
Currently, whenever warehouse pod crashes, Bugsnag sends alert to server team, instead of warehouse team. 
eg: https://app.squadcast.com/incident/627a4c7d1adea9000811385e
These alerts incorrect routing will be fixed with this PR.
https://www.notion.so/rudderstacks/bugsnag-false-routing-warehouse-one-coming-to-us-d4e4d771f3404b5f9ac6a9a779b10009
> fix: wrong routing of warehouse crash alerts

- rudder-docker.yml
To enable metrics to while deploying locally through docker compose
we added statsd-to-prometheus metrics exporter. In this sense we can
have prometheus metrics at: `localhost:9102/metrics`.
Also include env variables to project's docker-compose file.
https://www.notion.so/rudderstacks/Provide-or-disable-metrics-for-open-source-users-c6abd45ba9b24acea0a80d042f1be5ff
> fix(tooling): add prometheus endpoints for OSS users

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/processorAppHandler.go
- app/apphandlers/setup.go
- app/cluster/integration_test.go
- gateway/gateway.go
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_renameDs_test.go
- jobsdb/jobsdb_test.go
- jobsdb/prebackup/prebackup.go
- jobsdb/prebackup/prebackup_test.go
- jobsdb/unionQuery_test.go
- processor/manager.go
- processor/manager_test.go
- processor/processor.go
- processor/processor_test.go
- processor/stash/stash.go
- router/batchrouter/batchrouter.go
- router/batchrouter/batchrouter_test.go
- router/batchrouter/factory.go
- router/factory.go
- router/manager/manager_test.go
- router/router.go
- router/router_test.go
- router/utils/utils.go
- services/transientsource/transientsource.go
- services/transientsource/transientsource_test.go
- testhelper/destination/postgres.go
A **Source** can now be configured as `transient`. The system treats events of transient sources in the following way:
1. Events will not be backed up to the object storage.
2. Failed processor events will not be backed up in `rudder-processor-errors` either, this process is a.k.a `stash` internally.
3. Sample events will not be sent to the reporting service.
- Introduced `transientsource.Service` which is responsible for providing all required services pertaining to transient sources. There are 3 ways you can create a `transientsource.Service`
1. `transientsource.NewService` - creates a service which will listen for configuration changes and update its list of transient source ids automatically.
2. `transientsource.NewStaticService` creates a service which uses a static list of transient …
> feat(core): add support for transient sources

- app/cluster/dynamic.go
- config/backend-config/multitenant_workspaces.go
- config/backend-config/multitenant_workspaces_test.go
- main.go
Changes related to backend config URL for multi tenant backend config
https://www.notion.so/rudderstacks/Enhance-docker-compose-file-etcd-service-to-enable-rudder-server-testing-locally-14f0b3119d3d410f8c18331001196454
> fix(multi-tenant): multitenanat backend config

- docker-compose.yml
Added ETCD Based mode provider in docker-compose file. If you want to bring the mode provider service up then use `multi-tenant` profile with docker compose command. 
[Reference](https://docs.docker.com/compose/profiles/)
[Ticket](https://www.notion.so/rudderstacks/Enhance-docker-compose-file-etcd-service-to-enable-rudder-server-testing-locally-14f0b3119d3d410f8c18331001196454)
> feat(multi-tenant): add mode provider in docker-compose file

- main.go
Fix to allow usage of stats in Kafka manager. `kafka.Init()` was called after `stats.Setup()` causing a `panic`.
> fix: enabling earlier usage of stats in other components

- docker_test.go
- services/streammanager/kafka/client/client_test.go
- services/streammanager/kafka/kafkamanager_test.go
Converting flag to simple `os.Getenv`.
> fix: ovverride arm64 check

- warehouse/snowflake/snowflake.go
Fixing timeout issue for snowflake. By default snowflake GO SDK expects the timeout to be seconds which can be found from [here](https://github.com/snowflakedb/gosnowflake/blob/d34ce5fe3a421fc2a2d9283b703ad670bbc2a0e5/dsn.go#L160)
https://www.notion.so/rudderstacks/Verify-snowflake-timeouts-for-validation-f924ebbef7c643d5b2857fbf446cff4f
> fix(warehouse): fixing timeout issue for snowflake

- app/cluster/state/etcd.go
- app/cluster/state/etcd_test.go
Changed the ETCD key for workspace ID changes to `/<releaseName>/server/<serverIndex>/<app_type>/workspaces` from `/<releaseName>/server/<serverIndex>/workspaces` to include the app type also.
This is to give control to the schedular to first change the workspace IDs for Processor and then for the Gateway so that we don't loose any data. This include a risk of having dirty value (not consistent IDs for both the apps) but this is once in a million kind if possibility. 
[< Notion Link >](https://www.notion.so/rudderstacks/Change-workspace-ID-change-ETCD-Key-74b92e2a62664132816a4f4475563c60)
> chore(multi-tenant): change workspace change ETCD key

- app/cluster/dynamic.go
- app/cluster/state/etcd.go
- config/backend-config/multitenant_workspaces.go
- config/config.yaml
Use hosted backend config URL to fetch the backend config for multi-tenant as well because multi-tenant backend config cannot handle the requests with more than 250 workspace IDs. 
[Slack Thread](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1652791374640159)
To enable this flow, we have introduced a config variable with the name `BackendConfig.useHostedBackendConfig` which if true, multi-tenant will use hosted backend config URL.
[Notion](https://www.notion.so/rudderstacks/Use-hosted-backend-config-for-multi-tenant-230fa4c9e83b48fa9f940ea6ffc3310f)
[Slack](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1652797690847909?thread_ts=1652796871.012809&cid=C01HTT66UMB)
> chore(multi-tenant): add hack for MT to use hosted backend config

- app/cluster/dynamic.go
In case of gateway app, processor and router doesn't gets initialized in cluster manager so in we stop the cluster manager we have to skip stopping processor and router.
[ Notion Link ](https://www.notion.so/rudderstacks/Don-t-stop-gateway-from-cluster-manager-b4abf33dcef2452fbddde69798bf6929)
> chore(multi-tenant): not stop gateway from cluster manager

- warehouse/warehouse.go
Started capturing metrics for warehouse scheduling thus enabling deeper analysis into the operational efficiency.
[Ticket](https://www.notion.so/rudderstacks/Create-metrics-for-warehouse-scheduler-lag-measurement-7e515ac773af4509b8c61529b4070103)
> feat(warehouse): added metrics for capturing stats in warehouse scheduling

- warehouse/schema.go
- warehouse/schema_test.go
- warehouse/slave.go
warehouse schema int to float schema fix
https://www.notion.so/rudderstacks/Storing-nulls-when-int-value-is-received-for-a-float-column-f3eda9d87d7b44f89a13f63595a7a1c3
> fix(warehouse): warehouse schema int to float schema fix

- warehouse/deltalake/deltalake.go
HotFix for warehouse deltalake users table getting populated corruptly.
https://www.notion.so/rudderstacks/Deltalake-users-table-corrupt-data-9c9069da5e1049ca94827e7a08473562
> fix(warehouse): deltalake users table getting populated corruptly.

- jobsdb/jobsdb.go
With the new multi-tenant migrator approach we will have tables created with index 0 which might undergo internal migrations but the current new calculation assumes that we cannot have `_0` indices and can have only `_0_1` indices. This PR aims to skip this assert behind a flag before we find a cleaner approach to maintain backwards compatibility
[Notion Link](https://www.notion.so/rudderstacks/Don-t-create-0_0_1-index-for-tables-fcc14c3da3cf47c6a0e9da79dde99b51)
> chore(jobsdb): skip zero assertion for multitenant internal migrations

- app/cluster/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
- processor/processor.go
- processor/processor_test.go
With the new multi-tenant migrator approach we will have tables created with index 0 which might undergo internal migrations but the current new calculation assumes that we cannot have _0_1 indices and can have only _0_0_1 indices. This PR aims to generate the _0_1 indices behind a flag 
[Notion Link](https://www.notion.so/rudderstacks/Don-t-create-0_0_1-index-for-tables-fcc14c3da3cf47c6a0e9da79dde99b51)
> chore(jobsdb): fix migration sequence number for multitenant migration

- .github/workflows/housekeeping.yaml
Automatically delete stale branches.
Stale branch: 
- 2 months with no commit
- no open PR relates
- non main/master/release prefixed branches
> chore(ci): add stale branch clean up support

- config/backend-config/backend-config.go
- services/transientsource/transientsource.go
- services/transientsource/transientsource_test.go
Instead of relying to the source's generic config, use a static, top-level field for identifying transient sources.
[Identify transient sources through a top-level configuration field](https://www.notion.so/rudderstacks/Identify-transient-sources-through-a-top-level-configuration-field-2d03022b25564dbaac90421ec2f21afd)
> chore: identify transient sources through a top-level configuration field

- gateway/gateway.go
- gateway/gateway_test.go
- gateway/response/response.go
We try to type cast the event to a map[string]interface but do not check if the typecast was a success or a failure. This PR rejects the events at gateway if the typecast fails
```
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}
goroutine 570 [running]:
github.com/rudderlabs/rudder-server/gateway.(*HandleT).userWebRequestWorkerProcess.func1({0xc000e36a00, {0x0, 0x4c5}, {0x7fc3d3744d01, 0x500}, 0x3325de0, 0xc000e36a00, {0x0, 0x0, 0xc00c842950}}, ...)
/codebuild/output/src654764301/src/github.com/rudderlabs/rudder-server/gateway/gateway.go:499 +0x85a
github.com/tidwall/gjson.Result.ForEach({0x5, {0xc000e36a00, 0x4c5}, {0x0, 0x0}, 0x0, 0x9, {0x0, 0x0, 0x0}}, ...)
/go/pkg/mod/github.com/tidwall/gjson@v1.10.2/gjson.go:282 +0x485 …
```
> chore(gateway): reject the event if it's not valid map

- Dockerfile
- build/buildspec.docker.dev-ent.yml
- build/buildspec.docker.dev.yml
- docker-compose.yml
Part of our release 2.0 process
1.  Multi docker files `Dockerfile`, `Dockerfile-aws`, `Dockerfile-aws-dev` that we have to test and maintain.
2.  In most cases, the build process happens outside Dockerfile. Making it hard to build docker images outside code build.
A new `Dockerfile` is introduced in this PR, used for local `docker-compose` usage and PR builds.
The new image has a multi-stage build, and `make build` step is moved inside dockerimage. That makes it easy to build images locally and support different architectures.
Also, with the usage of ARGS we can control the go version, build info and switch on/off the race detector.
Once we ensure PR builds work correctly, master and release will use the new image as well and all the other Dockerfiles will be removed.
To ensure that the …
> chore(ci): introduce a single multi-stage dockerfile

- config/backend-config/hosted_workspaces.go
- config/backend-config/hosted_workspaces_test.go
- config/backend-config/multitenant_workspaces.go
[Notion Link](https://www.notion.so/rudderstacks/Use-cached-endpoint-for-hosted-configs-11a9ce59c6fa4917a94ad2a363c733ba)
> feat(multi-tenant): use cached backend config

- processor/stash/stash.go
When backup is disabled, `stash` still needs to update job statuses with a terminal state (aborted).
Furthermore, since we can now enable/disable backup during runtime, file uploader should be created when switching from disabled to enabled state.
[Do not skip stash aborting jobs if backup is disabled](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=f6deca3badf74dd79ec82bf1d31d5543)
> fix: do not skip stash aborting jobs if backup is disabled

- services/filemanager/fileManager_test.go
- services/filemanager/gcsmanager.go
- services/streammanager/bqstream/bqstreammanager.go
- services/streammanager/bqstream/bqstreammanager_test.go
- services/streammanager/googlepubsub/googlepubsubmanager.go
- services/streammanager/googlepubsub/googlepubsubmanager_test.go
- utils/googleutils/googleutils.go
- warehouse/bigquery/bigquery.go
- warehouse/bigquery/bigquery_test.go
In the latest `oauth2` library releases, support was [added](https://github.com/golang/oauth2/commit/81ed05c6b58c5509b83ac75450e38d97242e7168) for Google Developers Console `client_credentials.json` files.
However, this type of files is associated with a 3-legged OAuth flow and no environment-specific `AuthorizationHandler` is available, which results in a server panic (nil pointer dereference).
This fix, disables support for `client_credentials.json` files by returning an appropriate error.
[Disable support for Google Developers Console client_credentials json file](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=52d0d703a5fd4cadaf59b8c008c8b02e)
> fix: disable support for Google Developers Console client_credentials.json file

- jobsdb/internal/lock/lock.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_export.go
- jobsdb/jobsdb_import.go
- jobsdb/jobsdb_migration_checkpoints.go
- jobsdb/jobsdb_test.go
- jobsdb/jobsdb_utils.go
- jobsdb/setup.go
- jobsdb/unionQuery.go
Recovery doesn't delete new tables if a crash happens after the `MIGRATE_COPY` operation has completed, but before
`POST_MIGRATE_DS_OP` operation has started. As a result both old and new tables exist both containing the same jobs
- `MIGRATE_COPY` creates new tables 
- `POST_MIGRATE_DS_OP` drops or backups old ones
- Replaced some panics by returning errors instead
- Functions requiring a `dsListLock` to be acquired have been refactored in order to enforce callers acquire such a lock instead of relying exclusively on good intention. For that purpose, `DSListLockToken` and `DSListLocker` have been introduced
[Internal migration not recovering from crash happening after MIGRATE_COPY operation has completed, but before
POST_MIGRATE_DS_OP operation has …
> fix(jobsdb): mark MIGRATE_COPY done and POST_MIGRATE_DS_OP start atomically

- config/backend-config/hosted_workspaces.go
- config/backend-config/hosted_workspaces_test.go
- config/backend-config/multitenant_workspaces.go
Marked the default value of BackendConfig.cachedHostedWorkspaceConfig
[ Notion Link ](https://www.notion.so/rudderstacks/Use-cached-endpoint-for-hosted-configs-11a9ce59c6fa4917a94ad2a363c733ba)
> chore(multi-tenant): defaulted cachedHostedWorkspaceConfig to false

- services/streammanager/kafka/kafkamanager.go
- services/streammanager/kafka/kafkamanager_test.go
We need to start collecting the real publishing time to Kafka because we're seeing delivery times of ~41s despite having a timeout of 10s. The reason for this PR is that the [current router deliveryTimeStat](https://github.com/rudderlabs/rudder-server/blob/6f27f4b9cc1190949123808b5df38db544795dc6/router/router.go#L820) includes several things, and not just the `client.Publish()` time.
I started looking at having all the Segment Writer stats as exposed by the Segment underlying library but given the urgency to get the alerts right for the CFDs I'm going with the simplest approach, which is to just get this single metric for now.
One alternative would be to leverage the [writer.Stats()](https://pkg.go.dev/github.com/segmentio/kafka-go#Writer.Stats) method but we would have to keep the …
> feat: kafka publishTime stat

- go.mod
- go.sum
- router/customdestinationmanager/customdestinationmanager.go
- router/customdestinationmanager/customdestinationmanager_test.go
In case of wrong configuration, clients are not being created successfully and their creation is being retried on every new event that arrives at the router.
Any delay in client creation causes cascading delays, since there can be multiple workers for the same destination, all of them waiting their turn to acquire a lock so that they can try to create the missing client introducing additional delays for the next workers in the queue.
For that reason we are introducing a circuit breaker in the client creation process. If the system fails to create a client for 6 consecutive times, it will stop trying (immediately returning an error) for the next 60 seconds. After this timeout, it will try once, if it fails again the circuit will reopen for another 60 seconds etc.
[Use a circuit breaker …
> feat(router): use a circuit breaker while producing custom destination clients

- router/batchrouter/batchrouter.go
- router/batchrouter/batchrouterBenchmark_test.go
Concurrent map writes fix for getting storage date format
https://www.notion.so/rudderstacks/Adhoc-Instamart-concurrent-map-issue-b78f52924ee44d6fb41b872df934747a
> fix(warehouse): use correct locks for dateformat in processor

- jobsdb/jobsdb.go
- router/router.go
- router/router_test.go
- router/utils/utils.go
The events which got drained by the router were not being reported to the *reports* table inside the
jobsdb database. This PR fixes that 
https://www.notion.so/rudderstacks/Report-drained-jobs-to-reporting-service-c8ce3d048e2945a797be3e31f8542ac2
> fix: reporting the drained events to the reports table

- warehouse/deltalake/deltalake.go
Handle extra columns when creating COPY command for deltalake destination because since we are using auto generated columns we are forced to do it.
Added corresponding integration test at [here](https://github.com/rudderlabs/rudder-server/blob/959c850294365c4a6a798d7baa17fdff278caa1e/warehouse/deltalake/deltalake_test.go).
https://www.notion.so/rudderstacks/Adhoc-Deltalake-columns-issue-8c10aa27a58a422dbcf2495c072fd076
> fix(warehouse): columns need to be provided during copy command for deltalake

- warehouse/warehouse.go
Reporting should only be done by Warehouse Master and should not be setup for slave
[Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=fbc420fced1d47499f7e9d4d6252cdd4)
> fix(warehouse): dsiable reporting setup for slave

- gateway/admin.go
- gateway/gateway.go
- gateway/gateway_test.go
- gateway/response/response.go
List of response changes at Gateway:-
- previously we were not using `statusMap` which has list of all possible response code and body. And, irrespective of the issue type with the request we simply returned `400` for all, except `429` for too many request. In this PR, we modified this behaviour get appropriate response code and body by making use of `statusMap` in `response.go`.
- `SourceDisabled` response is introduced. modified response for "disabled sources" from `401` to `404`, by storing the config for those source in `map`.
- `InvalidWebhookSource` status code changed from `400` to `404`.
https://www.notion.so/rudderstacks/Revisit-http-status-codes-returned-by-gateway-0cdda93d350b437589872237c7405af2
> chore: appropriate response at Gateway to incoming request

- gateway/response/response.go
Just stuff I did while reading the code for reverse engineering.
* avoid declaring `transPixel` constant each time function is invoked
* avoid `make` with `init` for `statusMap`, we can allocate the exact amount of memory needed without `init`, no need for reallocations while assigning stuff to the map
* removed unused `GetResponse` function
* unexporting `ResponseStatus` type as it is not needed from outside this package
> chore(gateway): response cleanup

- .github/workflows/release-please.yaml
Some fixes in relation to this [PR](https://github.com/rudderlabs/rudder-server/pull/2009):
* Use `bump-minor-pre-major` and `bump-patch-pre-minor` to avoid a 1.0.0 release 
* Use `secrets.GH_PAT` as token to use a github bot instead of sivashanmukh 
[Notion link](https://www.notion.so/rudderstacks/release-2-0-for-oss-images-c26b66dbf5ef4bc69f250cc287d26657)
> chore: fix release please action parameters

- .github/workflows/tests.yaml
- .gitignore
- Makefile
- app/cluster/integration_test.go
- build/buildspec.docker.master.yml
- build/buildspec.pr.yml
- docker_test.go
- jobsdb/integration_test.go
- jobsdb/jobsdb_renameDs_test.go
- jobsdb/jobsdb_suite_test.go
- jobsdb/jobsdb_test.go
- jobsdb/readonly_jobsdb_test.go
- jobsdb/unionQuery_test.go
I'm adding the possibility to run unit tests without the burden of bootstrapping containers that are setup just because in the same package we have a `TestMain` that is creating them.
Here I'm proposing to differentiate between the two by using build tags.
Additionally, I added a `slow` CLI argument to for `docker_test.go`.
At the moment we cannot run [these](https://github.com/rudderlabs/rudder-server/blob/10913e65702f26e5e4ab591d072a15dd4ea0e64d/app/cluster/dynamic_test.go) unit tests without also executing the `TestMain` from [here](https://github.com/rudderlabs/rudder-server/blob/10913e65702f26e5e4ab591d072a15dd4ea0e64d/app/cluster/integration_test.go#L50).
If you like the approach I can add the tag to all tests that are using Docker.
> feat: integration tags

- Makefile
Adding `make` recipe to run `golangci-lint` locally. I'm using Docker so that we don't have to do weird `go install`s or use the `.ONESHELL` in the Makefile given how certain GNU systems handle shells in Makefiles.
> chore: make lint

- router/router.go
After draining a job from router's jobsdb we also need to remove the job's userID from the failedJobIDMap, if present.
The following diagram captures the current router pipeline design (not including changes introduced by this fix)
[Drained jobs should be properly removed from failedJobIDMap
](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=94188b8363e04b708996d351bec622e1)
> fix: update failedJobIDMap after draining a job in router

- mocks/services/dedup/mock_dedup.go
- processor/processor.go
- services/dedup/dedup.go
- services/dedup/dedup_test.go
Using `badgerDB.NewTransaction` instead of `badgerDB.Update` which results in a **_Trying to commit a discarded txn_** error whenever a `ErrTxnTooBig` is returned by the `SetEntry` method.
[BadgerDB misuse](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=edc933e2190143119e369fedcdb244eb)
> fix: properly start a new badgerdb transaction on ErrTxnTooBig

- .github/workflows/builds.yml
- README.md
- rudder-docker.yml
* Replace AWS build badges with GitHub actions
* Change open-source image tag from `1-alpine` to `latest`
* Tag release images with `1-alpine` for existing references
[Minor-OSS-release-improvements](https://www.notion.so/rudderstacks/Minor-OSS-release-improvements-a203a6e2087d4b7d96a15fe11fb7db88)
> chore: update readme and docker compose

- app/cluster/dynamic.go
- app/cluster/integration_test.go
Removed unnecessary backend config AccessToken call. 
[ Notion Link ](https://www.notion.so/rudderstacks/Fix-flaky-test-app-cluster-integration_test-ce8e0d1984f7480f93ac53cf86d75ab4)
> fix(multi-tenant): removed unused mock calls

- .github/workflows/tests.yaml
- docker_test.go
- services/streammanager/googlepubsub/googlepubsubmanager_test.go
- services/streammanager/googlesheets/googlesheetsmanager_test.go
- testhelper/cleanup.go
- testhelper/destination/kafka.go
- testhelper/destination/minio.go
- testhelper/destination/postgres.go
- testhelper/destination/redis.go
- testhelper/destination/transformer.go
- testhelper/webhook/recorder.go
I need to write more integration tests that involve running `main` and unfortunately that is not possible from another package since `main` packages are not importable:
```go
package something
import (
"context"
"testing"
main "github.com/rudderlabs/rudder-server"
)
func TestSomethingInMain(t *testing.T) {
main.Run(context.TODO())
}
```
Produces:
> import "github.com/rudderlabs/rudder-server" is a program, not an importable package
Having said that and considering that I need to write additional tests that setup different containers, I had to get rid of `TestMain`.
* made the `Cleanup` struct similar to `testing.T.Cleanup` to simplify some tests that don't really need the `Cleanup` struct and can use `testing.T`
* removed arguments in favour of environment variables (see `SLOW`) due to …
> chore: removing TestMain from docker_test.go

- .github/workflows/notion-pr-sync.yaml
This PR removes unused notion sync github action
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=e2ba0e5dcec241eb9a46480b533074cd
> chore: remove issues event on notion pr sync github action

- app/apphandlers/embeddedAppHandler.go
Replay can either write to `gw` DB or `rt` DB, So it is essential to `gw` DB setup before the replay setup is called
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=977ff0511b5844d1a5dec1699aaec983)
> chore(gateway): start gateway before setting up replay

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/processorAppHandler.go
Fixing a regression introduced during `cluster.Dynamic` refactoring. During event replay, a writer jobsdb is required as a target. Instead, for `gw` we were using a reader jobsdb. 
Additionally, removed the replay feature when the app starts with `APP_TYPE=PROCESSOR` since no gw events can be replayed using this app type. To perform event replay, only `APP_TYPE=EMBEDDED` can be used.
[Use a writer jobsdb for writing to gw tables during replay](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=19e5fa5f34114ddf9b33525e04958f0f)
> fix: use a writer jobsdb for writing to gw tables during replay

- config/config.go
- jobsdb/jobsdb.go
Addressing https://rudderlabs.slack.com/archives/C02B0A38QQG/p1655839120236839 :
```
If not already done, can we suppress/debug-level these logs as requested by couple of people in the community
1. Empty workspace key provided while looking into jobsdb cachemap
2. wrong INSTANCE_ID provided
```
[suppress/debug-level spammy logs](https://www.notion.so/rudderstacks/suppress-debug-level-spammy-logs-2a592deee73046299830c26c1af50b80)
> chore(core): suppress/debug-level logs

- app/app.go
When we call HTTP GET / for the rudder server - we get the below output
```json
{"appType": "EMBEDDED", "server":"UP", "db":"UP","acceptingEvents":"TRUE","routingEvents":"TRUE","mode":"NORMAL","goroutines":"636", "backendConfigMode": "API", "lastSync":"2022-06-18T14:58:11Z", "lastRegulationSync":""}
```
Exposing values such as `goroutines` might be helpful information for harmful agents. This PR removes it from being shown by the server.
> fix: removed the output of goRoutine count from the HTTP GET / of the server

- gateway/gateway.go
- gateway/gateway_test.go
We want data-plane URLs to stop appearing in Google searches and avoid being crawled in general.
The common way to do this is using [robots.txt](https://www.cloudflare.com/en-gb/learning/bots/what-is-robots.txt/):
The simplest rules that exclude all:
```
User-agent: * 
Disallow: / 
```
Any bot is not allowed to scrape paths under `/` -> everything.
[Avoid-data-plane-URL-indexing](https://www.notion.so/rudderstacks/Avoid-data-plane-URL-indexing-b4dd98584cd344c3921ebf633d21262a)
> feat: expose robots.txt to disable crawling

- processor/processor.go
This is a hotfix for a regression introduced [in the last release](https://github.com/rudderlabs/rudder-server/pull/1829/files#diff-63264a27291123a1413bf5e86a8dcd368b9214681cafd30426fafbdaa2a182fa). The record ID was incorrectly mapped, leading to null being added to DB and returned to fail-request endpoint.
https://www.notion.so/rudderstacks/Fix-missing-record_id-439a6cb7d63c4e09ab72ffc69327baaa
> fix: recordId lookup

- docker_test.go
- router/customdestinationmanager/customdestinationmanager_test.go
- services/streammanager/kafka/client/client.go
- services/streammanager/kafka/client/client_test.go
- services/streammanager/kafka/client/testutil/util.go
- services/streammanager/kafka/kafkamanager.go
- services/streammanager/kafka/kafkamanager_test.go
Some parts of the Kafka manager didn't support multiple hosts/addresses.
The only part I couldn't test is the Azure producers because I ran out of free credit (and e-mails to create accounts there). Confluent Cloud and traditional Kafka are tested.
> fix: kafka multiple hosts

- services/stats/stats.go
- services/stats/stats_test.go
Previously we were calculating a cache key by iterating over the map using the default random order of the map. This meant that for 1 distinct set of 10 tags we ended up with 10! = 3628800 different key combinations in our cache map for the same thing.
Here I'm therefore introducing `stats.Tags#Strings` and `stats.Tags#String` methods. Both of them return tag key value pairs sorted by increasing key order.
Fixes an issue with inconsistent (unsorted) cache keys being calculated while populating an in-memory cache holding tagged stats clients.
[Calculate consistent tagStr cache keys in stats](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=80a1a01c2df4434da3b347f5177fef86)
> fix: calculate consistent tagStr cache keys in stats

- services/pgnotifier/pgnotifier.go
Handle errNoRows during a claim for pgNotifier. Here we don't intend to put debug/error logs when claim is failed for No updates because it is going to mess up the logs when we enable the Debug mode.
https://www.notion.so/rudderstacks/Handle-errNoRows-during-claim-for-pg-notifier-8a2702f2e5da4e4e88b033f8f5864b58
> chore(warehouse): handle ErrNoRows during pgnotifier claim

- processor/processor.go
- processor/processor_test.go
Added sources fields to existing tests in processor along with asserts to make sure fields are populated.
[Add test scenario for verifying rudder-sources specific json fields](https://www.notion.so/rudderstacks/Add-test-scenario-for-verifying-rudder-sources-specific-json-fields-ffd8489f84e64869b7d14f28521a0953)
> fix(processor): include test for sources fields in transform event metadata

- processor/trackingplan.go
- processor/trackingplan_test.go
Add tracking plan version when populating context violations
https://www.notion.so/rudderstacks/Add-tracking-plan-version-Id-during-context-population-fdaa08e9936b4d409a81dc33f07b3200
> chore(warehouse): add tracking plan version when populating context violations

- mocks/router/oauthResponseHandler/mock_oauthResponseHandler.go
- router/oauthResponseHandler/oauthResponseHandler.go
- router/router.go
- router/router_test.go
Moving from `sjson` to `jsonfast` gives us both memory and performance improvement. This is to address growing memory 
footprint of this function
```
goos: darwin
goarch: arm64
pkg: github.com/rudderlabs/rudder-server/router
Benchmark_SJSON_SET-8             144646              7980 ns/op           15336 B/op         64 allocs/op
Benchmark_JSON_MARSHAL-8          469032              2776 ns/op            2376 B/op         39 allocs/op
Benchmark_FASTJSON_MARSHAL-8      458791              2827 ns/op            2416 B/op         27 allocs/op
```
[Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=c8b968f0ec424e8b9cba64979bd55289)
> chore(router): improve collect metrics performance

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/processorAppHandler.go
- services/rsources/handler.go
- services/rsources/handler_test.go
- services/rsources/mock_rsources.go
- services/rsources/rsources.go
rsources.JobService now provides support for adding/deleting and getting failed records.
[Failed records support](https://www.notion.so/rudderstacks/Failed-records-support-in-rsources-JobService-6a44ebf12aba4fd7b5b9099d334fd28a)
> feat(core): add support for managing failed records in rsources.JobService

- config/config_test.go
- docker_test.go
- jobsdb/jobsdb_backup_test.go
- regulation-worker/internal/delete/api/api_test.go
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
> chore: use `T.Setenv` to set env vars in tests

- .github/workflows/builds.yml
- .github/workflows/release-please.yaml
Currently, an image was tagged with `latest` or `1-alpha` if it was a release or merged to master. As `latest` images are used by open-source customers, this behaviour can be problematic as master is not considered very stable at this point. It is better for `latest` to pinpoint our latest release.
https://www.notion.so/CI-fixes-62049a66091840bd8d18a714676af9b3
> fix: only tag images with `:latest` if they are part of a release

- app/apphandlers/setup.go
- services/rsources/handler.go
- services/rsources/handler_test.go
- services/rsources/http/http.go
- services/rsources/http/http_test.go
- services/rsources/rsources.go
- Add support for disabling failed keys collection.
- Respond with `HTTP 400` if failed keys collection is disabled on server and client performs a `GET /v1/job-status/{job_run_id}/failed-records` request.
- Increase default retention period of stats to 3 days.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=97a78100d41f47a1afbe3bbde41591d0&pm=s)
> chore: rsources integration improvements

- processor/processor.go
- router/batchrouter/batchrouter.go
- router/router.go
- services/metric/measurement.go
We use both `workspace` and `workspaceId` as tags for the metrics. Replacing with `workspaceId` to be consistent.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=4c71cd5376fe4515a28dc96e438aa134&pm=s
> chore: using workspaceId as the tag everywhere

- app/cluster/state/etcd.go
- services/filemanager/azureBlobStoragemanager.go
- services/filemanager/digitalOceanSpacesManager.go
- services/filemanager/fileManager_test.go
- services/filemanager/gcsmanager.go
- services/filemanager/miniomanager.go
- services/filemanager/s3manager.go
This avoids manually checking and if conditions.
Mainly started with a small change to get an idea about the process.
Improves S3 file name generation logic.
This minor refactor, no particular bug fix, do we still need a notion ticket?
> refactor: use path pkg in s3 manager to make s3 filename

- enterprise/migrator/export.go
- enterprise/replay/dumpsloader.go
- enterprise/replay/replay.go
- enterprise/replay/sourceWorker.go
- gateway/gateway.go
- gateway/gateway_test.go
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_backup_test.go
- jobsdb/jobsdb_export.go
- jobsdb/jobsdb_import.go
- jobsdb/unionQuery.go
- jobsdb/unionQuery_test.go
- mocks/jobsdb/mock_jobsdb.go
- mocks/jobsdb/mock_unionQuery.go
- processor/manager_test.go
- processor/processor.go
- processor/processor_test.go
- processor/stash/stash.go
- router/batchrouter/batchrouter.go
- router/batchrouter/batchrouter_test.go
- router/router.go
- router/router_test.go
- utils/misc/retry.go
- utils/misc/retry_test.go
Currently, when we execute any query jobsDB, we don't make it with timeout (using context) & retry. And, this sometimes leads to rudder-sever getting stuck for long time (maybe because of deadlock or any other reason). In this PR, we attempt to introduce timeout & retry for all `store` & `update` type queries of jobsDB.
https://www.notion.so/rudderstacks/Introduce-context-in-jobsdb-Store-UpdateJobStatus-commands-6c2685d91dd04c3a87cecb252a4758b0
> chore: introduce context in jobsDB insert & update commands

- gateway/gateway.go
Fixing 404s on `/` as per https://rudderlabs.slack.com/archives/C01HTT66UMB/p1659516020173379
Restoring this that was merged by mistake: https://github.com/rudderlabs/rudder-server/commit/e242c7d5d94ecc903f2565639a1b43b4a3d31ffa#diff-17cb8b37eda9018fe1c6cdb5f96b3fc948fc8ba49bc516987b8269576db9fcd4L1376
> fix: restore / endpoint

- regulation-worker/internal/delete/api/api_test.go
- regulation-worker/internal/delete/api/schema.go
When the API was returning with an error, and the `error` field of the response was set, we were getting the following unmarshal error.
This is because, you can not unmarshal a JSON string into an error field.
```
ERROR	api/api.go:82	error while decoding response body: json: cannot unmarshal string into Go struct field JobRespSchema.error of type error
```
So I change the type and update the tests.
[Notion Link](https://www.notion.so/rudderstacks/Proper-error-parsing-or-regulation-worker-cba8f92e8c48436e92eb88521de3d6ab)
> fix: parse JSON error field as a string

- multi_tenant_test.go
- testhelper/etcd/etcd.go
Fixing old version of ETCD plus case where `main.go` could terminate before the test.
> fix: multi_tenant_test.go improvements

- warehouse/snowflake/snowflake.go
Do do not create schema Query if the schema is already present for Snowflake.
https://www.notion.so/rudderstacks/One-Medical-says-they-re-still-experiencing-this-bug-despite-the-hotfix-deployed-in-the-original-th-1aeb6b7af4f54d8cba3f04c7d67c88b9
> chore(warehouse): revert schemaExist changes to follow statement execution for snowflake

- utils/misc/misc.go
`bugsnag.AutoNotify` performs recovery itself too, thus its call needs be deferred and followed by a panic within the same function.
> fix: reinstate bugsnag notifications

- services/streammanager/eventbridge/eventbridgemanager.go
- services/streammanager/firehose/firehosemanager.go
- services/streammanager/kinesis/kinesismanager.go
- services/streammanager/personalize/personalizemanager.go
To print int used %s instead of %d so this comming fixes it.
It is breaking anything but it is printing like this  %!s(int=400).
[FTR Streaming Destinations](https://www.notion.so/rudderstacks/AWS-FTR-for-streaming-destination-PoC-78b63869ac904ba49b0018a527ccb343)
> fix: stream manager logging format string

- go.mod
- services/streammanager/eventbridge/eventbridgemanager.go
- services/streammanager/eventbridge/eventbridgemanager_test.go
- services/streammanager/firehose/firehosemanager.go
- services/streammanager/firehose/firehosemanager_test.go
- services/streammanager/kinesis/kinesis_suite_test.go
- services/streammanager/kinesis/kinesismanager.go
- services/streammanager/personalize/personalizamanager_test.go
- services/streammanager/personalize/personalizemanager.go
- services/streammanager/streammanager.go
- utils/awsutils/session.go
- utils/awsutils/session_test.go
We were using slightly inefficient way to populate SessionConfig from
destination config so in order to improve this, we need to take destination
config as map[string]interface{}.
Rohith suggested this change in the PR#2241
[FTR for Streaming Destinations](https://www.notion.so/rudderstacks/AWS-FTR-for-streaming-destination-78b63869ac904ba49b0018a527ccb343)
> refactor: destination config from interface{} to map[string]interface{}

- warehouse/clickhouse/clickhouse_test.go
Some build in GA is failing with the following error: 
> code: 517, message: Metadata on replica is not up to date with common metadata in Zookeeper. It means that this replica still not applied some of previous alters. Probably too many alters executing concurrently (highly not recommended). You can retry this error
Ref: https://github.com/rudderlabs/rudder-server/runs/7763129218?check_suite_focus=true#step:8:1657
ZooKeeper is not getting updated if we are running several alter statements for the same table for multiple columns at the same time and we are getting this error. In order to avoid this, we can merge several ALTER statements into a single one for the same table.
Ref: https://stackoverflow.com/questions/69257245/clickhouse-cannot-alter-columns-throws-dbexception-metadata-on-repl …
> chore(warehouse): batching clickhouse cluster alter statements

- app/apphandlers/embeddedAppHandler.go
- enterprise/replay/dumpsloader.go
- enterprise/replay/replay.go
- enterprise/replay/setup.go
- enterprise/replay/sourceWorker.go
- services/filemanager/filemanager.go
- services/filemanager/s3manager.go
- utils/misc/misc.go
- Added time stamp filtering for replay jobs
- Fixed initialisation bug in generator loop
- Cleaned Up ENV's used for replay
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=797121feb413406aa67d1adcfa3c22c2&pm=s
> chore: fix replay bugs

- Dockerfile
The below copy in dockerfile is overriding `generate-event` script
```
COPY scripts/generate-event /scripts
COPY scripts/batch.json /scripts
```
Batch.json is getting overwritten into scripts. Note that scripts has created as file instead of folder. Hence the generate-events first gets copied into scripts file after that copy batch.json overwrites the scripts
> fix: dockerfile issues related to scripts

- router/oauthResponseHandler/oauthResponseHandler.go
- router/router.go
- router/transformer/transformer.go
In this PR, we want to change the stats which have the destination definition name detail to be `destType` as this is the convention followed in `rudder-server`
https://www.notion.so/rudderstacks/Transformer-alerts-Revamp-5af8ab9e12bc4247b24515504dd74f9f
> chore(destination): change dest def name to destType for stats

- mocks/router/transformer/mock_transformer.go
- router/admin.go
- router/router.go
- router/transformer/transformer.go
- router/transformer/transformer_test.go
- router/types/types.go
During router transform, the transformer may erroneously return more than 1 job per input jobID. This results in: 
- sending the same event multiple times to the destination, 
- messing with our statistics (negative pending events & rsources in/out inconsistency)
This change introduces two additional validations during router's `transformer.Transform`:
1. Validate that job numbers match (`in` equals `out`)
2. Validate that job ids match between `in` and `out` jobs
If any of the above validations fail, all jobs of this transformation request will be marked as failed (HTTP 500) so that they can be retried later.
Additionally, a new counter has been introduced `router.transformer.invalid.response` against which an alert can be configured to get notified about such errors. …
> fix(router): handle transformer in/out inconsistencies

- router/types/types.go
- utils/misc/misc.go
JSON Marshal omitted the worker assigned time causing the requests to time out as in routerTransformed payloads we rely on the information sent from transformer via MetaData
[<Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=0b45a450fe9c420fba1aeba0514f5887&pm=s)
> chore: fix misc master issues

- utils/awsutils/session.go
- utils/awsutils/session_test.go
Some AWS destinations are using accessKey to represent AWS access Key and others using secretAccessKey but current awsutils are supporting only accessKey so added support so that those destinations doesn't break when deployed.
https://www.notion.so/rudderstacks/AWS-FTR-for-streaming-destination-78b63869ac904ba49b0018a527ccb343
> fix: awsutils to support secretAccessKey

- enterprise/replay/setup.go
- jobsdb/jobsdb.go
- processor/stash/stash.go
- services/archiver/archiver.go
- services/filemanager/azureBlobStoragemanager.go
- services/filemanager/filemanager.go
- services/filemanager/s3manager.go
- warehouse/archiver.go
If BACKUP_IAM_ROLE_ARN env is specified, sts creds are generated assuming the role for backups to customer bucket. BACKUP_IAM_ROLE_ARN is the ARN of the role the customer creates with a trust policy principal being our AWS acccount and allowing necessary S3 actions on their bucket
More details: https://rudderlabs.slack.com/archives/C03KSBL7JM7/p1657156293344469
https://www.notion.so/rudderstacks/Secure-connection-to-customer-S3-buckets-for-backups-47fa67c7cd1c40fc9edbdf9118a39703
> feat(core): secure customer s3 bucket access for backups using cross-account role

- router/transformer/transformer.go
- router/transformer/transformer_test.go
Not using a set for collecting transformer's out stats in order to capture duplicates
> chore(router): fix defect in validating in/out inconsistencies

- warehouse/warehouse.go
Reset priority if uploads are already in progress
https://www.notion.so/rudderstacks/Reset-priority-for-if-uploads-are-in-progress-fb4cb2af50484b069ac1cff30585feb3
> fix(warehouse): reset priority if earlier upload is already in progress

- utils/misc/retry.go
Retry based on context error, not on returned error
> chore: fix RetryWith logic

- main.go
- services/validators/envValidator.go
- warehouse/upload.go
- warehouse/warehouse.go
When using an `errgroup.Group`, if more than one routine returns an error it is swallowed: https://go.dev/play/p/5f6nHLHEEwu
I'm therefore making sure that we log all errors in each routine just in case more than one would return an error.
This is also useful in case one of them gets stuck and doesn't return while another prints an error immediately. In fact if the context gets canceled and one of the routines doesn't return, we would just get some log entries with a `context canceled` error printed by other components, but the `g.Wait()` would never get a chance to run so we would not know why the context was canceled in the first place.
Additionally, I removed a `time.Sleep(time.Second)` in the Warehouse `Setup()` method and I replaced it with a retry policy with an exponential backoff. …
> fix: group errors swallowed + honouring ctx

- .github/workflows/tests.yaml
https://github.com/actions/runner-images/issues/6002
https://www.notion.so/rudderstacks/Upgrade-actions-runner-image-400f14fcb48f40f4a6a5b47b88ae07fb
> chore: upgrade actions runner to ubuntu 20.04

- warehouse/deltalake/deltalake.go
Update errorMap for deltalake partition Query.
https://www.notion.so/rudderstacks/Deltalake-Partitioning-Pruning-36b3999668d244b39045c14d2a6aae5d
> chore(warehouse): update errorMap for deltalake partition query

- README.md
I have noticed [go report-card](https://goreportcard.com/)  is used around go projects. We have a good score (and a few things to fix), so added it to our readme.
https://www.notion.so/rudderstacks/Add-go-card-banner-in-readme-df884a21fc54454a9ea725946b7d29aa
> chore: introduce go report card

- .github/workflows/release-please.yaml
Not all PR types were included in the release PR and changelog. This was creating confusion as to what will be included in the next release. In the case of debugging, the hidden PRs might be critical for the investigation. For example, a simple chore could introduce a bug.
This PR changes release-please yaml file to include all our supported types in the release PR and changelog.
This is how those types map to changelog sections:
Section -> PR types 
--------------------
Features -> feat
Bug Fixes -> fix
Miscellaneous -> chore, refactor, test 
Documentation -> doc
Type `exp` is not expected to be merged on master, and thus it will be hidden.
https://www.notion.so/rudderstacks/Include-all-types-in-release-PRs-689e5a8cba5043b6b4cc2d461aaa59aa
> chore: include all supported pr types in changelog

- jobsdb/jobsdb.go
Gateway's jobsdb is operating in writer mode and always reports at most two tables even though there are more gw table.
With this fix we are reporting the table count metrics before shrinking the dataset list for writer dbs.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=65986a9f6c374adcabec389b2af6b1c7&pm=s)
> fix(jobsdb): report correct table count metrics from gateway writer

- warehouse/upload.go
Destination validation should happen only if validators are set
https://www.notion.so/rudderstacks/destination-validation-should-happen-only-if-validators-are-set-14b50c9ab667454c81b18cee66c93940
> fix(warehouse): upload validations should happen when validator is set

- .github/workflows/tests.yaml
- Makefile
- app/cluster/integration_test.go
- docker_test.go
- jobsdb/integration_test.go
- jobsdb/jobsdb_renameDs_test.go
- jobsdb/jobsdb_suite_test.go
- jobsdb/readonly_jobsdb_test.go
The usage of build tags to enable/disable specific tests files `//go:build integration` is problematic:
1. By default, most go tools will skip those files if not configured correctly. Linting and formatting tools won't fix or report issues on those files. This applies to cli invocations, IDEs and services like deepsource.
2. Testsuites do not warn/ complain about those files being skipped; you might run `go test` or `gingko` it will return without reporting any problem. This can create confusion, or tests end up skipped at worst.
When running `make test` we were already running the tests under `integration` tag.
https://www.notion.so/rudderstacks/remove-integration-tag-2fa2eb23004146b4a19b5821a6f6ca8a
> chore: remove build tags from tests

- admin/admin.go
- config/backend-config/single_workspace.go
- eventorder_test.go
- main.go
- router/admin.go
- router/router.go
- services/multitenant/tenantstats.go
- testdata/eventOrderTestTemplate.json
Fixed a bug with respect to event ordering when there are aborted jobs. The issue was that the algorithm was modifying its relevant `abortedUserIDMap` state in the wrong place at the wrong time, instead of waiting for the next iteration of `generatorLoop` to start, which is the pipeline's entry point and the proper synchronisation barrier.
Additionally
- Introduced an integration test to verify that ordering guarantees are respected in practice.
Side jobs
- Did some minor modification in logs in order to mute some false positive errors such as **_"Server closed"_**
- Modified tenantstats algorithm to make it respect the `jobQueryBatchSize` limit in case of a single workspace
**_Note_**
We are redesigning the event order algorithm in #2344 …
> fix(router): event ordering algorithm with proper aborted job limiting support

- jobsdb/jobsdb.go
- jobsdb/jobsdb_backup_test.go
- jobsdb/jobsdb_test.go
- jobsdb/jobsdb_utils.go
Currently, `ADD_DS` operation to add new jobs table & job status table doesn't happen in a single transaction. Since, we are journaling, so any crash in middle of the addition would be reverted during recovery. But, this might create a problem in case of multiple writer to a single DB, i.e. in case of Gateway HA. So, we here we are performing the complete operation in a single transaction to avoid any problem in case of multiple writers.
https://www.notion.so/rudderstacks/Perform-ADD_DS-operation-in-a-single-transaction-4cc30f0bdd17473ab1f2acba59afe653
> feat: perform ADD_DS operation in a single transaction

- app/cluster/integration_test.go
- enterprise/replay/replay.go
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_backup_test.go
- jobsdb/jobsdb_import.go
- jobsdb/jobsdb_migration_checkpoints.go
- jobsdb/jobsdb_test.go
- jobsdb/queued_db_request.go
- jobsdb/unionQuery.go
- jobsdb/unionQueryLegacy.go
- jobsdb/unionQuery_test.go
- mocks/jobsdb/mock_jobsdb.go
- mocks/jobsdb/mock_unionQuery.go
- processor/manager_test.go
- processor/processor.go
- processor/processor_test.go
- processor/stash/stash.go
- router/batchrouter/batchrouter.go
- router/batchrouter/batchrouter_test.go
- router/router.go
- router/router_test.go
- services/multitenant/tenantstats.go
- services/multitenant/tenantstats_test.go
- utils/misc/retry.go
- utils/misc/retry_test.go
Currently, when any `query` method is called in jobsDB, we don't make the query with timeout (using context) & retry. And, this sometimes leads to rudder-sever getting stuck for long time (maybe because of deadlock or any other reason). Also, rudder-server panics immediately, if jobsDB server goes down.
In this PR, we attempt to introduce `timeout` & `retry` for all `query` methods in jobsDB.
https://www.notion.so/rudderstacks/Introduce-timeouts-and-retries-during-jobsdb-Get-Processed-Unprocessed-6c7b3c43762b46feb4642f8fde071564
> feat: introduce context, timeout and retries in jobsDB queries

- README.md
Add www and trailing slash to rudderstack.com links
> fix: add www and trailing slash to RS links

- router/customdestinationmanager/customdestinationmanager.go
- router/customdestinationmanager/customdestinationmanager_test.go
After a number of failed attempts to create a client for a specific destination, the circuit breaker opens and fails with an error that doesn't convey anything about the original error:
```
circuit breaker is open
```
This change includes the original error in the circuit breaker's error, e.g.
```
circuit breaker is open, last error: could not ping: could not dial any of the addresses
```
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=542d9035f86c49da95f4d6e7169e1fa0&pm=s)
> chore(router): include original client creation error when circuit breaker is open

- router/batchrouter/asyncdestinationmanager/asyncdestinationmanager.go
- router/batchrouter/batchrouter.go
We have seen significant performance improvement by using jsoniter library in the past, and it is safe as a drop-in replacement.
We have observe significant CPU usage by batchrouter component for marshaling / unmarshaling:
https://www.notion.so/rudderstacks/jsoniter-for-batchrouter-4c8a2d0a54d14310b2ed4cc5fd5c6a39
> fix: use jsoniter when unmarshaling to avoid perfromance issues

- jobsdb/jobsdb.go
>Added stats `backup_DS_failed` with tags for table prefix & provider to track DS backup failure.
https://www.notion.so/rudderstacks/add-alert-if-backup-fails-e424b94f8ce24186887449d2b749b979
> chore: added metrics to track failed DS backup

- jobsdb/internal/lock/lock.go
- jobsdb/internal/lock/lock_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
- jobsdb/jobsdb_utils.go
- utils/misc/dbutils.go
Currently, `addNewDSLoop` that is responsible for continuously checking if latest DS is full or not & creates a new one if it is full is not thread safe, i.e if two instance of JobsDB are running in parallel & both found that the last DS is full then both the instance will try to add a new DS & one will succeed & other will panic. 
In this PR, we solved the above described problem & made it thread safe.
TLDR:
- Essentially, to coordinate between multiple jobsDB instances we are using advisory lock, i.e. to add a new DS, jobsDB has to first acquire an advisory lock `JobsDBAddDsAdvisoryLock`. Once acquired, only then it can add new DS. 
- Also, to make sure that no one else adds a new DS from the time we checked if the latest DS is full & actually add a DS we are doing the following:-  
1. …
> feat(jobsdb): thread safe addNewDSLoop

- eventorder_test.go
- router/admin.go
- router/internal/eventorder/eventorder.go
- router/internal/eventorder/eventorder_simulation_test.go
- router/internal/eventorder/eventorder_test.go
- router/router.go
- Introduced a new `eventorder.Barrier` abstraction for implementing the event ordering algorithm.
- Replaced previous event ordering implementation with the new one in `router` component.
The following behavioral change is introduced by the new algorithm: 
**_The concurrency limiter will only be enabled if an `aborted `state is recorded for a job whose previous state was `failed`._**
In the previous implementation, the concurrency limiter was enabled whenever an `aborted `state was encountered for a job, regardless of the job's previous state history.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=d5a293e7a4c34b6399ab914bb1e879ae&pm=s)
> refactor(router): new event ordering algorithm with proper aborted job limiting

- Makefile
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
Small tables may result, after a table has been migrated at least once, leaving it with a low number of non-terminal state jobs.
So far, we are not defragmenting such tables, since the migration loop is not considering they should be migrated.
Tables with a low number of rows, e.g. < 5000 or less than 5% of the max job capacity of a table should be eligible for migration.
* `Makefile` test recipe proceeds with the deletion of files even when tests fail
* Ability to use `MinDSRetentionPeriod` to avoid having the same table migrated in an infinite loop without delays (see `we avoid multiple migrations in a row` test)
* using the same package for `integration_test.go` to simplify mocking
* optimizing valid and non valid terminal states slice (no need to build it each time, I'm now doing it …
> chore: migrate small tables

- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
Tokens are getting exposed in logs. It shouldn't be. Removing those from logs for Redshift and Snowflake.
https://www.notion.so/rudderstacks/Tokens-are-getting-exposed-in-logs-e5ecac1ab38b42ca99823bc5faf4333a
> chore(warehouse): remove tokens from logs for redshift and snowflake

- Makefile
- docker_test.go
- eventorder_test.go
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_backup_test.go
- jobsdb/jobsdb_renameDs_test.go
- jobsdb/jobsdb_test.go
- jobsdb/readonly_jobsdb_test.go
- jobsdb/unionQuery_test.go
- testhelper/destination/kafka.go
- testhelper/destination/minio.go
- testhelper/freeport.go
As long as we are depending on global and environment variables for initialization, it is not safe to execute tests in parallel, e.g.
1. One test might pick up the configuration of another test
2. One test might override the configuration of another test
3. One test's initialization (config, logging, admin, etc.) might cause a panic to another running test.
Even though parallel test execution is desirable, however it is unsafe and constantly requires effort for debugging, retrying, etc. Thus disabling it.
Furthermore, the following refactoring was performed in jobsdb tests
- Using a common function for starting the postgresql container, setting required environment variables and initializing global variables across go tests, benchmarks & ginkgo tests
- Using a different postgresql …
> chore: disable parallel test execution and refactor jobsdb tests

- config/backend-config/backend_config_test.go
> `TestNewForDeployment` test in config file is breaking in `master` with nil pointer error. This is to fix it.
https://www.notion.so/rudderstacks/fix-master-breaking-test-c993574afda143e9b0b1e1592f778964
> chore: fix for TestNewForDeployment test

- gateway/gateway.go
- gateway/gateway_test.go
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- Properly starting and stopping the gateway on each test
- Fixing a bug where we were sending an empty batch request to the worker during gateway shutdown
- acquire a read lock on the jobsdb DS list before reading it
- avoid unnecessarily setting jobsdb DS list to nil when refreshing it
> chore: fix flaky tests

- router/internal/eventorder/eventorder.go
- router/internal/eventorder/eventorder_simulation_test.go
- router/internal/eventorder/eventorder_test.go
- router/router.go
To help with debugging router's complex codebase when event ordering guarantees are being violated
> chore(router): include runtime information during event ordering errors

- services/destination-connection-tester/destination_connection_tester.go
Treating improper (nil) body close
> fix: close http response body only if there is no error

- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
- processor/processor.go
- processor/stash/stash.go
- router/batchrouter/batchrouter.go
- router/router.go
- services/multitenant/tenantstats.go
- utils/misc/retry.go
- utils/misc/retry_test.go
>Here we have introduced logs & metrics for retry of `query` & `execute` methods of jobsDB. This is done by passing `notify` func while calling `RetryWithNotify` & `QueryWithRetriesAndNotify`.  `notify` is called whenever an attempt fails.
https://www.notion.so/rudderstacks/Introduce-logs-and-alerts-for-jobsDB-retries-f20f44ddb5a7492a9c99fa49dba5cf3c
> chore: introduced log & stats for retry of  jobsDB execute & query methods

- warehouse/api.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
For sources to know that the task run has no transient uploads in the system, we need to capture the task run id in the endpoint and then call the pendingUploadCount with this filterBy clause.
https://www.notion.so/rudderstacks/Warehouse-Pending-Events-API-a3e22ec2834c427fa3a7b8ed02c8e63e
> chore(warehouse): warehouse api to capture task run ID when calculating the pending uploads.

- regulation-worker/cmd/main_test.go
- regulation-worker/internal/client/client.go
- regulation-worker/internal/client/client_test.go
- regulation-worker/internal/client/schema.go
- regulation-worker/internal/delete/api/api.go
- regulation-worker/internal/delete/api/api_test.go
- regulation-worker/internal/delete/api/schema.go
- regulation-worker/internal/delete/batch/batch.go
- regulation-worker/internal/delete/batch/batch_test.go
- regulation-worker/internal/delete/kvstore/kvstore.go
- regulation-worker/internal/delete/kvstore/kvstore_test.go
- regulation-worker/internal/model/model.go
>Currently, when we sent request to transformer to further call down stream destination to perform deletion, the `userAttributes` section of the request can only have `userID` (required), `phone` (optional) & `email` (optional). We are modifying it to support variadic keys with only `userID` as required field.
https://www.notion.so/rudderstacks/data-regulation-worker-support-key-value-user-attributes-1771ea8b38ac43d1a09e6ada68f2ce83
> feat: changes to support variadic keys for deletion from API dest.

- warehouse/snowflake/snowflake.go
Use namespace as an identifier for snowflake queries. No need to add a database since we are already adding that in the connection itself.
https://www.notion.so/rudderstacks/Schema-identifier-for-Snowflake-d3a9c90bd69f44a893e600c869958f6d
> fix: snowflake identifier issue

- main.go
Added metrics with following rudder-server config details as tag:-  
- Version
- Major
- Minor
- Patch
- Commit
- BuildDate
- BuiltBy
- GitUrl
- TransformerVersion
- DatabricksVersion
https://www.notion.so/rudderstacks/Report-version-to-metrics-60b766e8186d48adb45621fbdee7e6be
> chore: added rudder-server config metrics with version and other details as tag

- .github/workflows/semantic-pr.yaml
The semantic PR, was complaining in PRs with a single commit - when that commit didn't follow the standards and that it was matching the PR title. This was inconvenient, but necessary since: 
>   When using "Squash and merge" on a PR with only one commit, GitHub
>   will suggest using that commit message instead of the PR title for the
>   merge commit, and it's easy to commit this by mistake.
However, after github [introduced some options](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) and we chose the following,:
This is no longer the case:
(this is a PR with a single commit, trust me)
https://www.notion.so/rudderstacks/semantic-PR-improvements-40fb40bdc73648aca1f4b …
> chore: disable semantic PR single commit validation

- .github/workflows/tests.yaml
- services/streammanager/kafka/client/client.go
- services/streammanager/kafka/client/client_test.go
- services/streammanager/kafka/kafkamanager.go
- services/streammanager/kafka/kafkamanager_test.go
PR to add comments and test CI integration. Some tests like `TestAzureEventHubsCloud` are skipped unless some environment variables with credentials are set. I'm creating this PR to inject the secrets accordingly.
* `TestAzureEventHubsCloud`
* `TestNewProducerForAzureEventHubs/ok`
* `TestConfluentAzureCloud`
* `TestProducerForConfluentCloud/ok`
:point_up: the above now connect to real clusters.
Small refactoring to simplify a few things and added a few assertions here and there.
< [Notion Link](https://www.notion.so/rudderstacks/Azure-Event-Hubs-and-Confuent-Cloud-CI-integration-a18134e3b807438e8969c9d1479aaff2) >
> chore: kafka cloud platform CI integration

- eventorder_test.go
- gateway/gateway.go
- gateway/gateway_test.go
- go.mod
- go.sum
- jobsdb/integration_test.go
- jobsdb/internal/lock/lock.go
- jobsdb/internal/lock/lock_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_backup_test.go
- jobsdb/jobsdb_test.go
- jobsdb/setup.go
- jobsdb/unionQuery.go
- mocks/jobsdb/mock_jobsdb.go
- mocks/jobsdb/mock_unionQuery.go
- processor/processor.go
- processor/processor_test.go
- router/batchrouter/batchrouter.go
- router/batchrouter/batchrouter_test.go
- router/router.go
- router/router_test.go
1. Introduced context aware lock for `dsListLock` & `dsMigrationLock`.
2. Modified `migrateDSLoop` to do migration in single transaction.
3. Introduced `migrateDSTimeout` & `refreshDSTimeout` to skip & continue, if failed to acquire lock in the required time.
4. Relevant code refactoring around migration.
https://www.notion.so/rudderstacks/Postpone-jobsdb-operations-migrate-addDS-that-cannot-acquire-a-mutex-lock-after-a-timeout-311d74d6eb624e62a4cb7bbb163f01ed
> refactor(jobsdb): introduce context aware mutex locks,  transactional migrations & cancelable maintenance operations

- gateway/gateway.go
- middleware/middleware.go
Using the matched template's path instead the url's raw path in order to keep measurement cardinality under control, and be able to group requests for paths that contain path parameters, such as:
* /v1/job-status/{job_run_id}
* /schemas/event-model/{EventID}/key-counts
* /schemas/event-version/{VersionID}/metadata
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=cbebdcd5d77e4a8f84151563e7483019&pm=s)
> chore: include matched template path in gateway's request metrics

- jobsdb/internal/dsindex/dsindex.go
- jobsdb/internal/dsindex/dsindex_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
- jobsdb/jobsdb_utils.go
After removing the old migrator, the algorithm for calculating dataset indices can be simplified.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=e7ebbf8478c743e3ad0904b9a179bc8c&pm=s)
> refactor: dataset index calculation

- warehouse/bigquery/bigquery.go
Typo with fetch schema for the bigquery
https://www.notion.so/rudderstacks/Formal-SQL-Queries-Parameterized-it-cb44268e604c446c9f31858bba98635f
> fix(warehouse): typo with fetch schema for bigquery

- eventorder_test.go
- router/internal/eventorder/eventorder.go
- router/internal/eventorder/eventorder_simulation_test.go
- router/internal/eventorder/eventorder_test.go
- router/router.go
- router/router_test.go
- router/utils/utils.go
- testdata/eventOrderTestTemplate.json
- warehouse/api.go
- warehouse/jobs/runner.go
When a job needs to be drained from the router, we cannot drain it early, but we need to push it to the worker's queue, so that all other (waiting) jobs for the same userID have time to flush from the pipeline's buffers, before the job is actually drained.
[Link](https://www.notion.so/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=ca310400e89541129789bb20d104b93b&pm=s)
> fix(router): preserve event order while draining a previously failed job

- main.go
Exclude destId tag for free tier to prevent tags blowup.
> chore: excluding destId tag for free customers

- jobsdb/integration_test.go
- jobsdb/jobsdb.go
Rudder server triggers internal migration when required. No longer job fetching and then copying into new DS.
Does so using a `insert into newDS (select * from oldDS where non-terminal)` statement.
[Perform internal migrations using insert into select statements](https://www.notion.so/rudderstacks/Perform-internal-migrations-using-insert-into-select-statements-cda23b8d9f754796997aa9b4f80b7e5a)
> refactor: internal migration in postgres

- gateway/gateway.go
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_backup_test.go
- jobsdb/jobsdb_test.go
- mocks/jobsdb/mock_jobsdb.go
- processor/processor.go
- processor/processor_test.go
- router/batchrouter/batchrouter.go
- router/router.go
By updating (invalidating) the cache entries before the transaction commits and for the period until the transaction actually commits, we are risking to have other select queries who arrive during this timeframe to populate the cache with incorrect values: until the transaction commits, changes are not visible to other queries, thus they may erroneously put "no result" entries in the cache.
The above can have as a side-effect to: 
1. Delay processing of whole datasets until cache entries expire (observed with `proc_error` tables)
2. Cause out-of-order event delivery
This fix introduces a `jobsdb.Tx` that wraps a `sql.Tx`, adding support for registering success listeners. Now, all cache entries are updated after the transaction has been successfully committed. …
> fix(jobsdb): update cache after transaction completes

- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
- utils/misc/dbutils.go
Different table prefixes shouldn't use the same advisory lock.
> chore(jobsdb): use a different advisory lock for different table prefixes

- router/router.go
- router/router_test.go
Accessing `destination` without checking for its existence first. Fixes that.
[fix: router destination map access](https://www.notion.so/rudderstacks/fix-router-destination-map-access-2834a4985d0c4886aa080abe77174053)
> fix: router destinationsMap access

- jobsdb/jobsdb.go
Fixes a race condition causing empty migrated tables getting created and leading to server panic
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=0a514ad1d34d4bf1bbfb10b31f002de1&pm=s)
> fix(jobsdb): race - repeat job count calculation after acquiring migration lock

- .github/workflows/tests.yaml
- Makefile
Running tests with `gotestsum` [simplifies the console's output](https://github.com/rudderlabs/rudder-server/actions/runs/3280212449/jobs/5400716707) and makes it easier to identify test failures, since only logs from the failed tests are included.
```sh
✓  . (1m43.657s) (coverage: 78.7% of statements)
∅  admin
∅  admin/profiler
∅  app
∅  app/apphandlers
✓  app/cluster (3.591s) (coverage: 71.6% of statements)
✓  app/cluster/state (1.677s) (coverage: 74.3% of statements)
∅  build/wait-for-go
∅  cmd/devtool
∅  cmd/devtool/commands
✓  config (7ms) (coverage: 69.5% of statements)
✓  config/backend-config (16.917s) (coverage: 59.8% of statements)
...
```
If still, for any reason, the full logs from all tests are required, you may enable [debug …
> chore: use gotestsum for test execution

- services/pgnotifier/pgnotifier.go
For backward compatibility, the job type can be NULL. So added default handling for the job type to use for the upload flow.
https://www.notion.so/rudderstacks/PGNotifier-default-jobType-1197a7b1438847418899a9e548aaf1e6
> fix(warehouse): default job type

- router/oauthResponseHandler/oauthResponseHandler.go
According to the doc, if a request fails with error the response must be ignored as it can be nil
> fix: only close response body in oauth handler in case of no error

- router/router.go
Updating job status in the barrier. Regression introduced by #2582
[fix: router destination map access](https://www.notion.so/rudderstacks/fix-router-destination-map-access-2834a4985d0c4886aa080abe77174053)
> chore: fix defect with router destinations map access event order

- gateway/gateway.go
- middleware/middleware.go
- middleware/middleware_test.go
Fixing a bug where the retrieved RouteMatch template was ignored. Additionally, added the response's status code in the measurement's tags.
_**Note:** added a test to verify correct behaviour_
> fix: don't ignore stats middleware template path calculation

- enterprise/suppress-user/suppressUser.go
Currently, `pageSize` is only set if `suppressAPIToken` is set, which is set only after we get response for 1st request from `gw`. So, the the 1st request url from gw doesn't have `pageSize` set. And, since the go routine sleep for 5 min if the number of suppression user received is less than `pageSize`. Because of this bug, there was an unnecessary delay in suppression sync at `gw` end.
This issue is fixed in this PR.
https://www.notion.so/rudderstacks/GW-suppression-pageSize-bug-fix-71f965130db842d188ae265263f72fa1
> fix: page size fixed irrespectiveof suppressAPIToken

- jobsdb/jobsdb.go
> currently, we see `pre_drop` table pileup if a lot of jobs are failing. Since, we have a limit on number of rows read at a time to 1000 (by default). And, when failure is high we have a lot of columns in status table. Because of while taking backup of a single table requires querying DB a lot of time, which takes really really long time. 
So, to avoid this, we are setting the default value of `LIMIT` to a large value `100,000` since, we are already guarded by `running_payload_size`, to avoid OOM kill.
https://www.notion.so/rudderstacks/remove-LIMIT-on-row-count-from-getBackUpQuery-bde1f44331d444f7a33e3b3f99904470
> fix: jobsDB backup query time

- go.mod
- go.sum
- router/batchrouter/batchrouter.go
- router/batchrouter/batchrouterBenchmark_test.go
1. Grouping jobs by destination before sending to workers, to avoid filtering at worker.
2. Introducing [lo](github.com/samber/lo), a generics library for streamlining operations on collections.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a2c313e544a24ccc9add232b9b0cf92e&pm=s)
> fix(batchrouter): concurrent modification of job parameters causes panic

- services/pgnotifier/pgnotifier.go
This fix addresses a panic when running with `--race` flag:
```
fatal error: checkptr: pointer arithmetic result points to invalid allocation
```
The culprit is the following line, which is called `murmur3.Sum64` 
```
k1 := *(*uint32)(unsafe.Pointer(p))
```
The usage of unsafe is being condemned in [this issue](https://github.com/spaolacci/murmur3/issues/29
) and we should probably consider changing the library all together 
Does it make sense to use int64 ?
Yes, both the pglock library and postgress supports this:
```go
pg_advisory_lock(key bigint)
```
https://www.postgresql.org/docs/9.1/functions-admin.html
It also works with negative numbers
To avoid code like this being added in the future, I am [considering](https://github.com/rudderlabs/rudder-server/pull/2646) enabling `--race` …
> fix: use sum64 to avoid checkptr race bug

- gateway/gateway.go
- gateway/response/response.go
Remove panic in `gateway.dbWriterWorkerProcess` on store failure.
[remove gateway panic on write failure](https://www.notion.so/rudderstacks/remove-gateway-panic-on-write-timeout-f65be5e734cc42718c37a0436b449308)
> fix: remove gateway db write panic

- gateway/gateway.go
> chore: use WriteTimeout instead of Gateway.pendingEventsQueryTimeout

- warehouse/warehouse.go
Github reported few vulnerability. Mentioning the slack conversation:
https://rudderlabs.slack.com/archives/C049T5P2Z97/p1667507291386099
https://www.notion.so/rudderstacks/SQL-injection-vulnerability-in-TriggerWHUploads-rudder-server-25b7e45711034ad7889f458ad24768b0
> fix: changed query to accept user input in prepared sql statement

- Makefile
- codecov.yml
- services/rsources/handler_test.go
Attempting to fix a flaky test & adding some more logging
> chore: rsources flaky test - start services before all

- config/backend-config/types.go
- config/config.yaml
- enterprise/reporting/noop.go
- enterprise/reporting/reporting.go
- enterprise/reporting/reporting_test.go
- mocks/utils/types/mock_types.go
- utils/types/types.go
Added support to filter reporting data based on backend config settings.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=5accd4e1fbf9480c9102059897e6068b&pm=s
> feat: support reporting pii filter based on config backend

- router/batchrouter/batchrouter.go
- router/batchrouter/batchrouter_test.go
Handle status code when batch router hits warehouse` v1/process` URL.
https://www.notion.so/rudderstacks/Handle-warehouse-process-9fa6aa8da88948999ea81bf5a34a352a
> fix: use proper status code to handle warehouse process

- router/failed-events-manager.go
Using double quotes and escaping the table name when querying for failed events, until we drop support for the old endpoint.
[Reference](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#:~:text=Quoted%20identifiers%20can,limitation%20still%20applies)
> fix: properly escape table name when querying for failed events

- services/filemanager/gcsmanager.go
GCS Manager creates an iterator to fetch objects. Bug: We were passing context to it and later cancelling at the end of the function call although the iterator will be used for every call of the function
https://www.notion.so/rudderstacks/Fix-GCS-Replay-2dd4e0f0e97942a5bcce282a5f61ea77
> fix: gcs manager cancels context

- services/fileuploader/fileuploader.go
- services/fileuploader/fileuploader_test.go
Setting all backup preferences to false incase there is invalid bucket provided
https://www.notion.so/rudderstacks/Allow-Customers-to-use-self-storage-26f45f75e38b4ef6bd872bea6187aa06
> fix: preferences should be false incase of invalid bucket

- router/failed-events-manager.go
Extracted a common function for escaping the table name and including a scenario missed by #2663
> fix: always use a sql safe table name in failed events manager

- integration_test/docker_test/docker_test.go
- main.go
- runner/runner.go
Falling back to enterprise token read from env (if not provided as an ldflag)
> fix: use enterprise token from env as fallback

- regulation-worker/cmd/main.go
- regulation-worker/internal/client/client.go
- regulation-worker/internal/client/client_test.go
- regulation-worker/internal/delete/api/api.go
- regulation-worker/internal/model/model.go
- regulation-worker/internal/service/looper.go
- regulation-worker/internal/service/service.go
- Modified regulation-worker to avoid panic if regulation-manager API call times out. Instead we are simply retrying after a minute & pushing the stats for it. 
- Added stats to get metrics like number of users deleted till now, deletion time, total loop time.
- Called from main with bugsnag to get notified in case of crash.
https://www.notion.so/rudderstacks/regulation-manager-worker-fail-safe-with-metrics-alert-a6c1eee073924651a15e9caad45750d7
> chore: regulation worker avoid panic in case of timeout

- integration_test/docker_test/docker_test.go
- integration_test/multi_tentant_test/multi_tenant_test.go
- services/streammanager/kafka/client/client_test.go
- services/streammanager/kafka/kafkamanager_test.go
- testhelper/destination/kafka.go
- testhelper/etcd/etcd.go
- Enabling all tests in arm64 machines (m1 macbooks)
- Fixing flaky multitenant test
> test: using arm64 compatible images if necessary

- router/router.go
The oauth account id can be empty. Due to the changes we might do as part of the regulation-worker support for Universal Analytics.
This check serves as protection when `rudderAccountId` is missing. 
As part of the changes for supporting OAuth in regulation-worker module. We need to have one more field in destination config known as `rudderUserDeleteAccountId` which indicates that this account information will be used for sending delete user request to destination
This user delete feature can sometimes only require OAuth and event-delivery for the same destination might not need OAuth, int this case, we don’t populate `rudderAccountId` but we populate `rudderUserDeleteAccountId` with the access token information(which will be used for user-deletion requests)
This can cause a problem while …
> fix(destination): empty oauth account check

- processor/stash/stash.go
- processor/stash/stash_test.go
- services/fileuploader/fileuploader.go
Close Init after storage settings are assigned and log errors while uploading proc_errors instead of panic
https://www.notion.so/rudderstacks/Allow-Customers-to-use-self-storage-26f45f75e38b4ef6bd872bea6187aa06
> fix: close init after assigning storage settings

- services/fileuploader/fileuploader.go
workspaceId is taken from config backend key instead of workspaceId field from config backend value. Bug: workspaceId is being sent as empty in hosted but given for single tenant
https://www.notion.so/rudderstacks/Allow-Customers-to-use-self-storage-26f45f75e38b4ef6bd872bea6187aa06
> fix: take workpaceid from config backend key

- SECURITY.md
Added a SECURITY.md file with the relevant contact email for reporting any security-related issues.
https://www.notion.so/rudderstacks/Add-security-md-to-all-the-major-public-repos-d6696c93147f4d8299302fa59c4ad465
> doc: create SECURITY.md

- gateway/configuration.go
Enable max concurrent gateway request limit with default value of 50000.
Discussion ref: https://rudderlabs.slack.com/archives/C01JF5MGUAG/p1667401042399559
https://www.notion.so/rudderstacks/enable-max-concurrent-gw-request-limit-ce0781d221984678a0f843823d50d303
> chore: by default enable max concurrent gw request limit.

- runner/runner.go
Warehouse archiver Init() is not being called from anywhere. It needs to be initialized during the start of the application from the runner.
https://www.notion.so/rudderstacks/Warehouse-archiver-Init-79b09dfb38ed4123ac6d7ac59f7ed656
> fix(warehouse): warehouse archiver initialize

- router/router.go
Fixes a bug where iterator stats were captured early, just after the first query was performed, instead of waiting until the iteration was done.
> fix: capture router's iterator stats after iteration is complete

- processor/stash/stash.go
Use a variable copy inside the goroutine
https://www.notion.so/rudderstacks/Fix-stash-backups-1-3-0-922b1b6a556a4379ba52f9c6c0bb14a1
> fix: use local variable for workspaceId in stash backup

- utils/awsutils/session.go
AWS role session name should not contain any spaces so replacing space with hyphen.
https://www.notion.so/rudderstacks/Add-AWS-IAM-role-option-for-S3-Lambda-Eventbridge-Kinesis-Firehose-Personalize-destinations-b67c98e8425f4ef8b1b6b906fff08484
> fix: aws role session name

- router/batchrouter/batchrouter.go
Fix event delivery time for batch router.
https://www.notion.so/rudderstacks/Batch-router-event-delivery-time-bug-0900f5fa5f604c67b82d2faabbbe4ae3
> fix: batch router event delivery time

- services/rsources/handler.go
- services/rsources/handler_test.go
- services/rsources/rsources.go
- testhelper/log/log.go
Resolved 3 issues with the flaky tests:
1. Removed transactions and `if exists` clauses from `create table`, since it could lead to tables not being created in some scenarios, e.g. 2 concurrent transactions, 1st creates the table, 2nd skips, then 1st does a Tx rollback so table is not created.
2. Improper use of nested `Ordered` Ginkgo containers and `BeforeAll` which caused containers to be reused beyond the desired boundaries.
3. Assertion of expected response when retrieving failed records could fail due to ordering inconsistencies.
> chore: fixing a flaky rsources test

- gateway/gateway.go
- gateway/webhook/setup.go
- gateway/webhook/webhook.go
- mocks/gateway/webhook/mock_webhook.go
fixed some faulty stats at the gateway.
Due to how we were using a map(`statTagMap`), some `sourceTag`s were seeing multiple `sourceID`s and `workspaceID`s.
Added another level in the same map to cater to this.
In this example we see multiple `workspaceID`s for one source.
[gateway stats fix](https://www.notion.so/rudderstacks/gateway-stats-fix-fdd2547dc268452bad79462f2e3c179d)
> fix: incorrect stats captured at gateway

- jobsdb/jobsdb.go
- jobsdb/readonly_jobsdb.go
- jobsdb/unionQuery.go
- sql/migrations/jobsdb/000010_add_index_job_status_table.down.tmpl
- sql/migrations/jobsdb/000010_add_index_job_status_table.up.tmpl
- sql/migrations/node/000008_unionjobsdb_fn.down.sql
- sql/migrations/node/000008_unionjobsdb_fn.up.sql
When `jobsdb` queries the database for jobs, it needs to get the latest job status for each job. The current way of achieving this is through a `SELECT MAX(id) GROUP BY job_id` query in the job status table.
However, a specialized index `(job_id asc, id desc)` along with using `SELECT DISTINCT ON (job_id)` yields significant performance improvements over the current strategy (25% - 100% faster), see some example query plans: [old](https://explain.dalibo.com/plan/dbb1fa24db6h1h5h) vs [new](https://explain.dalibo.com/plan/3h2e17deb3008f9f). See also the [relevant thread](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1667647521011599).
To simplify queries even further, a new database view is introduced for every job status table (e.g. table `rt_job_status_1` has view …
> chore(jobsdb): latest job status query optimization

- warehouse/bigquery/bigquery.go
- warehouse/upload.go
- We are using the wrong config for columnsBatchSize as `customDatasetPrefix`.
- Also we don't need to log the load files information for BiqQuery. It is polluting the logs. 
https://www.notion.so/rudderstacks/Use-batching-to-run-several-of-alter-statements-81ae26d5db6f4b2ca8e0258e3ce0cba6
> fix(warehouse): use correct config for columns batch size

- jobsdb/jobsdb.go
There are references to `assertError` function in init function. `assertError` uses logger to log some internal data structures. But logger is initialised in the end of init. This is causing a nil pointer exception in case of errors in init function.
In this pr, initing the logger in the beginning of init.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=69fbdd52094d428583317ad0a5dcc64f&pm=s
> fix: init jobsdb logger at the right place

- router/router.go
Add workspaceid label to router aborted events metric.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=ee0f6d49ea664964ba3d610929f154af&pm=s
> chore: add workspaceid label to router aborted events

- warehouse/upload_test.go
Added a fix for [deep-sources](https://deepsource.io/gh/rudderlabs/rudder-server/run/2284a648-4dd4-41a9-8dc3-c3d87c9e1fff/go/GO-W1024?listindex=0) issue `fix for use of empty error string in errors.New`.
https://www.notion.so/rudderstacks/Test-cleanup-for-Datalakes-Integration-e6f8e3fd7b024b22aff23427d3e7d2c6
> fix(warehouse): deepsource fix for use of empty error string in errors.New

- app/apphandlers/apphandlers_test.go
- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/gatewayAppHandler.go
- app/apphandlers/processorAppHandler.go
- app/apphandlers/setup.go
- config/mode.go
- jobsdb/jobsdb_test.go
- jobsdb/jobsdb_utils.go
- jobsdb/readonly_jobsdb.go
- runner/runner.go
- runner/runner_test.go
- runner/testdata/config.json
- services/db/embeddedRecovery.go
- services/db/nullRecovery.go
- services/db/recovery.go
- services/validators/envValidator.go
- utils/misc/misc.go
- warehouse/warehouse.go
When running in `embedded` mode (core & warehouse) and using separate database instances for core & warehouse data, it is possible that one database's unavailability panic may cause the other database's schema migration to become dirty (corrupted) due to the asynchronous nature of the two components' startup sequence.
To eliminate this, we are now initialising both databases sequentially and stop the process gracefully in case of an error. Database initialisation for reach component happens only if the component needs to be started.
Other improvements:
- removed a handful of panics for supporting graceful termination on failure scenarios
- refactored the `apphandlers` package to remove global variables
- introduced tests for some exceptional `runner` & `apphandler` scenarios …
> refactor: safe database initialisation and schema migration during startup

- warehouse/bigquery/bigquery.go
- warehouse/jobs/handlers.go
- warehouse/jobs/utils.go
- warehouse/snowflake/snowflake.go
We are getting the following error for BQ and SNOWFLAKE destinations for the Async Job Framework.
> ERROR	warehouse.bigquery	bigquery/bigquery.go:269	BQ: Error running job: googleapi: Error 400: Syntax error: Unexpected string literal "bwh_e_470_edf_7_0547_4_bf_3_b_896_29_cd_08_c_289..." at [1:13], invalidQuery
> 000904 (42000): SQL compilation error: error line 2 at position 2
> invalid identifier 'CONTEXT_SOURCES_JOB_RUN_ID'
> 
> 002049 (42601): SQL compilation error: error line 2 at position 32
> Bind variable:jobrunid not set.
https://www.notion.so/rudderstacks/Async-JOB-Queries-are-failing-with-BigQuery-and-Snowflake-c1edd033a228426eb6d5108311152ddc
> fix: warehouse sync job queries for snowflake and bigquery

- gateway/gateway.go
- middleware/uncompress.go
- middleware/uncompress_test.go
- router/eventorder_test.go
Adding support for accepting requests using a gzipped body along with the appropriate `Content-Encoding: gzip` header.
Compressed request bodies are being uncompressed lazily and in a streaming fashion.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=e46c493fa108495cb6b9c85ad7594409&pm=s)
> feat: add support for request payloads using gzip content-encoding

- jobsdb/readonly_jobsdb.go
Set max connections to readonly jobsdbs to prevent exhausting all the available connections.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=a0094efc17da43c1a552d5ab636aa4a9&pm=s
> chore: set max connections to readonly jobsdbs

- event-schema/event_schema.go
The event schema tables have a metadata column which contains a TotalCount field. This was being casted to a 32 bit integer. We exceeded those limits for one of our customers resulting in the value of TotalCount to be greater that the 32 bit integer range, and leading to a subsequent crash in the server pod. The SQL query has been modified to cast that into a 64 bit integer field.
> fix: metadata in event_schema table has TotalCount which exceeds 32bit integer limits

- jobsdb/jobsdb.go
- jobsdb/migration.go
The status compaction step during `migrateDSLoop` might sometimes miss compacting some DSs due to some level of inaccuracy in postgres estimates. With `jobsdb. jobStatusCountMigrationCheck` flag, we can ensure that we check for status overload in a DS again(during `checkIfMigrateDS`) to ensure that DS is migrated(this time based on actual row count instead of estimates).
This behaviour is disabled by default.
https://www.notion.so/rudderstacks/add-safeguard-for-status-estimates-during-migration-03be2fe46b134333b194d450048b9331
> chore: ensure internal migration of large job-status datasets

- info/features.go
- integration_test/multi_tentant_test/testdata/expected_features.json
- runner/runner.go
Server features are now included in the `/version` endpoint to allow for SDK clients to have an easy way to discover whether the data plane they are sending events to supports (or not) a specific feature.
The first use case is `gzip-req-payload`, i.e. the ability of rudder-server to uncompress gzipped request payloads of requests carrying the `Content-Encoding: gzip` header.
Before any SDK starts compressing its request payloads using gzip, it needs to first make sure that the data plane that is going to receive these requests supports gzipped requests. Thus the SDK needs to perform a `GET /version` request, discover the server's features, configure itself accordingly and then start sending events.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0 …
> chore: advertise server features in version endpoint

- app/cluster/integration_test.go
- config/backend-config/backend_config_test.go
- docker-compose.yml
- processor/manager_test.go
- router/manager/manager_test.go
- rudder-docker.yml
- services/rsources/handler_test.go
- testhelper/destination/postgres.go
- warehouse/docker-compose.test.yml
Upgrading Postgres to 15 in the default docker-compose file and the relevant tests
[ Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=97b29b8fee654a52ac58812513c06ff6&pm=s)
> chore: upgrade postgres image

- jobsdb/jobsdb.go
The `add_ds` advisory lock is already acquired, thus removing the second lock statement.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=accc62687a574edbb6b4bcff120107b5&pm=s)
> chore: remove redundant/duplicate add_ds distributed lock

- processor/transformer/transformer.go
- router/transformer/transformer.go
If any transformation times out, processing gets stuck indefinitely. This pr will fail those jobs.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=181b1dd84c864ce1abe1818e7cf7cb1e&pm=s
> chore: fail transformer timeouts

- gateway/webhook/configuration.go
Making sourceListForParsingParams non hot reloadable
> chore: remove shopify autoreload

- warehouse/internal/api/http.go
- warehouse/internal/api/http_test.go
- warehouse/internal/model/staging.go
- warehouse/internal/model/staging_test.go
- warehouse/internal/repo/staging.go
- warehouse/internal/repo/staging_test.go
- warehouse/types.go
In a recent PR, I introduced the repository & DTO pattern to access the database. I wanted the DTO to contain all the information about a staging file. However, the schema field requires a lot of memory for some customers (100Kbytes - 200Kbyes).
We should avoid including the schema if not needed, but I didn't want to have a partial field DTO. Thus, I have introduced a new type, `StagingFileWithSchema`, which should be used when the schema is needed.
The HTTP API inserts staging file with schema, and all the get method return staging file without schema.
https://www.notion.so/rudderstacks/fix-OOM-staging-file-19d84c51d5be4251944b35531b4dd778
> fix: remove schema from stage file model

- jobsdb/migration.go
converting postgres `reltuples` estimate to a float64 instead of int64.
`Failed to migrate ds: sql: Scan error on column index 0, name "estimate": converting driver.Value type float64 ("1.018263e+06") to a int64: invalid syntax`
https://www.notion.so/rudderstacks/float64-status-cleanup-estimates-1d85800371d3467c884fa98e19d6363f
> fix: using a wrong datatype for pg_class.reltuples causes internal migration to fail

- services/multitenant/tenantstats.go
- services/multitenant/tenantstats_test.go
During application startup, we incremented pending events stats twice, once while creating the `tenantstats.Stats` and once more while starting `tenantstats.Stats`. This caused in-memory stats to be seeded incorrectly (x2 the actual stats) and, subsequently, causing erroneous firing of stuck-processing-pipeline alerts.
Removed stats initialization logic from `tenantstats.NewStats`.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=4ca5ea2d2f954b3e94356c713d1d2e01&pm=s)
> fix: pending events stats incremented twice during startup due to tenantstats being initialized twice

- warehouse/azure-synapse/azure-synapse.go
- warehouse/clickhouse/clickhouse.go
- warehouse/deltalake/deltalake.go
- warehouse/mssql/mssql.go
- warehouse/postgres/postgres.go
- warehouse/snowflake/snowflake.go
1. Use `strings.builder` for building up the query for adding columns instead of concatenating strings to create one.
2. Reserved keywords handling for Azure Synapse.
https://www.notion.so/rudderstacks/use-strings-Builder-for-add-columns-7464daf2d48748f2a7e2ac960d132e93
> refactor(warehouse): use strings.builder for warehouse add columns

- app/apphandlers/setup.go
- config/config.yaml
- router/router.go
Enable the failed keys by default.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=fa820a352a7542d39d9d0c90bf82bc04&pm=s
> chore: enable failed keys by default

- services/filemanager/filemanager.go
- services/filemanager/s3manager.go
- services/filemanager/s3manager_test.go
- utils/awsutils/session.go
- utils/awsutils/session_test.go
- warehouse/utils/utils.go
Unify AWS session config creation process so that it is consistent across all AWS destinations. Earlier S3 has slightly different process to create SessionConfing so when updated the session config creation in aws utils to support RoleBasedAuth flag, it got missed for S3 manager as it was using different implementation so this unification should prevent such errors in the future.
[Warehouse AWS Role support] https://www.notion.so/rudderstacks/Warehouse-destination-config-for-Role-base-Authentication-control-plane-db9198dce2024723959c224e91a11ef4
> fix: aws session creation is failing for s3 manager when roles are used

- router/router.go
- router/router_test.go
The issue is that, when `transformerProxy` was enabled and `skipRtAbortAlertForDelivery` configuration was not present, the `alert` tag(or flag) was coming out to be `true`, which is not expected
We want the alert to only be triggered when the following happens during delivery phase for cloud-mode destinations
|proxy|skipRtAbortAlertForDelivery(in configuration)|alert(in router_aborted_events or router_response_counts stat)|
|--|--|--|
|0|0|1
|0|1|0
|1|0|0
|1|1|0
https://www.notion.so/rudderstacks/Kapacitor-alerts-configuration-Prometheus-migration-a0f65d8ff61e440a9f69f9884752bf51
> fix(destination): alert flag setting for router-aborted-count alert definition

- gateway/webhook/webhook.go
- gateway/webhook/webhookTransformer.go
Here we are looking forward to collecting the error stats at the rudder-server end based on the source-transformer status codes.
Note: created from https://github.com/rudderlabs/rudder-server/pull/2806 as that wasn't created as hot fix.
[Notion Link](https://www.notion.so/rudderstacks/Add-alerts-on-source-transformation-10c57b78060c4eccb255321de9fc0f73)
> chore(gateway): enabling source transformation alerts

- jobsdb/jobsdb.go
- jobsdb/readonly_jobsdb.go
Quote table identifier. Fixes cases when table name has "-" in it.
Note: Manually tested these changes. Not writing tests, because this code is gonna be removed soon.
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=47af60cd5cb841769e640c3b9403c8fb&pm=s
> chore: quote table identifier

- regulation-worker/internal/delete/delete.go
- regulation-worker/internal/delete/delete_test.go
There is no point in retrying regulation deletion jobs for unsupported destination types
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=87a22e23ea624c5ca0772abc3b38cd19&pm=s)
> chore: abort jobs in regulation worker for unsupported destinations

- go.mod
- services/stats/memstats/stats.go
- warehouse/warehouse.go
The available number of workers to be Guage stats.
https://www.notion.so/rudderstacks/fix-warehouse-processing-stats-to-be-guage-for-workers-3f9ad02af83541459ae1a3434d65561a
> fix(warehouse): processing available workers to be gauge stats

- warehouse/warehouse.go
The Control plane client needs to be initialized for all warehouse master modes not just for the stand-alone mode.
https://www.notion.so/rudderstacks/control-plane-client-needs-to-be-initialized-for-master-mode-5fb54e30fdb640a4a6de4cf4b2a61823
> fix(warehouse): control plane client needs to be initialized for master mode

- services/streammanager/lambda/lambdamanager.go
- services/streammanager/lambda/lambdamanager_test.go
Earlier transformer was sending destConfig in message and it contains secrets so it is appearing in live events so refactored code to use config from CP.
[Lambda Keys exposed in Live events](https://www.notion.so/rudderstacks/CFD-Destination-config-leaking-to-Live-Events-for-AWS-Lambda-0efdfbd385384462b0f194dca2c66bfd)
> refactor: use destination config from config-be than from message

- processor/processor.go
- router/batchrouter/batchrouter.go
- router/router.go
- services/multitenant/tenantstats.go
Fixes unnecessary extra statistics captured at router level, where pending event Gauges were initialized for all destinations for all workspaces served by the server instance.
[fix router pending event alerts](https://www.notion.so/rudderstacks/fix-router-pending-event-count-stats-935e387b59e24372b7a57e00338fedba)
> fix: unnecessary router pending event counts

- router/router.go
- router/transformer/transformer.go
For the stats router_batch_num_output_jobs and router_transform_num_output_jobs we don't have workspaceId as one of the labels. And these stats are being used to calculate the percentage of failures
Without workspaceId information, in a multi-tenant kind of environment, it would be very difficult to find out from which workspace are we getting error from.
Also, for transformerProxy enabled destinations, we are using transformer_proxy.delivery_request to calculate the percentage of failures during delivery to destination. Even this stat doesn't have workspaceId
Hence made the changes below
Add workspaceId stat for transformer_proxy_delivery_request
Add a new stat router_transform_num_jobs which tracks the jobs for batch/router transformation, includes workspaceId …
> fix(destination): add proper stats for rt/batch transformation & proxy

- Makefile
- processor/processor.go
- processor/processor_test.go
Shallow copy destination config for config filters
[Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=e80d05de22cb4dc48f18741bb7072227&pm=s)
> fix: shallow copy config in processor

- services/stats/measurement.go
- services/stats/stats_internal_test.go
Treating 2 edge cases where `Timer#Stop` might panic:
1. Calling `Stop` without calling `Start` first.
2. Calling `Start` first, before the statsd client is ready and calling `Stop` next, but after statsd client is ready.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=f655981f7a0946f29b613371ae05dd82&pm=s)
> fix: stats.Timer#End panics with nil pointer

- event-schema/event_schema.go
- gateway/gateway.go
- gateway/webhook/webhook.go
- gateway/webhook/webhookTransformer.go
- internal/throttling/throttling.go
- jobsdb/admin.go
- jobsdb/backup.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_utils.go
- jobsdb/migration.go
- jobsdb/queued_db_request.go
- mocks/services/stats/mock_stats.go
- processor/stash/stash.go
- processor/trackingplan.go
- regulation-worker/internal/delete/api/api.go
- regulation-worker/internal/delete/batch/batch.go
- regulation-worker/internal/delete/kvstore/kvstore.go
- router/batchrouter/batchrouter.go
- router/router.go
- services/stats/measurement.go
- services/stats/memstats/stats.go
- services/stats/memstats/stats_test.go
- services/stats/stats_internal_test.go
- services/stats/stats_test.go
- warehouse/clickhouse/clickhouse.go
- warehouse/deltalake/databricks/databricks.go
- warehouse/deltalake/deltalake.go
- warehouse/slave.go
- warehouse/upload.go
- warehouse/warehouse.go
Removes `statsdTimer.#Start,#End`
Introduces `statsdTimer.#RecordDuration` - a deferred call will record the duration of the calling function
```
func someFunction(...) error {
defer timerStat.RecordDuration()()
// do work
return nil
}
```
[reference](https://stackoverflow.com/a/45766707/19093808)
[Drop stats.Timer#{Start,Stop} interface](https://www.notion.so/rudderstacks/Drop-stats-Timer-Start-Stop-interface-70f43122b5f4447482d4304f6fab9fd3)
> refactor: timerStat.RecordDuration, Since instead of timerStat.Start, End

- regulation-worker/cmd/main_test.go
- regulation-worker/internal/delete/batch/batch.go
Disable batch destinations by default through a configuration option
> chore: disable batch destinations by default in regulation worker

- app/cluster/integration_test.go
- processor/manager.go
- processor/manager_test.go
- processor/processor.go
- processor/processor_test.go
- processor/trackingplan.go
- processor/transformqueue.go
- runner/runner.go
- utils/misc/asyncinit.go
- utils/misc/asyncinit_test.go
Preparation steps before starting the actual work for introducing workspace isolation in processor:
- Removing global variables from the `processor` package
- Renaming `processor.HandleT` to `processor.Handle`
- Introducing `misc.AsyncInit` for streamlining how our components wait for their proper initialization before actually starting working (hint: `backendconfig.WaitForConfig` is not 100% safe)
- Make sure that processor is properly initialized before starting (using `misc.AsyncInit`)
- Fix issue with multiple successful HTTP requests performed for transformer features when starting up
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=4f93b562e40743fcad2ce119dcacdc84&pm=s)
> refactor(processor): stop using global variables

- processor/processor.go
event filter in count was showing the successful output count. Fixes that
[event filter in count fix](https://www.notion.so/rudderstacks/eventFilterInCount-fix-4bf937f8cb6b4144982172fa6d92456d)
> fix(processor): wrong event filter in count stat captured

- services/streammanager/kafka/client/client_test.go
- services/streammanager/kafka/client/logger.go
- services/streammanager/kafka/client/producer.go
- services/streammanager/kafka/kafkamanager.go
- services/streammanager/kafka/kafkamanager_test.go
When `WriteErrors` from the Segment Kafka library are wrapped they don't result as temporary anymore. This PR aims to fix this issue.
< [Notion Link](https://www.notion.so/rudderstacks/Handling-wrapped-temporary-errors-for-Kafka-destinations-0959d007cbc64dcc82baaf02ec187007) >
> chore: handling wrapped temporary errors for Kafka destinations

- enterprise/replay/replay.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
- jobsdb/jobsdb_utils.go
Jobsdb queries to support filtering by `workspace_id`.
[jobsdb adaptations for workspace isolation](https://www.notion.so/rudderstacks/Processor-isolation-jobsdb-adaptations-86a6151e51dd469fa32e674c2b33dfe1)
> chore(jobsdb): support query filter by workspaceID

- config/config.yaml
- router/router.go
Adding throttling stats in router.
> fix: adding throttling stats in router

- gateway/webhook/webhook.go
Fixing the following error:
> runtime error: slice bounds out of range [:-1] 
```
BugsnagNotify.func1.1 in /rudder-server/utils/misc/misc.go 1207
(*Once).doSlow in sync/once.go 74
BugsnagNotify.func1 in /rudder-server/utils/misc/misc.go 1196
gopanic in runtime/panic.go 884
goPanicSliceAcap in runtime/panic.go 139
(*batchWebhookTransformerT).batchTransformLoop in /rudder-server/gateway/webhook/webhook.go 330
Setup.func1 in /rudder-server/gateway/webhook/setup.go 67
WithBugsnag.func1 in /rudder-server/utils/misc/misc.go 1217
(*Group).Go.func1 in /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go 75
```
[Squadcast incident](https://app.squadcast.com/incident/63dbc5176511482a359539c6)
> fix: runtime error: slice bounds out of range [:-1]

- warehouse/tracker.go
- warehouse/tracker_test.go
- warehouse/utils/utils.go
- Use gauge instead of the counter
- Instead of reporting 0 or 1, we are going to report always 1 and use a flag ok=true/false to capture the problematic uploads.
- We are going to log every time a problem is detected
https://www.notion.so/rudderstacks/Make-the-alert-for-stuck-wh-pipelines-warehouse-successful-upload-exist-as-P0-d69f679ee0d04907ae0ed76b7a482ac7
> fix(warehouse): warehouse successful upload exists

- warehouse/upload.go
use single protocol source category while doing dedup for new record
https://www.notion.so/rudderstacks/d8ea6e5cd7b2481db207d6b239676688?v=799e76e4eabd45b3ad80c87fdebdb765&p=df40e0715c0f4a12addeb849174d9e36&pm=c
> fix(warehouse): use single protocol source category while doing dedup for new record

- enterprise/suppress-user/syncer.go
Using the appropriate credentials depending on the deployment mode
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=82e8f8920320483d8c8c4d02f9bdda51&pm=s)
> fix: suppression syncer using wrong credentials in multi-tenant mode

- services/debugger/destination/eventDeliveryStatusUploader.go
- services/debugger/transformation/transformationStatusUploader.go
- services/debugger/transformation/transformationStatusUploader_test.go
update cache with only the `messageID`s of events that are put into the cache.
Done to avoid an issue scene recently where successful events were being displayed as `dropped` in live events.
[context](https://rudderlabs.slack.com/archives/C018SGKA998/p1674657597947759)
[notion ticket](https://www.notion.so/rudderstacks/live-events-cache-messageIDs-fix-ebdcb3068a354861a68ded5186d82033)
> fix: limit entire transformationStatus struct when caching them

- services/stats/measurement.go
- services/stats/stats.go
- services/stats/stats_test.go
Protecting `stats` package from invalid measurements:
1. If the measurement's name is empty, a warning will be logged and the measurement's name will be set to `novalue`.
2. If an empty tag key is found, a warning will be logged and the empty tag will be removed from the measurment's set of tags.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=698b01a23d824197bf154fccee6143ce&pm=s)
> chore: protect measurement & tag names from empty strings

- warehouse/client/controlplane/client.go
- warehouse/validations/validate.go
The warehouse validations are moved to use the sshKeyId which is injected from upstream when making a call to run validations. The benefit is to not depend on the warehouse destinationId the first time we have created a destination.
https://www.notion.so/rudderstacks/Augment-the-warehouse-validation-flow-to-play-nicely-with-the-sql-tunnel-based-validations-eb71efa64fcc466bb28da64b2d64a0f0
> fix(warehouse): warehouse validations fixed to lookup secrets using sshKeyId

- warehouse/integrations/deltalake/client/client.go
- warehouse/integrations/deltalake/deltalake.go
- When the validation fails at the connection step and we try to do the cleanup, the client is not yet set up. Causing the nil pointer.
- **Also, now we don't need these stats as well. These we have added initially for the monitoring purpose for calls made to the data bricks connector during POC**.
- **Also, this is already fixed in https://github.com/rudderlabs/rudder-server/pull/2940**
https://www.notion.so/rudderstacks/Unity-catalogue-for-Databricks-8898be7a27054896aae0f395c74b7d78?pvs=4
> fix(warehouse): deltalake client crashing when failing on connectionstep

- warehouse/warehouse.go
Count was the incorrect metric type to capture the number of pending events. Since we were interested in the time value and not the rate of change. 
https://www.notion.so/rudderstacks/Reduce-alert-noise-Improve-observability-5beff5b1a6e34a92a071b37ab117bf45?pvs=4
> chore: use gauge for capturing pending events

- services/debugger/transformation/transformationStatusUploader.go
- services/debugger/transformation/transformationStatusUploader_test.go
> fix: backporting limit entire transformationStatus struct when caching them

- warehouse/internal/repo/upload.go
- warehouse/internal/repo/upload_test.go
- warehouse/upload.go
- warehouse/upload_test.go
The original code didn't handle NULL correctly, but since the error has not been handled we weren't aware of the issue.
After a recent refactoring, the error code was exposed as a log.
In this PR, I have moved the SQL-related code to repo, added tests and handle the NULL case using `COALESCE(timings, '[]')::JSONB`
https://www.notion.so/rudderstacks/Handle-NULL-timings-0e2e23f055c54ee2abb6e19420ee88e3?pvs=4
> fix: handle NULL on upload timings

- warehouse/logfield/logfield.go
- warehouse/tracker.go
- warehouse/upload.go
- warehouse/utils/utils.go
**Log Improvement**: Make total count error to Warning instead of Error
https://www.notion.so/rudderstacks/Make-total-count-in-table-as-Warning-instead-of-Error-277b88c979ae41bbaed0ff63d202e37b
> chore(warehouse): use warn while getting total count in warehouse

- warehouse/internal/model/upload.go
- warehouse/internal/repo/upload.go
- warehouse/internal/repo/upload_test.go
- warehouse/internal/service/recovery.go
- warehouse/internal/service/recovery_test.go
- warehouse/upload.go
- warehouse/warehouse.go
Under some conditions, recovery can take time. We have seen cases from 30 minutes to 4 hours.
The recovery can block the scheduler loop for a particular destination type. Causing significant delays to upload creations.
By moving recovery to the upload loop we mitigate the problem. A single blocking recovery process can not block other uploads from being processed. Multiple (>8) blocking recoveries can saturate the available workers, in this case, we will increase the available workers.
The original was split into two parts:
* repo: querying the database to get interrupted destinations 
* service: the logic of triggering the recovery once, if it is needed
In an effort to simplify the recovery interface, the detection - querying the database -  happens just in time.
The logic is now …
> fix: move recovery from scheduler to upload

- sql/migrations/reports/000003_alter_reports_remove_source_batch_id.up.sql
Drop Column only if it exists in reports migration
https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=94f69f8b3ab84461adf0aab881da2cde&pm=s
> chore: drop column only if exists

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/processorAppHandler.go
- processor/manager.go
- processor/processor.go
- processor/stash/stash.go
- router/batchrouter/batchrouter.go
- router/batchrouter/factory.go
- router/factory.go
- router/router.go
- router/router_throttling_test.go
- utils/payload/limiter.go
- utils/payload/limiter_config.go
- utils/payload/limiter_setup.go
- utils/payload/limiter_test.go
Introduces utils/payload package.
1. utils mem package to fetch memory statistics(`available`, `free`, `used`) and publish them every fifteen seconds.
2. Further uses the free memory stat above to dynamically compute memory that can be safely used by various processes. This can be done optionally via `AdaptivePayloadLimiter.enabled`(disabled by default). Default behaviour is where all processes use their own pre-defined limits on memory.
Once enabled, there's three states that the limiter could be in - `normal`, `threshold`, `critical`.
`normal` state - all processes may use the maximum memory available(each usually has it's own pre-defined limit, so max here means each process may use the limit it imposes on itself)
`threshold` state - here each process uses a proportion of it's …
> feat: adaptive payload size limits

- router/router.go
Workaround until transformer adaptations are ready so that we can enforce validations introduced by #2970
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=5228050c2a6248189dcd738b151449bf&pm=s)
> chore: dedup destination metadata in router based on job id

- warehouse/integrations/azure-synapse/azure-synapse.go
- warehouse/integrations/bigquery/bigquery.go
- warehouse/integrations/clickhouse/clickhouse.go
- warehouse/integrations/deltalake/deltalake.go
- warehouse/integrations/deltalake/deltalake_test.go
- warehouse/integrations/mssql/mssql.go
- warehouse/integrations/postgres/postgres.go
- warehouse/integrations/postgres/postgres_test.go
- warehouse/integrations/redshift/redshift.go
- warehouse/integrations/snowflake/snowflake.go
- warehouse/integrations/testhelper/setup.go
Since we are already logging the error at the caller function, we don't want to log it twice. This is creating too much noise for the `ERROR` logs.
https://www.notion.so/rudderstacks/Log-improvement-for-Total-count-in-warehouse-integrations-fce52fb18a0d4b16947ea2900e1ba02e?pvs=4
> chore(warehouse): log improvements for total count in warehouse integrations

- warehouse/schema.go
- warehouse/schema_test.go
During the consolidation of local schema and staging files schema, we need to give preference for `text` datatype.
https://www.notion.so/rudderstacks/Consolidated-merge-schema-fix-40667555f36e47b38c0905b63a4030d0?pvs=4
> fix(warehouse): consolidaiton for merged schema to give preference for text datatype

- warehouse/logfield/logfield.go
- warehouse/validations/helper.go
nil fix for the file manager while running the validations.
https://www.notion.so/rudderstacks/Nil-check-for-manager-in-Error-Handling-e1d56655a88f482a8aaaedd83a859882?pvs=4
> chore(warehouse): filemanager nil fix for validations

- warehouse/identities.go
- warehouse/logfield/logfield.go
- warehouse/schema.go
- warehouse/schema_test.go
- warehouse/utils/utils.go
- Users tables have a hard dependency on `identifies` tables to have a similar schema. 
- Since in the `ALTER` column flow, if there is a dependent column, we are leaving the dependent columns as it is asking for customers to drop it.
- This is causing differences in the schema for users and identifies and it's causing failure for the creation of staging users table in [here](https://github.com/rudderlabs/rudder-server/blob/47a12bd3a270d76da8e2509bd59746ddd078a04d/warehouse/integrations/redshift/redshift.go#L566).
- Corresponding error logs:
`pq: column "context_<prop>-deprecated-<uuid>" does not exist in rudder_staging_identifies_73ffe05a67886765c9f0ebb64fe8a1e01`
https://www.notion.so/rudderstacks/skipping-deprecated-columns-14e79ea3e5ac4a3280b71aead9634f76?pvs=4
> fix(warehouse): skipping deprecated columns

- .github/workflows/builds.yml
Only releases should update the `latest` tag in rudder-server's docker image
> chore: don't include prereleases in docker latest tag

- warehouse/integrations/redshift/redshift.go
- Redshift dedup window should we false by default
- Redshift dedupWindowInHours is linked with DAY instead of HOUR
https://www.notion.so/rudderstacks/Redshift-dedup-window-should-be-in-Hours-452a5de839934fa1acb1fc3f0726cb05?pvs=4
> fix(warehouse): redshift dedup window

- router/router.go
- router/types/types.go
The `destinationID` was not taken into consideration in router's job ordering logic when doing batching, which caused invalid state to be captured in barriers. 
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=acf43fb2f6cb46909cb8fcbb42e24833&pm=s)
> fix(router): wrong job order keys used in batching job order logic

- internal/throttling/throttling_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_utils.go
- jobsdb/unionQuery.go
- router/router.go
- router/router_test.go
Addressing router job retry backoff inconsistencies which may also cause memory leak:
- We don’t delete entries from the map in case we drain jobs or mark them as aborted in places other than `postStatusOnResponseQ`.
- In case event ordering is disabled, the worker-specific map we are using now is not really useful, since there is no guarantee that the same job will always be assigned to the same worker…
To fix these issues we are no longer using an in-memory map per worker, but the job status' `retry_time` column is used for storing the calculated backoff time. JobsDB queries for retrieving jobs don't use any conditions against the `retry_time` column, otherwise in case of a server restart this would cause jobs to be picked out-of-order as router's event-ordering algorithm doesn't …
> fix: inconsistent and leaky retry delay logic in router

- processor/processor.go
- processor/processor_test.go
Corrected reading the destination config in processor.
Gets the consent categories pertinent to event filtering.
[relevant thread](https://rudderlabs.slack.com/archives/C04JAHUEP1B/p1677060333492419)
> fix: processor read of dest consent categories

- warehouse/warehouse.go
Since the warehouse processor expects priority orders by ASC, setting the default value to 100.
https://www.notion.so/rudderstacks/Warehouse-default-priority-to-set-to-100-20f47a2db688451d97710842496972c2?pvs=4
> chore(warehouse): default warehouse priority set to 100

- gateway/admin.go
- gateway/gateway.go
- processor/transformer/transformer.go
- router/router.go
- router/router_throttling_test.go
Using `lo.BufferWithTimeout` that either waits for a number of objects to receive from a channel or a timeout whichever's first.
[BufferWithTimeout](https://github.com/samber/lo#bufferwithtimeout)
> refactor: prefer using lo.BufferWithTimeout

- regulation-worker/cmd/main.go
- regulation-worker/internal/client/client.go
- regulation-worker/internal/client/schema.go
- regulation-worker/internal/model/model.go
- regulation-worker/internal/service/service.go
- regulation-worker/internal/service/service_test.go
Logic to `abort` deletion job after 5 failed_attempts is added.
regulation-manager changes can be found here: https://github.com/rudderlabs/data-regulation-service/pull/79
https://www.notion.so/rudderstacks/after-5-retires-of-deletion-job-change-mark-it-as-aborted-129b7ab0838140308fa032f00992a575?pvs=4
> chore: abort job after 5 attempts at deletion-worker

- warehouse/internal/repo/upload.go
Use first_event_at while pickup for warehouse processing jobs 
https://www.notion.so/rudderstacks/Use-first_event_at-while-pickup-from-processing-31c841fcdecc4ea8b6139ee0cb4d8daa?pvs=4
> chore(warehouse): use first_event_at while pickup for warehouse processing jobs

- services/debugger/cache/internal/badger/badger.go
- services/debugger/cache/internal/badger/badger_test.go
- Using multiple versions of the same key instead of a single version of each key containing multiple values (less cpu, i/o & memory intensive)
- Getting rid of mutexes (non-blocking between competing goroutines, e.g. router or gateway workers operating on the same keys)
- Delete previous values after reading them from cache
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=81356fa4f1da4929825e7ffebd2d368f&pm=s)
> chore: debugger's badgerdb cache optimisations

- utils/payload/limiter_setup.go
Using proper numeric values (non-custom types) for limiter stats. Fixes #3046
[ref github issue](https://github.com/rudderlabs/rudder-server/issues/3046)
> fix: payload limiter gauge reports invalid value type

- gateway/gateway.go
- gateway/gateway_test.go
Losing typecase to avoid missing out on events where `userId`/`anonymousId` is not of type string.
[gateway userId read fix](https://www.notion.so/rudderstacks/gateway-userId-read-fix-6b190ee8f1f24f6089664295ee54174c?pvs=4)
> fix: user/anonymous id read at gateway

- gateway/gateway.go
Remove workerID tag to reduce the number of Prometheus time series
[Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=d32db0263fb445098b216475f72906de&pm=s)
> chore: remove workerID tag

- Makefile
- warehouse/integrations/docker-compose.test.yml
1. increase timeouts for the backend container
2. improve logs in case of a failed setup
3. update databricks connector to v1.4.2
https://www.notion.so/rudderstacks/Warehouse-integration-tests-fix-c45039d9faa2481b9772d00beebfdd4c?pvs=4
> chore(warehouse): warehouse integration tests improvements

- jobsdb/jobsdb_utils.go
- services/metric/measurement.go
- services/stats/stats_test.go
Not including a `workspaceId` tag in jobsdb metrics when its value is empty or `_all_`
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=ad24c6fda36e4a37b4640ba50d1f364a&pm=s)
> chore(jobsdb): omit workspaceId tag when it doesn't correspond to an actual workspace

- utils/queue/priorityQueue.go
- utils/queue/priorityQueue_test.go
- utils/sync/limiter.go
In case of high contention, a deadlock was possible if the limiter was trying to notify a dynamic priority item which in turn was trying to increase its priority in the queue.
The limiter now releases the lock earlier, just before notifying the item's channel. The (removed) item will no longer block trying to increase its priority in the queue, it will execute this no-op and then get properly notified.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=feb16db615794204a0c3d9810073f2fb&pm=s)
> fix: limiter deadlock while trying to notify a dynamic priority item

- CHANGELOG.md
- utils/queue/priorityQueue.go
- utils/queue/priorityQueue_test.go
- utils/sync/limiter.go
Applying 1.6.3 hotfixes to main branch
fix: limiter deadlock while trying to notify a dynamic priority item (#3056)
> chore: applying 1.6.3 hotfixes to main branch

- services/stats/config.go
- services/stats/measurement.go
- services/stats/stats.go
Don't mind the stack trace that says v1.5.0, this happens on the latest of RudderServer as well.
Quick fix for:
```
==================
WARNING: DATA RACE
Write at 0x00c000195be0 by goroutine 905:
github.com/rudderlabs/rudder-server/services/stats.(*statsdStats).Start()
/Users/debanjanchatterjee/.go/pkg/mod/github.com/rudderlabs/rudder-server@v1.5.0-preview.2/services/stats/stats.go:126 +0x3de
github.com/rudderlabs/device-mode-transformation-server/cmd/server.Run()
/Users/debanjanchatterjee/backend/device-mode-transformation-server/cmd/server/main.go:51 +0x2c3
github.com/rudderlabs/device-mode-transformation-server/cmd/server_test.beforeEach.func1()
/Users/debanjanchatterjee/backend/device-mode-transformation-server/cmd/server/main_test.go:51 +0x3c …
```
> fix: enabled data race

- utils/mem/internal/cgroup/mem.go
- utils/mem/internal/cgroup/mem_test.go
- utils/mem/internal/cgroup/testdata/cgroups_v1_mem_limit_proc_self/sys/fs/cgroup/memory/pid1/memory.stat
- utils/mem/mem.go
- utils/mem/mem_test.go
- utils/mem/testdata/cgroups_v1_mem_limit/sys/fs/cgroup/memory/memory.stat
Previous calculation of memory usage under cgroups was not taking into consideration RSS & WSS memory, it was relying only to `memory.usage_in_bytes` which can be imprecise under circumstances. [This article](https://mohamedmsaeed.medium.com/memory-working-set-vs-memory-rss-in-kubernetes-which-one-you-should-monitor-8ef77bf0acee) explains how k8s actually calculates RSS & WSS memory respectively. 
With this change, we are now calculating both RSS & WSS values and consider the greatest one to be equal to the actual memory usage.
**_Note:_** verified in `prousmt` environment where this inconsistency was initially observed.
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=dfc827ae9677450b9f2a5b8e7ce4a742&pm=s)
> chore: perform rss/wss-aware cgroups memory usage calculation

- .github/workflows/verify.yml
Our CI checks sometimes fails with the following error:
As suggested by [setup-protoc's README](https://github.com/arduino/setup-protoc#usage), the following option can be used to avoid rate-limit:
```
with:
repo-token: ${{ secrets.GITHUB_TOKEN }}
```
https://www.notion.so/rudderstacks/Fix-CI-setup-protoc-rate-limit-90e1c06be0464184bb6aaf7e53e3fade?pvs=4
> chore: use token on protoc setup to avoid rate-limit

- jobsdb/admin.go
- services/metric/measurement.go
Adding new metric to query pending events on hosted given that `workspaceId` gets filtered out for free users.
Router pickup jobs won't be affected since they use their own in memory implementation.
Tested on dev.
< [Notion Link](https://www.notion.so/rudderstacks/Fix-workspaceId-ALL-efc7524f29574cd496b9547c3aa0557c) >
> fix: pending events all

- warehouse/internal/repo/upload.go
- warehouse/internal/repo/upload_test.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
The PR augments the capability of repo to count over wh_uploads using generic filters which gets used in the pending events API when calculating pending events and aborted events.
https://www.notion.so/rudderstacks/Fix-the-Pending-Events-API-to-return-always-if-the-events-have-been-aborted-in-a-boolean-flag-e251b60a20484513ad802fe4ed50d790
> fix(warehouse): added support for filtering on the uploads and calculating aborted events for task_run_id

- event-schema/event_schema_api.go
> Empty schema is allowed in json schema obtained from event models
https://www.notion.so/rudderstacks/Spreadsheet-Show-all-events-from-event-models-irrespective-of-no-properties-10c9bb3afe4e4340b1a0bf95c10e154e?pvs=4
> chore(warehouse): allow empty properties schema for event models

- router/router.go
Since job retry time is now persisted in the database and survives server restarts we need to adapt the backoff mechanism so that:
1. backoff logic is only performed if previous job status is failed and attempt number is greater than 0, and
2. if backoff is indeed performed for a job, then avoid picking subsequent jobs for the same ordering key in the same loop
_**Note:** During server startup, jobsdb recovery updates jobs marked as `executing` to `failed`._
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=c67732015ce349e5b402df9df0b7bbbc&pm=s)
> fix(router): retry backoff causing out-of-order job processing

- warehouse/integrations/snowflake/snowflake.go
- warehouse/upload.go
- Added support for observability around loading tables for SNOWFLAKE.
- Deepsource recommendations
- use %q instead of "%s" for quoted strings
https://www.notion.so/rudderstacks/dedup-metrics-for-snowflake-2ff3ff988a9f4b01bd1815ecc70849e6?pvs=4
> feat(warehouse): added duplicates stats for snowflake

- warehouse/integrations/snowflake/snowflake.go
- Snowflake default timestamp to timestamp with time zone
https://www.notion.so/rudderstacks/Snowflake-default-timestamp-to-timestamp_tz-69f60cef979841a5b3fbcdc805d7ce95?pvs=4
> fix(warehouse): snowflake default timestamp to timestamp with time zone

- services/debugger/cache/internal/badger/badger.go
- services/debugger/cache/internal/badger/badger_test.go
1. Using `1MB` as `valueThreshold` by default (this is what we are using now through an override)
2. Using 5 minutes as ttl by default (30 seconds is too short)
3. Cleanup badgerDB folder on startup by default (transitive data)
[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=cb3e9166a6d149af8845dd11ed433234&pm=s)
> chore: badgerDB improvements for debugger

- config/backend-config/types.go
- services/fileuploader/fileuploader.go
- services/fileuploader/fileuploader_test.go
in case of default backup retention period(7 days for now) to rudder-storage, jobs must be uploaded to `bucket/7dayretention` prefix(configurable via env - `JOBS_BACKUP_STORAGE_DEFAULT_PREFIX`).
[Implement 7-day data retention policy ](https://www.notion.so/rudderstacks/Implement-7-day-data-retention-policy-84be80a3881947df932ff664a45ed672?pvs=4)
> feat: default retention period set to 7 days for rudder backups

- warehouse/testdata/sql/namespace_test.sql
- warehouse/warehouse.go
- warehouse/warehouse_test.go
Fixing the bug introduced in the previous refactoring of `getNamespace` function which returned an empty namespace even though there was a valid namespace present in the `schema` table also adding tests for the same
[ Notion Link ](https://www.notion.so/rudderstacks/Fix-getNamespace-bug-a21a74603ef14372bf9aa4d0c51c67b5?pvs=4)
> chore: fix namespace bug

- .github/workflows/verify.yml
- enterprise/suppress-user/internal/badgerdb/badgerdb.go
- enterprise/suppress-user/internal/badgerdb/badgerdb_backup_bench_test.go
- enterprise/suppress-user/internal/badgerdb/badgerdb_repo_test.go
- enterprise/suppress-user/internal/badgerdb/badgerdb_test.go
- enterprise/suppress-user/repository.go
- services/debugger/cache/cache.go
- services/debugger/cache/internal/badger/badger.go
- services/debugger/cache/internal/badger/badger_test.go
- services/dedup/dedup.go
- utils/misc/misc.go
- utils/misc/misc_test.go
Introduce metrics to monitor the disk usage of badgerDB for various services (dedup, live-events, suppress-user)
https://www.notion.so/rudderstacks/measure-file-sizes-per-badgerDB-9e908f82c9fc448db466b021b950a87a?pvs=4
> chore: add metrics for file sizes for badgerDB

- router/transformer/transformer.go
- router/transformer/transformer_test.go
- router/types/types.go
- router/types/types_test.go
Job information in metadata is not of any use to transformer, thus excluding it from the request.
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=655d85119e6e4b07ac4abe1c8991df3d&pm=s)
> chore(router): don't include job in metadata during transformation requests

- warehouse/internal/repo/table_upload.go
- warehouse/internal/repo/table_upload_test.go
- warehouse/upload.go
Table uploads are not getting updated in case of load failures.
https://www.notion.so/rudderstacks/Table-uploads-not-updates-errors-41e6eee090fc4957a528221ecc1c07f9?pvs=4
> fix(warehouse): table uploads were not getting updated during errors

- warehouse/upload.go
identity tables load files are not generated
https://www.notion.so/rudderstacks/identity-tables-load-files-are-not-generated-a93496fff93e40c2bcc46f8d565e7a7d?pvs=4
> fix: identity tables load files are not generated

- warehouse/internal/loadfiles/loadfiles.go
In case when all the staging files are getting aborted, an Update of the staging file's status is failing with `no staging files to update`. 
We need to skip updates in case there are no staging files processed successfully.
https://www.notion.so/rudderstacks/no-staging-files-to-update-33aca1cfdcf6459fb02e1dc05cc13c81?pvs=4
> fix(warehouse): all staging files processing failed

- services/streammanager/kafka/client/testutil/util.go
This PR is to fix these kind of errors in our tests:
```
client_test.go:782: Could not create topic: create topic: cannot create topic with controller "kafka2:9092" and addresses [kafka1:9092 kafka2:9092 kafka3:9092]: [41] Not Controller: this is not the correct controller for this cluster
```
< [Notion Link](https://www.notion.so/rudderstacks/Controller-conn-kafka-test-bug-96886f4c03164b32a25286fe33c45852) >
> fix: controller conn

- processor/transformer/transformer.go
- router/transformer/transformer.go
Disabling keep-alives for load-balancing reasons. [This article](https://learnk8s.io/kubernetes-long-lived-connections) explains the issue.
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=b15943ec4c6a4ec0a977f3331e926254&pm=s)
> chore: disable KeepAlives by default in transformer HTTP clients

- utils/awsutils/session.go
- utils/awsutils/session_test.go
Setting the sessionConfig.RoleConfigAuth parameter before throwing an error for incompatible configs
> fix: roleBasedAuth parameter wasn't being set correctly

- services/filemanager/filemanager.go
- services/fileuploader/fileuploader.go
- services/fileuploader/fileuploader_test.go
- warehouse/api.go
adds externalID(workspaceID) to S3 fileuploader config.
The externalID was [spelled wrong](https://github.com/rudderlabs/rudder-server/blob/master/utils/awsutils/session.go#L26)([correct usage](https://github.com/rudderlabs/rudder-server/blob/master/utils/misc/misc.go#L931))
Also it is a required for IAM role.
Proc_error job status:
```
{
"Error": "error starting S3 session: externalID is required for IAM role"
}
```
Going with what's being done at batch-router as jobs uploaded to destination with same credentials succeeds but dumps being uploaded to the same bucket fails.
[data-retention role based auth](https://www.notion.so/rudderstacks/testing-data-retention-changes-0aeba1ea3a5d4c7c80b31ec55fb3fedb?pvs=4)
> fix: add externalID to S3 file uploader config

- regulation-worker/cmd/main.go
- runner/runner.go
Some components (e.g. kafka manager from the custom destination manager workflow) were creating measurements in their `Init` and they were initialized before we overwrote `stats.Default` with `stats.NewStats()`. That caused the loss of those metrics.
This PR is an attempt to fix that issue by making sure that `stats.Default` is created before the other "inits" are called.
< [Notion Link](https://www.notion.so/rudderstacks/Stats-order-bug-f40f6526fb18464b81453ffbbab7e8ef) >
> fix: stats come first

- router/router.go
- router/router_test.go
Out-of-order delivery was possible when `maxRetriesLimitReached` happened for a job with **batch transformation enabled** or when **transformation happened at the router (implicit batching)**: 
_A failed job that reached its max retries' limit was ultimately marked as `aborted` instead of `failed`, but jobs in the same batch for the same order key were marked as `waiting`. This caused other later jobs, already in the worker's buffer, for the same order key to be processed out-of-order, i.e. before the `waiting` jobs._
This fix, moves the process of marking such jobs as aborted to the next loop, at the beginning of the worker's process, in the same step where job draining is happening.
A side-effect of this change is that some metrics are affected too, i.e. instead of the …
> fix: illegal job order with maxRetriesLimitReached

- .github/workflows/builds.yml
- .github/workflows/housekeeping.yaml
- .github/workflows/tests.yaml
- .github/workflows/verify.yml
upgrading warehouse tests to use action v3 since  Node.js 12 actions are deprecated
> chore: upgrading workflow to use action v3.

- go.mod
- go.sum
- integration_test/kafka_batching/kafka_batching_test.go
- integration_test/kafka_batching/testdata/backend_config.json
- services/streammanager/kafka/client/producer.go
- services/streammanager/kafka/kafkamanager.go
- services/streammanager/kafka/kafkamanager_test.go
Making sure that batching on Kafka works as expected.
< [Notion Link](https://www.notion.so/rudderstacks/Increase-Kafka-batching-usage-432e3f51e50941189bb9be4981acd4da) >
> chore: kafka batching

- gateway/gateway.go
- jobsdb/jobsdb.go
The `errorMessagesMap` might not be initialized if `gwAllowPartialWriteWithErrors` is `false` which would lead to a `panic` in [line 337](https://github.com/rudderlabs/rudder-server/blob/release/1.7.x/gateway/gateway.go#L337).
It could also be that `internalStoreWithRetryEachInTx` returns a `nil` map with a non-nil error (i.e. `errStaleDsList`) [here](https://github.com/rudderlabs/rudder-server/blob/release/1.7.x/jobsdb/jobsdb.go#L1775).
Given that there might be multiple places where a wrong pair (i.e. map+error) can be returned, I'm proposing to do a final check right before the assignment to simplify things and to be 100% this won't break again in the future.
< [Notion Link](https://www.notion.so/rudderstacks/nana-gateway-nil-map-assignment-33fddcc13cd64fbd9af027dfbba9cb78) >
> fix: error messages map !initialized in gateway

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/gatewayAppHandler.go
- app/apphandlers/processorAppHandler.go
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_backup_test.go
- jobsdb/jobsdb_test.go
- jobsdb/migration_test.go
- jobsdb/unionQuery_test.go
- processor/manager_test.go
removing status handler artefacts from jobsdb.
[remove status handler](https://www.notion.so/rudderstacks/remove-readonlyjobsdb-and-status-handlers-bdcdccfc955a48ee961b248dede8fae6?pvs=4)
> chore: remove jobsdb status handler

- warehouse/integrations/redshift/redshift.go
`'load table: running copy command: pq: Spectrum Scan Error'`
```
'load table: running copy command: pq: message: Spectrum Scan Error, detail: 
-----------------------------------------------
error:  Spectrum Scan Error
code:      15007
context:   File ''https://s3.us-east-1.amazonaws.com/akash-dev/rudder-warehouse-load-objects/test_varchar_512/279L3gEKqwruBoKGsXZtSVX7vIy/79adf26f-0c8b-45b3-a021-56f168c50fc3-test_varchar_512/1681051854.279L3gEKqwruBoKGsXZtSVX7vIy.9511b0dc-f4ec-4f36-a197-15571560d6f8.
query:     26599180
location:  dory_util.cpp:1450
process:   worker_thread [pid=10160]
-----------------------------------------------
'
```
https://www.notion.so/rudderstacks/Redshift-error-handling-cad6b54563d54e9da480a7badb9fd73c?pvs=4
> chore: error enrichment for redshift

- warehouse/internal/api/http.go
- warehouse/warehouse.go
Remove logging in LogRequest messages potentially leaking credentials. 
https://www.notion.so/rudderstacks/Warehouse-logging-credentials-835d5e39ef3d4971a13616c67b1069a3?pvs=4
> fix: remove logging in messages potentially leaking creds

- processor/eventfilter/eventfilter.go
We want to maintain convention of using `slices` over `lo` package across the repository
https://www.notion.so/rudderstacks/GA4-page-calls-error-is-displaying-in-live-events-tab-for-hybrid-mode-connection-52c58ee1924941f1b037fb8f63fc2445?pvs=4
> fix: update lo to slices in eventfilter package

- warehouse/integrations/snowflake/datatype_mapper.go
- warehouse/integrations/snowflake/datatype_mapper_test.go
- warehouse/integrations/snowflake/snowflake.go
When mapping the Snowflake numeric datatype with the Rudder datatype, it is recommended to include the scale information, as Snowflake supports scales. This can help map the Snowflake numeric datatype with the float datatype in Rudder, instead of the integer datatype.
https://docs.snowflake.com/en/sql-reference/data-types-numeric#number
https://www.notion.so/rudderstacks/Add-precision-support-for-numeric-type-in-snowflake-724401dbf9d54314a36589d8d5445a96?pvs=4
> fix: add numeric scale precision to snowflake

- router/eventorder_test.go
- router/internal/eventorder/eventorder.go
- router/internal/eventorder/eventorder_test.go
- router/router.go
- schema-forwarder/internal/forwarder/abortingforwarder.go
Until now, a single concurrency limiter existed in router's barrier, i.e. our event ordering mechanism, which was there to ensure that when a failed job got drained (aborted), in the next router generator loop only a single job would be picked up by the router for the same ordering key. This happens so as not to flood the worker's queue with jobs which are most probably going to be marked as `waiting` later on.
We are now introducing an additional concurrency limiter, which is responsible for limiting the overall maximum number of jobs that can enter the barrier for the same ordering key, regardless of failures. This barrier will protect us from a single "chatty" ordering key saturating the worker’s queue, so that jobs for other ordering keys can have a fair chance of being picked up by …
> feat(router): limit number of jobs with the same ordering key in worker's queue

- warehouse/internal/loadfiles/loadfiles.go
Fix the panic caused on proeumt
```
panic: interface conversion: interface {} is int, not float64 [recovered]
panic: interface conversion: interface {} is int, not float64 [recovered]
panic: interface conversion: interface {} is int, not float64
goroutine 110 [running]:
github.com/bugsnag/bugsnag-go/v2.AutoNotify({0xc001db5310, 0x3, 0xc000100c00?})
/go/pkg/mod/github.com/bugsnag/bugsnag-go/v2@v2.2.0/bugsnag.go:112 +0x3ec
panic({0x25c2f00, 0xc001148f90})
/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/rudderlabs/rudder-server/utils/misc.BugsnagNotify.func1.1()
/rudder-server/utils/misc/misc.go:1173 +0x35c
sync.(*Once).doSlow(0xc0016095e8?, 0x40e087?)
/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
/usr/local/go/src/sync/once.go:65 …
```
> chore: fix typecast panic

- services/debugger/destination/eventDeliveryStatusUploader.go
- warehouse/warehouse.go
- Initiate db handle in warehouse slave 
- Fix deadlock issue faced on multi-tenant production
[Notion Link](https://www.notion.so/rudderstacks/Async-job-framework-not-working-cbe5bb3cad84414a84d5f6ce2e034119?pvs=4)
> chore: initiate db handle warehouse slave

- services/debugger/destination/eventDeliveryStatusUploader.go
- services/debugger/source/eventUploader.go
- services/debugger/transformation/transformationStatusUploader.go
Fixes the Deadlock described below as described clearly by @atzoum 
- goroutine-1 acquires a read lock [here](https://github.com/rudderlabs/rudder-server/blob/0ad29a3222b68d7cb82a6395672b91f12d363840/services/debugger/destination/eventDeliveryStatusUploader.go#L127) successfully!
- goroutine-2 tries to acquire a full lock [here](https://github.com/rudderlabs/rudder-server/blob/0ad29a3222b68d7cb82a6395672b91f12d363840/services/debugger/destination/eventDeliveryStatusUploader.go#L185), but is waiting since goroutine-1 already has a read lock.
- goroutine-1 proceeds and calls HasUploadEnabled, which in turn tries to acquire a read lock again [here](https://github.com/rudderlabs/rudder-server/blob/0ad29a3222b68d7cb82a6395672b91f12d363840/services/debugger/destination/eventDeliveryStatusUploade …
> chore: fix deadlock issue uploader

- services/controlplane/client.go
- services/controlplane/client_test.go
- services/streammanager/kafka/client/client.go
- services/streammanager/kafka/client/client_test.go
- services/streammanager/kafka/client/config.go
- services/streammanager/kafka/kafkamanager.go
- services/streammanager/kafka/kafkamanager_test.go
Modified kafka to get ssh config from config-BE in addition to from env. 
NOTE: getting config via env has to be deprecated in future. 
https://www.notion.so/rudderstacks/Kafka-with-SSH-control-plane-config-8a25b92171464903a2a5db9e40645290?pvs=4
> feat: modifed kafka to use config received from config-be.

- processor/stash/stash.go
The stash loop should sleep if query limits are not reached. The previous logic was inverse, i.e. stash kept querying the database continuously for more jobs even though no jobs were present
> fix: stash loop is not sleeping even though query limits are not being reached

- warehouse/integrations/deltalake-native/deltalake.go
- Add `databricks` retries policy to the `databricks` client. This is basically used as a cold start time in order to connect to the `databricks` cluster.
https://www.notion.so/rudderstacks/Databricks-intermittent-failures-d5e939f3749543888b8f070a4c14c7e2?pvs=4
> fix: databricks retries

- services/streammanager/kafka/kafkamanager.go
SSH is enabled for Cars so the SSH keys that are read are now those ones although for backwards compatibility, if present, the ones from the secret should be read first.
< [Notion Link](https://www.notion.so/rudderstacks/Kafka-SSH-fixes-df083da3e3564dd0bdfcddcefda0c838) >
> fix: kafka secret comes first

- processor/stash/stash.go
Properly calculating sleep time when no jobs are retrieved by the stash loop
> fix: stash sleep

- backend-config/backend-config.go
Add the ability to disable db caching. 
In environments with large config files (~600Mbs uncompressed) having multiple instances (warehouse masters + N x slaves) can potentially impact database performance. Moreover caching in these environments is not as important, as warehouse doesn't have the same availability requirements as gateway.
https://www.notion.so/rudderstacks/Toggle-for-config-db-caching-52b551ad354e437d8265b82ef59e9547?pvs=4
> chore: add toggle for backendconfig db caching

- enterprise/reporting/error-detail-extractor.go
- enterprise/reporting/error_detail_reporting.go
- enterprise/reporting/reporting_test.go
~~Add error extraction logic using `gjson`~~
Updated the logic a bit used json in some parts for more concrete evaluation of json & parsing the json itself before we go for recursive search of probable error message keys
https://www.notion.so/rudderstacks/Adding-errorMessage-field-in-reports-table-of-rudder-server-e584e48c6959476abc5b5b72dd8693c3?pvs=4
> feat: add error extraction logic

- warehouse/warehouse.go
- warehouse/warehouse_test.go
- Fix flaky test for Test_GetNamespace
```
=== Failed
=== FAIL: warehouse Test_GetNamespace/should_return_namespace#06 (3.68s)
warehouse_test.go:346: 
Error Trace:	/home/runner/work/rudder-server/rudder-server/warehouse/warehouse_test.go:346
Error:      	Not equal: 
expected: "config_result"
actual  : "stringempty"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-config_result
+stringempty
Test:       	Test_GetNamespace/should_return_namespace#06
--- FAIL: Test_GetNamespace/should_return_namespace#06 (3.68s)
=== FAIL: warehouse Test_GetNamespace (0.00s)
```
https://www.notion.so/rudderstacks/Flaky-test-f0de0f027e8c4c22ba7c05be4ce46100?pvs=4
> chore: fix flaky test

- warehouse/internal/repo/staging.go
- Set staging files status to waiting instead of an empty string when inserting.
https://www.notion.so/rudderstacks/Staging-files-status-set-to-waiting-when-insert-8ccbac193d234598a2937ca051938ef6?pvs=4
> fix: staging files status when insert

- backend-config/backend-config.go
- backend-config/backend_config_test.go
- backend-config/namespace_config.go
- backend-config/namespace_config_test.go
- backend-config/testdata/sample_namespace.json
- backend-config/types.go
We have added support to fetch incremental updates from the control-plane while getting the workspace configs for a particular workspace. The way it works is when we first fetch the config from the control-plane, the config corresponding to every workspace has the **updateAt** field set. The control-plane api also supports a parameter called **updatedAfter** , which if passed, is expected to return only those workspaces which have seen a change. The semantics of the behavior is such that we keep track of the last value of the **updateAt** field in the various workspaces and pass that in subsequent request to only get the updates which are then applied on top of the previously maintained state of the configs. 
https://www.notion.so/rudderstacks/use-test-updatedAt-for-backend-config-1701f037 …
> feat: support for incremental updates while fetching backend config

- processor/processor.go
- processor/worker.go
- processor/worker_test.go
To avoid very frequent jobsDB queries by processor's workers, we are now using longer sleep times by default, but we also avoid sleeping when query limits are being reached.
> chore: adaptive processor worker sleep time

- processor/processor.go
Source definition type was being sent as empty string("") when user transformation is connected to a destination.
As `SourceDefinitionType` was not being populated in the metadata(`commonMetadata`) before sending to user transformation.
We are aiming to fix.
https://www.notion.so/rudderstacks/GA4-page-calls-error-is-displaying-in-live-events-tab-for-hybrid-mode-connection-52c58ee1924941f1b037fb8f63fc2445?pvs=4
> fix: include source definition type when destination has UT

- warehouse/warehouse.go
- Queries are getting blocked on GetNamespace waiting for the connection to be free.
https://www.notion.so/rudderstacks/Max-connections-e8600736c8934804abf187849dfac51e?pvs=4
> fix: max connections for warehouse slaves

- jobsdb/jobsdb.go
- schema-forwarder/internal/forwarder/jobsforwarder.go
A missing close statement in jobsdb, in combination with schema forwarder using invalid jsonb data in job status rows, caused rudder-server's processor to get stuck, waiting for a ROLLBACK query to complete, in vain, until the context timed out.
> fix: schema forwarder records invalid json in statuses

- go.mod
- go.sum
- suppression-backup-service/api/api.go
Upgrade `Chi` middleware from v1 to v5
> chore: upgraded chi v1 middleware to v5

- .github/workflows/tests.yaml
- Makefile
- Separate job to scrape unit and integration test coverage and upload to codecov
https://www.notion.so/rudderstacks/Tests-coverage-fcdf2e7376d048b99e0358aa9f2a89d8?pvs=4
> chore: tests coverage

- README.md
Data Learning Center is a great resource for Data Engineers. Replace current slack link in announcement with the link to Data Learning Center.
> chore: replace announcement header with data learning centre link

- utils/sync/limiter.go
Options should be executed before tags are being used
> fix: limiter not respecting WithLimiterTags option

- warehouse/integrations/deltalake-native/deltalake_test.go
- warehouse/validations/validate.go
- warehouse/validations/validations.go
- In case of databricks external table, since we are using the same table and performing alter on it, We can't create the table again because there will be a mismatch in the schema. It is basically returning the following error:
```
The specified schema does not match the existing schema at s3://acorns-rudderstack-s3-sink-staging/rudder/delta/tables/rudderstack_setup_test/setup_test_staging.
== Specified ==
root
|-- id: long (nullable = true)
|-- val: string (nullable = true)
== Existing ==
root
|-- id: long (nullable = true)
|-- val: string (nullable = true)
|-- val_alter: string (nullable = true)
== Differences ==
- Specified schema is missing field(s): val_alter
If your intention is to keep the existing schema, you can omit the
schema from the create table command. Otherwise please …
```
> fix: external table support for databricks validations

- warehouse/errors.go
- warehouse/warehouse.go
- Error handling for getUploadToProcess.
- More at [here](https://github.com/rudderlabs/rudder-server/pull/3088#discussion_r1193947223).
https://www.notion.so/rudderstacks/GetUploadToProcess-error-handling-04fe991f6a90426195f8a9db78fd6e08?pvs=4
> chore: getUploadsToProcess error handling

- warehouse/integrations/deltalake-native/deltalake.go
- warehouse/integrations/deltalake/deltalake.go
- Since during the loading of the data from parquet using the **COPY command**, there is a default type that is inferred from the data. 
- It's better to typecast the data into the one which we used while we generate the load files to avoid having a mismatch.
https://www.notion.so/rudderstacks/Databricks-TIMESTAMP_NTZ-issue-a0a478b30e01457fbd2002db68dbfe9d?pvs=4
> fix: deltalake parquet datatype support

- processor/manager.go
- processor/processor.go
Processor must call shutdown after waitgroup returns. 
Issue surfaced after changes in https://github.com/rudderlabs/rudder-server/pull/3289 where badgerDB is being shut down.
> fix: processor panicking during shutdown

- warehouse/archive/archiver_test.go
- warehouse/integrations/clickhouse/clickhouse_test.go
- warehouse/integrations/clickhouse/testdata/docker-compose.clickhouse-cluster.yml
- warehouse/integrations/clickhouse/testdata/docker-compose.clickhouse.yml
- warehouse/integrations/middleware/sqlquerywrapper/sql_test.go
- warehouse/integrations/postgres/load_test.go
- warehouse/integrations/redshift/redshift_test.go
- warehouse/internal/service/loadfiles/downloader/downloader_test.go
- warehouse/tracker_test.go
- warehouse/upload_test.go
- warehouse/validations/validate_test.go
- warehouse/warehouse_test.go
- warehouse/warehousegrpc_test.go
- Added some debugging logs.
- Use a simpler setup for bringing up the dependencies using compose.
```
clickhouse_test.go:451: could not remove clickhouse minio network: API error (403): error while removing network: network 
clickhouse-minio-network id 58d24af95ecd9660a51954f61f41e52ddf875124fd998199e87b80c872543f87 has active endpoints
```
https://www.notion.so/rudderstacks/fix-removal-of-clickhouse-network-properly-0a34e4e2c72448d49556df09ff65c8e3?pvs=4
> fix: clickhouse flaky test

- CHANGELOG.md
- go.mod
- go.sum
- integration_test/kafka_batching/kafka_batching_test.go
- jobsdb/jobsdb.go
- processor/manager.go
- processor/processor.go
- router/batchrouter/handle.go
- router/batchrouter/handle_lifecycle.go
- utils/sync/limiter.go
- warehouse/integrations/deltalake-native/deltalake.go
- warehouse/integrations/deltalake-native/deltalake_test.go
- warehouse/integrations/deltalake/deltalake.go
- warehouse/validations/validate.go
- warehouse/validations/validations.go
merge release 1.9.0 in main branch
chore: tests coverage (#3349)
chore(deps): bump github.com/aws/aws-sdk-go from 1.44.264 to 1.44.265 (#3361)
chore(deps): bump google.golang.org/api from 0.122.0 to 0.123.0 (#3362)
chore(deps): bump github.com/stretchr/testify from 1.8.2 to 1.8.3 (#3359)
chore(deps): bump github.com/onsi/gomega from 1.27.6 to 1.27.7 (#3360)
chore: replace announcement header with data learning centre link (#3358)
feat(warehouse): staging file schema consolidation (#3088)
chore: make tests required for passing (#3347)
chore(deps): bump github.com/minio/minio-go/v7 from 7.0.52 to 7.0.53 (#3370)
chore(deps): bump github.com/aws/aws-sdk-go from 1.44.265 to 1.44.266 (#3368)
fix: gateway flaky test (#3356)
chore: getUploadsToProcess error handling (#3380) …
> chore: merge release 1.9.0 in main branch

- gateway/configuration.go
- gateway/gateway.go
- gateway/gateway_test.go
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
- mocks/jobsdb/mock_jobsdb.go
- processor/processor.go
- processor/processor_isolation_test.go
- processor/processor_test.go
- processor/worker.go
- processor/worker_handle.go
- processor/worker_test.go
gateway opens a batch of event, stores each event inside as its own batch.
gateway receives:
```
{
"batch": [
{event-1},
{event-2}
]
}
```
gateway stores:
```
jobid - 1:
{
"batch": [
{event-1}
]
}
jobid - 2:
{
"batch": [
{event-2}
]
}
```
Tangential to another [PR](https://github.com/rudderlabs/rudder-server/pull/3251) where gateway simply stores the singular event to gateway table.
The current approach avoids changing things at processor, and does not bear the burden of transitioning from previous behaviour which is evident from the other PR.
[relevant slack thread](https://rudderlabs.slack.com/archives/C01HTT66UMB/p1682402259238799)
> chore: gateway stores singular event batches

- schema-forwarder/internal/batcher/batcher.go
- schema-forwarder/internal/forwarder/jobsforwarder.go
Slice index changes as we are removing elements from it, thus reverting to the previous behaviour. Regression of #3406
> fix: jobsforwarder panics with slice bounds out of range

- .github/workflows/tests.yaml
- Makefile
Split unit test to have separate for server and warehouse.
https://www.notion.so/rudderstacks/Split-unit-tests-17b9ccd7a2c440d5adfbffc2d758ae57?pvs=4
> chore: split unit tests

- warehouse/integrations/azure-synapse/azure_synapse_test.go
- warehouse/integrations/bigquery/bigquery_test.go
- warehouse/integrations/clickhouse/clickhouse_test.go
- warehouse/integrations/datalake/datalake_test.go
- warehouse/integrations/deltalake-native/deltalake_test.go
- warehouse/integrations/mssql/mssql_test.go
- warehouse/integrations/postgres/postgres_test.go
- warehouse/integrations/redshift/redshift_test.go
- warehouse/integrations/snowflake/snowflake_test.go
Since [cleanup](https://github.com/rudderlabs/compose-test/blob/a2cf79de282196159ab0b4ce8ba11cd29f3fbe14/testcompose/compose.go#L36) is already being called from within [Start](https://github.com/rudderlabs/compose-test/blob/a2cf79de282196159ab0b4ce8ba11cd29f3fbe14/testcompose/compose.go#L29) of compose library, no need to call it twice.
https://www.notion.so/rudderstacks/Cleanup-for-warehouse-integration-tests-1820ba3fdc1646309b88d83ec384b5a8?pvs=4
> chore: cleanup for integration tests for warehouse

- router/batchrouter/handle_lifecycle.go
- utils/sync/limiter.go
Wrong order of arguments passed to the function calculating the config option key caused limiter's limit to be calculated as zero, leading batchrouter to not being able to enter the limiter.
> fix(batchrouter): batchrouter stops processing events for destinations where a destType-specific config option is set

- services/dedup/dedup_test.go
Fixing the flaky dedup test where the logger would be a nil pointer in misc package if misc hasn't been initialised
[ Notion Link ](https://www.notion.so/rudderstacks/upgrade-to-badgerV4-86d09c352df94fd5b6c6c109eafc1271?pvs=4)
> chore: fix flaky dedup test

- app/app.go
`/health` returns 503 if db is down
https://www.notion.so/rudderstacks/Improve-gateway-health-endpoint-86bae24700cc424ca7e44d7b9cde4bd9
> chore: gateway health endpoint should return 503 if db is down

- schema-forwarder/internal/transformer/transformer.go
- schema-forwarder/internal/transformer/transformer_test.go
- schema-forwarder/internal/transformer/types.go
Setting maximum limits in event properties while capturing schemas:
- Events with identifiers larger than **100 characters** will be discarded (0.3% of existing schemas)
- Events with schemas containing more than **500 keys** will be discarded (1% of existing versions)
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=a34916c6bd7b4ffcacfe7ec3a9d11985&pm=s)
> chore: set limits for event schema messages and discard messages above these limits

- .github/workflows/verify.yml
- Makefile
- build/wait-for-go/wait-for.go
- jobsdb/admin.go
- jobsdb/backup.go
- jobsdb/integration_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_utils.go
- jobsdb/migration.go
- router/eventorder_test.go
- services/multitenant/tenantstats.go
- services/pgnotifier/pgnotifier.go
- services/validators/envValidator.go
- utils/misc/dbutils.go
- utils/misc/misc.go
- warehouse/api.go
- warehouse/archive/archiver.go
- warehouse/client/client.go
- warehouse/identity/identity.go
- warehouse/integrations/azure-synapse/azure-synapse.go
- warehouse/integrations/clickhouse/clickhouse_test.go
- warehouse/integrations/deltalake-native/deltalake.go
- warehouse/integrations/middleware/sqlquerywrapper/sql_test.go
- warehouse/integrations/mssql/mssql.go
- warehouse/integrations/postgres-legacy/postgres.go
- warehouse/integrations/redshift/redshift.go
- warehouse/integrations/snowflake/snowflake.go
- warehouse/internal/repo/staging.go
- warehouse/internal/repo/upload.go
- warehouse/upload.go
I have upgraded golangci to `version: v1.52`, I have only specified up to minor versions so that patch upgrades will happen automatically.
With the upgrade, the following linters were reenabled again (disabled before due to generics)
* [rowserrcheck](https://github.com/golangci/golangci-lint/pull/3691)
* [wastedassign](https://github.com/golangci/golangci-lint/pull/3689)
rowserrcheck: After `rows.Next()` iteration we need to check for `rows.Err()`.
wastedassign: Assign and value and not use it. In most cases `x := 0` -> `var x int`
https://www.notion.so/rudderstacks/Upgrade-golangci-version-lint-fixes-7abe589fec944d16b16ca378363ac8d1?pvs=4
> chore: upgrade golangci version and lint fixes

- services/streammanager/kafka/kafkamanager_test.go
Increasing timeout since [I can't find any failure](https://github.com/rudderlabs/rudder-server/actions/runs/5184540788/jobs/9343545830?pr=3397) I'm guessing that simply Kafka was not ready yet.
> fix: kafka flaky batching test

- processor/processor.go
Since multiple goroutines might be trying to store jobs in router's jobsdb for the same destinationID and to avoid job ordering guarantee panics (router encountering a job with id less than a job it has previously encountered), we are introducing a partition locker to serialise write access.
Now, before writing a batch of jobs in router, the goroutine in processor will acquire all required partition locks (using an ascending lock order for avoiding deadlocks) and release them after store is completed.
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=326809a9d1dd409d9786fb70ac9389ce&pm=s)
> chore(processor): support multiple jobsdb writers when source isolation is enabled

- processor/transformer/transformer.go
Handle non 2xx response codes in processor transformer and retry the events
[ Notion Link ](https://www.notion.so/rudderstacks/Retry-non-2xx-responses-processor-transformer-58ee7768907c4a61bc48f40b63653dc9?pvs=4)
> chore: add resp body status check

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/processorAppHandler.go
- app/cluster/integration_test.go
- app/features.go
- enterprise/reporting/error_reporting.go
- enterprise/reporting/mediator.go
- enterprise/reporting/reporting_test.go
- enterprise/reporting/setup.go
- enterprise/reporting/setup_test.go
- mocks/utils/types/mock_types.go
- processor/manager.go
- processor/manager_test.go
- processor/processor.go
- processor/processor_test.go
- router/factory.go
- router/manager/manager_test.go
- router/router.go
- router/router_test.go
- utils/types/reporting_types.go
- utils/types/types.go
- warehouse/upload.go
- warehouse/warehouse.go
We are implementing a facade or mediator for reporting to make it easier for us to integrate
This is how things look at high-level
We have created a new component that is responsible for:
- calling multiple error reporting implementations
- only call them if they are enabled
Advantages:
- This will simplify the code in the processor, router, and warehouse
- They will just call a single interface, and no need to check if reporting is enabled or not
**Credits**: @lvrach for the image, the following content
https://www.notion.so/rudderstacks/Design-for-errorCode-and-errorMessage-in-reports-table-3d5db2e4d485459f9b4f98b601c7a5e5?pvs=4
> feat: facade implementation for reporting

- jobsdb/backup.go
- jobsdb/migration.go
- jobsdb/migration_test.go
- services/dedup/dedup_test.go
Issue introduced by #3434, since a VACUUM command cannot be executed inside a transaction. Vacuum or vacuum full are now being executed, if necessary, after the transaction completes. Added the necessary test case to verify proper behaviour.
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=3a8df920ee344586b44817a490e58ddb&pm=s)
> fix: migration fails with error pq: VACUUM cannot run inside a transaction block

- router/handle_lifecycle.go
Wrong order of arguments while calling `getRouterConfigInt` caused issues with configurations containing destination type specific configuration overrides in router module.
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=31d3bf3af81c42a293bb08ef4d93c169&pm=s)
> fix: router panics with limit for rt_pickup must be greater than 0

- router/handle.go
- router/isolation/isolation.go
- router/isolation/isolation_test.go
- router/router_test.go
- router/types/types.go
Adding a counter for monitoring discarded jobs in router's iterator and stopping iteration in case jobs are discarded due to throttling and destination isolation is enabled
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=bcb07ce489a245e3b4dd614c66a7e7e6&pm=s)
> chore(router): observability on job iterator discards & stop iteration if throttled with destination isolation enabled

- jobsdb/jobsdb.go
Avoid querying a dataset if `params.AfterJobID != nil && *params.AfterJobID > dsRange.maxJobID`.
Added said logic to `jobsdb.GetProcessed(...)` and `jobsdb.GetUnprocessed(...)`
[update archive status](https://www.notion.so/rudderstacks/jobsdb-support-archive-state-a9c85931f711407a9cc0415f2c75ed83?pvs=4)
> chore: avoid querying a dataset in case AfterJobID falls after said dataset

- enterprise/reporting/error_extractor.go
- enterprise/reporting/reporting_test.go
The error message during transformation was not getting captured correctly in our error extraction logic. Through this PR we are aiming to fix it
https://www.notion.so/rudderstacks/Research-Integrate-generic-errorMsg-extractor-in-rudder-transformer-6a6775b37c8241a49cf7bfb655f3bf8e?pvs=4
> fix: error extraction for errors in destination transformation

- jobsdb/admin.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
introduces `MaxAge` for jobs.(default 720h)
A new routine(that runs once a day by default) cleans up jobs that have exceeded said duration by inserting an `aborted` status for said jobs.
[cleanup jobs whose workspace do not belong to server](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?pvs=4)
> chore: jobsdb max age for jobs, cleanup routine

- gateway/gateway.go
- gateway/gateway_test.go
Fix the HTTP method for the warehouse `/fetch-tables` endpoint. It should be `GET` 
[ticket](https://www.notion.so/rudderstacks/Fix-for-warehouse-endpoint-for-fetching-endpoints-0b86acfaa10c494587259a45ab17c6c9)
> fix(gateway): use get method for /fetch-tables 

- gateway/webhook/webhook.go
- gateway/webhook/webhook_test.go
Add a metric to count the number of source transformation errors.
We currently have webhook_num_errors metric. But this is not a true depiction of number of errors occurring during source transformation. Alerts defined on webhook_num_errors are noisy. This metric is added to prevent the alert noise on source transformation errors.
https://www.notion.so/rudderstacks/d5d15ce4be354e3caae11d4ea9f41477?v=2ad23dce1aeb431a82f783e6607d3cb0&p=79b89517ca0b47c39074944b922d6971&pm=c
> chore: source transformation failures stat

- .golangci.yml
Increase lint timeout to prevent github [actions](https://github.com/rudderlabs/rudder-server/actions/runs/5344164222/jobs/9688210263?pr=3536) from failing:
https://www.notion.so/rudderstacks/inc-lint-timeout-2effb94a84444f6aaaaad79d982ad33f?pvs=4
> chore: increase golangci lint execution timeout

- gateway/gateway.go
- gateway/gateway_test.go
- warehouse/warehouse.go
Move warehouse fetch tables under internal.
[ticket](https://www.notion.so/rudderstacks/Move-fetch-tables-endpoint-to-internal-endpoints-117e9b2261b54f51817b64d6ada285cb)
> chore(gateway): move warehouse fetch tables under internal

- gateway/webhook/webhook.go
- gateway/webhook/webhook_test.go
Got rid of recently introduced `source_transformation_errors` metric and using the existing `webhook_num_errors` metric after enriching the `webhook_num_errors` metric with more labels. This (reason label) makes debugging the webhook errors easy.
https://www.notion.so/rudderstacks/d5d15ce4be354e3caae11d4ea9f41477?v=2ad23dce1aeb431a82f783e6607d3cb0&p=79b89517ca0b47c39074944b922d6971&pm=c
> chore: source transformation failures stat tag correction

- router/batchrouter/handle.go
- router/batchrouter/handle_observability.go
- router/worker.go
- services/diagnostics/diagnostics.go
Removing the `attempt_number` tag as this can cause serious metric cardinality issues.
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=47b856c6a77542b4bf3ffbe3aca5ef75&pm=s)
> chore: drop attempt_number tag from metrics

- warehouse/internal/api/http.go
Use workspaceId instead of workspace_id for tags in metrics **rows_staged**
https://www.notion.so/rudderstacks/workspace_id-tag-for-rows-staged-metrics-ec3505370e664686bbe729e87fe349bc?pvs=4
> chore: typo for workspaceId in stats

- jobsdb/jobsdb.go
- jobsdb/jobsdb_test.go
- jobsdb/migration.go
Acquiring a dsList write lock when not needed and while jobsdb queries are performing slow can have cascading effects on throughput, thus we now acquire one only when necessary and we are acquiring read locks for shorter periods as well:
- During `addNewDSLoop` jobsdb acquires a `dsList` lock only if its needs to add a new dataset.
- During `refreshDSListLoop` jobsdb acquires a `dsList` lock only if it detects a new dataset.
- While reading, jobsdb releases the `dsList` rlock early. The `migration` rlock that has already been acquired will make sure that no existing dataset will be removed from the list. Any new (rightmost) dataset can be added without any adverse effect.
- While updating job statuses, josdb releases the `dsList` rlock early. The `migration` rlock provides the same …
> chore(jobsdb): dsList lock performance improvements

- integration_test/kafka_batching/kafka_batching_test.go
- runner/buckets.go
- runner/runner.go
I don't think we need as many buckets as we do by default for the `gateway_response_time metric`. This task is to keep only the relevant buckets.
I propose we remove the boundaries for requests that take longer than 5 minutes. Data wise, knowing that it takes even longer isn't helpful in my opinion and we should try to avoid anything that goes above 1 minute and possibly look into anything that goes above 5.
Screenshot from `prousmt`:
Tested locally:
Let me know if the boundaries make sense to you and if you think we should have different ones.
Also, if you think we should do the same with other metrics we might as well add them here.
< [Notion Link](https://www.notion.so/rudderstacks/gw-response-time-buckets-9ff53d3d1a334d359c61b5e914825a5d) >
> chore: gateway_response_time buckets

- processor/transformer/transformer.go
- processor/transformer/transformer_test.go
Fixing a regression introduced by #3446
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=4f72cce4d22a48ac95feabb7875081d9&pm=s)
> fix: transformation does not retry indefinitely when control plane is down

- jobsdb/jobsdb.go
- jobsdb/migration.go
- router/handle_lifecycle.go
- Change default values
- `JobsDB.jobDoneMigrateThres: 0.7` tables with 70% of jobs completed will be eligible for migration
- `JobsDB.refreshDSListLoopSleepDuration: 10s` refresh loop will run less often
- `JobsDB.cacheExpiration: 120m` no-jobs cache will expire after 2 hours
- New `migration_loop_lock` metric: Count the time that jobsdb operations will be blocked due to a migration/dsList lock
- New `refresh_ds_loop_lock` metric: Count the time that jobsdb operations will be blocked due to a dsList lock
- Remove `jobStatusCountMigrationCheck`: this was disabled by default and we planned to remove it anyway
- Don't care about the number of job statuses while deciding whether a table is small during migrations (small tables will be migrated as long as there are two of them, i.e. …
> chore(jobsdb): tuning and improvements

- warehouse/internal/loadfiles/loadfiles.go
- warehouse/upload.go
- Since viper internally stores its keys in lowercase, we need to compare checking with lowercase for StringMap
https://www.notion.so/rudderstacks/warehouse-config-string-map-comparision-in-lower-case-941eae92d77946fc9f41be8d17e5f685?pvs=4
> fix: warehouse stringmap configs are lower case w.r.t viper

- services/pgnotifier/pgnotifier.go
- warehouse/warehouse.go
- Setting maxOpenConnections for Warehouse and PgNotifier db handle.
https://www.notion.so/rudderstacks/Max-open-connection-for-warehouse-and-postgres-91e4987ff26b41f6a7aa337fa3cb8f80?pvs=4
> chore: add max connections to warehouse and pgnotifier

- warehouse/integrations/bigquery/bigquery_test.go
- warehouse/integrations/deltalake/deltalake_test.go
- warehouse/integrations/redshift/redshift_test.go
- warehouse/integrations/snowflake/snowflake_test.go
Since validation tests are also running which creates the schema but not drops it. Added cleanup during validations.
https://www.notion.so/rudderstacks/Cleanup-integration-tests-fa75cc8c7d9e4ce887988a107d1f684f?pvs=4
> fix: cleanup for warehouse integration tests

- app/cluster/integration_test.go
- enterprise/replay/replay.go
- enterprise/replay/sourceWorker.go
- mocks/processor/transformer/mock_transformer.go
- processor/eventfilter/eventfilter.go
- processor/integrations/integrations.go
- processor/manager.go
- processor/manager_test.go
- processor/processor.go
- processor/processor_test.go
- processor/trackingplan.go
- processor/trackingplan_test.go
- processor/transformer/transformer.go
- processor/transformer/transformer_test.go
- runner/runner.go
- services/debugger/transformation/transformationStatusUploader.go
- services/debugger/transformation/transformationStatusUploader_test.go
- warehouse/utils/utils.go
- Add support for handling panics in case of user transformations for timeouts.
- Small refactoring around removing globals.
https://www.notion.so/rudderstacks/Hosted-abort-jobs-timed-out-during-UT-c21526789be046b3bec857bd239b8ae3?pvs=4
> fix: user transformations timeout

- processor/transformer/transformer.go
- router/batchrouter/util.go
- router/misc.go
Retry events when traefik gives 408 as a response to server.
[Notion Link](https://www.notion.so/rudderstacks/Retry-408-transformer-65ab447caf224d00b227b65fff1d1959?pvs=4)
> chore: retry on 408 response events

- processor/transformer/transformer.go
- router/batchrouter/util.go
- router/misc.go
Retry events when traefik gives 408 as a response to server.
[Notion Link](https://www.notion.so/rudderstacks/Retry-408-transformer-65ab447caf224d00b227b65fff1d1959?pvs=4)
> chore: retry on 408 response events hot fix

- processor/manager.go
- processor/processor.go
The call to populate pending events should be a blocking call and should be completed before any of the components start
Since the removal of multi-tenant stats the population of pending events is done at `processor.Start` which is a non blocking call and the `router`,`batch router` components might start before the backfilling of in-memory stats.
Now the backfilling code is made blocking and will be executed before the processor starts
[ Notion Link ](https://www.notion.so/rudderstacks/negative-pending-event-count-bug-1d57bd99cb874b5b96e6a691820f4a1e?pvs=4)
> chore: fix negative pending event count

- jobsdb/jobsdb.go
In scenarios where the database is being throttled, database query delays can cause jobsdb's maintenance operations to take much longer. 
Usually, a maintenance operation times out when it doesn't manage to acquire a write lock in time. But this operation will keep retrying periodically and will be timing out continuously, causing the system to come to a standstill (a waiting write lock causes any other read lock requests to block too).
Therefore increasing timeouts to more sensible values (`10m`) and making them hot-reloadable as well
[Link](https://www.notion.so/rudderstacks/Pipelines-Sprint-68c1c213e9b840b3a9b3826e3631e39a?p=122ab1effd184bdb881d02c069c2235b&pm=s)
> chore(jobsdb): increase maintenance operation timeouts and make them hot-reloadable

- runner/buckets.go
Add custom buckets i.e. 1 day, 5 days, 10 days, 30 days, 60 days, 90 days, 180 days, 360 days for gateway.user_suppression_age metric
https://www.notion.so/rudderstacks/Add-custom-buckets-1-day-5-days-10-days-30-days-60-days-90-days-180-days-360-days-for-gateway-6fc3093d32834f6a9ee3576964f81a81
> chore: add custom buckets to gateway.user_suppression_age

- jobsdb/backup.go
- processor/stash/stash_test.go
- services/fileuploader/fileuploader.go
- services/fileuploader/fileuploader_test.go
Ignore error resulting from a workspace's backup config not being found.
This is done so the backup is not stalled in such case.
[linear cfd link](https://linear.app/rudderstack/issue/RUD-412/subteams03sekbfx0dserver-on-call-lot-of-pre-drop-gw-tables-on)
> fix: ignore workspace if no backup config is found

- warehouse/utils/utils.go
edit warehouse timeout config name to maintain consistency.
[warehouse timeout](https://www.notion.so/rudderstacks/Timeout-for-all-SQL-queries-in-warehouse-7fb3196d38684ef483079f971c7719f4?pvs=4)
> chore: standardize warehouse timeout config name

- router/router_test.go
- router/worker.go
This PR sends the last error response to reporting and in the job status table for the jobs which get aborted due the exhausting their retries
[ Linear Link ](https://linear.app/rudderstack/issue/PIPE-78/propagate-error-response-for-aborted-jobs-to-reporting)
> fix: send last error response for aborted jobs to reporting

- backend-config/backend-config.go
- backend-config/backend_config_test.go
- gateway/gateway.go
- Respect the context in `gateway.backendConfigSubscriber`
- Wait until the first configuration has been consumed by the gateway before starting gateway's http listeners
- Add some more information in the **Workspace Config changed** log, such as the number of workspaces and total sources contained in the updated configuration.
[Link](https://linear.app/rudderstack/issue/PIPE-81/gateway-backend-config-initialisation-improvements)
> chore: gateway backend config initialisation improvements

- jobsdb/backup.go
Drop backups after a fixed number of retries 
[ Linear Link ](https://linear.app/rudderstack/issue/PIPE-57/subteams03sekbfx0dserver-on-call-lot-of-pre-drop-gw-tables-on)
> chore: drop failing backups after few retries

- processor/transformer/transformer.go
- router/handle.go
- router/handle_lifecycle.go
- router/transformer/transformer.go
- router/worker.go
There are multiple occasions where we currently need a much higher timeout than `30s` during transformation requests, e.g. when using large event batches and transformer needs to perform some external request(s). This has also caused a number of issues already, forcing us to manually increase this timeout. Therefore increasing the default timeout to 10 minutes, instead of 30 seconds.
[Link](https://linear.app/rudderstack/issue/PIPE-96/increase-default-transformer-timeout-in-rudder-server)
> chore: increase transformer request timeouts

- warehouse/integrations/deltalake/deltalake.go
- warehouse/integrations/postgres/load.go
- warehouse/integrations/redshift/redshift.go
- warehouse/integrations/snowflake/snowflake.go
- We want this to filter and group `dedup_rows` based on source category as well. Especially extract sources because they use a different deduplication strategy based on `recordID`.
- https://linear.app/rudderstack/issue/PIPE-69/clean-up-duplicate-dashboard
> chore: introduce source category for deduplication

- router/handle.go
During router's pickup iteration, while trying to find an available worker slot, if the barrier forbids the job to enter, this job needs to be added to the `blockedOrderKeys`, so that no other job for the same ordering key can be picked up in this iteration.
Even though the barrier is synced only once before the router iterator's loop begins, the barrier's two limiters (concurrency & drain) are updated in realtime and can at any time fill or empty causing barrier#Enter's response to vary.
[Link](https://linear.app/rudderstack/issue/PIPE-133/bug-causing-illegal-job-sequence-during-barrier-enter-in-router-pickup)
> fix: illegal job sequence during barrier enter in router pickup
