rudderlabs/rudder-server

- config/backend-config/backend-config.go
> OnChange notifier for backend config

- config/config.toml
- jobsdb/jobsdb.go
added maxTableSizeInMB limit for shifting to new Dataset.
> dataset table limit size configuration

- gateway/gateway.go
- gateway/responseStatus.go
- checking for valid json before saving it in db
- checking for writekey if its empty or not
> checking for valid json before saving it in db

- gateway/gateway.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/169)
> Writekey stats fix

- config/config.toml
- router/batchrouter/batchrouter.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/171)
> Abort batch router jobs after some retries.

- warehouse/utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/175)
> pick unique load files

- jobsdb/jobsdb.go
- processor/processor.go
- router/batchrouter/batchrouter.go
- services/db/maintenanceModeHandler.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/172)
> fix for crash on recoverfromcrash due to journal count > 1

- warehouse/utils/utils.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/176)
> Warehouse refactor r

- router/warehouse/bigquery/bigquery.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/177)
> Fix closure bug in bigquery uploads

- config/config.toml
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/178)
> Warehouse refactor raj

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/181)
> remove go report card badge

- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/186)
> total overall warehouse time

- build/wait-for
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/188)
> Added support to udp port in wait-for script

- utils/config-gen/src/components/connections/index.tsx
- utils/config-gen/src/components/sourceDetails/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/192)
> Pretty print exported config

- README.md
- build/docker-compose.codebuild.yml
- build/docker.env
- config/backend-config/backend-config.go
- config/backend-config/workspace-config.go
- config/config.go
- config/sample.env
- jobsdb/jobsdb.go
- main.go
- rudder-docker.yml
- services/db/maintenanceModeHandler.go
- services/source-debugger/eventUploader.go
- services/validators/envValidator.go
- tests/e2e/buildspec.yml
- tests/helpers/helpers.go
- tests/helpers/testInputs.go
- utils/logger/logger.go
- utils/misc/dbutils.go
- utils/misc/misc.go
Workspace token switch support
Backend-config: removed default workspace token
Moved postgres compatibility check to envValidator
Logger: warn level introduced
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/180)
> Workspace token switch support

- processor/processor.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/193)
> processor loop backoff logic bug fixed

- config/backend-config/workspace-config.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/194)
> Fix wrong function name in commment

- config/backend-config/backend-config.go
- gateway/gateway.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/195)
> Add backend config type & last sync in healthcheck

- tests/e2e/warehouse/config_overrides.toml
- tests/e2e/warehouse/warehouse_suite_test.go
- tests/e2e/warehouse/warehouse_test.go
- tests/helpers/gcs.go
- tests/helpers/helpers.go
- tests/helpers/testInputs.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/197)
> warehouse integration tests

- tests/e2e/e2e_test.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/202)
> Warehouse saas fixes

- config/backend-config/backend-config.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/196)
> sorting workspace config before use

- config/config.toml
- main.go
- router/batchrouter/batchrouter.go
- router/router.go
- services/destination-debugger/eventDeliveryStatusUploader.go
* destination delivery status feature
Co-authored-by: Chandra shekar Varkala <chandra@rudderlabs.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/211)
> Destination delivery status (#203)

- utils/misc/misc.go
Closes #207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/208)
> Fix GetIPFromReq in misc package

- config/config.go
- config/config.toml
- jobsdb/jobsdb.go
- main.go
- services/db/degradedModeHandler.go
- tests/helpers/helpers.go
- tests/main/main.go
TODO: Need to monitor stats
Tests done using tests/helpers.go utility methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/191)
> Backup routertables

- router/router.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/215)
> blockjob assert crash fix

- utils/misc/misc.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/220)
> crash time added in error store

- services/streammanager/kinesis/kinesismanager.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/225)
> Persist Kinesis error reason in db

- services/db/recovery.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/227)
> Send the recovery mode stat every 1 minute.

- router/batchrouter/batchrouter.go
- services/filemanager/azureBlobStoragemanager.go
- warehouse/bigquery/bigquery.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
- warehouse/utils/utils.go
- warehouse/utils/utils_suite_test.go
- warehouse/utils/utils_test.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/219)
> Multi cloud object storage support for snowflake

- warehouse/bigquery/bigquery.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/213)
> Store data type discards

- rudder-docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/237)
> Updating docker image tags for rudder-docker

- router/network.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/238)
> not trimming query values while sending request

- warehouse/snowflake/snowflake.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/242)
> Use snowflake integration (configured with s3 access arn) for aws cloud

- router/batchrouter/batchrouter.go
Use localhost by default when warehouse mode is embedded
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/250)
> Use localhost by default when warehouse mode is embedded (#209)

- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/251)
> Fix issue in adding timings column in wh_uploads

- services/source-debugger/eventUploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/255)
> send event properties in source debugger

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/247)
> Typo correction in README

- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/258)
> Fix compatability issue with missing timings for existing deployments

- build/Dockerfile
- build/Dockerfile-dev
- build/Dockerfile-sink
- go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/252)
> Update golang version in dockerfiles etc.

- warehouse/bigquery/bigquery.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
- warehouse/utils/utils.go
- warehouse/utils/utils_test.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/244)
> Fix bug in updating current schema in wh_schemas

- gateway/gateway.go
- services/source-debugger/eventUploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/263)
> Fix issue in adding missing anonymousId and show in source debugger

- config/config.toml
- warehouse/scheduling.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/268)
> config value to ignore sync freq

- services/pgnotifier/pgnotifier.go
- utils/misc/misc.go
- warehouse/warehouse.go
Also includes bug fix for setting error on generating load file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/254)
> Fix OOM for warehouse master

- README.md
fixed and added utm params to signup links
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/275)
> update Readme.md with url fixes

- utils/logger/logger.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/280)
> Fix logger interface

- router/batchrouter/batchrouter.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/276)
> warehouse maxRetryTime Fix

- .gitignore
- gateway/gateway_suite_test.go
- utils/tests/reporter.go
- warehouse/utils/utils_suite_test.go
- warehouse/warehouse_suite_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/282)
> Ginkgo junit reporter

- .enterprise/scripts/init.sh
- build/buildspec.enterprise.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/290)
> Enterprise build

- gateway/gateway.go
- gateway/responseStatus.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/289)
> Pixel API Support

- gateway/gateway.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/294)
> Pixel API-empty queryParam handling

- gateway/gateway.go
Added handling for empty queryParams
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/295)
> Pixel API-empty queryParam handling (#294)

- warehouse/bigquery/bigquery.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/301)
> close warehouse db calls

- processor/processor.go
- router/router.go
- services/customdestinationmanager/customdestinationmanager.go
- services/streammanager/kafka/kafkamanager.go
- services/streammanager/streammanager.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/299)
> Azure event hub

- gateway/gateway.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/308)
> Add conditional to use webhook in rudder server

- build/docker.env
- config/sample.env
- router/batchrouter/batchrouter.go
- services/filemanager/s3manager.go
- utils/misc/misc.go
- warehouse/redshift/redshift.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/309)
> iam approach for redshift and s3

- warehouse/bigquery/bigquery.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
- warehouse/utils/utils.go
- warehouse/utils/utils_test.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/305)
> ignore letter case while comparing schema

- utils/misc/misc.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/315)
> remove port from requestIp

- services/filemanager/filemanager.go
- services/filemanager/miniomanager.go
- services/filemanager/s3manager.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/316)
> sse support for s3

- warehouse/redshift/redshift.go
- warehouse/utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/320)
> Merge redshift user records

- jobsdb/jobsdb.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/325)
> Assignment to nil value fix

- jobsdb/jobsdb.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/328)
> Foreign key constraint crash fix

- warehouse/utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/330)
> fix getting keys from map for postgres

- warehouse/postgres/postgres.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/331)
> empty value string to nil while loading to postgres

- jobsdb/jobsdb_export.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/333)
> Nil reference fix

- utils/misc/dbutils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/311)
> add quotes for table names having - or pg keywords

- gateway/gateway_test.go
- mocks/jobsdb/mock_jobsdb.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/324)
> Fixing unit tests around Store to replace with StoreWithRetryEach

- config/config.go
- gateway/gateway_test.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_export.go
- main.go
- mocks/jobsdb/mock_jobsdb.go
- processor/integrations/integrations.go
- services/validators/envValidator.go
- utils/misc/dbutils.go
- utils/misc/misc.go
- warehouse/bigquery/bigquery.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
- warehouse/utils/utils.go
- warehouse/utils/utils_test.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/335)
> [Jun 3] Merge master to rudder-saas

- services/pgnotifier/pgnotifier.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/334)
> removtes quotes in a query for a quoteLiteral value

- warehouse/utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/336)
> Fix duplicate imports on git merge

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/338)
> rudderstack logo link update

- jobsdb/jobsdb.go
- router/batchrouter/batchrouter.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/343)
> MigrateJobs Crash fix

- build/buildspec.docker.dev.yml
- build/buildspec.docker.master.yml
- build/docker-compose.codebuild.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/340)
> Added unit and integration tests in build pipelines

- build/buildspec.docker.dev.yml
- build/buildspec.docker.master.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/355)
> Code build unit tests fix

- .gitignore
- gateway/gateway_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/359)
> Gateway test fix

- build/buildspec.docker.dev.yml
- build/buildspec.docker.master.yml
- gateway/gateway_test.go
- processor/processor_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/360)
> Fix processor test deadlocks

- warehouse/redshift/redshift.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/361)
> Redshift: Merge user records in identifies with same anonymousId

- gateway/gateway.go
- gateway/gateway_test.go
- main.go
This is done so that its served from gateway's webhandler
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/362)
> Moving /version to custom serveMux instead of the default one

- jobsdb/jobsdb.go
- processor/processor.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/363)
> Avoiding stats for unwanted scenarios

- build/buildspec.docker.dev.yml
- build/buildspec.docker.master.yml
- build/codecov.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/366)
> Added codecov integration for code coverage reports

- gateway/gateway.go
- go.mod
- go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/368)
> webhookhandler init before workspace config fetch

- services/sql-migrator/migrator.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/372)
> Suppressed no change error in warehouse migrations

- jobsdb/jobsdb.go
- jobsdb/setup.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/373)
> Using -cleardb flag will also drop jobsdb schema migration tables

- build/buildspec.docker.dev.yml
- build/buildspec.docker.master.yml
- build/buildspec.docker.saas.yml
- build/buildspec.docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/377)
> Static linked binary in codebuild

- build/buildspec.docker.dev.yml
- build/buildspec.docker.master.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/382)
> preventing go.mod changes because of go get ginkgo

- gateway/gateway.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/383)
> An api to view writekeys allowed by gateway

- build/docker.env
- config/sample.env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/395)
> Comment on kafka keys in env files

- warehouse/redshift/redshift.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/369)
> distkey for redshift

- Makefile
- build/buildspec.docker.saas.yml
- warehouse/bigquery/bigquery.go
- warehouse/warehouse.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/401)
> Saas -> Master

- warehouse/postgres/postgres.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/400)
> Remove downloaded files after loading to postgres

- warehouse/redshift/redshift.go
> Master -> SaaS

- main.go
- [-] Bug fix (non-breaking change which fixes an issue)
- [-] My code follows the style guidelines of this project
- [-] I have performed a self-review of my own code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/406)
> moved backendconfig setup place

- gateway/gateway_test.go
- processor/integrations/integrations.go
- processor/processor.go
- processor/processor_test.go
- router/router.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/409)
> Fix for assigning router worker

- warehouse/bigquery/bigquery.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/417)
> Close all warhouse connections

- config/backend-config/backend-config.go
- config/backend-config/backend-config_test.go
- config/config.toml
- main.go
- warehouse/warehouse.go
> review comments

- services/filemanager/azureBlobStoragemanager.go
- services/filemanager/filemanager.go
- services/filemanager/gcsmanager.go
- services/filemanager/miniomanager.go
- services/filemanager/s3manager.go
- warehouse/utils/utils.go
> Fix parsing key from s3 url for non US region buckets

- processor/processor.go
> session fix

- warehouse/bigquery/bigquery.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
> Remove expiry on BQ partitions

- services/source-debugger/eventUploader.go
> Show full payload in source debugger

- warehouse/bigquery/bigquery.go
> WH: Ignore non time partitioned tables in updating expiry

- warehouse/clickhouse/clickhouse.go
- warehouse/utils/utils.go
tls support for clickhouse destination
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/438)
> Clickhouse tls support

- warehouse/clickhouse/clickhouse.go
- warehouse/utils/utils.go
clickhouse tls support is saas
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/444)
> Clickhouse tls support (#438)

- warehouse/redshift/redshift.go
Add runlength encoding to boolean columns for redshift destination
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/440)
> redshift boolean encoding

- gateway/gateway.go
- gateway/gateway_test.go
> gateway tests fixed. DBWriter logic optimized.

- gateway/gateway.go
- gateway/gateway_test.go
- gateway/responseStatus.go
- rruntime/goroutine-factory.go
- utils/misc/misc.go
Generating anonymousId from userId if anonymousId is not present. Rejecting request if neither of them is present
> Handling anonymousId

- build/Dockerfile-aws
- build/Dockerfile-aws-dev
> Remove code from docker images

- utils/logger/zaplogger.go
- utils/misc/misc.go
- warehouse/clickhouse/clickhouse.go
- warehouse/warehouse.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/483)
> partition support for clickhouse

- README.md
- build/Dockerfile-aws
- build/Dockerfile-aws-dev
- build/buildspec.docker.dev.yml
- utils/logger/zaplogger.go
- utils/misc/misc.go
- warehouse/clickhouse/clickhouse.go
- warehouse/warehouse.go
updating saas with latest master
> updating saas with latest master

- processor/processor.go
- services/source-debugger/eventUploader.go
- utils/misc/misc.go
> Timestamp fix

- jobsdb/jobsdb.go
> moved unncessary info logs to debug

- services/customdestinationmanager/customdestinationmanager.go
> Fix: Restrain use of producer after closing it

- router/batchrouter/batchrouter.go
- warehouse/bigquery/bigquery.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
> BQ: Add loaded_at timestamp field

- warehouse/clickhouse/clickhouse.go
**Fixes** #504
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/505)
> sort key changed to received_at fromm uuid_ts for clickhouse

- go.sum
> Fixing build

- warehouse/bigquery/bigquery.go
**Fixes** #357 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/507)
> bigquery location fix

- processor/integrations/integrations.go
- utils/misc/misc.go
> Supporting optional tag value for json tag in integrations.go

- router/throttler/config.go
- utils/misc/misc.go
- warehouse/warehouse.go
> Error logs for GZWriter

- router/batchrouter/batchrouter.go
> Fixing lock and naming symbols

- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/523)
> change few logs level to debug from info

- processor/processor.go
- router/network.go
- router/router.go
> setting userId in processor based on transformer response

- warehouse/clickhouse/clickhouse.go
**Fixes** #530 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/531)
> fix datetime empty bug

- gateway/gateway.go
> Non identifiable code revert

- gateway/gateway.go
- jobsdb/jobsdb.go
- utils/misc/misc.go
- warehouse/clickhouse/clickhouse.go
> Rudder saas

- config/config.toml
- router/router.go
- tests/eventSchema/config.toml
> dont put in failedmapid when job is aborted

- config/config.toml
- gateway/configuration.go
- gateway/gateway.go
> Enabling protocols feature by default. URI change to remove protocols from it

- router/batchrouter/batchrouter.go
- warehouse/snowflake/snowflake.go
> optimize brt picking jobs for high number of sources

- services/sql-migrator/migrator.go
- services/validators/envValidator.go
- warehouse/warehouse.go
> force reset db migration version on change to older versions

- CONTRIBUTING.md
> Update CONTRIBUTING.md with Installation Steps

- router/router.go
- services/stats/stats.go
> Router response alerts

- vendor/github.com/EagleChen/restrictor/restrictor.go
> Remove debug log in vendor file

- warehouse/clickhouse/clickhouse.go
- warehouse/postgres/postgres.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/568)
> info about failed file

- gateway/gateway.go
> Beacon support

- utils/misc/misc.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/578)
> fetch error while closing gzip writer and closing file

- jobsdb/jobsdb.go
> Fix bug in setting empty cache false

- utils/misc/misc.go
> SaaS <- Master

- services/diagnostics/diagnostics.go
> update diagnostics dataplane url

- gateway/gateway.go
> Maxage for preflight request caching

- warehouse/bigquery/bigquery.go
- warehouse/warehouse.go
> saas->master

- build/buildspec.docker.dev.yml
- main.go
- processor/processor.go
- processor/transformer/transformer.go
- router/router.go
> New stats for processor

- gateway/webhook/webhook.go
- gateway/webhook/webhookTransformer.go
> Reject invalid json webhooks

- router/network.go
- warehouse/snowflake/snowflake.go
> Master <- SaaS 

- README.md
> Logo Update in README.md

- processor/processor.go
- services/stats/stats.go
> Proc-Error Metrics

- build/buildspec.docker.dev.yml
- mocks/stats/mock_rudderstats.go
- mocks/stats/mock_stats.go
- processor/processor_test.go
- router/router.go
- services/stats/stats.go
> fix processor tests

- build/buildspec.docker.dev.yml
- config/config.go
- config/config.toml
- mocks/stats/mock_rudderstats.go
- mocks/stats/mock_stats.go
- processor/processor.go
- processor/processor_test.go
- processor/transformer/transformer.go
- router/config.go
- router/network.go
- router/router.go
- services/stats/stats.go
> Braze debug

- config/backend-config/admin.go
- mocks/stats/mock_stats.go
> panic issue due to wrong assignment of destination secret keys resolved

- services/filemanager/miniomanager.go
**Fixes** #570 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/579)
> handle minio upload error

- warehouse/upload.go
- warehouse/warehouse.go
> add alert for long running upload

- router/router.go
> Fix router responses count

- services/pgnotifier/pgnotifier.go
> pgnotifier: fix closing sql rows after read

- .gitignore
- router/batchrouter/batchrouter.go
- router/batchrouter/config.go
- router/router.go
> Functionality to tune routerWorkers per destination type

- services/tablearchiver/tablearchiver.go
- warehouse/archiver.go
- warehouse/warehouse.go
> Archive staging/load file table records created before 45 days

- gateway/gateway_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/628)
> fix gateway writeKey stasts test

- utils/logger/logger.go
> Clear logger level cache on resetting root level

- admin/admin.go
- rate-limiter/rate-limiter.go
- router/network.go
- router/router.go
- services/destination-debugger/eventDeliveryStatusUploader.go
- utils/logger/logger.go
> Module logging fixes

- gateway/gateway.go
> Use healthHandler for root url

- utils/misc/misc.go
- warehouse/clickhouse/clickhouse.go
- warehouse/postgres/postgres.go
- warehouse/upload.go
> Wh: pgNotifier publish paginated

- services/kvstoremanager/redis.go
> redis default to cluster mode option

- config/backend-config/backend-config.go
- gateway/gateway.go
- main.go
- router/batchrouter/batchrouter.go
- router/router.go
- services/diagnostics/diagnostics.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/635)
> fix user id bug in diagnostic events

- admin/admin.go
- config/backend-config/admin.go
> added panic recovery code

- config/config.toml
- gateway/configuration.go
- processor/processor.go
> disabled eventschemas

- services/db/recovery.go
- utils/misc/misc.go
> Not panicking for invalid error, recovery json

- router/batchrouter/batchrouter.go
> Adding stats for aborted job count in batch router

- docker-compose.yml
- rudder-docker.yml
- services/pgnotifier/pgnotifier.go
- warehouse/warehouse.go
> Fix setting enqueuedUploadJobs

- jobsdb/jobsdb.go
- jobsdb/jobsdb_export.go
- jobsdb/jobsdb_import.go
- scripts/generate-event
> Fix for db getting updated as get(Un)Processed executes

- config/config.toml
- router/router.go
> Limit aborted user router jobs

- warehouse/clickhouse/clickhouse.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
> fix typo is dct timeout

- jobsdb/jobsdb.go
> setting correct sequence

- router/customdestinationmanager/customdestinationmanager.go
- router/router.go
> Fixing synchronization crash

- processor/processor.go
- router/customdestinationmanager/customdestinationmanager.go
- services/streammanager/kafka/kafkamanager.go
- services/streammanager/streammanager.go
> Confluent cloud

- warehouse/bigquery/bigquery.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/schema.go
- warehouse/snowflake/snowflake.go
- warehouse/upload.go
- warehouse/utils/utils.go
> WH: Fix resuming from exporting failed state

- config/config.toml
- main.go
- services/db/degradedModeHandler.go
- services/db/recovery.go
> Remove invalid mode

- processor/processor.go
- router/batchrouter/batchrouter.go
- router/router.go
- warehouse/stats.go
- warehouse/types.go
- warehouse/upload.go
> Additional fixes to stats cleanup

- main.go
> Start processor router order

- warehouse/slave.go
> Call cancel() to stop all goroutines in slave uploads

- main.go
- warehouse/slave.go
- warehouse/warehouse.go
> close channel to avoid memory leak in wh slave

- config/config.toml
- event-schema/event_schema.go
- processor/processor.go
> stats, parallelism for event-schemas

- config/config.toml
- processor/processor.go
- router/router.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/698)
> add sleep in processor cycle

- config/config.toml
- router/batchrouter/batchrouter.go
- router/router.go
- tests/eventSchema/config.toml
> Destination specific router conf

- event-schema/event_schema_api.go
- gateway/gateway.go
- gateway/gateway_test.go
- gateway/response/response.go
- gateway/webhook/webhook.go
- tests/sink.go
- warehouse/warehouse.go
> Ensuring all the RudderAPI returns json

- warehouse/bigquery/bigquery.go
- warehouse/clickhouse/clickhouse.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/713)
> extra logs around sql errs

- warehouse/warehouse.go
> wh: rudder-cli to query warehouse even in degraded mode

- warehouse/redshift/redshift.go
- warehouse/utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/716)
> add quotes for columns in redshift user's table

- warehouse/utils/utils.go
- warehouse/utils/utils_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/718)
> format and add unit tests

- warehouse/snowflake/snowflake.go
> WH: Use quotes in all queries for snowflake

- main.go
> jobsdb setup order fix

- router/network.go
> Do not copy tls config

- jobsdb/jobsdb.go
- jobsdb/jobsdb_export.go
> move var maps to handleT

- warehouse/snowflake/snowflake.go
> Fix incorrect quoting for partitionKey in loading snowflake tables

- config/config.toml
- jobsdb/jobsdb.go
> backup query batch size

- warehouse/clickhouse/clickhouse.go
- warehouse/warehouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/735)
> add logs for failed query

- gateway/gateway.go
> GW BatchWrite sizes

- services/destination-connection-tester/destination_connection_tester.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/734)
> use instanceId instead of nodeID

- warehouse/clickhouse/clickhouse.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/711)
> clickhouse cluster support

- warehouse/clickhouse/clickhouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/740)
> cluster support for older version of clickhouse 

- warehouse/snowflake/snowflake.go
> wh: snowflake dedup keep original

- warehouse/bigquery/bigquery.go
- warehouse/clickhouse/clickhouse.go
- warehouse/debugger.go
- warehouse/identities.go
- warehouse/identity/identity.go
- warehouse/manager/manager.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/scheduling.go
- warehouse/schema.go
- warehouse/snowflake/snowflake.go
- warehouse/table_upload.go
- warehouse/upload.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
> Do not block all table uploads on schema update failure for one table

- config/config.toml
- services/pgnotifier/pgnotifier.go
- warehouse/slave.go
- warehouse/upload.go
> PG Notifier Fixes

- admin/admin.go
- config/config.go
- gateway/admin.go
- gateway/gateway.go
- processor/priorityqueue.go
- processor/processor.go
- processor/stash/admin.go
- processor/stash/stash.go
- router/admin.go
- router/router.go
- utils/misc/misc.go
> Additional functionality to support CLI

- warehouse/upload.go
- warehouse/warehouse.go
> Compile fixes

- jobsdb/setup.go
- services/sql-migrator/migrator.go
> set lower migration version support for jobsdb tables

- warehouse/clickhouse/clickhouse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/759)
> return default data while typecasting

- processor/transformer/transformer.go
> Handling proc errors

- jobsdb/jobsdb.go
> DS Rangelist assert skipping

- warehouse/upload.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/770)
> fix empty upload schema while retrying failed upload

- processor/integrations/integrations.go
> add support for map in integrations

- router/router.go
> aborted job metric fix

- warehouse/upload.go
> Adding log for skipped tables

- warehouse/upload.go
> WH: Set failed upload state on error im all cases

- utils/misc/misc.go
- warehouse/identity/identity.go
> WH: Fix quoted properties issue in id-resolution

- gateway/gateway.go
- gateway/webhook/setup.go
- gateway/webhook/webhook.go
> Minor refactor

- router/batchrouter/batchrouter.go
- services/pgnotifier/pgnotifier.go
- warehouse/identity/identity.go
- warehouse/slave.go
- warehouse/stats.go
- warehouse/upload.go
- warehouse/utils/csvLoader.go
- warehouse/utils/jsonLoader.go
- warehouse/warehouse.go
> Hotfix -> SaaS: Add randomness to load file path

- services/pgnotifier/pgnotifier.go
- warehouse/slave.go
- warehouse/types.go
- warehouse/upload.go
- warehouse/warehouse.go
> WH: Remove slave dependency on warehouseDB

- .deepsource.toml
> Update analyzer meta in .deepsource.toml

- README.md
- warehouse/stats.go
> WH: Add tag to metric rows_synced for all tables

- utils/misc/misc.go
- warehouse/bigquery/bigquery.go
- warehouse/clickhouse/clickhouse.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/slave.go
- warehouse/snowflake/snowflake.go
- warehouse/table_upload.go
- warehouse/upload.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
> Removing unused code

- utils/misc/misc.go
- warehouse/clickhouse/clickhouse.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
- warehouse/upload.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
Removing unnecessary fmt.Sprintfs
Handling err wherever unhandled or dropping err wherever not required
Remove unnecessary breaks
> Code clean up

- services/pgnotifier/pgnotifier.go
> Add FOR UPDATE SKIP LOCKED in triggerPending func

- warehouse/upload.go
- warehouse/warehouse.go
> WH: Fix scheduling using lastEventAt

- warehouse/snowflake/snowflake.go
> Handle special characters in snowflake password

- scripts/batch-with-identify.json
- warehouse/upload.go
- warehouse/warehouse.go
> Table skip load bug fix

- services/pgnotifier/pgnotifier.go
- warehouse/upload.go
- warehouse/warehouse.go
Merge pull request #805 from rudderlabs/rudder-saas**Fixes** # (*issue*)
> Master <- SaaS

- services/stats/stats.go
Added namespace tag in stats.go all stats interface functions.
> Added namespace tag in stats

- warehouse/upload.go
> Missing continue

- app/apphandlers/setup.go
- config/backend-config/backend-config.go
- processor/processor.go
- processor/processor_test.go
- router/destinationReponseHandler.go
- router/destinationReponseHandler_test.go
- router/router.go
- router/transformer/transformer.go
- router/types/types.go
- [-] New feature (non-breaking change which adds functionality)
> V2 router transform

- jobsdb/jobsdb.go
- jobsdb/jobsdb_import.go
- processor/processor_test.go
- router/admin.go
- router/drain/drain.go
- router/router.go
> drain jobs support

- warehouse/upload.go
> Don't push to metric if a wh-job has skipped because of previous failures

- go.mod
- go.sum
- warehouse/identities.go
- warehouse/upload.go
- warehouse/utils/utils.go
> Using go-multierror to manage a slice of errors

- gateway/gateway.go
- gateway/webhook/setup.go
- gateway/webhook/webhook.go
> Adding WriteKey Tag for GateWay metrics

- warehouse/bigquery/bigquery.go
- warehouse/clickhouse/clickhouse.go
- warehouse/identity/identity.go
- warehouse/manager/manager.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/snowflake/snowflake.go
- warehouse/stats.go
- warehouse/table_upload.go
- warehouse/upload.go
- warehouse/utils/utils.go
> WH: Verify event counts in load file gen and export stages

- router/admin.go
> Batch router cli stats

- config/config.toml
- jobsdb/jobsdb.go
- router/batchrouter/batchrouter.go
- router/batchrouter/config.go
> Batch router retry

- router/batchrouter/batchrouter.go
> WH tmp space bloat bug

- go.mod
- go.sum
- vendor/github.com/mkmik/multierror/LICENSE
- vendor/github.com/mkmik/multierror/compat.go
- vendor/github.com/mkmik/multierror/compat_go113.go
- vendor/github.com/mkmik/multierror/go.mod
- vendor/github.com/mkmik/multierror/multierror.go
- vendor/modules.txt
- warehouse/identities.go
- warehouse/upload.go
- warehouse/utils/utils.go
> Making all table loads concurrent and independent of each other

- warehouse/warehouse.go
> Aborting jobs when source or destionation or the connection is deleted

- warehouse/schema.go
- warehouse/table_upload.go
- warehouse/upload.go
> saas -> master (empty user table fixes)

- event-schema/event_schema_api.go
- gateway/gateway.go
- gateway/response/response.go
> EventSchemas response headers to json

- warehouse/warehouse.go
> WH: Fix logic in setting lastEventAt marker for scheduling

- warehouse/warehouse.go
> WH: Set current time as last processed marker always

- config/config.go
- services/pgnotifier/pgnotifier.go
- services/stats/stats.go
- warehouse/warehouse.go
> WH: Delete only same workspace jobs in pgnotifier on wh-master restart

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/gatewayAppHandler.go
- app/apphandlers/setup.go
- build/wait-for
- config/config.toml
- gateway/gateway.go
- gateway/response/response.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_utils.go
- jobsdb/readonly_jobsdb.go
- router/destinationReponseHandler.go
- router/router.go
- router/transformer/transformer.go
> V1 pending jobs endpoint

- config/backend-config/backend-config.go
- event-schema/counter.go
- event-schema/event_schema.go
- gateway/gateway.go
- gateway/webhook/webhook.go
- jobsdb/jobsdb.go
- jobsdb/jobsdb_migration_checkpoints.go
- processor/stash/admin.go
- router/config.go
- router/throttler/throttler.go
- router/transformer/transformer.go
- services/filemanager/digitalOceanSpacesManager.go
- services/source-debugger/eventUploader.go
- services/sql-migrator/migrator.go
- services/streammanager/kafka/kafkamanager.go
- services/streammanager/kinesis/kinesismanager.go
- services/streammanager/streammanager.go
- tests/helpers/helpers.go
- utils/logger/logger.go
- utils/logger/zaplogger.go
- utils/misc/misc.go
- utils/misc/waitgroup.go
- utils/tests/GA/GAcheck.go
> Deepsource fixes

- warehouse/scheduling.go
- warehouse/warehouse.go
> WH: Fix lastStartedAt for warehouses with syncStartAt

- processor/processor.go
- processor/processor_test.go
> Rohith additional parameters router

- jobsdb/jobsdb.go
- router/batchrouter/batchrouter.go
> remove customvalfilters in batchrouter

- router/batchrouter/batchrouter.go
> batchrouter append jobs order fix

- config/config.toml
> Adding File Name to Logger by Default

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/processorAppHandler.go
- app/apphandlers/setup.go
- router/batchrouter/batchrouter.go
- router/router.go
- router/transformer/transformer.go
- router/types/types.go
- utils/misc/misc.go
> aborted event store proc_error

- config/config.toml
- router/router.go
- services/diagnostics/diagnostics.go
> sampling router track

- config/config.toml
- router/router.go
- router/throttler/throttler.go
> Throttle correction

- router/router.go
> destination live events fix

- warehouse/postgres/postgres.go
- warehouse/schema.go
> WH: Use column data type in identifies for creating in users table

- router/batchrouter/batchrouter.go
- router/router.go
- warehouse/stats.go
- warehouse/upload.go
> metrics clean up

- config/config.toml
- processor/processor.go
> Event Type and Event Name Stats

- jobsdb/jobsdb.go
- mocks/jobsdb/mock_jobsdb.go
- processor/processor.go
- processor/processor_test.go
- processor/stash/stash.go
- router/batchrouter/batchrouter.go
- router/router.go
> support to ignore custom val filter in query

- warehouse/warehouse.go
> WH: Increment active workers on upload job start

- warehouse/api.go
> [ Saas <- Master ] WH: Compute duration with current time for ongoing uploads

- Makefile
- build/Dockerfile-aws
- build/Dockerfile-aws-dev
- build/wait-for-go/wait-for.go
> Wait for in go (rudder-saas)

- services/filemanager/s3manager.go
> Removing return at error

- go.mod
- go.sum
- router/admin.go
- router/router.go
- utils/misc/misc.go
> better logs

- config/config.toml
- processor/stash/stash.go
> Correcting defaults

- jobsdb/jobsdb.go
- mocks/app/mock_app.go
- mocks/app/mock_features.go
- mocks/config/backend-config/mock_backendconfig.go
- mocks/jobsdb/mock_jobsdb.go
- mocks/processor/transformer/mock_transformer.go
- mocks/rate-limiter/mock_ratelimiter.go
- mocks/utils/logger/mock_logger.go
- mocks/utils/mock_pubsub.go
- mocks/utils/sysUtils/mock_archive.go
- mocks/utils/sysUtils/mock_compress.go
- mocks/utils/sysUtils/mock_http.go
- mocks/utils/sysUtils/mock_io.go
- mocks/utils/sysUtils/mock_os.go
- mocks/utils/types/mock_types.go
- processor/processor.go
- processor/stash/stash.go
- router/batchrouter/batchrouter.go
- router/router.go
> propogating updatejobstatus err to its clients

- utils/misc/misc.go
- warehouse/identities.go
- warehouse/upload.go
> Multi-error fix

- processor/processor.go
- services/destination-debugger/eventDeliveryStatusUploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/908)
> destination delivery proc error panic fix

- utils/logger/zaplogger.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/912)
> fix file names while logging when enableFileNameInLog config is enabled

- services/dedup/dedup.go
> dedup open badger with truncate

- router/router.go
> use guarantee event order flag for batching and routertransform

- processor/processor.go
- processor/transformer/transformer.go
> Handle recordId from cloud sources

- warehouse/clickhouse/clickhouse.go
- warehouse/postgres/postgres.go
> WH: Return error on mismatch of csv columns with upload schema

- warehouse/snowflake/snowflake.go
- warehouse/upload.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
> WH: On dedup, use new record for cloud sources in snowflake

- warehouse/schema.go
- warehouse/table_upload.go
- warehouse/upload.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/827)
> empty user table fixes

- warehouse/stats.go
> Fix passing warehouseID in warehouse stats

- router/router.go
> Fix incrementing abortUserIDMap in case of backoff, throttling

- services/streammanager/kafka/kafkamanager.go
> string casting crash fix

- warehouse/stats.go
- warehouse/upload.go
> warehouse successful upload alert

- build/buildspec.docker.dev.yml
- gateway/gateway.go
- jobsdb/jobsdb.go
- mocks/jobsdb/mock_jobsdb.go
- processor/processor.go
- router/batchrouter/batchrouter.go
- router/router.go
> returning error from jobsdb Store function

- processor/processor.go
> json encode before storing to postgres json column

- router/batchrouter/batchrouter.go
> WH: Fix caching in brt for id resolution

- gateway/gateway.go
- gateway/gateway_test.go
- processor/processor.go
- processor/processor_test.go
- processor/transformer/transformer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-server/934)
> job_run_id filter in pending job endpoint

- services/stats/stats.go
> restore enableStats default value - true

- warehouse/postgres/postgres.go
> Removing temporary tables, trimming names

- warehouse/warehouse.go
> rebase updates

- processor/transformer/transformer.go
> no panic for incorrect transformer response. writing for proc error

- router/network.go
- router/router.go
- utils/misc/misc.go
> save error response in proc errors parameters

- router/router.go
> Drain a destination's jobs on demand via ENV

- router/network.go
> look for content type header before detection

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/processorAppHandler.go
- main.go
> no reporting by gw pod

- warehouse/warehouse.go
> reporing setup

- gateway/gateway.go
- processor/processor.go
- warehouse/warehouse.go
> json_encoding parameters

- services/streammanager/googlesheets/googlesheetsmanager.go
> Google sheets V2

- warehouse/archiver.go
> Fix error in archiving load files when staging files are not present

- warehouse/warehouse.go
> Fix crash in warehouse slave on degraded mode

- jobsdb/jobsdb.go
> check_if_backup_configured

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/gatewayAppHandler.go
- app/apphandlers/processorAppHandler.go
- app/options.go
- main.go
- services/db/embeddedRecovery.go
- services/db/nullRecovery.go
- services/db/recovery.go
- services/db/standbyModeHandler.go
> enabled standbymode

- main.go
> standbymode return 500

- router/network.go
Removed the dependency on ioutil.Nopcloser and passed the payload into the request instead on nil
> Posthog fix

- services/filemanager/s3manager.go
> Make s3 error logs verbose

- services/filemanager/s3manager.go
> Get region hint as env

- main.go
> Changed enable suppress to true

- jobsdb/jobsdb.go
> drop_old_tables

- router/batchrouter/batchrouter.go
> BRT Deadlock Fix

- config/config.go
- router/batchrouter/batchrouter.go
- services/destination-connection-tester/destination_connection_tester.go
- utils/misc/misc.go
- warehouse/clickhouse/clickhouse.go
- warehouse/identity/identity.go
- warehouse/mssql/mssql.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/slave.go
- warehouse/snowflake/snowflake.go
- warehouse/types.go
- warehouse/upload.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
> Support to use Rudder S3 for warehouse object storage

- router/batchrouter/batchrouter.go
- services/destination-connection-tester/destination_connection_tester.go
- utils/misc/misc.go
- warehouse/clickhouse/clickhouse.go
- warehouse/identity/identity.go
- warehouse/mssql/mssql.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
- warehouse/slave.go
- warehouse/types.go
- warehouse/upload.go
> Fix rudder storage predix in shared slave setup

- warehouse/stats.go
- warehouse/upload.go
> WH: Tweak backoff for warehouse nextRetryTime

- warehouse/mssql/mssql.go
> type assertion bug

- services/stats/stats.go
> use enableStats environment variable properly

- services/filemanager/azureBlobStoragemanager.go
- services/filemanager/digitalOceanSpacesManager.go
- services/filemanager/filemanager.go
- services/filemanager/gcsmanager.go
- services/filemanager/miniomanager.go
- services/filemanager/s3manager.go
- warehouse/archiver.go
> WH: Delete rudder storage files during archival

- utils/misc/misc.go
> WH: Enable SSE on Rudder S3

- services/filemanager/digitalOceanSpacesManager.go
- services/filemanager/s3manager.go
> WH: Fix download from buckets with dot in name

- router/batchrouter/batchrouter.go
- router/customdestinationmanager/customdestinationmanager.go
- router/network.go
- router/router.go
> rt_brt_disableOutgoingTraffic_ReloadableFlag

- warehouse/warehouse.go
> WH: Fix for live events on  warehouse separate master

- warehouse/mssql/mssql.go
> mssql diacritic support

- gateway/gateway.go
> Gw req logs

- gateway/gateway.go
- gateway/webhook/webhook.go
> tags to gw stats

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/gatewayAppHandler.go
- gateway/configuration.go
- gateway/gateway.go
- services/diagnostics/diagnostics.go
> clearQueue_newPort

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/gatewayAppHandler.go
- app/apphandlers/processorAppHandler.go
- jobsdb/jobsdb.go
- mocks/jobsdb/mock_jobsdb.go
- router/batchrouter/batchrouter.go
- router/router.go
> Hosted improvement

- warehouse/mssql/mssql.go
> Adding mssql nvarchar support

- gateway/gateway.go
- operation-manager/operation-manager.go
> get op status

- warehouse/mssql/mssql.go
> MSSQL float type support

- config/config.go
- processor/processor.go
- processor/transformer/transformer.go
- router/router.go
> processor transformer stats

- gateway/gateway.go
- mocks/jobsdb/mock_jobsdb.go
> reqtype tag in latency stat

- processor/processor.go
> Disabling recording event-schemas

- utils/pubsub.go
> publish config in different channel

- app/apphandlers/setup.go
- config/config.yaml
- processor/processor.go
- router/batchrouter/batchrouter.go
- warehouse/azure-synapse/azure-synapse.go
- warehouse/manager/manager.go
- warehouse/mssql/mssql.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
> azure synapse test

- warehouse/mssql/mssql.go
> changing the logger type for nil columns

- services/streammanager/googlepubsub/googlepubsubmanager.go
> add attributes map for pubsub

- jobsdb/jobsdb.go
> dropds fix

- jobsdb/jobsdb.go
- jobsdb/jobsdb_export.go
- jobsdb/jobsdb_import.go
- jobsdb/jobsdb_utils.go
- mocks/jobsdb/mock_jobsdb.go
- processor/processor.go
- processor/processor_test.go
- processor/stash/stash.go
- router/batchrouter/batchrouter.go
- router/router.go
- router/utils/utils.go
> Dest features

- jobsdb/jobsdb.go
- jobsdb/jobsdb_export.go
- jobsdb/jobsdb_import.go
- jobsdb/jobsdb_utils.go
- mocks/jobsdb/mock_jobsdb.go
- processor/processor.go
- processor/processor_test.go
- processor/stash/stash.go
- router/batchrouter/batchrouter.go
- router/router.go
- router/utils/utils.go
> brt read improvements

- config/config.yaml
- processor/processor.go
> disable dedup by default

- warehouse/snowflake/snowflake.go
> snowflake truncate string default

- warehouse/table_upload.go
> wh: createTableUploads in batches to avoid postgres row insert limits

- warehouse/mssql/mssql.go
> varchar to nvarchar for all char support

- CONTRIBUTING.md
> made edits to the contributing readme file

- warehouse/admin.go
- warehouse/scheduling.go
- warehouse/utils/utils.go
- warehouse/warehouse.go
> wh: support pending-events and trigger-upload APIs

- processor/processor.go
> transformation live events fix

- gateway/gateway.go
- router/batchrouter/batchrouter.go
- utils/misc/misc.go
> wh pending events

- jobsdb/jobsdb_test.go
- jobsdb/readonly_jobsdb.go
- jobsdb/readonly_jobsdb_test.go
> readonlyjobsdb_tests

- warehouse/postgres/postgres.go
> limiting table creation to ns in pg

- router/router.go
> Store Destination Disabled Aborted Jobs

- warehouse/mssql/mssql.go
- warehouse/postgres/postgres.go
- warehouse/redshift/redshift.go
> WH: Add missing txn rollback on any errors in customer warehouse

- warehouse/api.go
> WH: Return empty syncs when no sources in workspace

- router/network.go
> router support for xml payloads

- app/apphandlers/embeddedAppHandler.go
- app/apphandlers/gatewayAppHandler.go
- app/apphandlers/processorAppHandler.go
- jobsdb/jobsdb.go
- mocks/services/dedup/mock_dedup.go
> clearStaleKeys

- operation-manager/operation-manager.go
> close db prepare stmt

- warehouse/archiver.go
> Fix for warehouse archival when staging files do not exist in wh db

- warehouse/slave.go
> wh: add discard writer to outputFileWritersMap

- config/config.go
> Not Updating Vars for Non Hotreloadable

- router/router.go
> flag to save router payload on error

- gateway/gateway.go
- gateway/gateway_test.go
> Audience List Endpoint

- router/router.go
> read write race in router fix

- gateway/response/response.go
- gateway/webhook/webhook.go
> added for custom sources

- jobsdb/jobsdb.go
- jobsdb/readonly_jobsdb.go
> rollingback errored transactions

- warehouse/snowflake/snowflake.go
> WH: Add Rudderstack application name to Snowflake connection

- services/filemanager/s3manager.go
> More descriptive error for S3 - Bucket not found

- processor/processor.go
- processor/processor_test.go
> filter out unsupported message types

- config/backend-config/multi-workspace-config.go
- config/backend-config/multi-workspace-config_test.go
- config/backend-config/workspace-config.go
> Remove workspace config body from error log

- gateway/gateway.go
> gateway_function_descriptions

- router/batchrouter/batchrouter.go
- router/batchrouter/batchrouter_test.go
- router/router.go
- router/router_test.go
- router/utils/utils.go
> dropEventsAfter24Hrs

- warehouse/s3-datalake/s3-datalake.go
- warehouse/s3-datalake/schema-repository/schema-repository.go
> s3-datalake: use varchar(65535) instead of varchar(max)

- router/batchrouter/asyncdestinationmanager/asyncdestinationmanager.go
- router/batchrouter/batchrouter.go
- utils/misc/misc.go
> Add Debug Logs

- services/pgnotifier/pgnotifier.go
- warehouse/upload.go
- warehouse/warehouse.go
> WH: Pass upload priority to pg notifier

- services/pgnotifier/pgnotifier.go
- warehouse/upload.go
- warehouse/warehouse.go
> WH: Fix setting priority in pg notifier claims

- services/pgnotifier/pgnotifier.go
- warehouse/slave.go
> WH: Change channel size for claiming jobs in slave

- warehouse/slave.go
- warehouse/stats.go
> WH: Add metric to track staging files processed

- warehouse/warehouse.go
> WH: Skip sending live events for uploads

- router/batchrouter/batchrouter.go
> parameter fix

- event-schema/counter.go
- event-schema/event_schema.go
> Allow decreasing sample size for event schemas

- processor/processor.go
> enabled proc reporting

- services/streammanager/personalize/personalizemanager.go
> Personalize putItems putUsers

- services/streammanager/personalize/personalizemanager.go
> err error personalise

- services/streammanager/personalize/personalizemanager.go
> Personalize : Compatibility Issue

- warehouse/postgres/postgres.go
> include namespace in queries for staging tables

- warehouse/bigquery/bigquery.go
- warehouse/utils/utils.go
> wh: bq: load table:use users_view instead of users table for merging traits while loading table

- config/backend-config/backend-config.go
- distributed/computeConfigController.go
- jobsdb/datamanager.go
- processor/processor.go
- router/router.go
> Processor MT
